### ISSUE TITLE
Foundry, EIP 1559 Not Support 

### ISSUE THREAD

**Issue by avenbreaks** [0xPolygon/polygon-edge#1011]
# [ Foundry Smartcontract ]
## Description
Trying to deploy smartcontract using Foundry but EIP-1559 Not Support 

## Your environment
- OS and version : Ubuntu
- The version of the Polygon Edge : v0.6.0 - v0.6.1

## Steps to reproduce
`forge update `

```
forge create --contracts <path/contracts> \
--rpc-url <localhostRPC> \
--private-key <priv-key> \
--constructor-args:Contract
```

## Expected behavior
Successful Deployed 

## Logs Foundry 
Foundry EIP-1559 Not Support

**Comment by laviniat1996** [comment]
Hi @avenbreaks ,

Unfortunately, Edge doesn't support EIP-1559.
