### ISSUE TITLE
Peer rejected:insufficient capacity

### ISSUE THREAD

**Issue by ghost** [0xPolygon/polygon-edge#1016]
# [ Subject of the issue ]
## Description
Describe your issue in as much detail as possible here.. We have 65 peers. 25 are boot nodes. 40 are validators. On a few of the boot nodes, we get this error. Our  --max-peers set at 100

## Your environment
- OS and version. Ubuntu 20.04
- The version of the Polygon Edge.    0.6.1
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider). AWS cloud
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.). no

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.

polygon-edge server --max-peers 100 --data-dir ./newchain --chain genesis.json --libp2p 0.0.0.0:1478 --jsonrpc 0.0.0.0:10002 --price-limit 7150000000000000 --max-slots 40960000 --seal

- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm? yes

## Expected behavior
- Tell us what should happen. Run without errors
- Tell us what happened instead. We get the output below

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

-12-08T11:02:10.725Z [INFO]  polygon.server.ibft.consensus: sequence started: height=144082              │·····································································································2022-12-08T11:02:10.725Z [INFO]  polygon.server.ibft.consensus: round started: round=0                       │·····································································································2022-12-08T11:02:11.206Z [ERROR] polygon.network.discovery: Failed to add new peer to routing table: peer=16U│·····································································································iu2HAm1Kr667HcnaRMHxNukSfSXgffiHXbj4gDuJXUbi2owYmv err="peer rejected; insufficient capacity"                │·····································································································
2022-12-08T11:02:11.206Z [ERROR] polygon.network.discovery: Failed to add new peer to routing table: peer=16U│·····································································································iu2HAmCyVHRmX9JHp83tHy7m1PzGUfkFGswXdH45NfYfzQhkdV err="peer rejected; insufficient capacity"                │·····································································································
2022-12-08T11:02:11.206Z [ERROR] polygon.network.discovery: Failed to add new peer to routing table: peer=16U│·····································································································iu2HAmJiGCv3zj3ayDufia5qrtLECgFuAGjT1atPSNKtiKteim err="peer rejected; insufficient capacity"                │·····································································································2022-12-08T11:02:11.206Z [ERROR] polygon.network.discovery: Failed to add new peer to routing table: peer=16U│·····································································································
iu2HAmSAsAbuyiWMMB61ABo2srknccXZDvar7SPvn1NTnPFsA7 err="peer rejected; insufficient capacity"                │·····································································································2022-12-08T11:02:11.207Z [ERROR] polygon.network.discovery: Failed to add new peer to routing table: peer=16U│·····································································································
iu2HAmKAAUkxTDQKVkRyzD5EyPNq97kC2XYMsHV4vi56wsCDVF err="peer rejected; insufficient capacity"                │·····································································································2022-12-08T11:02:11.207Z [ERROR] polygon.network.discovery: Failed to add new peer to routing table: peer=16U│·····································································································
iu2HAmFMLK2coEznboxnt2tm4J2qe4L3BwGHHi5PG8WiRGf6RJ err="peer rejected; insufficient capacity"                │·····································································································2022-12-08T11:02:11.207Z [ERROR] polygon.network.discovery: Failed to add new peer to routing table: peer=16U│·····································································································
iu2HAmRyXwWVjsevF5S4tmsStVcug7DJ4o9VXTMST7tBwb9UkK err="peer rejected; insufficient capacity"                │·····································································································2022-12-08T11:02:11.207Z [ERROR] polygon.network.discovery: Failed to add new peer to routing table: peer=16U│·····································································································
iu2HAmSE9vH7EwYgmPgsVBV34zDXq2BWrxzBTHDpfjwStnvAYW err="peer rejected; insufficient capacity"                │·····································································································
2022-12-08T11:02:14.098Z [INFO]  polygon.blockchain: new block: number=144082 txs=0 hash=0x275177d0618b2cd940│·····································································································
59e2198c89bfd7c1b72c58ffbfcf753e74e4edcbf22189 parent=0x3dd74b926d4891fcb9255647325c7141d892f2c24c4d5f2acf248│·····································································································
23ba539322d generation_time_in_seconds=3                                                                     │·····································································································
2022-12-08T11:02:14.423Z [INFO]  polygon.blockchain: block already inserted: block=144082 source=consensus   │·····································································································
2022-12-08T11:02:14.423Z [INFO]  polygon.server.ibft: block committed: number=144082 hash=0x275177d0618b2cd94│·····································································································
059e2198c89bfd7c1b72c58ffbfcf753e74e4edcbf22189 validation_type=bls validators=65 committed=44               │·····································································································
2022-12-08T11:02:14.423Z [INFO]  polygon.server.ibft.consensus: sequence done: height=144082                 │·····································································································
2022-12-08T11:02:14.423Z [INFO]  polygon.server.ibft: canceled sequence: sequence=144082                     │·····································································································
2022-12-08T11:02:14.423Z [INFO]  polygon.server.ibft.consensus: sequence 

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by ghost** [comment]
@laviniat1996 Can I have your help on this one please?
Thanks, Nex

**Comment by laviniat1996** [comment]
Hi @Nexsuperne101 , did you add the max peers command for each node?

**Comment by laviniat1996** [comment]
@Nexsuperne101  PoS, right?

**Comment by ghost** [comment]
@laviniat1996 yes it's PoS and every single node runs the seal line above.
Thanks

**Comment by laviniat1996** [comment]
when you add the staker to the contract does it go as expected, without any errors?

**Comment by ghost** [comment]
@laviniat1996 It stakes as expected, and the BLS key registration does as it should. The list of stakers is here
Current validators list [
  '0x6a54e3C419b7482b213CA242bFb655eDB96D7813',
  '0x847A24c3f371c20e60f7B192d0EcEde4faD6c31a',
  '0x810F86Ce461fC0E06a8Abfc5a2F8D689836c1804',
  '0xA86d5525ac9F47e2614B88f3Bf8AEB21b0BFD10B',
  '0x87a347D2a57b491b0B7Da95a54f4D11cf9e891c1',
  '0xf284be6A011E8F89F895Fbc20ead554166046F8b',
  '0xD7c83b4CF4aA9b790A53564aF15bd191090fe985',
  '0xEc4488A92b6C686575bc8Df9512810bea707a9c2',
  '0xeBe599Ec13a98C55A0c3DCcAf5145Ac4D34549b9',
  '0xbB93C6d0C4062503294d08598F8cE245cB45944F',
  '0x2cb54ea7f953bFCe78D335F0b29BA64624F2b46f',
  '0x3eB2A4121C0A3BCF6763910cd627B2aA401f2873',
  '0x81082deac3AA2275AEcfb4F78EE9817EdBAC3ebC',
  '0xf5a0aFF33fA8a3eB37c038AE84791e95CeCD7543',
  '0x733529C3763E7B7785F74Eb9BF307EFd258e1065',
  '0xda7AA518b47Fc1f5F5c0dE9eE4419610d0F88D21',
  '0x804af9907E6A5b453449D7A78459Ed9c8D63aF72',
  '0x11182c9973b0A9aBA5fdA6aF9492c39D1DfD3CCe',
  '0x1da5B740C285c0b4fa1139dF0b2076B934E24503',
  '0x278A02149EdD7a0EC11ceb2c0E9Cc4869c06761E',
  '0x3420BFc907093d3DDD7eE609C36fB50Fdb1e1752',
  '0x5A7C18b1F6E0A8C5ebAbafDC119496D28A796D88',
  '0xA0d4427e7D606B70DeDa934c529d9F4a1B45186e',
  '0x3e6Df8eDeEFb87F05Acefb9dC58e5E9397B2daA2',
  '0x7dEF5FCA303fE833cA052E9CC86320d5c3bf922D',
  '0xFEa74A2DC509787833AB9e5bf899f5a3BfC4af96',
  '0xe5E127B406ee46342e231A70fF0fE459C0412ace',
  '0x61F15A8E3DDaC28f3715A47F350a7938361B1E59',
  '0x7d3AaFf5B5785a884a198A8B82C85C8F91C19C70',
  '0x4b13E1007A9E2E95BC88e13b4F1bB5d2c51C2B03',
  '0xE02E04C311Acd1409a1aAfAc681DdC18725A50Be',
  '0x076544215E2a55f74d09e2027C473Fe84dAfa938',
  '0x63302A101d50A2F7Cc73EA64Fa04C112EDf94817',
  '0x5e456F5b0eC66559b168A41CE43219808aEb9f47',
  '0x995E7b0B9C268dbceEE4055d75aF4078cC6BA14E',
  '0xb8761a3c1E763479b8E5648f3be5B40619604647',
  '0x7782379C3A99a7008DBD3239f413A50aFe628A26',
  '0x66CA080A532D4BAef081500bE99333b74B615Dd5',
  '0x6f8eF38860F102C84b0Eb0Bb07D5D82857575850',
  '0xE4CaED38588F8ce0f82911a08982fb1337110255',
  '0x7e37D28b2cA8Ae83bFA449A3D73A9CeB23d7177E',
  '0xDD35702d51c5e9F30e8be9639A71D9eb0e3398C1',
  '0x9Ca48BD0fB6005E1886e4E2683e17A85A3765537',
  '0x0D6Da4C662CD745Ce26fc0976a629ACAce855f4B',
  '0x607c3789eA2ebf1fE0aEA56A2d798dFB4ABbF869',
  '0xb5BC904e4c84acC470db452c214aF9D34bF31539',
  '0x2962E260b4b234B4BA4C6d964bbfFD46A443EDf4',
  '0x0a54f4a72306270179A0769bDD81CA62EeBAF5d5',
  '0x1eE774BbC05fFa9DE05c70451d86e62416c5342a',
  '0x968a3CbC21468aEf09Cd644AFC90cdFcc4Cc90B0',
  '0xb302E80859D249fFB73473758aB395d160176215',
  '0x0976EdC3E31Ed046EcEe6EEBCd470354b09A4fcd',
  '0x00B10E1E2d9361e11cE4c3B353c781732D3B3083',
  '0x0913038904DA2F08215D04F8c86d9847f9e898De',
  '0x70CAaD3d454466dA7e51f9aB704B37FbdB4752Aa',
  '0xf16e245F8fe0525EcD2097C9787c17d8193e6DD2',
  '0x166F4cc3Fd8D2CD353f3336e958F5aFD46a70501',
  '0xB50EEF098276c3979fC3Df98f41c46FCC9D8Afbc',
  '0x8c1fFde45F92cfAa2DA6574e4E4bD356fdA0fF2d',
  '0x58BDBE702276d2b1976AB70E6ac0591A85DBDa9E',
  '0x5d2c3E0A6eBd66E4cFFA4f22E2574e3dd01593bB',
  '0xF73B36330aD3c3238041D42DE2F92839C9AC4837',
  '0x677b3814854FB63bf35F8c17ef7577f22c4cD905',
  '0x1884a1cFB4E6459FB1646D906cb5206Ce08f05bc',
  '0x9751Ff7dB33B115e21BBBe732B6c0859DDd2F700'
]
BLS Public Keys [
  '0x950d4458a54dd2edfbffb23d4a5f67975cb98df9bf186097a2e4a6b34feb595d4566cf1b4ef2503b030abd197876d9e5',
  '0x98d3ec098f822a47703cf977c7d86558f713104735eb2b5b55e6c6e1e350297a85f5d8d49d9f092b3ca89df3a77c016a',
  '0x8349cebb82aabd5853040fff0878cbbb6921e075617e0acaa1aad741cfac7ed9035ab1581e4cab06cbfc736567c32b44',
  '0x8040227caa5821cda9384c7fdcaa096b27578c8f8d02fbb0e6cd736ac1a3ec5e68ea1ddb034b907f3d40a7c8672df5b3',
  '0xa44d8c959f994649554ad16deca9f7ec1402c53ef88f245594a663b91bfbe13c828a9244102bf3fe1750ceb74f5f01e3',
  '0xb9c8edb73ac38017abd421081cc644ce0b326e7d14645f08f45b7a74421b8ecdedb7623acf8a6dad679873f7e281d85a',
  '0xa768ddb749f0cf31d891050d456f14817ceac366d0db04a7a8e22140a5004d0d20585196d2ef2b7da6e5124095637f3f',
  '0x8573d7578ba9a1309e6a45da86dbcb215f87868a4f8d3a0478b6ef56d8d1133d7eb2c3872f42944452e2e711f14f4d34',
  '0xa4205ce71f268ad9738d2757409887cff7626295e150b122b445ae70445dfd836f8e403ae10acf86d01b375867457b1d',
  '0xaf227b62024df083ec1ce613e4a453daeeb7d3814f84a8541a20baa95e9fc0c95b05c69ea41f07344a9e0b33c9b86de1',
  '0xb033fb56111f68a4f07168baf4573ce981de8836310333e0f74990e8c616e9c814183329d393c172d1b778c14afbe121',
  '0x8d2451ed0bbe2c87ded7d2f23568319716d37f8f9eb5ef1be90ac56e37e3bf1b3b1d0bc9839275f92d1a9ca6d79f3a6b',
  '0xa1da5095c0d2093f90e8ce1efc66cdbafe3438a6baaa1b72643f85b0d6d4c9d9d55065a1192c9cb38a1f3730cea8f64c',
  '0x8dbc7d475c1c5275fa65babc889c6ace5e041f0b68b190adb2f339d6d9253c6492a80c463e6b28489c8e62c5397084aa',
  '0x93cf173b0777beb2fe9d467aab6ae4c4386998091ab6f1a5891c0e3a7db16146fce943be5d5b3cc39dee1cabb83816e3',
  '0xab5b7e40bdaa17a3c9ce709674113bacad473547ad2eddd0d17323b94b402d2820ad8c8d591f40a0d10fa91ee7be48cb',
  '0x8757918fa654211d388ff052140d4f7c1c175c7ca2f1892fe7cb7796e12e7aead9a127cfd106a503fc06bf8170f39374',
  '0xb76bedabbdf230888a39bb4c27080d3375f311194aa82eb6ff640fac4cf254f5491055dcb4f8873114e95c946d29810f',
  '0xb3a81051813ec2fc8467194b73b4c2263c2d3b939d09973adc550f1919e67e4d3fde1af2b010281403fb0bfe7be1b58b',
  '0xa4b81379ca1e0b31c476179f550d49103d4cb38bac137e0c93488665759a5d809a615c249c9ac46925e506e0ffd20f55',
  '0x8655012d26a0e6cf0f5de12be0f06304bca3e6b1907b55b16e38dcc0ecbcabef22c8747a159533e6e7472ef1811a0980',
  '0xb8a60e7e162f8abac97e8c6e5dbc317d12e572e00b95979fa416d9b4bbf49a631706c7e03aa908794af1db2b5b4370fd',
  '0x93e9a94977c3197cc92a43d0db9f77d8506e88a092c8a2ebd1377fe7fc7520af0e0034641a78e1844010d025bc6f7365',
  '0x96888571a864f47035d57dcd3f2e7125ef1da7300aa6541e73758197aa236f652888f7313f9ea7bbc1e8ee93730123c9',
  '0x8fe5d304066d31431b3419f8cc4bd9288e74e327248f230f89e92f52d5c0581bb81d0e3b5cbd14d8798d445d8d53018c',
  '0x9330fe92f001f806d103b8c98bafa451eb609f765640d999016e07803e6ee25aabb2a3252428919b7478acf9fec9c0fa',
  '0xa99fc78b006a7bced197460ebc4749ab078d2433886cc8719866424a2e4ab89817dff3845d8a76ca0dec3345973dc3e7',
  '0x8eeb72188ca68f272af25aab4f77c498fa8fe2d9417e2392702a857a49af7fc463e386b549ec2266835f027759d5f505',
  '0xa4696067a2c40ae1a066bbc93a50d3005e99ff2a19ba94736c9a72175bd3dc84867134e8dd9b4c1d17b80ff1c1aec951',
  '0x947d52deee7d7880e7a3790c125ca219c1e713d3920c93bdf9a9bf06bcdf081c3d1003459e1ee23ceb70dded018f0f56',
  '0xa29b0f466d68572875cecd35ce7786d8f8c71f2bfa6f89ec032ee060bf5cd17dcb6880aa30ff593d7747859e7f49a583',
  '0xb676895927e089835ad23398e2b3c8b5b9ea1eac3a996beae69646a874d8a36563938c6b5d5098f1af7e2e74b9449a28',
  '0xa56d108d87a2cbcbffa239da3711910adb8e4e4887c9db3298179f8ac24846950fb7be468dcd1ac796f4e630b78bb5c8',
  '0xa126a60e8bb7addf64404f60982fd6a5006849e0269244c8e830c5ab95d12113e14858a707e1dc536c79a612516e8251',
  '0xb9efbbe3fe1cfa1f701950fe6659b9f5e5c4d102ddb7374dfd3c776800c719e1ac06cecb80ccca307117ad443d3852eb',
  '0x862ddbb136f1e28a14f0060f6060bfc7a338a4f724fa9b14b97bf157553e0f8df146736c552d2cd204fcadbbedbda10d',
  '0x92c0a2ece114a264c1b2a7c6455128e989cc3b61fa7b6d221b9082f9125f6ebe5aea523832356b4e62dcaf450c8e4a4e',
  '0xa8cd53b7e405c5fe082bc83af2bc0a1ecdc9eb86d993261f14c86c2f9b277b49c5f4fb1525d5990c0e4d6c1cf7a9a9ef',
  '0xa9942e32c31a08c5ff7323585fb5713a6f9203ac3e17e5b54cbd97735ff37bdb57eb9b3f3f99ccf19e12bf5c572fec16',
  '0xb2146df890b699dfca7f8d9fc1293e9a02e4bdf52c8c76f4ad8d36139da0343b5a935d99268041c364a3d51c08518e4d',
  '0xab0c3a253e8d3f509f19b00f6c7cb771add5cfb246a8b0365bcb67af899429610ebb9986d72e30556673f30851428813',
  '0x83aa5be9831c7e5a9260310a696c548238f7f2278eb316f8a3007a4d908a8b714dfdf0620c49b4f2a5b53e56ae696a8c',
  '0x86bc5d19933ca5d0f4cfc95ac42e2344ec7cb459403a887b771a01872c5ad0c65e86756664c9f15e64d37a29fdc27e11',
  '0x85d49b088bbdd6cee38bd37b8e5d8cf84ad8658f4c6f3fc0d9ee89881a7fbee643e1fcdb843fd9c65f56dd52bf4e6b03',
  '0x8f2f6ce284de83af32fedcb153df0aad83c443027079ae22d86ad8ecddaa3ce6c1d7bcbb6348e7ab01ad0254b38ec80d',
  '0xa0078f00efb3c7961c0fc4b83015ef63b4614875b06ada1439dcdf6abc6b45032db0d4470217e8460f75061bd9874a7d',
  '0xab8e549cacb57996b7cd70c77e627e94c8a8a0a766a857357f1b7b104249599047768f85f3f466fd05a64d98c6fb3ce6',
  '0x949a127589b8957a34f4e7bdf60b7ebc5b27f9c0355d18c6cba9b2cc906ae8d4a44b7d29221aa8a41985d9a7d340ebd3',
  '0x97ce6fd7cf9a92f570ffc8bff64ab206ff21e7ea5ee3424c64dc31edcd4ce7815e077cef4bb2695901d38fac5492e041',
  '0xb8f3568d9f80bbd7a455aee2d3c4a558f310a86f7aa040a310b69eef249e197ac48e64ed9794226fb67d3a7e5f1ec3bf',
  '0xb05e71b31eae6b8e38ab5977c30d2d64bccdd326e118777ba9ac8c07ecefc8da821b32e8c2423b432d166fb36a5016e3',
  '0xb53b0d864d475e1ba5740e81a77b9bfa2fe97ce409ed9ade02ec3ed3f35edc5bb0a566b283599d3208ad680fc1a58049',
  '0xb6a269a8012a002671c18053fabc5aea03b884088b4e2049142ed8ce368a1f4cdb88d5e04f6daa2eb34c2b6a76fd4904',
  '0x830cc23c248bf21282f477033e3192e72c46f6d3d816dcc25625fd1de14429c7105eaa9c4869690f5fb4798b26c1eea1',
  '0xb78af98ba1fa1512e53f1e5c4710d43f720c1b547fd46c996672fc8ca81921b1c503ae8f6b184dc6b2f669c054c68a3c',
  '0x874af9468e3120cee1d1970699cc7f009ae88c43dfa13a9b8d627d1834e4b9142119b387bbe9e0a1509e25feea9a583a',
  '0xb2cba0ab0c909dec91de37461e6906af70d535ac61e64fd754af9df2c4e6d91f08570b4cd39f21b80ff52cf4ca4314eb',
  '0x8283d083f366d856d1a08f65d0feb1d5b841ebf9e139b1f08abfef6fc4359e609d48a279b73b27888301b544b24d5fb2',
  '0x818c71fed379c0d6655df42645de2a2401e6ae76d2c5c560b52dcc13e226de1a5c3ce6b3b78fa13adae2b83b35b6f211',
  '0xa98519699571228fe91ebd158d033c69864fee02d4a9184f6c14e84e5f7711ab8c0b986138a3f0a9aea0c9f848840e7b',
  '0x962dc22e6987078ea68edbb3e126a8655147efb3c61c87d800361c2ec59e26c7ac55ebe6400db0bb7014fd14c42fc893',
  '0xb1652d1eda8dc5f61302bc17115b11d6c1c798e24043c6e7126c1e203d7eaa836feedb5438dad7050000e433d6d926a7',
  '0xa29b789b09f30d88134a7ed857c8f068db73d8b4acbb8ed455eed775088d530e4fedaa24fb9a9575e0a43b0c30809b08',
  '0x94c1bbc5707dc7ca31871fe994acfdfabd34750494392b38be9aaa5cb8ae22c2643c63188d4c11aa16d94db1d882ca0e',
  '0x80883107f43d75b05466b84d8ae3563658504329f3ff15bdc4e8aa3ec333f8ae3a9b05a1b632aff4c4efc6350f8d76ba'

65 for 65. We did have a couple of issues where installs had been altered, so the node was on new secrets and validator.key details, but still running on the original staked values. We think we have redone them all now. There were 3 like this,

**Comment by laviniat1996** [comment]
@Nexsuperne101 After how many peers did you start seeing that error?

**Comment by ghost** [comment]
@laviniat1996 about 50. When we did this last time, and I didn't have the --max-peers 100 set, we never made it passed 51. Chain locked up. I think that was more down to --max-slots being set way too low.

**Comment by laviniat1996** [comment]
@Nexsuperne101 Thanks for all the info. I am looking into it today and trying to find a solution. Will keep you posted.

**Comment by ghost** [comment]
ok, thank you.

**Comment by laviniat1996** [comment]
@Nexsuperne101 You see the error only on bootnodes?

**Comment by ghost** [comment]
@laviniat1996 yes, only bootnodes.

**Comment by laviniat1996** [comment]
@Nexsuperne101 just to confirm, your block production didn't stop, right?

**Comment by ghost** [comment]
@laviniat1996 Blocks are still going.

**Comment by ghost** [comment]
@laviniat1996 

Did you manage to find a solution to this please? The chain crashed completely yesterday, when just 2 bootnodes out of 25 stopped working. Node 5, the one above, was displaying more and more errors about peer rejected. The --max-peers was set to 100 on all nodes, and we only had 66 nodes on the chain at the time.  At the moment, we are trying to get it to restart, but if there is an update that addresses the issue, then we'd like to install that first.

Thanks, Nex

**Comment by laviniat1996** [comment]
@Nexsuperne101 did those nodes display any other errors?

I found the cause of this issue, and we are working on it. But I couldn't tell you for sure when it will be ready.

I just want to make sure the node stopped because of that, and not cause of other issues that might have happened.

**Comment by ghost** [comment]
@laviniat1996 no, that's the only issues that it has shown so far. We did have a max-slots error on the first attempt, but that was cured with the new --max-slots value in the seal line. 
Thanks for your help, I look forward to a fix.

**Comment by laviniat1996** [comment]
@Nexsuperne101 I saw that you thought you had this issue too: `cannot parse long array: cannot parse array value: cannot parse empty string`

**Comment by ghost** [comment]
@laviniat1996 

I think that was an AWS server write issue. I restored the backup to a completely new instance on another server, and that cured it. Interestingly, one of the others saw the same issue on the N. Virginia servers a few days later. That's now on Ohio.

**Comment by laviniat1996** [comment]
@Nexsuperne101 If your chain has halted, stop all the nodes and start them again (that's the easiest way). Regarding that error, I will let you know when we have updates. This is all we can do for now.

**Comment by ghost** [comment]
@laviniat1996 What about the stray validator that is probably on Round=14 by now? Won't that stop us? We have 66 peers, how many do we need online to get it to restart please? I can co-ordinate it so that they are all started within seconds of each other. That stray node is not staked. PoS


Thanks, Nex

**Comment by laviniat1996** [comment]
If you try to get them on the same round, it could take an extremely long time. The time between rounds increases exponentially. If you stop them all, and then restart them, it will be much faster and easier.

**Comment by ghost** [comment]
@laviniat1996 
We can't find out who owns that last one. Is there any way to kick it from the network?

Thanks, Nex

**Comment by laviniat1996** [comment]
@Nexsuperne101 What do you mean by who owns the last one? The last validator?

**Comment by ghost** [comment]
@laviniat1996 
yes, we have no access to the person that created that validator, so we can't get them to shut it off. Is there a way round this situation?

Thanks, Nex

**Comment by laviniat1996** [comment]
@Nexsuperne101 try to remove it from the staking contract: https://wiki.polygon.technology/docs/edge/consensus/pos-stake-unstake#unstaking-funds, and then stop and start again the nodes (without that one ofc). If that node is not a validator anymore, it shouldn't affect the rounds (the rounds for all the validators when you start them should be the same).

**Comment by laviniat1996** [comment]
@Nexsuperne101 sorry, just realised that you probably don't have the private key for it :)

**Comment by ghost** [comment]
@laviniat1996 We are sure it isn't staked. We can't find any BLS or public wallet details in npm run info for it. All of the 66 on the stake list are accounted for.

Thanks, Nex

**Comment by laviniat1996** [comment]
@Nexsuperne101  Then that node isn't a validator. If it didn't stake, then it can't be part of the validators list.

**Comment by ghost** [comment]
@laviniat1996 We had a successful restart last night. We started 21 out of 25 boot nodes at 11pm UTC, and then at 11.15pm started adding the 41 validators  and the last 4 boot bodes. At 1:30am this morning the chain restarted. The unstaked node had no effect on the restart.

Thanks for all your help, Nex

**Comment by ghost** [comment]
One thing I have noticed is that we have 66 peers online, but only 30 show up in the peers list on each node. Are they just the ones connected to that particular node? I thought it would show system-wide?

**Comment by laviniat1996** [comment]
@Nexsuperne101 That's great news. So is the chain working now?

If you are talking about the peers-list command, it is normal that each node know only about certain other nodes, not all of them.

**Comment by ghost** [comment]
@laviniat1996  Yes, the chain went live about 37 hours ago now, much to my relief!  

Thanks for your reply, Nex

**Comment by laviniat1996** [comment]
@Nexsuperne101 You are very welcome, glad I could help. Will keep this issue open for when I have news about the peer rejected error.

**Comment by ghost** [comment]
Good morning. Have you managed to find a solution to the peers connection error? We are trying to list with a centralised exchange, but they are concerned that their node shows this error every so often. I know you said you had identified the cause.

Thanks, Nex
