### ISSUE TITLE
ibftOperator.getSnapshot changed response please communicate in Release notes

### ISSUE THREAD

**Issue by inglkruiz** [0xPolygon/polygon-edge#1019]
# ibftOperator.getSnapshot changed response please communicate in Release notes 
## Description
I'm using the GRPC endpoint `ibftOperator.getSnapshot` in GRPC client I built, this is the proto message I have, v0.5.1:
```proto
message Snapshot {
    repeated Validator validators = 1;

    uint64 number = 2;

    string hash = 3;

    repeated Vote votes = 4;

    message Validator {
        string address = 1;
    }

    message Vote {
        string validator = 1;
        string proposed = 2;
        bool auth = 3;
    }
}
```

In v0.6.0, the message changed to
```proto
message Snapshot {
    repeated Validator validators = 1;

    uint64 number = 2;

    string hash = 3;

    repeated Vote votes = 4;

    message Validator {
        string type = 1;
        string address = 2;
        bytes data = 3;
    }

    message Vote {
        string validator = 1;
        string proposed = 2;
        bool auth = 3;
    }
}
```

As you can see `Validator.address` was moved to be number 2, therefore my GRPC client started to read `type` when upgrading nodes to v0.6.0.

## Your environment
- OS and version: Kubernetes GCP/EKS
- The version of the Polygon Edge: v0.6.1
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.): Yes, they are!

## Steps to reproduce
N/A

## Expected behavior
N/A

## Logs
N/A

## Proposed solution
I do expect these changes to be communicated in the Release notes and/or have GRPC endpoints list in the Docs.

**Comment by ivanbozic21** [comment]
Hi @inglkruiz 
Can you please explain to us in a bit more detail how the following release change has affected your Edge environment?

**Comment by inglkruiz** [comment]
Sure, here's what happened.

 I have automated polygon edge node deployments and I have built a component, a GRPC client, that runs the voting round for adding new validators or removing them from the Blockchain network PoA. I use the Snapshot message for validating that a validator was successfully added to the Blockchain as well as when it's removed. When you changed Snapshot.Validator.address from number 1 to number 2, my GRPC client which was still using the proto file from the v0.5.1 started to read Snapshot.Validator.type because you changed the numbers, type is number 1 and address is number 2, I did update my nodes but I didn't know the proto file was modified, therefore, my GRPC client started to fail.

You could have avoided changing the numbers because it was an unnecessary change, Snapshot.Validator.type could have been added as number 2 instead of number 1, it was a new field in the message. Now, please don't rotate the numbers, but for new versions please consider that changes in your proto files might break third-party components, hence changes should be me communicated along with the release notes. That's my suggestion.

**Comment by ivanbozic21** [comment]
Hi @inglkruiz 
First of all, please accept our apology for not stating this change in our latest release note.

We can promise that changes of this kind will be clearly stated in our upcoming Edge releases.
