### ISSUE TITLE
polygon-edge version not working with go installation

### ISSUE THREAD

**Issue by jjbailey-io** [0xPolygon/polygon-edge#1041]
# polygon-edge version not working when installed via go
## Description
After installing polygon-edge, I attempted to determine the version of the polygon edge installation via the version command. This command did not output any useful info:

> [VERSION INFO]
> Release version = \<none>
> Git branch      = \<none>
> Commit hash     = \<none>
> Build time      = \<none>

## Your environment
- MacOS 13.0.1
- Go logs indicate the following version: v0.6.2-0.20221212114708-9cde1e330f54
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
```
$polygon-edge version --grpc-address http://localhost:10002
Error: unknown flag: --grpc-address
Usage:
   version [flags]

Flags:
  -h, --help   help for version

Global Flags:
      --json   get all outputs in json format (default false)
```

## Steps to reproduce

1. Install polygon-edge via the documented method (https://wiki.polygon.technology/docs/edge/get-started/installation#using-go-install): 
`go install github.com/0xPolygon/polygon-edge@develop`
2. Attempt to use the version flag for polygon-edge:
```
$polygon-edge version

[VERSION INFO]
Release version = <none>
Git branch      = <none>
Commit hash     = <none>
Build time      = <none>
```

## Expected behavior
I would expect the version to be displayed.

**Comment by laviniat1996** [comment]
Hi @johnathan-thrackle ,

If you have Edge on the develop branch, then it doesn't have any version associated with it. The develop branch doesn't  represent release. It's expected for the command to not return a version.

If you use one of the versions from [Releases](https://github.com/0xPolygon/polygon-edge/releases), then you will see it reflected in the version command too.

**Comment by jjbailey-io** [comment]
Ah, that make a lot of sense. I should have realized that. Thank you!
