### ISSUE TITLE
JSON-RPC error object should be wrapped within Response object

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#107]
##JSON-RPC error object should be nested within response object

### Description

While adding support for batch JSON-RPC requests (https://github.com/0xPolygon/polygon-sdk/pull/106), I noticed that the current implementation sends back error responses that aren't being nested within a response object - see https://www.jsonrpc.org/specification#error_object.

For example, the response body of an errored request currently appears as:
```
{"code":-32603,"message":"internal error"}
```
when it should actually be something more like:
```
{"id":1,"jsonrpc":"2.0", "error": {"code":-32603,"message":"internal error"} }
```

### Your environment

* OSX 11.4
* develop
* a0618c4 (latest on develop)

### Steps to reproduce

1. Run `./main dev...`
2. Used postman to send the following request (which errors since we are `unable to get block by num 0`):
```
{"id":1,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x0", true]}
```
3. Observed the following response:
```
{"code":-32603,"message":"internal error"}
```

### Expected behaviour

The response should have the error object nested to appear as:
```
{"id":1,"jsonrpc":"2.0", "error": {"code":-32603,"message":"internal error"} }
```

### Actual behaviour

Observed the following response instead:
```
{"code":-32603,"message":"internal error"}
```

**Comment by munna0908** [comment]
This issue is fixed, Here is the [PR](https://github.com/0xPolygon/polygon-sdk/pull/138).

Thanks for your inputs ..!!!
