### ISSUE TITLE
"tracer": "callTracer" not showing correct trace info

### ISSUE THREAD

**Issue by LuxesOwen** [0xPolygon/polygon-edge#1073]
# "tracer": "callTracer" not showing correct trace info
## Description
call debug_traceTransaction can't process my parameter {"tracer": "callTracer"}
## Your environment
- OS and version.
Linux version 5.10.118-111.515.amzn2.x86_64 (mockbuild@ip-10-0-43-203) (gcc10-gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1), GNU ld version 2.35-21.amzn2.0.1) #1 SMP Wed May 25 22:12:19 UTC 2022
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
v0.6.2
- The branch that causes this issue.
tag v0.6.2
- Locally or Cloud hosted (which provider).
aws
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).
no
## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

I send this request to my rpc
```
curl --location --request POST 'https://rpc.pioneer.etm.network' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc":"2.0", 
    "method":"debug_traceTransaction", 
    "params":[
        "0xfadf70d43fb9757ad0a9319fd1e79f511ddeb395c9a32b93ac43eeb3e6ba14b3", 
        {"tracer": "callTracer"}
    ], 
    "id":1
}'
```

## Expected behavior
- Tell us what should happen.
It should return trace info. but return all data.my parameter {"tracer": "callTracer"} didn't work.
- Tell us what happened instead.
It return result.json 
[result.json.zip](https://github.com/0xPolygon/polygon-edge/files/10293563/result.json.zip)

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
we use go-ethereum's tracers module add into polygon-edge v0.5.0,had solved this issue.But this time I update to v0.6.2 I dropped my tracers,then encounter this issue again.   
There's my old solution: https://github.com/ETM-Proterozoic/etmp-chain/tree/master/tracers

**Comment by ivanbozic21** [comment]
@LuxesOwen 
Thank you for providing all the details about the issue you encountered, and please know that we're reviewing them now.

**Comment by scalalang2** [comment]
👀

**Comment by ivanbozic21** [comment]
@LuxesOwen 
Unfortunately, the parameter callTracer is not supported in the latest release, and we will have to let you know in the next few days if and when it will be supported once again.

**Comment by LuxesOwen** [comment]
> @LuxesOwen Unfortunately, the parameter callTracer is not supported in the latest release, and we will have to let you know in the next few days if and when it will be supported once again.

OK.Thanks for reply.
We Looking forward to your updates.

**Comment by ivanbozic21** [comment]
Hi @LuxesOwen 
Because this is actually a custom endpoint, this is something that we're not responsible for fixing, and it's required to be adjusted on the third-party side. 

We will close this issue request.

**Comment by LuxesOwen** [comment]
@ivanbozic21 It is very regrettable,If more people and app use this way in the future,I wish you will consider supporting it.
