### ISSUE TITLE
Integration with Polygon-Edge with blockscout explorer create issues. Could you please help me out?

### ISSUE THREAD

**Issue by isingh108** [0xPolygon/polygon-edge#1079]
### Discussed in https://github.com/0xPolygon/polygon-edge/discussions/1072

<div type='discussions-op-text'>

<sup>Originally posted by **iqbalsingh108** December 23, 2022</sup>
# Blockscout doesn't show the creation code and bytecode of any smart contract
## Description
We have been trying to run a Polygon-edge chain with Blockscout as our block explorer since past 2 months. Blockscout works perfectly with Geth based chains.
 
The issue is that blockscout is unable to display the creation code and the bytecode for any smart contract.

Previously, whenever we tried to fetch a smart contract's code, the chain returned "unable to fetch code" error messages. This seems to have been fixed by the v0.6.2 release.

Is it due to the differences in RPC protocols of geth and polygon-edge? Do we need to go with polygon-supernets to build a production system?

## Your environment
- Ubuntu 20.04 LTS.
- v0.6.2 (unable to find "polygon-edge" in node's docker container)
- branch: develop.
- Cloud hosted: AWS.
- Docker Compose.

## Steps to reproduce
- setup a polygon-edge using docker compose cloud deployment.
- Run blockscout using docker compose after defining envirnoment variables

## Expected behavior
- Blocksouct should show the creation code and bytecode of smart contracts

## Proposed solution
The blockscout tutorial recommends the usage of Trapesys fork of blockscout. We tried it with the previous version of polygon-edge but that also showed identical errors/behavior.</div>

**Comment by ivanbozic21** [comment]
Hi @iqbalsingh108 

There was an issue with the previous develop branch which would explain the reason why you were getting unable to fetch code error messages.

Supernets is just a program and you can familiarize yourself with it by checking our FAQ section:

https://polygon.technology/supernets

> The issue is that blockscout is unable to display the creation code and the bytecode for any smart contract.

Can you please provide us with more details about this and how we can replicate this from our end?

**Comment by ivanbozic21** [comment]
@iqbalsingh108 do you still require further assistance with this query?

**Comment by ivanbozic21** [comment]
@iqbalsingh108 do you still require further assistance with this query?

**Comment by ivanbozic21** [comment]
Hi @iqbalsingh108 
We didn't hear back from you, and if you will require further assistance feel free to respond back to this query or raise a new one.

**Comment by Nexsuperne101** [comment]
What was the solution? I have just opened a ticket with exactly this issue. Thanks for your help!
