### ISSUE TITLE
Does not produce a Block on All Connected Servers & LocalHost

### ISSUE THREAD

**Issue by avenbreaks** [0xPolygon/polygon-edge#1090]
# [ Subject of the issue ]
## Description
can the version for 0.7.0 alpha1 be used for testing? i tried that version as reference material. on trying it produces no block at all the port is already enabled and my configuration is correct. but when trying to localhost it produces a block but in explorer it doesn't show any blocks at all.

`polygon-edge monitor --grpc-address 0.0.0.0:9632`

Block is produced but in explorer it is not visible only genesis-0 block is visible.

![Screenshot from 2022-12-31 18-00-59](https://user-images.githubusercontent.com/93043826/210208724-72ba9b24-a0fd-441d-86fb-4f0429ba7d03.png)

**Comment by ivanbozic21** [comment]
Hi @avenbreaks 

We can't provide you with support for alpha release, and please use the latest 0.6.2 for testing purposes.

For blockexplorer issues you will have to post a query under their official Github repo.
