### ISSUE TITLE
Premined Balance is zero on Private Chain based on Polygon-edge technology

### ISSUE THREAD

**Issue by SYSADMGARG** [0xPolygon/polygon-edge#1101]
# [ Premined Balance Is Zero]
## Description
Actually i'm stuck with some silly thing,i've deployed polygon-edge chain with release 0.6.2 but after the chain is deployed when i checked the balance of premined account its showing me 0 balance.I don't have any idea regarding why this happening???
If any suggestions or solution please let me know
Wallet i'm using is metamask
I'm using 0.6.2 release
4 nodes=2 bootnodes ,2 regular nodes and also all the nodes are validators.
My chain structure
Please provide your suggestions or solutions if anyone is listening.

## Your environment
- ubuntu 20.04.
- The version of the Polygon Edge=0.6.2 release.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue=Using source Code Zip.
- Locally or Cloud hosted (which provider)=AWS Cloud.
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.)=Nothing is running in containerized environment.

## Steps to reproduce
- Tell us how to reproduce this issue=Just Followed the Official doc of polygon-edge to setup private blockchain and after that added my network on metamask wallet but there is not premined balance for my account which i settted up in genesis of chain.
- Where the issue is, if you know=No idea about this.
- Which commands triggered the issue, if any=No idea.
- Provide us with the content of your genesis file=.{
    "name": "Meta-Chain",
    "genesis": {
        "nonce": "0x0000000000000000",
        "timestamp": "0x0",
        "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f90127f90120f8469481f77de688146625eab389e5f149f67cdc766cb4b0b71ab10cf1648fa575236c839e764bb9972603cc8df4924ee629a374708f>
        "gasLimit": "0x500000",
        "difficulty": "0x1",
        "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "coinbase": "0x0000000000000000000000000000000000000000",
        "alloc": {
            "0x0000000000000000000000000000000000001001": {
                "code": "0x6080604052600436106101185760003560e01c80637a6eea37116100a0578063d94c111b11610064578063d94c111b1461040a578063e387a7ed14610433578063e804fbf61461045e578063f90ecacc14610489578063facd743>
                "storage": {
                    "0x0000000000000000000000000000000000000000000000000000000000000000": "0x0000000000000000000000000000000000000000000000000000000000000004",
                    "0x0000000000000000000000000000000000000000000000000000000000000004": "0x0000000000000000000000000000000000000000000000022b1c8c1227a00000",
                    "0x0000000000000000000000000000000000000000000000000000000000000005": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0x0000000000000000000000000000000000000000000000000000000000000006": "0x000000000000000000000000000000000000000000000000001ffffffffffffe",
                    "0x062223b79041ffa469056a2f1d0529e76a65fbb0d1b1fb14f7c71df1fe4d702c": "0x0000000000000000000000000000000000000000000000008ac7230489e80000",
                    "0x067549999e2a415e89aeafcd77315d5fffd2fcc6f3b27d136201226c014bfbab": "0x0000000000000000000000000000000000000000000000000000000000000061",
                    "0x174374399c51283d3dd7039fe930a2b76474e3d95cab04ea6f9c6e3ae38412cd": "0xb05ac5a908eee75b5e497e00f1110971d6fcf0ac6019929c796ef561158bf138",
                    "0x174374399c51283d3dd7039fe930a2b76474e3d95cab04ea6f9c6e3ae38412ce": "0x5bd3926e5879afb7b62e8df327becd5900000000000000000000000000000000",
                    "0x1e58ec0971906261a3ef94c175ecb8e30e8fa1041e010ae2998fe5a8a5bb013a": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563": "0x00000000000000000000000081f77de688146625eab389e5f149f67cdc766cb4",
                    "0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e564": "0x000000000000000000000000ddc495ee26de5fd68745020bb2a8bd6107c2d2ba",
                    "0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e565": "0x000000000000000000000000abb69377c5e5125bd7e4f9c06146de5b13e55a33",
                    "0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e566": "0x0000000000000000000000000ff6b55130c44056e4e43b0538d5e2d537c5a466",
                    "0x315161a66b3a2dfffce955378676e7ded49077f83d453ba36b42aa701adc8772": "0x0000000000000000000000000000000000000000000000008ac7230489e80000",
                    "0x479132dce5b191d9ea0e3b2f6727a416fc713d7a072a6e8a5291fd3ee1722d23": "0x0000000000000000000000000000000000000000000000008ac7230489e80000",
                    "0x53da103e870bf641f4fb8c3a25406e6144c546fbdcf7b754e8f32f91760147e4": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0x5ff8f587493e474dc8631dc38a3dd288f44278e615d36ea36d0b6b64f8e5ef64": "0x0000000000000000000000000000000000000000000000000000000000000061",
                    "0x6055c67cda4f8914cd949ae81330e977eca6c0bdccbc082016724ccb8045e3b9": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0x65cc45ff06784e1c4a012137c7455c9036692dcc159f184b7825bcec22f0a34a": "0x0000000000000000000000000000000000000000000000000000000000000000",
                    "0x6e503c47d59c3b20258d3237396eb29b5815c4abe51f689022f8b7475797ef20": "0xb71ab10cf1648fa575236c839e764bb9972603cc8df4924ee629a374708fe301",
                    "0x6e503c47d59c3b20258d3237396eb29b5815c4abe51f689022f8b7475797ef21": "0x3ae1c38c9e0d0d8083ce062bc197861800000000000000000000000000000000",
                    "0x8aabef6aeb4a6e06e90f7487e3a86417a10371e9f14db23f89c654edcf3d461b": "0x0000000000000000000000000000000000000000000000008ac7230489e80000",
                    "0x96ea372db79d064770d2a405679f257fe0c54e42423b807a5839433e55628d8b": "0x0000000000000000000000000000000000000000000000000000000000000061",
                    "0xbddcb08712837268f68ff58f9a29c677035abd6377c1605c6390cb660d75540b": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0xc0d93d8a014b40dd1606bc732021011ea42279429436fe24f2653a8aedd1b825": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0xdb2f7cde8ab4aee49fa8ec79b47516e59d5afa00036d797310d42a3352e4c079": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0xe985cf054d32eaca8d7456e6eea0b0a5224d6980970c88fc64a446c21d9925c1": "0xb64ecaa2819f471721714ff2c7d0623ec85e48f5132bbe6f8ffe9d88ab25a29f",
                    "0xe985cf054d32eaca8d7456e6eea0b0a5224d6980970c88fc64a446c21d9925c2": "0xe2c8d732a5a02105ed56f10c3936777b00000000000000000000000000000000",
                    "0xf7111a9a04e566f2d03666d21962132c893df915b79eca3a8defc7d6d58d6c1a": "0xa23d2235a38414f6b52990622fa40ba0343c6638c3ee635966052ba4bf1f2666",
                    "0xf7111a9a04e566f2d03666d21962132c893df915b79eca3a8defc7d6d58d6c1b": "0x183683c6aec6ee8f86b5a5ddf353068f00000000000000000000000000000000",
                    "0xf7591913a5bb186664f1c6ae09cb30ff70fe6ede74664deeb00c77b1ee8f4e4f": "0x0000000000000000000000000000000000000000000000000000000000000061",
                    "0xf973b1172cab060bbaf1d47103858f94a1e76dc8492a1211f5d1d9aa36e1bf06": "0x0000000000000000000000000000000000000000000000000000000000000003"
                },
"balance": "0x22b1c8c1227a00000"
            },
            "0x817B1A14A7857009FE01a816CEc9163476339102": {
                "balance": "0x47868c00"
            }
        },
        "number": "0x0",
        "gasUsed": "0x70000",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
    },
    "params": {
        "forks": {
            "homestead": 0,
            "byzantium": 0,
            "constantinople": 0,
            "petersburg": 0,
            "istanbul": 0,
            "EIP150": 0,
            "EIP158": 0,
            "EIP155": 0
        },
        "chainID": 1011,
        "engine": {
            "ibft": {
                "epochSize": 50,
                "type": "PoS",
                "validator_type": "bls"
            }
        },
        "blockGasTarget": 0
    },
    "bootnodes": [
        "/ip4/184.169.172.50/tcp/1478/p2p/16Uiu2HAkwYw3nNUiL7hVAtHbGTLTAudQUfp77h7ituLDKmKjQpyy",
        "/ip4/52.9.77.116/tcp/1478/p2p/16Uiu2HAmPQZrzsUFs7RPUqm9qRe7QZvEqN7CMWjFsBqmrZraKDMv"
    ]
}
- Provide us with commands that you used to start your validators=polygon-edge server --data-dir ./node4 --chain genesis.json --libp2p 0.0.0.0:1478 --nat <Public Ip> --price-limit 4700000 --seal &.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`=[0] = 16Uiu2HAmPQZrzsUFs7RPUqm9qRe7QZvEqN7CMWjFsBqmrZraKDMv
[1] = 16Uiu2HAkwYw3nNUiL7hVAtHbGTLTAudQUfp77h7ituLDKmKjQpyy
[2] = 16Uiu2HAm4BENUyHGtXqHSZZzLdvb6f5ftZpHfzkpYEdeAs4cY1Mr.
- Is the chain producing blocks and serving customers atm=YES seems everything fine of chain end?

## Expected behavior
- Tell us what should happen=Premined Balance be in the Premined account.
- Tell us what happened instead=But Premined balance is zero in premined account.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`
![image](https://user-images.githubusercontent.com/90236304/211143221-704a6035-6c2e-4459-914a-74391b74b1c0.png)

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it
No idea but i just want to say
My issue is not that much big aur complicated
Simply my premined balance is not showing on setted premined account
One important thing is that i have setted up three private chains with same release 0.6.2 but 1 is working fine and showing balance and all but other 2 are giving only this balance issue
Thanks
![image](https://user-images.githubusercontent.com/90236304/211143278-3904823f-b922-4845-a38b-28ff91410db0.png)

**Comment by laviniat1996** [comment]
Hi @SYSADMGARG , 

From your genesis file, I guess this is the premined account: 0x817B1A14A7857009FE01a816CEc9163476339102, is that right?

**Comment by SYSADMGARG** [comment]
> Hi @SYSADMGARG ,
> 
> From your genesis file, I guess this is the premined account: 0x817B1A14A7857009FE01a816CEc9163476339102, is that right?

Yes @laviniat1996 
Also want to add i've tried with two latest releases of polygon-edge which 0.6.2 & 0.6.3 but nothing worked for me and there is one chain with release 0.6.2 is already running on my one of aws account servers which i setted up firstly which works perfectly.I don't have any idea what's going on???

Please provide your valuable suggestions and solutions for this ,actually i'm looking for production.
Thanks

**Comment by laviniat1996** [comment]
I understand. Can you please tell me how you are trying to see the balance of that account, are you using metamask? Do you have any block explorer? Looking forward to your reply.

**Comment by SYSADMGARG** [comment]
> I understand. Can you please tell me how you are trying to see the balance of that account, are you using metamask? Do you have any block explorer? Looking forward to your reply.

@laviniat1996 I'm checking with metamask right now i don't have any explorer right now

**Comment by laviniat1996** [comment]
One thing I want to add, are you 100% sure you imported the premined account via private key? You could try and import all the others just to be sure.

**Comment by SYSADMGARG** [comment]
> One thing I want to add, are you 100% sure you imported the premined account via private key? You could try and import all the others just to be sure.

@laviniat1996 My metamask is prfectly fine and my metamask is created on present browser and not transferred somewhere and there is another private chain based on polygon-edge is working fine but after this i've setted up another that is not working fine
No idea???

On strange thing is here that there is no error in logs all seems perfectly fine but why premined balance is not showing up in account??

**Comment by laviniat1996** [comment]
So basically, for each validator's account you have a private key. You should find it in the validator's directory, under consensus->validator.key. Did you import it to metamask?

**Comment by SYSADMGARG** [comment]
> So basically, for each validator's account you have a private key. You should find it in the validator's directory, under consensus->validator.key. Did you import it to metamask?

No,this all the procedure i haven't done

**Comment by laviniat1996** [comment]
Can you please try doing that and see if it works? Waiting for your updates.

**Comment by SYSADMGARG** [comment]
> Can you please try doing that and see if it works? Waiting for your updates.

ok let me try and one question so i've to import validator key which is generated with node dir on metamask right?

**Comment by laviniat1996** [comment]
Yes, exactly. And you can try to import all of the validators' private keys, just to make sure you get the right one.

**Comment by laviniat1996** [comment]
Also, please add your network to metamask if it isn't already added.

**Comment by SYSADMGARG** [comment]
> Also, please add your network to metamask if it isn't already added.

ok @laviniat1996 Let me try this and get back to you in a while

**Comment by SYSADMGARG** [comment]
@laviniat1996 What is the format of validator key in json or what?
![image](https://user-images.githubusercontent.com/90236304/211242595-2db0e143-1fad-4229-b787-00e500bc930b.png)
![image](https://user-images.githubusercontent.com/90236304/211242616-79b9f089-03da-41a7-b95f-e33e9bc4b361.png)
I'm trying with this,is this a right process?If not Please guide??

**Comment by SYSADMGARG** [comment]
![image](https://user-images.githubusercontent.com/90236304/211242871-973ca68a-9f45-4880-994c-88051f4044a8.png)
@laviniat1996 When i'm trying with my validators key,this is giving me an error as you're seeing in screenshot.

**Comment by laviniat1996** [comment]
@SYSADMGARG from where did you get the private key? the format should be something like this:
<img width="802" alt="image" src="https://user-images.githubusercontent.com/103824766/211246555-d2477c6d-8209-47cc-96c6-6911c2439471.png">

**Comment by SYSADMGARG** [comment]
> @SYSADMGARG from where did you get the private key? the format should be something like this: <img alt="image" width="802" src="https://user-images.githubusercontent.com/103824766/211246555-d2477c6d-8209-47cc-96c6-6911c2439471.png">

@laviniat1996 i got it from this command i've ran on node server
polygon-edge secrets output --data-dir test-chain-4

**Comment by SYSADMGARG** [comment]
> > @SYSADMGARG from where did you get the private key? the format should be something like this: <img alt="image" width="802" src="https://user-images.githubusercontent.com/103824766/211246555-d2477c6d-8209-47cc-96c6-6911c2439471.png">
> 
> @laviniat1996 i got it from this command i've ran on node server polygon-edge secrets output --data-dir test-chain-4

I think i'm doing a silly mistake i'm not removing 0x from this key.Let me try without this.

**Comment by SYSADMGARG** [comment]
@laviniat1996 no i tried but i think something i'm doing wrong,need your help in this.I'm doing right or not?

**Comment by laviniat1996** [comment]
That command doesn't give you the private key, instead it gives you the public key of that validator. To get the private key, you will need to go to the validator's directory-> consensus->validator.key.

**Comment by SYSADMGARG** [comment]
> That command doesn't give you the private key, instead it gives you the public key of that validator. To get the private key, you will need to go to the validator's directory-> consensus->validator.key.

@laviniat1996 I found the keys and tried with all of them but still not getting balance
found key on this path /node4/consensus

**Comment by laviniat1996** [comment]
did you check it for all nodes?

**Comment by SYSADMGARG** [comment]
> did you check it for all nodes?

yes one by one @laviniat1996 still balance is zero

**Comment by laviniat1996** [comment]
So, you took the private key from other paths, like /node1/consensus? Also, please make sure to add your network in metamask by going to settings->networks and here you can edit the localhost network.

**Comment by SYSADMGARG** [comment]
> So, you took the private key from other paths, like /node1/consensus? Also, please make sure to add your network in metamask by going to settings->networks and here you can edit the localhost network.

I've added my chain network on metamask and also tried the process of extracting validator.key from chain side and paste it on metamask import account tab but still not getting balance just new 4 accounts are created.
Also i've tried to check jspn rpc api commands to check the balance on rpc but it also shows me the balance in account.

**Comment by laviniat1996** [comment]
do you see any account in metamask that has this address: 0x817B1A14A7857009FE01a816CEc9163476339102? 

You should see the account's address here 
<img width="165" alt="image" src="https://user-images.githubusercontent.com/103824766/211250667-aa37669c-644b-4b0a-989f-aff04551da50.png">

**Comment by SYSADMGARG** [comment]
> do you see any account in metamask that has this address: 0x817B1A14A7857009FE01a816CEc9163476339102?
> 
> You should see the account's address here <img alt="image" width="165" src="https://user-images.githubusercontent.com/103824766/211250667-aa37669c-644b-4b0a-989f-aff04551da50.png">

![image](https://user-images.githubusercontent.com/90236304/211251247-60d962c2-2f92-4f59-8b0a-a0842bcc4735.png)
This is the account which i used for premined balance

But which is imported with validator keys
are:
![image](https://user-images.githubusercontent.com/90236304/211251351-de606e65-25f9-4156-a802-858057964baf.png)
![image](https://user-images.githubusercontent.com/90236304/211251383-dc7dbdf3-48de-44f9-8137-7d996f9cac6b.png)
![image](https://user-images.githubusercontent.com/90236304/211251418-9456553f-b1e3-4ab7-bcca-d772849c4384.png)
![image](https://user-images.githubusercontent.com/90236304/211251471-ab1a9e39-6081-419d-88c3-8b8ceecc40f1.png)

**Comment by SYSADMGARG** [comment]
> > do you see any account in metamask that has this address: 0x817B1A14A7857009FE01a816CEc9163476339102?
> > You should see the account's address here <img alt="image" width="165" src="https://user-images.githubusercontent.com/103824766/211250667-aa37669c-644b-4b0a-989f-aff04551da50.png">
> 
> ![image](https://user-images.githubusercontent.com/90236304/211251247-60d962c2-2f92-4f59-8b0a-a0842bcc4735.png) This is the account which i used for premined balance
> 
> But which is imported with validator keys are: ![image](https://user-images.githubusercontent.com/90236304/211251351-de606e65-25f9-4156-a802-858057964baf.png) ![image](https://user-images.githubusercontent.com/90236304/211251383-dc7dbdf3-48de-44f9-8137-7d996f9cac6b.png) ![image](https://user-images.githubusercontent.com/90236304/211251418-9456553f-b1e3-4ab7-bcca-d772849c4384.png) ![image](https://user-images.githubusercontent.com/90236304/211251471-ab1a9e39-6081-419d-88c3-8b8ceecc40f1.png)

Hope You're understanding my issue?
@laviniat1996

**Comment by laviniat1996** [comment]
Did you premine an account that isn't actually part of the validators for that network?

**Comment by SYSADMGARG** [comment]
> Did you premine an account that isn't actually part of the validators for that network?

no how can i premine because because that accounts are not the part of metamask till now.I just created or we can say imported with validator keys

**Comment by laviniat1996** [comment]
How did you get this account in metamask though, this is what i'm curious about
<img width="172" alt="image" src="https://user-images.githubusercontent.com/103824766/211253274-551d2a02-1d5c-4796-9c5d-ba53b5066372.png">
Cause, as you described the situation, none of the private keys for your validators imported this account to your metamask.

**Comment by SYSADMGARG** [comment]
> How did you get this account in metamask though, this is what i'm curious about <img alt="image" width="172" src="https://user-images.githubusercontent.com/103824766/211253274-551d2a02-1d5c-4796-9c5d-ba53b5066372.png"> Cause, as you described the situation, none of the private keys for your validators imported this account to your metamask.

I just used this account generally from metamask,i think something is wrong in choosing right account...

**Comment by SYSADMGARG** [comment]
@laviniat1996 I haven't created new account for this

**Comment by SYSADMGARG** [comment]
using the same account for different chains....

**Comment by laviniat1996** [comment]
so you just premined that specific account you had in metamask? is that right?

**Comment by SYSADMGARG** [comment]
> so you just premined that specific account you had in metamask? is that right?

yes @laviniat1996 i used one single account for different networks in my metamask.

**Comment by laviniat1996** [comment]
Okay, I get it now. Well, one problem could be the problem is that the network setup in metamask is not right. 
<img width="380" alt="image" src="https://user-images.githubusercontent.com/103824766/211254716-db400ea9-6a5b-413b-8770-01aeaa5ec88c.png">
The two things very important here are the chain ID, which is 100 if you didn't choose a certain one with `--chain-id ` flag, and the RPC URL.

**Comment by laviniat1996** [comment]
Of course, you need to fill in the info for your own network.

**Comment by SYSADMGARG** [comment]
> Okay, I get it now. Well, one problem could be the problem is that the network setup in metamask is not right. <img alt="image" width="380" src="https://user-images.githubusercontent.com/103824766/211254716-db400ea9-6a5b-413b-8770-01aeaa5ec88c.png"> The two things very important here are the chain ID, which is 100 if you didn't choose a certain one with `--chain-id ` flag, and the RPC URL.

I checked Everything is in right place as you described @laviniat1996 
Before i setup same chain with 0.6.2 release and but day before yesterday i again setted up new release 0.6.3

**Comment by laviniat1996** [comment]
How did you serup the same chain with the new release?

**Comment by SYSADMGARG** [comment]
> How did you serup the same chain with the new release?

https://wiki.polygon.technology/docs/edge/get-started/set-up-ibft-on-the-cloud
Following this for both releases case
What's your suggestion in this case,what i've to do now?

**Comment by laviniat1996** [comment]
@SYSADMGARG when you want to update your network to the latest release, that isn't the guide to follow. It basically sets up a whole new network. You just need to stop the nodes and change the binaries when updating.

**Comment by SYSADMGARG** [comment]
> @SYSADMGARG when you want to update your network to the latest release, that isn't the guide to follow. It basically sets up a whole new network. You just need to stop the nodes and change the binaries when updating.

Ya i know and you're absolutely right but i setted up a whole new chain with new releases.I don't bother the existing chain in my case.

**Comment by laviniat1996** [comment]
So, as far as the info from genesis goes, you do have a balance on this address 0x817B1A14A7857009FE01a816CEc9163476339102. And you have this account in your metamask. You have a cloud setup, right? Please make sure you used the right chain id and, very important, the correct RPC URL in metamask. Also, check if your ports are open.

**Comment by SYSADMGARG** [comment]
> So, as far as the info from genesis goes, you do have a balance on this address 0x817B1A14A7857009FE01a816CEc9163476339102. And you have this account in your metamask. You have a cloud setup, right? Please make sure you used the right chain id and, very important, the correct RPC URL in metamask. Also, check if your ports are open.

All checked twice and fine from my end.

**Comment by SYSADMGARG** [comment]
> So, as far as the info from genesis goes, you do have a balance on this address 0x817B1A14A7857009FE01a816CEc9163476339102. And you have this account in your metamask. You have a cloud setup, right? Please make sure you used the right chain id and, very important, the correct RPC URL in metamask. Also, check if your ports are open.

All checked again looks fine

**Comment by SYSADMGARG** [comment]
> So, as far as the info from genesis goes, you do have a balance on this address 0x817B1A14A7857009FE01a816CEc9163476339102. And you have this account in your metamask. You have a cloud setup, right? Please make sure you used the right chain id and, very important, the correct RPC URL in metamask. Also, check if your ports are open.
I'm using this command to run a server:
polygon-edge server --data-dir ./node1 --chain genesis.json --libp2p 0.0.0.0:1478 --nat "ip" --price-limit 4700000 --seal

**Comment by laviniat1996** [comment]
I'm curious why do you have the localhost ip address here: 
![image](https://user-images.githubusercontent.com/103824766/211282105-a6b53588-8faf-4e06-8ced-dcac44755320.png)
?

**Comment by SYSADMGARG** [comment]
> I'm curious why do you have the localhost ip address here: ![image](https://user-images.githubusercontent.com/103824766/211282105-a6b53588-8faf-4e06-8ced-dcac44755320.png) ?

From where you're checking these logs?

**Comment by laviniat1996** [comment]
from here:
<img width="911" alt="image" src="https://user-images.githubusercontent.com/103824766/211282648-d489e508-f502-4836-a2f5-906c26c6d7d4.png">

**Comment by SYSADMGARG** [comment]
> from here: <img alt="image" width="911" src="https://user-images.githubusercontent.com/103824766/211282648-d489e508-f502-4836-a2f5-906c26c6d7d4.png">

ok i don't know why

**Comment by laviniat1996** [comment]
I tried to reproduce this on my end, and the balance was reflected in metamask. I think the problem is with the setup you have. Was the premined balance  reflected on any of your chains?

**Comment by SYSADMGARG** [comment]
> I tried to reproduce this on my end, and the balance was reflected in metamask. I think the problem is with the setup you have. Was the premined balance reflected on any of your chains?

yes i've one chain which i setted up firstly with 0.6.2 release that one is working absolutely fine and from that i tally all thing but didn't found anything what's going wrong here

**Comment by laviniat1996** [comment]
And you can see the premined balance in metamask from that one?

**Comment by SYSADMGARG** [comment]
> And you can see the premined balance in metamask from that one?

yes
I'm not able to understand what is wrong

**Comment by SYSADMGARG** [comment]
As per you what points causes that kind of issue.If you elaborate then i can recheck again thoroughly.

**Comment by laviniat1996** [comment]
After creating this new network, did you change the RPC URL in metamask with the one for the new network?

**Comment by SYSADMGARG** [comment]
> After creating this new network, did you change the RPC URL in metamask with the one for the new network?

I just know that i setted up new neworks in metamask with respective rpc urls not from the another network

**Comment by laviniat1996** [comment]
What happens when you switch between those networks? Do you see any balance for that account on any of them?

**Comment by SYSADMGARG** [comment]
> What happens when you switch between those networks? Do you see any balance for that account on any of them?

I only see balance on that account which i premined  on first ever chain i setted with 0.6.2 and after that i setted up another chain with 0.6.2 or 0.6.3 there is no balance in premined account.

**Comment by laviniat1996** [comment]
So, for this network to which you provided the genesis file, the chain id is 1011, the rpc url is known to you only, and the premined address is this one 0x817B1A14A7857009FE01a816CEc9163476339102. You should be able to see the premined amount on this address when switching to this specific network in metamask.

**Comment by SYSADMGARG** [comment]
> So, for this network to which you provided the genesis file, the chain id is 1011, the rpc url is known to you only, and the premined address is this one 0x817B1A14A7857009FE01a816CEc9163476339102. You should be able to see the premined amount on this address when switching to this specific network in metamask.

But now i need balance on this address 0x337B1F7C3eD2d3Fc954b9dF496894832f48327E4

**Comment by SYSADMGARG** [comment]
Actually i tried again to resetup but same no balance with this address 0x337B1F7C3eD2d3Fc954b9dF496894832f48327E4 @laviniat1996

**Comment by SYSADMGARG** [comment]
Apologies for closure done by mistake @laviniat1996

**Comment by laviniat1996** [comment]
did you use your JSON RPC port in metamask?

**Comment by laviniat1996** [comment]
I would suggest you to stop all nodes, and add this flag to the command you are using for starting each node: `--jsonrpc 0.0.0.0:<port of your choice>`, and then use that port in metamask.

**Comment by SYSADMGARG** [comment]
> did you use your JSON RPC port in metamask?

yes i've used the port

**Comment by laviniat1996** [comment]
can you provide your network setup from metamask?

**Comment by SYSADMGARG** [comment]
> can you provide your network setup from metamask?

![image](https://user-images.githubusercontent.com/90236304/211458092-39408339-20d3-42eb-ae1a-4a12a263d076.png)
Please check this out @laviniat1996

**Comment by laviniat1996** [comment]
Can you try sending me some tokens by using this script? My account: 0x18558d7ec368B105bF9f830C085d52161F31ffa1.
```
var Web3 = require("web3");

const web3 = new Web3("<provider's websocket jsonrpc address>"); //example: ws://localhost:10002/ws
web3.eth.accounts
  .signTransaction(
    {
      to: "<recipient address>",
      value: web3.utils.toWei("100"),
      gas: 21000,
    },
    "<private key from premined account>"
  )
  .then((signedTxData) => {
    web3.eth
      .sendSignedTransaction(signedTxData.rawTransaction)
      .on("receipt", console.log);
  });
```
Fill in the data between <>. To get the private key for your account from metamask, click on account details, and then on export private key.

**Comment by SYSADMGARG** [comment]
> Can you try sending me some tokens by using this script? My account: 0x18558d7ec368B105bF9f830C085d52161F31ffa1.
> 
> ```
> var Web3 = require("web3");
> 
> const web3 = new Web3("<provider's websocket jsonrpc address>"); //example: ws://localhost:10002/ws
> web3.eth.accounts
>   .signTransaction(
>     {
>       to: "<recipient address>",
>       value: web3.utils.toWei("100"),
>       gas: 21000,
>     },
>     "<private key from premined account>"
>   )
>   .then((signedTxData) => {
>     web3.eth
>       .sendSignedTransaction(signedTxData.rawTransaction)
>       .on("receipt", console.log);
>   });
> ```
> 
> Fill in the data between <>. To get the private key for your account from metamask, click on account details, and then on export private key.

ok @laviniat1996  Let me do it for you,give me sometime

**Comment by SYSADMGARG** [comment]
![image](https://user-images.githubusercontent.com/90236304/211471781-6f512ce8-e2ef-4f43-a813-576822d396fa.png)
This 100 figure is chain id or what???
@laviniat1996

**Comment by SYSADMGARG** [comment]
> 0x18558d7ec368B105bF9f830C085d52161F31ffa1

![image](https://user-images.githubusercontent.com/90236304/211480653-6973ce6a-b61b-4a33-bf8c-fe4e5b4bbc20.png)
When i'm trying to run this script giving me error.Any idea? @laviniat1996

**Comment by SYSADMGARG** [comment]
@laviniat1996 I have one question that is there any aws cloud region specific limitations on chain because i just setted up the chain on my INDIAN origin account and its working fine with latest release 0.6.3 of polygon-edge with exact balance which i deployed for premined account.Please provide your views on this?

**Comment by laviniat1996** [comment]
@SYSADMGARG By setting up the chain you mean you created a new one on another aws account?

**Comment by laviniat1996** [comment]
@SYSADMGARG We do not have any region limitations. I think it could have been a problem with the previous setup somewhere, and now it works because everything was done right. Glad it finally works 💯

**Comment by SYSADMGARG** [comment]
@laviniat1996 Ya but sometime its not working
![image](https://user-images.githubusercontent.com/90236304/211773753-a7da7232-cdfa-4ba8-9be1-71dba69b58a9.png)

**Comment by laviniat1996** [comment]
does this happen randomly?

**Comment by SYSADMGARG** [comment]
> does this happen randomly?

@laviniat1996 Please give me time of one or two or maximum till monday.I'll give you proper scenario details with you so that this can help you further.
Thanks

**Comment by SYSADMGARG** [comment]
Hi @laviniat1996 
Hope you're doing good
Apologies much delayed in the status on my issue.Actually Present status on my issue is that its working sometime but giving same issue randomly.I don't have any idea.I thought this is some cloud region specific issue but no this is not.I've one chain which is working perfectly and showing balance after too much efforts no extra specification amd with same efforts or configuration another chain is not showing balance.
Thats it for now.
If you found something let me know
Version of polygon-edge in my case is 0.6.3
Thanks

**Comment by laviniat1996** [comment]
Hello @laviniat1996 , good to hear back from you :).
Can you please provide some logs of how your network is working now. Also, if on one chain the balance shows up okay, then it probably isn't an Edge problem with that.

**Comment by SYSADMGARG** [comment]
> Hello @laviniat1996 , good to hear back from you :). Can you please provide some logs of how your network is working now. Also, if on one chain the balance shows up okay, then it probably isn't an Edge problem with that.

What kind of logs you're looking for 

can you please provide me the command which output you want right now?

**Comment by SYSADMGARG** [comment]
Hey @laviniat1996 
My issue is resolved and i found where i'm wrong,actually my team member is giving me premined balance figure in ETH format not in Wei thats why my balance is not visible on metamask.
Thanks for your such a kind support.
You can now close this Issue if you want.

Thanks once again.

**Comment by laviniat1996** [comment]
@SYSADMGARG You are very welcome. I'm glad everything got sorted out. Please feel free to reach out again whenever you encounter a problem or have any questions! 🙏
