### ISSUE TITLE
Failed to fetch internal transactions for blocks

### ISSUE THREAD

**Issue by mrdernst** [0xPolygon/polygon-edge#1108]
# Failed to fetch internal transactions for blocks
## Description
When I host a node cluster on AWS and configure BlockScount on a separate server, the RPC node is not providing internal transactions. When BlockScout requests them, the following errors are thrown:

```
Jan 10 10:24:47 mix[63595]: 2023-01-10T10:24:47.495 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: %MatchError{term: []}
Jan 10 10:24:47 mix[63595]: 2023-01-10T10:24:47.549 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: %ArgumentError{message: "errors were found at the given arguments:\n\n  * 1st argument: not a textual representation of an integer\n"}
Jan 10 10:24:47 mix[63595]: 2023-01-10T10:24:47.549 application=indexer fetcher=internal_transaction count=10 error_count=10 [error] failed to fetch internal transactions for blocks: %FunctionClauseError{args: nil, arity: 1, clauses: nil, function: :integer_to_quantity, kind: nil, module: EthereumJSONRPC}
```

## Your environment
- Polygon-Edge-Node-Server: Amazon Linux 2 (Karoo) | BlockScout-Server: Ubuntu 20.04.5 LTS
- Polygon Edge Version: v0.6.3
- Tag v0.6.3
- Cloud hosted (AWS).
- The Validators are not running containerized.

## Steps to reproduce
- Deploy a default Edge-Cluster with 4 nodes
- Deploy a default BlockScout-Server and connect it with one of the Edge-Nodes through RPC
Important config:
```
ETHEREUM_JSONRPC_VARIANT="geth"
INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER="false"
```
- start everything up and in the log of the BlockScout-Service you can see the errors mentioned above.

## Expected behavior
- The internal transactions should be parsed
- The data for the internal transactions is not available

## Logs
[https://pad.envs.net/pad/#/2/pad/edit/g8CE6MGk2QKq7i5OJqAf8Mfu/](url)

**Comment by ivanbozic21** [comment]
Hi @mrdernst 
We can't provide support for Blockscout logs, and you will have to raise an issue at their Github repo:

https://github.com/blockscout/blockscout

Let us know if you will have any further queries.
