### ISSUE TITLE
Validator rewards question

### ISSUE THREAD

**Issue by adaki2004** [0xPolygon/polygon-edge#1119]
# [ Validator rewards ]
## Description
I would like to set up faucet contract(s) and therefore I'd like to redirect the funds from validator rewards to that contract on a polygon edge private blockchain.
I know `premine` flag which works fine for me, but how can I access the rewards of the validators (if they have any?)

## Your environment
- Currently running 4 nodes in docker, minikube environment with 4 nodes
- Latest image on dockerhub  

## Expected behavior
Maybe I have forgotten some flags, or searching for something wrong.
polygon.server.ibft: validator key: addr=0x5f00f9614d1b990770744Aed2E3b4C8eFda77cF8

Through RPC i'm querying the validator key for eth_getBalance and shows me 0, while the premined account has the proper amount of native token.

Is there any flag I need to supply in order to get those rewards ?

This is how I invoke polygon-edge to create genesis:

```
polygon-edge genesis \
            --dir "$GENESIS_PATH" \
            --consensus ibft \
            --ibft-validators-prefix-path data- \
            --premine=XXXXXXXXXXX:100000000000000000000000 \
            --bootnode /dns/node-1/tcp/1478/p2p/$(echo $secrets | jq -r '.[0] | .node_id') \
            --bootnode /dns/node-2/tcp/1478/p2p/$(echo $secrets | jq -r '.[1] | .node_id')
```

And this is how i start the nodes:
```
    - args:
        - server
        - --data-dir
        - /data/data-1
        - --chain
        - /data/genesis.json
        - --grpc-address
        - 0.0.0.0:9632
        - --libp2p
        - 0.0.0.0:1478
        - --jsonrpc
        - 0.0.0.0:8545
        - --prometheus
        - 0.0.0.0:5001
        - --seal
```

Thank you in advance!

**Comment by laviniat1996** [comment]
Hello @adaki2004 ,
The rewards for each validator are stored on that validator's account. To get the rewards, you can use their private keys, import them in a wallet and access those funds.
