### ISSUE TITLE
Block miner hash value always 0x0 in `eth_getBlockBy*` jsonrpc response

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#112]
### Description

According to https://eth.wiki/json-rpc/API#eth_getBlockByHash, the miner hash should be "the address of the beneficiary to whom the mining rewards were given" (or the address of the block's validator).

Using either the `dev` or `server` command - and tested on both `eth_getBlockByNumber` and `eth_getBlockByHash`, I always see the miner value being: 
```
0x0000000000000000000000000000000000000000
```

I expect the miner value to be one of the validator's addresses.

### Your environment

* OS and version `OSX 11.4`
* version of the Polygon SDK https://github.com/0xPolygon/polygon-sdk/commit/ad7b97eeb3a8b66346730b844e0c609992f0efdf
* branch that causes this issue `develop`

### Steps to reproduce

1. Set up 4 nodes, each running `./main server...` and ensure all 4 nodes have visibility of eachother:
```
2021-08-03T23:54:36.390Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=25530
2021-08-03T23:54:36.390Z [INFO]  polygon.consensus.ibft: current snapshot: validators=4 votes=0
2021-08-03T23:54:36.390Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x40dd53141a759efd606a13d3e8a7c0aa005faf35 block=25530
```
2. Send HTTP request `{"id":1,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", true]}`
3. Observe that the miner of the JSON-RPC response object is always:
```
"miner":"0x0000000000000000000000000000000000000000"
```

### Expected behaviour

I expect the miner value to be one of the validator's addresses. In my example above running 4 validators, I expect the miner hash to be the address of one of those 4 validators.

### Actual behaviour

I always see the HTTP response containing:
```
"miner":"0x0000000000000000000000000000000000000000"
```
which makes it difficult to determine who mined the block.

**Comment by lazartravica** [comment]
@dankostiuk The consensus used currently in polygon-sdk is IBFT, which is implemented according to https://github.com/ethereum/EIPs/issues/650 which in turn builds upon the voting mechanism explained in Clique PoA: https://github.com/ethereum/EIPs/issues/225

Looking at the EIP-225 (Clique PoA), this is the relevant part that explains what the `miner` (aka `beneficiary`) is used for: 

```
We repurpose the ethash header fields as follows:

    beneficiary: Address to propose modifying the list of authorized signers with.
        Should be filled with zeroes normally, modified only while voting.
        Arbitrary values are permitted nonetheless (even meaningless ones such as voting out non signers) to avoid extra complexity in implementations around voting mechanics.
        Must be filled with zeroes on checkpoint (i.e. epoch transition) blocks.
```

thus, you can see that the `miner` field is used for proposing a vote for a certain address, not to show the proposer of the block.

The information about the proposer of the block can be found by recovering the pubkey from the Seal field of the RLP encoded Istanbul extra data field in the block headers.
