### ISSUE TITLE
not enough seals to seal block

### ISSUE THREAD

**Issue by LuxesOwen** [0xPolygon/polygon-edge#1127]
# not enough seals to seal block
## Description
In our prod env. the max validator count=21,min validator count=3,we had start 15 validators at the same time,then got this error.
Please help to explain how it was caused?

## Your environment
- OS and version.
Linux version 5.10.118-111.515.amzn2.x86_64 (mockbuild@ip-10-0-43-203) (gcc10-gcc (GCC) 10.3.1 20210422 (Red Hat 10.3.1-1), GNU ld version 2.35-21.amzn2.0.1) 
- The version of the Polygon Edge.
v0.6.3
- The branch that causes this issue.
tag v0.6.3
- Locally or Cloud hosted (which provider).
aws
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).
no
## Steps to reproduce
- Which commands triggered the issue, if any.
start servers

- Provide us with commands that you used to start your validators.
```
/data/etmp/bin/etmp-chain server \
    --data-dir /data/etmp/data/node7 \
    --chain /data/etmp/conf/genesis.json \
    --grpc 0.0.0.0:10000 \
    --libp2p 0.0.0.0:10001 \
    --jsonrpc 0.0.0.0:10002 \
    --prometheus 127.0.0.1:9002 \
    --price-limit 12000000000 \
    --log-level DEBUG \
    --seal
```

## Logs
Provide us with debug logs from all of your validators by setting logging to debug output with: server --log-level debug
<img width="851" alt="image" src="https://user-images.githubusercontent.com/66360114/212628794-7ca02e92-c482-4025-8840-91e9b796673a.png">
2023-01-14T08:05:02.752Z [WARN]  polygon.server.syncer: failed to complete bulk sync with peer, try to next one: peer ID=error 16Uiu2HAmB23bwsaDLHWsH7fK2HbSyT3VNUHmcWY7UeQ7idd1Kwdy="unable to verify block, failed to verify the header: not enough seals to seal block"

**Comment by LuxesOwen** [comment]
I had reproduced this issue in our test env. I start 6 nodes in one server,they running well.I move one node to another server,then the same issue appeared in the single node. 
<img width="817" alt="image" src="https://user-images.githubusercontent.com/66360114/212641398-5558b35d-7f3d-4696-8b14-1c7f16190d14.png">

**Comment by laviniat1996** [comment]
Hi @LuxesOwen ,
While reproducing this in your test env,  did you use the same genesis file for the 7th node?

**Comment by LuxesOwen** [comment]
> Hi @LuxesOwen , While reproducing this in your test env, did you use the same genesis file for the 7th node?

Yes,They use same genesis file,but the 7th node could only sync blocks completely,then arise above warnning.

**Comment by laviniat1996** [comment]
@LuxesOwen PoA or PoS? bls or ecdsa?

**Comment by LuxesOwen** [comment]
> @LuxesOwen PoA or PoS? bls or ecdsa?

PoS and ecdsa

**Comment by laviniat1996** [comment]
did you update from an earlier version? if so, from which one?

**Comment by laviniat1996** [comment]
Also, when reproducing this, did you move one of those six nodes or created a seventh one?

**Comment by LuxesOwen** [comment]
I had update your v0.6.3,but we changed some this about kms and forks. here is our repo :https://github.com/ETM-Proterozoic/etmp-chain

**Comment by LuxesOwen** [comment]
> Also, when reproducing this, did you move one of those six nodes or created a seventh one?
At first time I stopped sixth node, then created new one in another server.
Later I start the sixth node again,No matter how I tried I can't running 7th node normally with --seal.

**Comment by LuxesOwen** [comment]
At first time I stopped sixth node, then created new one in another server.
Later I start the sixth node again,No matter how I tried I can't running 7th node normally with --seal.

**Comment by laviniat1996** [comment]
Thanks for the info. Did you vote for addition for the 7th node?

**Comment by LuxesOwen** [comment]
> Thanks for the info. Did you vote for addition for the 7th node?

Tanks for your help. I havn't vote it .It still not a validator.

**Comment by LuxesOwen** [comment]
In my test env. I set max validators count=5

**Comment by laviniat1996** [comment]
If you want it to not be a validator, this is how to start a non-validator node: https://wiki.polygon.technology/docs/edge/get-started/set-up-ibft-on-the-cloud#step-4-run-all-the-clients . Please let me know if this worked.

**Comment by laviniat1996** [comment]
Even so, that 7th node should still be able to sync up with other nodes on block production..

**Comment by LuxesOwen** [comment]
No,I want it to be a validator by voting at sometime.So it should have seal function.

**Comment by LuxesOwen** [comment]
We have other non-validator node

**Comment by laviniat1996** [comment]
As a side note, you don't need to include the seal flag on the server command. It is deprecated.

**Comment by laviniat1996** [comment]
can you try the following trick: backup the data directory from a working node and restore it onto the non-validating node (7th one)?

**Comment by LuxesOwen** [comment]
OK,I will try.

**Comment by laviniat1996** [comment]
great, looking forward to updates

**Comment by LuxesOwen** [comment]
Hi @laviniat1996 ,I stopped all nodes ,then copy data from 6th node to 7th node. Then start all 7 nodes at the same time,all of them could running nomally. That is to say my chain could not create an new node without backup data..We have had a fork of the chain,Should it be the problem it causes?

**Comment by laviniat1996** [comment]
So all nodes are running okay at the moment, right? 
Would be helpful if you could provide the genesis for this chain, and also which commands you used to generate the keys. Did you create the chain from scratch while on v0.6.3?

**Comment by LuxesOwen** [comment]
Yes, all nodes running OK now.
Our chain is probably created from polygon-edge v0.2.1,all the way up to now.

genesis file
```
{
    "name": "etmp-testnet",
    "genesis": {
        "nonce": "0x0000000000000000",
        "timestamp": "0x0",
        "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f858f854941645b9512c43a5a792df86631be18ee34397337a942860fd12b5687a3fe1a1cd3cbd213d7054e53976940489b78aa10490ee0a03c65944db56428fe7784b945f73f812c2e4cad5ab6b81b1068a7221abc62a3880c0",
        "gasLimit": "0x1c9c380",
        "difficulty": "0x1",
        "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "coinbase": "0x0000000000000000000000000000000000000000",
        "alloc": {
            "0x0000000000000000000000000000000000001001": {
            "code": "6080604052600436106100b15760003560e01c806322dc5595146101065780632367f6b51461011b5780632def662014610160578063373d6132146101755780633a4b66f11461018a5780633fd1e3a8146101925780634d238c8e146101c557806350d68ed8146101f85780636a768705146102295780637f2f2914146102575780638f8451b21461028a578063ca1e7819146102bb578063f90ecacc14610320578063facd743b1461034a57610101565b36610101576100bf33610391565b156100ff576040805162461bcd60e51b815260206004820152601a6024820152600080516020610a2d833981519152604482015290519081900360640190fd5b005b600080fd5b34801561011257600080fd5b506100ff6103cf565b34801561012757600080fd5b5061014e6004803603602081101561013e57600080fd5b50356001600160a01b031661046d565b60408051918252519081900360200190f35b34801561016c57600080fd5b506100ff610494565b34801561018157600080fd5b5061014e61053e565b6100ff61054e565b34801561019e57600080fd5b506100ff600480360360208110156101b557600080fd5b50356001600160a01b0316610597565b3480156101d157600080fd5b506100ff600480360360208110156101e857600080fd5b50356001600160a01b03166105ee565b34801561020457600080fd5b5061020d610642565b604080516001600160801b039092168252519081900360200190f35b34801561023557600080fd5b5061023e61064e565b6040805163ffffffff9092168252519081900360200190f35b34801561026357600080fd5b506100ff6004803603602081101561027a57600080fd5b50356001600160a01b0316610653565b34801561029657600080fd5b5061029f61070d565b604080516001600160a01b039092168252519081900360200190f35b3480156102c757600080fd5b506102d061071c565b60408051602080825283518183015283519192839290830191858101910280838360005b8381101561030c5781810151838201526020016102f4565b505050509050019250505060405180910390f35b34801561032c57600080fd5b5061029f6004803603602081101561034357600080fd5b503561077e565b34801561035657600080fd5b5061037d6004803603602081101561036d57600080fd5b50356001600160a01b03166107a5565b604080519115158252519081900360200190f35b6000813f7fc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a4708181148015906103c557508115155b925050505b919050565b6005546001600160a01b0316156103e557600080fd5b600580546001600160a01b03191633179055610414737d409286bc68144fb4aa0fedfbd886d896fa2a866107c3565b61043173653b492bb119689e33c3c8ace65c29b9b0f8dd266107c3565b61044e73224b67b83301ddb7138ed2a83cfaf551b40be72a6107c3565b61046b73125ccffad7d46408b20c9b13e1273f1fc6799c126107c3565b565b6000610478826107a5565b1561048c5750670de0b6b3a76400006103ca565b5060006103ca565b61049d33610391565b156104dd576040805162461bcd60e51b815260206004820152601a6024820152600080516020610a2d833981519152604482015290519081900360640190fd5b3360009081526002602052604090205461046b576040805162461bcd60e51b815260206004820152601d60248201527f4f6e6c79207374616b65722063616e2063616c6c2066756e6374696f6e000000604482015290519081900360640190fd5b600054670de0b6b3a76400000290565b61055733610391565b1561046b576040805162461bcd60e51b815260206004820152601a6024820152600080516020610a2d833981519152604482015290519081900360640190fd5b6005546001600160a01b031633146105e2576040805162461bcd60e51b81526020600482015260096024820152686f6e6c792064706f7360b81b604482015290519081900360640190fd5b6105eb8161086e565b50565b6005546001600160a01b03163314610639576040805162461bcd60e51b81526020600482015260096024820152686f6e6c792064706f7360b81b604482015290519081900360640190fd5b6105eb816107c3565b670de0b6b3a764000081565b600381565b6005546001600160a01b0316331461069e576040805162461bcd60e51b81526020600482015260096024820152686f6e6c792064706f7360b81b604482015290519081900360640190fd5b6001600160a01b0381166106b157600080fd5b6005546040516001600160a01b038084169216907fb98b0beca16ce6abcd208c67386b7903b2fbd3cd854ea7cdeb5745277d01dc4e90600090a3600580546001600160a01b0319166001600160a01b0392909216919091179055565b6005546001600160a01b031681565b6060600080548060200260200160405190810160405280929190818152602001828054801561077457602002820191906000526020600020905b81546001600160a01b03168152600190910190602001808311610756575b5050505050905090565b6000818154811061078b57fe5b6000918252602090912001546001600160a01b0316905081565b6001600160a01b031660009081526001602052604090205460ff1690565b3360009081526001602052604090205460ff166105eb576001600160a01b0381166000818152600160208181526040808420805460ff1916841790558354600390925280842082905591810183558280527f290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e5630180546001600160a01b03191684179055517fe366c1c0452ed8eec96861e9e54141ebff23c9ec89fe27b996b45f5ec38849879190a250565b6001600160a01b03811660009081526001602052604090205460ff1615806108995750600054600310155b156108a3576105eb565b600080546001600160a01b0383168252600360205260409091205410610905576040805162461bcd60e51b8152602060048201526012602482015271696e646578206f7574206f662072616e676560701b604482015290519081900360640190fd5b6001600160a01b03811660009081526003602052604081205490546000190180821461099b57600080828154811061093957fe5b600091825260208220015481546001600160a01b0390911692508291908590811061096057fe5b600091825260208083209190910180546001600160a01b0319166001600160a01b039485161790559290911681526003909152604090208290555b6001600160a01b0383166000908152600160209081526040808320805460ff19169055600390915281208190558054806109d157fe5b600082815260208120820160001990810180546001600160a01b03191690559091019091556040516001600160a01b038516917fa7a579573d398d7b67cd7450121bb250bbd060b29eabafdebc3ce0918658635c91a250505056fe4f6e6c7920454f412063616e2063616c6c2066756e6374696f6e000000000000a2646970667358221220882158442c33283da2afbaae126e54d7a0b13a52129fad962034884c9766ce0d64736f6c634300060c0033",
            "storage": {
                    "0x0000000000000000000000000000000000000000000000000000000000000000": "0x0000000000000000000000000000000000000000000000000000000000000004",
                    "0x0000000000000000000000000000000000000000000000000000000000000005": "0x000000000000000000000000a311a9ede8900ffd5b9bab1c3234ea34e5c9878f",
                    "0x1252dcf457671f27fddee49e8e50747c857f50c77c1e88359206ce601330c4cd": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e563": "0x0000000000000000000000001645b9512c43a5a792df86631be18ee34397337a",
                    "0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e564": "0x0000000000000000000000002860fd12b5687a3fe1a1cd3cbd213d7054e53976",
                    "0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e565": "0x0000000000000000000000000489b78aa10490ee0a03c65944db56428fe7784b",
                    "0x290decd9548b62a8d60345a988386fc84ba6bc95484008f6362f93160ef3e566": "0x0000000000000000000000005f73f812c2e4cad5ab6b81b1068a7221abc62a38",
                    "0x3e82107690a2749765edace21a7d61793fdff3ef2089fe3639b78bb73add2c57": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0x6038fbc190b8381adac1e444b76185000975bee58feaa1283d37d8533e265a7d": "0x0000000000000000000000000000000000000000000000000000000000000003",
                    "0x9051fb47a6b60c0a93ff7f5d21cdf999313201d6224781d063f08a95c79502f2": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0x943e0a49cd29fa58aa6c03f8144d2460bc11a93c7f7cae5500c1f367916b433c": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0xb5466c55c8eae1deed7e6ee319174d40eff262d2320f461be113966362729a07": "0x0000000000000000000000000000000000000000000000000000000000000001",
                    "0xda0cfca5a8e8170e9fa2e2b56e8cffa8eacf0337cdf962a8c20c7b9590c579b7": "0x0000000000000000000000000000000000000000000000000000000000000002"
                },
                "balance": "0x0"
            },
            "0xa311a9ede8900ffd5b9bab1c3234ea34e5c9878f": {
                "balance": "0x92349635c9adc5dea00000"
            }
        },
        "number": "0x0",
        "gasUsed": "0x70000",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
    },
    "params": {
        "forks": {
            "homestead": 0,
            "byzantium": 0,
            "constantinople": 0,
            "petersburg": 0,
            "istanbul": 0,
            "EIP150": 0,
            "EIP158": 0,
            "EIP155": 0,
            "chainIDChange":2696777
        },
        "chainID": 49,
        "oldChainID": 37,
        "engine": {
            "ibft": {
                "epochSize": 300,
                "type": "PoS"
            }
        },
        "blockGasTarget": 0
    },
    "bootnodes": [
        "/ip4/127.0.0.1/tcp/10001/p2p/16Uiu2HAkyAHZTf85dbqQLCyhMZBVDoguJBVHZ1RLxa2oNtAPXPGb",
        "/ip4/127.0.0.1/tcp/20001/p2p/16Uiu2HAm4R5oBDkxNmPphur9YS88bmow2TYxWLHcTucvjAD6Ybgi",
        "/ip4/127.0.0.1/tcp/30001/p2p/16Uiu2HAmUgmLLccJDwZhJkRKdFzD5rUn1uTrq6JuUtP5ZFTeJepv",
        "/ip4/127.0.0.1/tcp/40001/p2p/16Uiu2HAm9EgrzfLdRJi6PHdMdwm8sgdTF5ZFn5yH6NuohvwtGXP1"
    ]
}
```

commands used to generate keys :
polygon-edge secrets init --data-dir test-chain-1

**Comment by laviniat1996** [comment]
Just to make sure, you have two chains: one with 15 nodes, and another one created for testing this issue, is that right?

**Comment by LuxesOwen** [comment]
We have two chains:main network have 15 nodes max 21 validators,test network have 7 nodes now max 5 validators.I use test network to testing this issue just now,not a local test env.

**Comment by laviniat1996** [comment]
Yes. that's why I'm asking...it would help me to see the genesis for the test chain too

**Comment by LuxesOwen** [comment]
OK,you also can see this chain on chainlist.org, Looking forward to your updates.

**Comment by LuxesOwen** [comment]
Hi @laviniat1996 ,I had track the variables of function signer.VerifyCommittedSeals,It output "numSeals:3 quorumSize:4"
I noticed you had modified the verify logic of this part after v0.6.
<img width="628" alt="image" src="https://user-images.githubusercontent.com/66360114/213108584-8b6d8660-0e14-4f75-914a-d0ab917058d2.png">

**Comment by laviniat1996** [comment]
@LuxesOwen  Sorry for the late reply, looking into this right now. Will provide an update later today or tomorrow.

**Comment by LuxesOwen** [comment]
> @LuxesOwen Sorry for the late reply, looking into this right now. Will provide an update later today or tomorrow.

Never mind.Just let me know if you got any progress.

**Comment by LuxesOwen** [comment]
hi,@laviniat1996
I went on to track this issue,Then I found the sync progress interruptted at a same block every time.
The reason is probably that I added a validator at that time.I printted the following logs from function ibft.VerifyHeader().

Logs of blocks sync success:
——validators.Len:4 ——validators:&{ValidatorType:ecdsa Validators:[0x1645B9512c43a5A792dF86631Be18eE34397337a 0x2860fD12b5687A3fe1A1cd3CBD213d7054E53976 0x0489b78Aa10490ee0a03c65944DB56428fE7784b 0x5F73f812C2e4CAD5Ab6B81b1068a7221ABC62A38]} 
——numSeals:3 ——quorumSize:3 

Logs of blocks sync failed:
——validators.Len:5 ——validators:&{ValidatorType:ecdsa Validators:[0x1645B9512c43a5A792dF86631Be18eE34397337a 0x2860fD12b5687A3fe1A1cd3CBD213d7054E53976 0x0489b78Aa10490ee0a03c65944DB56428fE7784b 0x5F73f812C2e4CAD5Ab6B81b1068a7221ABC62A38 0xD320214A7C46d960b4925b78883C424012f03b4e]} 
——numSeals:3 ——quorumSize:4

**Comment by LuxesOwen** [comment]
I created a new node using our old version that based on polygon-edge v0.5.0,It could sync success over that block number(the sync failed block I said last time).
In this version I added logs in function sign.verifyCommittedFields.
<img width="796" alt="image" src="https://user-images.githubusercontent.com/66360114/216539425-b7f754c3-c4ca-4c08-8905-3eed4bfe10a5.png">
It print "——validSeals:4 ——quorumSizeBlockNum:4" when sync program runs down to blocks contains 5 validators,and it could pass the validation.

So I think the reason is you dropped snapshot data, change to use other way to verify seals,it cause seals validation failed.

**Comment by laviniat1996** [comment]
Hi @LuxesOwen ,

I was not able to reproduce this unfortunately. 
One thing I wanted to know: is your chain working okay now?

**Comment by LuxesOwen** [comment]
@laviniat1996 Yes,because our mainnet running old version(0.5.0),and we never modified the maximum number of validators,so it's no problem.

Our testnet running 0.6.3 version program now,it can't add new node now ,because new node will sync interrupt.I don't know how to solve it. It blocked our upgrade plans.

I think I need to tell you more details about the process that happened:
One day I change the field "maxValidators" of my staking contract from 4 to 5,at that moment my chain was running version 0.5.0 ,this operation cause my validators count became 5,because we had running more than 5 nodes. But we havn't encounter issue until we upgrade to version 0.6+. The sync interrupted block always be the first block after validators count bacame 5.

The logs I sent recently should explain the difference of seals validate between version 0.5 and 0.6,right?

**Comment by LuxesOwen** [comment]
You can ignore the issue in our prod env I mentioned at the beginning,This issue only appears in our TestNet as I said yesterday.
