### ISSUE TITLE
Validator rewards missing

### ISSUE THREAD

**Issue by adaki2004** [0xPolygon/polygon-edge#1157]
### Discussed in https://github.com/0xPolygon/polygon-edge/discussions/1129

<div type='discussions-op-text'>

<sup>Originally posted by **adaki2004** January 13, 2023</sup>
# [ Validator rewards ]
## Description
I would like to set up faucet contract(s) and therefore I'd like to redirect the funds from validator rewards to that contract on a polygon edge private blockchain.
I know `premine` flag which works fine for me, but how can I access the rewards of the validators (if they have any?)

## Your environment
- Currently running 4 nodes in docker, aws environment with 4 nodes
- Latest image on dockerhub
- json rpc port is forwarded to my localhost 8545

## Expected behavior
Maybe I have forgotten some flags, or searching for something wrong.
polygon.server.ibft: validator key: addr=0x5f00f9614d1b990770744Aed2E3b4C8eFda77cF8

Through RPC i'm querying the validator key for eth_getBalance and shows me 0, while the premined account has the proper amount of native token.

Is there any flag I need to supply in order to get those rewards ?

This is how I invoke polygon-edge to create genesis:

```
polygon-edge genesis \
            --dir "$GENESIS_PATH" \
            --consensus ibft \
            --ibft-validators-prefix-path data- \
            --premine=XXXXXXXXXXX:100000000000000000000000 \
            --bootnode /dns/node-1/tcp/1478/p2p/$(echo $secrets | jq -r '.[0] | .node_id') \
            --bootnode /dns/node-2/tcp/1478/p2p/$(echo $secrets | jq -r '.[1] | .node_id')
```

And this is how i start the nodes:
```
    - args:
        - server
        - --data-dir
        - /data/data-1
        - --chain
        - /data/genesis.json
        - --grpc-address
        - 0.0.0.0:9632
        - --libp2p
        - 0.0.0.0:1478
        - --jsonrpc
        - 0.0.0.0:8545
        - --prometheus
        - 0.0.0.0:5001
        - --seal
```

Thank you in advance!</div>

I printed out the validator key of the nodes nodes (`exec -it node-4 -- cat data/data-4/consensus/validator.key`) and imported it to MM and also query the balance via the rpc.
```
curl --location --request POST 'localhost:8545' \                 
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": 2,
    "method": "eth_getBalance",
    "params": ["0x1170beBEE2825fF0835FC49fdE5Aa7950339788B","latest"]
}'
```

All of the 4 nodes have 0 rewards. May I ask you for some help ? Thanks

**Comment by laviniat1996** [comment]
Hi @adaki2004 ,

You should find the validators' rewards on their account (you can access it by importing the validator private keys to a wallet)

**Comment by adaki2004** [comment]
Hello !
This is how i tried (i think). Please read this section:

> cat data/data-4/consensus/validator.key) and imported it to MM and also query the balance via the rpc.

Maybe the validator.key is not the validator private key ? If not, what it is ?
Thanks.

**Comment by laviniat1996** [comment]
You can find the private key in the data directory of each validator: consensus->validator.key. So you are right, that is the private key

**Comment by adaki2004** [comment]
Yeah, thanks. So what is next, because I clearly see 0 balance there :) ?

**Comment by laviniat1996** [comment]
@adaki2004 Can you please provide the command with which you start a node?

**Comment by laviniat1996** [comment]
@adaki2004 Are you using the `--price-limit ` flag? If not, the network accepts transactions with 0 gas fee, and the validator rewards are based on how much gas was consumed (if it was 0 gas, you would get 0 rewards).

**Comment by adaki2004** [comment]
Hello @laviniat1996 !

The nodes are started with the following commands (4 nodes, and only difference is the data-dirs)
```
- server
        - --data-dir
        - /data/data-1
        - --chain
        - /data/genesis.json
        - --grpc-address
        - 0.0.0.0:9632
        - --libp2p
        - 0.0.0.0:1478
        - --jsonrpc
        - 0.0.0.0:8545
        - --prometheus
        - 0.0.0.0:5001
        - --seal
```

I thought in order to create a faucet, the easiest way to collect the mining rewards - by these nodes. Send it to a faucet smart contract and make it claimable there. Could you please help me out in the topic ?
Thanks,
Daniel

**Comment by laviniat1996** [comment]
You would need to set a minimum transaction fee for each node, by using the `--price-limit` flag. At this moment, your network accepts 0 fee transactions, so the validator doesn't get anything (because the gas fee is 0).

You can add a minimum gas fee like this:

```
- server
        - --data-dir
        - /data/data-1
        - --chain
        - /data/genesis.json
        - --grpc-address
        - 0.0.0.0:9632
        - --libp2p
        - 0.0.0.0:1478
        - --jsonrpc
        - 0.0.0.0:8545
        - --prometheus
        - 0.0.0.0:5001
        - -- price-limit 10000
```
Add the `--price-limit` flag for each node. The value is in WEI.
(the `seal` flag is deprecated)

**Comment by adaki2004** [comment]
Thank you @laviniat1996 !
This raises one more question in my head.
With this flag - will it collect rewards for transactions (i guess) BUT:
- will get rewards also after empty-blocks are mined ?

If not, then how can i get over the situation , when Alice at blockheight 1 has 0 native tokens - but the validators requiring her to pay gas when she is about to fire away a txn ?
Thank you for your answer!

**Comment by laviniat1996** [comment]
@adaki2004 You are very welcome!
You only get the transaction fee as a reward. For example, if a validator validates a block with a transaction which has a fee of 0.0021 tokens, that amount will go to that validator. If it validates an empty block there will be no rewards. 
When you set the price-limit, the validator won't accept transactions that have a gas fee lower than that limit.

**Comment by adaki2004** [comment]
Thank you @laviniat1996, that make sense now, so if you could confirm the approach of mine, creating a faucet, we can close this issue.
1. Start the private chain with `--premine` flag, to premine a bunch of native token to an address
2. After chain started create a faucet and send some tokens there

In order to claim from faucet, ppl (=wallets) need to pay gas - which they dont have since they do not have premined. So maybe a good approach is, to exclude this `-- price-limit 10000`. Hmm. Ok, anyhow, it is a private testnet so best approach to not include gas for transactions.
Thanks.
