### ISSUE TITLE
Upgrade go-ibft package version to 0.1.0

### ISSUE THREAD

**Issue by R-Santev** [0xPolygon/polygon-edge#1169]
Upgrade go-ibft package version to 0.1.0
## Description
Projects which want to use Polygon Edge to bootstrap their blockchains can't modify the quorum logic because in go-ibft@0.0.0 part of the quorum logic is handled there instead of in the client. This is changed in version 0.1.0.

## Proposed solution
Upgrading the go-ibft version to 0.1.0 will allow for blockchain projects using Polygon Edge to apply changes to the quorum logic when needed (applying staking amount weight for example) without the need to fork and apply changes in the go-ibft package.

**Comment by laviniat1996** [comment]
Hi @R-Santev ,
You can expect this change to happen soon. We have a PR on the works which updates the go-ibft package. 
I will notify you here when this will be merged to develop, and you can build from the develop branch (at your own risk).

**Comment by R-Santev** [comment]
Thanks, @laviniat1996! Would you like to provide a link to the PR?

**Comment by laviniat1996** [comment]
@R-Santev I have linked the PR to this issue
