### ISSUE TITLE
convert PoS to PoA on stalled chain

### ISSUE THREAD

**Issue by ghost** [0xPolygon/polygon-edge#1172]
# [ Subject of the issue ]
## Description

Hi, our PoS chain stalled. We need to restart as PoA. Can it be done? The reason is AWS locked out a validator, and they cannot get offline, so we can't restart. 

## Your environment
- OS and version. Ubuntu 20.04
- The version of the Polygon Edge.    0.6.1
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider). Cloud
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.). no

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm? no

## Expected behavior
- Tell us what should happen. Restart at block 1406465 (current block) as PoA
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by ghost** [comment]
@laviniat1996 @ivanbozic21 Your help will be very much appreciated. Thank you.

**Comment by laviniat1996** [comment]
@Nexsuperne101 Hey there, I see you marked this as completed. Is this issue solved?

**Comment by ghost** [comment]
@laviniat1996 in a roundabout way, yes. Because of the AWS account lockout, we couldn't get the last 2 staked non-boot nodes off of the chain, so we restarted all the bootnodes, and then 1 minute started all the remaining non-bootnodes. The 2 non-bootnodes were 30 hours head of the rest of the network at this point, so possibly on Round=14. I didn't expect block production for perhaps 2 days, but we had nothing else to lose. Anyway, about an hour later, the chain started making blocks. 

What I suspect happened is that because all bootnodes were taken offline, the remaining 2 that we couldn't get offline could no longer communicate with each other, so the Round=0,1,2,etc process must have stopped whilst waiting for a boot to become available. 

We are currently testing this behaviour to confirm my theory with a 6 node (2 bootnode, 4 non-bootnode) testnet. I think that the chain will stall when we take the 2 bootnodes offline. What I want to see is what the 4 non-bootnodes do. Do they just sit there, waiting for a bootnode to return? or do they keep independently counting Round=0, Round=1 etc, but never making blocks, as they cannot "see" each other without a bootnode, so cannot sync. 

If my theory is right, then the reason that the chain restarted with the 2 nodes still online was because of the lack of bootnodes, and the presence of bootnodes appearing back on the network reset the Round=0 and then started the sync process. 

We have 73 validators.  25 bootnodes. What I now hope is that if the chain stalls in future that all we do is take every bootnode offline, leave the non-bootnodes online, give it 5 minutes and then restart all 25 bootnodes within seconds of each other.

As always, thank you for your time, Nex.
