### ISSUE TITLE
JSON_RPC test fail

### ISSUE THREAD

**Issue by R-Santev** [0xPolygon/polygon-edge#1209]
# JSON_RPC test fail
## Description
One of the tests in the e2e module fails.

## Your environment
- OS and version.
Ubuntu 20.04
- The version of the Polygon Edge.    
 v0.6.3

## Steps to reproduce
- Tell us how to reproduce this issue.
Clone repo
Install packages
Run tests with go test ./...

## Logs
`--- FAIL: TestJsonRPC (446.44s)
    --- FAIL: TestJsonRPC/eth_getCode (318.08s)
        jsonrpc_test.go:127: 
            	Error Trace:	polygon-edge/e2e/jsonrpc_test.go:127
            	Error:      	Received unexpected error:
            	            	{"code":-32600,"message":"unable to fetch code"}
            	Test:       	TestJsonRPC/eth_getCode
  `

**Comment by zuiris** [comment]
Related to #1238

**Comment by stana-miric** [comment]
fixed by https://github.com/0xPolygon/polygon-edge/pull/1238
