### ISSUE TITLE
Cannot send txs using chainId other than 100 when running `server`

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#130]
### Description

When trying to send txs using MetaMask (eth_sendRawTransaction), tx signature encoding fails when using a genesis file created with `--chainid 647`. I observed the error message below after trying to do a simple transaction (sending the premined account 100eth from itself):

```
2021-08-17T20:07:47.398Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_sendRawTransaction err="invalid sender"
```

Upon testing again using chainId 100, I no longer saw this error.

It looks like this is related to an issue reported earlier (see https://github.com/0xPolygon/polygon-sdk/issues/99).

### Your environment

* OS and version `OSX 11.4`
* version of the Polygon SDK `d8b80b9 `
* branch that causes this issue `develop`

### Steps to reproduce

1. Set chainId in genesis file to be `647`. 
2. Spin up 4 validator nodes using `server`, with validator-1 being the premined account.
3. Using MetaMask, connect to the RPC URL, inputting `647` for the chainId.
4. Import premined account privateKey and see that I have the starting balance in my account.
5. Try sending 100ETH to the same account, observe a brief MetaMask error and errors in the logs indicating an "invalid sender".

### Expected behaviour

The transaction should have went through without any issues when using a chainId other than 100.

### Actual behaviour

The transaction failed to go through.

### Proposed solution

Looking at https://github.com/0xPolygon/polygon-sdk/issues/99, I see that using chainId 100 will avoid this issue however we'd like to use a number other than 100 when making our chain public.

**Comment by zivkovicmilos** [comment]
Hey @dankostiuk ,

Thank you for bringing this to our attention.
The bug has been confirmed, resolved, and is awaiting approval in this PR:
https://github.com/0xPolygon/polygon-sdk/pull/135
