### ISSUE TITLE
`eth_getTransactionCount` is failing on non initialized accounts

### ISSUE THREAD

**Issue by mrwillis** [0xPolygon/polygon-edge#131]
### Description

Calling `eth_getTransactionCount` on a non-initialized account (hasn't done any txs) in the state tree returns 

```json
{
    "code": -32603,
    "message": "internal error"
}
```

### Your environment

* OS and version Ubuntu 20 
* version of the Polygon SDK b8659d19bb432c74be9310055084ebd7c26fcd2b
* branch that causes this issue `develop`

### Steps to reproduce

* Tell us how to reproduce this issue <br /> Run polygon-sdk in dev mode and POST the json rpc endpoint with the below payload in the logs
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

```json
{
    "jsonrpc": "2.0",
    "id": 5482,
    "result": "0x0"
}
```

### Actual behaviour

```json
{"code":-32603,"message":"internal error"}
```

### Logs

```
2021-08-18T13:11:04.947-0400 [DEBUG] polygon-dev.jsonrpc: handle: request="{
  "jsonrpc" : "2.0",
  "id" : 5482,
  "method" : "eth_getTransactionCount",
  "params" : ["0x321395A4822f109Ae167987a6b0566cF91126F7e"]
}"
2021-08-18T13:11:04.947-0400 [DEBUG] polygon-dev.dispatcher: request: method=eth_getTransactionCount id=5482
2021-08-18T13:11:04.947-0400 [ERROR] polygon-dev.dispatcher: failed to dispatch: method=eth_getTransactionCount err="given root and slot not found in storage"

```

### Proposed solution

It seems like `getState` in `server.go` always complains if it can't find the storage slot. Perhaps returning an error all the time is not the best approach as this is a valid request and should give a valid response (of 0). Or maybe we can switch on the error type?

**Comment by Kourin1996** [comment]
Hello, @mrwillis. Thank you for reporting this issue with detailed information!
I've fixed this issue and the PR https://github.com/0xPolygon/polygon-sdk/pull/136 has been merged.
Now returns zero value even if account doesn't exist when you call `eth_getTransactionCount`.

I'm closing this issue. Thank you for your help.
