### ISSUE TITLE
How to migrate from 0.6.3 to 0.8?

### ISSUE THREAD

**Issue by ghost** [0xPolygon/polygon-edge#1334]
# [ Subject of the issue ]
## Description
Describe your issue in as much detail as possible here.
We are currently live on 0.6.3, which as I understand it from Polygon's website will still be supported. If I just change the polygon-edge file in /usr/local/bin to v0.8, then I get a multitude of errors. Anything from bulk sync to non-validators...

I wrote a quick test genesis.json and dropped that in, and v0.8 works fine, makes blocks with zero errors, so the environment is all good.

## Your environment
- OS and version. Ubuntu 20.04
- The version of the Polygon Edge.    0.63 to 0.8
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider). local for the 0.8 test, but normally on AWS cloud
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.). no

## Steps to reproduce
- Tell us how to reproduce this issue. Install v0.8 polygon-edge to /usr/local/bin/ and then try and make blocks on a previously running 0.6.3 polygon-edge.

- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen. It all runs with no issues.
- Tell us what happened instead. It just throws errors.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it. A migration guide would be epic!!, Thanks, Nex

**Comment by cybercorey** [comment]
I think you need to hard fork the chain:
https://wiki.polygon.technology/docs/supernets/operate/supernets-ibft-to-polybft/
