### ISSUE TITLE
Custom solidity errors (introduced in 0.8.4) not supported

### ISSUE THREAD

**Issue by sebastiendan** [0xPolygon/polygon-edge#1350]
# Custom solidity errors (introduced in solidity 0.8.4) not supported
## Description
Hi,

I haven't been capable of receiving proper error data when interacting with some contracts deployed to Edge chains. These contracts leverage solidity >0.8.4 custom errors, used with revert in the `revert MyError(myData)` manner.

Thinking the problem was on the js client side, I jumped on an older `ethers` issue. Investigating with their team, it seems the problem is coming from Edge which is not returning the error data at all.

Please find the details of my setup at the very bottom of the issue on `ethers`:
https://github.com/ethers-io/ethers.js/issues/1493

## Your environment
- macOS v13.2.1.
- Edge v0.8.0.
- Local docker setup with docker image built from `/docker/local`

## Steps to reproduce
- Run a polygon-edge chain
- Deploy the contract provided [here](https://github.com/ethers-io/ethers.js/issues/1493#issuecomment-1490610951)
- Interact with the contract to trigger the `revert`
- Notice that your js client (`ethers` or `web3`) is not parsing any information from the error (we only know that the call reverted)

## Expected behavior
- The explicit error should be returned

**Comment by sebastiendan** [comment]
Any update here?

**Comment by dankostiuk** [comment]
Any update @laviniat1996 ? Would be great to know whether or not edge can/will support custom errors in the near future, thanks!

**Comment by vcastellm** [comment]
Update: We're working on this
