### ISSUE TITLE
Run polygon-edge 0.8.1 on network created with 0.8 cause errors

### ISSUE THREAD

**Issue by polygomic** [0xPolygon/polygon-edge#1351]
# [ Subject of the issue ]
## Description
Describe your issue in as much detail as possible here.

## Your environment
- OS and version.
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

the error is :
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x151b5d6]

goroutine 1 [running]:
math/big.(*Int).Set(...)
        /usr/local/go/src/math/big/int.go:74
github.com/0xPolygon/polygon-edge/consensus/polybft.Validator.ToValidatorInitAPIBinding({{0x80, 0x76, 0x4c, 0x74, 0x9a, 0x8b, 0x9a, 0xca, 0xed, 0x75, ...}, ...})
        /root/polygon-edge/consensus/polybft/polybft_config.go:176 +0xd6
github.com/0xPolygon/polygon-edge/consensus/polybft.getInitChildValidatorSetInput({{0xc00136a7e0, 0xa, 0xd}, 0x0, 0x200, 0x1, 0x5, 0x77359400, {0x80, 0x76, ...}, ...})
        /root/polygon-edge/consensus/polybft/contracts_initializer.go:31 +0xd8
github.com/0xPolygon/polygon-edge/consensus/polybft.GenesisPostHookFactory.func1(0xc001775798?)
        /root/polygon-edge/consensus/polybft/polybft.go:122 +0x118
github.com/0xPolygon/polygon-edge/state.(*Executor).WriteGenesis(0xc0016ff5c0, 0xc6a6ceb32eca75ed?, {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...})
        /root/polygon-edge/state/executor.go:110 +0x4ca
github.com/0xPolygon/polygon-edge/server.NewServer(0xc00139f5e0)
        /root/polygon-edge/server/server.go:239 +0xc5a
github.com/0xPolygon/polygon-edge/command/server.runServerLoop(0x314de60?, {0x2371180, 0xc0013b2600})
        /root/polygon-edge/command/server/server.go:318 +0x27
github.com/0xPolygon/polygon-edge/command/server.runCommand(0xc001380900?, {0x1b11e83?, 0x4?, 0x4?})
        /root/polygon-edge/command/server/server.go:306 +0x45
github.com/spf13/cobra.(*Command).execute(0xc001380900, {0xc000dbdfc0, 0x4, 0x4})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc00026e300)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/0xPolygon/polygon-edge/command/root.(*RootCommand).Execute(0xc0000061a0?)
        /root/polygon-edge/command/root/root.go:72 +0x1c
main.main()
        /root/polygon-edge/main.go:18 +0x51

**Comment by Stefan-Ethernal** [comment]
This happens because the manifest file on `v0.8.1` expects a new parameter, called `Stake`. Since you are using the manifest file generated on `v0.8.0`, it is wrong. If possible, you should bootstrap the network from scratch (regenerate manifest, genesis, etc.)
