### ISSUE TITLE
Error writing genesis block: failed to initialize ChildValidatorSet contract. Reason: execution was reverted

### ISSUE THREAD

**Issue by nexiteam** [0xPolygon/polygon-edge#1352]
# [ Subject of the issue ]
## Description
Describe your issue in as much detail as possible here.
When I try to start polygon-edge 0.8.1 for a first time I got Error writing genesis block: failed to initialize ChildValidatorSet contract. Reason: execution was reverted error but I do not have this error with version 0.8.0

## Your environment
- OS and version. Ubuntu 22.04
- The version of the Polygon Edge.    0.8.1
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by PandasCoder** [comment]
Hi i have this same issue when i change the chainId from the mainfest.json and the genesis.json

- i found a solution, run the flag --chain-id into the secrets, mainfest and genesis generation, with that i can run the supernet with other chainID

**Comment by squiddyswap** [comment]
This error has been re-introduced with the lastest fixes and the removal of the manifest.  

Now even if you do command
./polygon-edge polybft-secrets --insecure --data-dir zroar-chain- --num 4 --chain-id <chain Id>

and then create genesis with command:

 ./polygon-edge genesis --block-gas-limit 10000000 --epoch-size 10 \
    --dir     ./genesis.json \
    --validators  <validator string>
    --premine 0x0000000000000000000000000000000000000000 \
    --chain-id <chain Id> \
    --name <name>  \
    --mintable-native-token \
    --pos \
    --native-token-config <name:symbol:decimals>

It will still throw this error.
Error writing genesis block: failed to initialize ChildValidatorSet contract. Reason: execution was reverted

**Comment by atiprashant** [comment]
I am also facing this issue while moving from poa to polybft. Getting same error 

{"@level":"info","@message":"Data dir","@module":"polygon.server","@timestamp":"2023-04-26T08:08:31.648669Z","path":"/data/edge-new"}
{"@level":"info","@message":"Initial state root checked and correct","@module":"polygon","@timestamp":"2023-04-26T08:08:32.319519Z"}
{"error":"Error writing genesis block: failed to initialize ChildValidatorSet contract. Reason: execution was reverted"}

**Comment by Stefan-Ethernal** [comment]
As @PandasCoder it is crucial to provide the same chain-id value to polybft-secrets, manifest and genesis CLI commands.
