### ISSUE TITLE
Flags for polygon-edge not known --path --admin-key

### ISSUE THREAD

**Issue by squiddyswap** [0xPolygon/polygon-edge#1357]
Flags for polygon-edge not known --path --admin-key
when running the command line:
./polygon-edge rootchain init-contracts --manifest ./manifest.json --path ./core-contracts/artifacts --json-rpc http://127.0.0.1:8545 
--admin-key <admin key>
says that the flags --path and --admin key are unknown

- OS and version - Debian Linux 11
- Polygon Edge v0.8.1    
- Hosted locally

## Steps to reproduce
- at the command line run the following command:
./polygon-edge rootchain init-contracts --manifest ./manifest.json --path ./core-contracts/artifacts --json-rpc http://127.0.0.1:8545 
--admin-key <admin key>

## Expected behavior
- command should run and deploy smart contracts
- It gave an error that the --flags path and admin-key was unknown

**Comment by squiddyswap** [comment]
This occurred while attempting to deploy a local Polygon Supernet in Bridge Mode

**Comment by rocky-balboa-1** [comment]
As I know, --path param has been replaced with --data-dir.
You could run 

./polygon-edge rootchain init-contracts --help

then see all available params.

**Comment by squiddyswap** [comment]
thanks for the help.  But, looks like they have changed the documentation and taken the --path option out and --admin-key is also incorrect its --deployer-key instead.  But, thanks again.

**Comment by Stefan-Ethernal** [comment]
> thanks for the help. But, looks like they have changed the documentation and taken the --path option out and --admin-key is also incorrect its --deployer-key instead. But, thanks again.

@squiddyswap That's right:
- instead of using `--admin-key`, a `--deployer-key` flag should be used,
- as per the `--path` flag, it was obsoleted some time ago (a couple of months ago), but possibly documentation got updated recently.

If you can point to the docs page where the wrong flags are enumerated so that we can fix the docs itself. Otherwise, the issue can be closed.
