### ISSUE TITLE
v0.8.1 vs 0.6.2 no way to name your root token

### ISSUE THREAD

**Issue by squiddyswap** [0xPolygon/polygon-edge#1366]
v0.8.1 vs 0.6.2 no way to name your root token
In the older version and non-bridge mode there was a parameter that allowed for naming your Native root token.  Looking at v0.8.1 for the bridge and non-bridge mode there is no way to name the native root token.  It puts in "TEST" as the default name without anyway to change that.  

## Your environment
- Debian 11 
- Polygon Edge v0.8.1    
- run locally on multiple VMs.

## Expected behavior
- Need an parameter or flag that allows the naming of the native root token.
- Tell us what happened instead.
- It gives a default name of "TEST" on the rootchain without an option to change the name of the token.

**Comment by squiddyswap** [comment]
./polygon-edge rootchain init-contracts --manifest ./manifest.json --json-rpc <http://testnet-url-placeholder>This occurs while running this command.  I guess it would be possibly setup within the manifest file.

**Comment by Stefan-Ethernal** [comment]
@squiddyswap If using `MockERC20` as the root ERC20 token (which is deployed out of the box), then it is not possible to rename it. `MockERC20` token is intended only for testing purposes and it is going to have a hardcoded `TEST` name all the time. 

What you can do is deploy ERC 20 token implementation of choice manually to the root chain (using Remix IDE for instance), initialize it with desired parameters, and then provide its address when running `rootchain init-contracts` command.

It would be like this:
```bash
./polygon-edge rootchain init-contracts --manifest ./manifest.json --json-rpc http://testnet-url-placeholder/ \
--rootchain-erc20 <rootchain erc 20 token address>
```

**Side note:** `--rootchain-erc20` flag is going to renamed to `--erc20-token` with the next release.

**Comment by squiddyswap** [comment]
Thanks @Stefan-Ethernal.  That also answered my crazy question of how do you mint to rootNativeERC20 token.
