### ISSUE TITLE
Sidechain contracts

### ISSUE THREAD

**Issue by polygomic** [0xPolygon/polygon-edge#1458]
Sidechain contracts
In setting up a test network, only the rootchain smart contracts are deployed on the bridge using the command "polygon-edge rootchain init-contracts --manifest ./manifest.json --json-rpc http://testnet-url-placeholder/ deploy". However, how should the smart contracts on the sidechain be deployed? There is no place for sidechain smart contracts in the sequence of commands below, and if they are automatically deployed, how can their addresses be obtained?

./polygon-edge polybft-secrets --insecure --data-dir test-chain- --num 4

./polygon-edge manifest \
--validators-path ./ \
--validators-prefix test-chain- \
--path ./manifest.json \
--premine-validators 100

./polygon-edge rootchain init-contracts --manifest ./manifest.json --json-rpc <http://testnet-url-placeholder>

./polygon-edge genesis --block-gas-limit 10000000 --epoch-size 10 --mintable-native-token
[--consensus polybft] [--premine <premine_address>:<premine_amount>]
[--bridge-json-rpc <rootchain_ip_address>] [--manifest ./manifest.json]

## Your environment
- OS and version.
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by Stefan-Ethernal** [comment]
Sidechain contracts (at least the predefined ones, which are deployed at genesis time) are deployed automatically in genesis command. Their addresses can be found in `genesis.json`, under `alloc`.
