### ISSUE TITLE
how to change to ibft from polybft in v0.9.0?

### ISSUE THREAD

**Issue by elaz48** [0xPolygon/polygon-edge#1485]
OS is Ubuntu 20.04 and I'm following the how-to on https://wiki.polygon.technology/docs/supernets/operate/supernets-local-deploy-supernet

How can I use IBFT instead of POLYBFT?

**Comment by Stefan-Ethernal** [comment]
You could provide the following flag to the genesis command: `--consensus ibft`. 

However, bear in mind that IBFT consensus protocol is obsoleted and support is no longer provided for it.
