### ISSUE TITLE
How to mint ERC721 on child then withdraw to root?

### ISSUE THREAD

**Issue by rocky-balboa-1** [0xPolygon/polygon-edge#1496]
As far as I know, from the code in core-contracts, we can only mint ERC721 on root then deposit it to child.

My question is, is there a way to mint ERC721 on child then withdraw it to root. If not, are you having a plan to implement it in the future?

Thanks in advance!

**Comment by Stefan-Ethernal** [comment]
> As far as I know, from the code in core-contracts, we can only mint ERC721 on root then deposit it to child.

That's correct.

> My question is, is there a way to mint ERC721 on child then withdraw it to root. If not, are you having a plan to implement it in the future?

It is not possible at the moment, but it is planned to be delivered in a near future (possibly next release, but still TBD).
