### ISSUE TITLE
How can we use custom chainid

### ISSUE THREAD

**Issue by polygomic** [0xPolygon/polygon-edge#1497]
How can we use custom chainid
We are going to use chainId 4242 as are sidechain chain id but the chain Id will get from jsonrpc
How can we get seperate chain id from rootchain like 4242 and has native bridge and use it

## Your environment
- OS and version.
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by steel-feel** [comment]
Couldn't see any configuration to do. I think there should be a flag at `rootchain deploy` command to set chain-id

**Comment by tandooricodes** [comment]
Hi @polygomic, thanks for reaching out!
The chainID can be found inside the manifest.json file

**Comment by polygomic** [comment]
in 0.9.0 manifest.json has been removed and only should use genesis file.

**Comment by steel-feel** [comment]
moreover, according to your recent documentation [here](https://wiki.polygon.technology/docs/supernets/operate/supernets-local-deploy-supernet#ii-chain-configuration-generate-the-genesis-file)

> Instead, the value for ChainID should come from the rootchain deployment, specifically from the StakeManager contract, when the Supernet is registered. This value is then automatically written to the genesis file during the deployment process. Please note that this means that the ChainID is no longer configurable through the genesis command, but rather through the StakeManager contract during Supernet registration.
> 
> The --chain-id flag remains present in some commands because the old IBFT implementation has not yet been removed from the codebase. As a result, the decision was made not to deprecate the flag until the removal process is complete.
>

**Comment by steel-feel** [comment]
but there is no way to mention `chain-id` besides genesis command.

I guess it has to do with `registerChild` of _ChildManagerLib_ in _StakeManager_ contract.

**Comment by vcastellm** [comment]
Hey @polygomic, `chainID` can not be specified anymore since v0.9, it's now assigned and managed by `StakeManager` contract and updated in Genesis file at rootchain deployment time, refer to the docs for more info https://wiki.polygon.technology/docs/supernets/operate/supernets-local-deploy-supernet#initialize-rootchain-contracts
