### ISSUE TITLE
Root Chain Fund Command fails for any network except local geth Instance for v0.9.0

### ISSUE THREAD

**Issue by adirola** [0xPolygon/polygon-edge#1528]
Root Chain Fund Command fails for any network except local geth Instance for v0.9.0
## Description
The command` ./polygon-edge rootchain fund --data-dir ./test-chain-1 --amount 10000000000000000 --native-root-token <root_token_address> --private-key <hex_encoded_deployer_private_key> --json-rpc https://matic-mumbai.chainstacklabs.com --mint`
with the following result : no accounts registered

## Your environment
- Linux (ubuntu 20.04).
- Edge / Supernets Version v0.9.0.    
- release :  v0.9.0.
- Locally build from source.
- No validators are not running on any container service.

## Steps to reproduce
- On running the root chain fund command on any network except local geth instance using a --private-key flag it gives error: no accounts registered
- The issue seems to be in the file fund.go in directory command/rootchain/fund. In this file irrespective of the json-rpc provided it will call sendTransactionLocal function which tries to execute the transaction on local geth Instance.
the above call can be found on line no. : 131  
error line : receipt, err := txRelayer.SendTransactionLocal(txn) 
- `./polygon-edge rootchain fund --data-dir ./test-chain-1 --amount 10000000000000000 --native-root-token <root_token_address> --private-key <hex_encoded_deployer_private_key> --json-rpc https://matic-mumbai.chainstacklabs.com --mint`

## Expected behavior
- The expected behavior is: I should be able to mint native-root-token to validator account using the --private key of the deployer address used to deploy root contracts on the chain
- The result received was no accounts registered.

## Logs
<img width="2238" alt="Screenshot 2023-05-19 at 5 22 17 PM" src="https://github.com/0xPolygon/polygon-edge/assets/9098273/93f074c1-0091-45a8-9266-99f9ac00251f">

## Proposed solution
The solution seems to be: If --private-key flag is passed then don't issue a sendTransactionLocal call 

<img width="790" alt="Screenshot 2023-05-19 at 9 44 33 PM" src="https://github.com/0xPolygon/polygon-edge/assets/9098273/bbaefd25-cf57-4f0b-9ffc-4cc44b4d6597">

If this issue is not being actively worked upon i can work on it as well and raise a PR.

**Comment by goran-ethernal** [comment]
Addressed through #1540

**Comment by adirola** [comment]
Hi Guys @dusan-maksimovic  @goran-ethernal @Stefan-Ethernal thank you so much for looking into the issue. Is it a norm on this repo to just open pull request without consulting the moderators. I was waiting for the reply and i see @dusan-maksimovic just open a pull request 2 hrs back while i had already worked on the issue.

**Comment by goran-ethernal** [comment]
> Hi Guys @dusan-maksimovic @goran-ethernal @Stefan-Ethernal thank you so much for looking into the issue. Is it a norm on this repo to just open pull request without consulting the moderators. I was waiting for the reply and i see @dusan-maksimovic just open a pull request 2 hrs back while i had already worked on the issue.

You can open a pull request any time if you are facing some issue, and you have a fix ready. We will be happy to take a look at it. This issue just happened to be worked on by us as well in the same time.

**Comment by adirola** [comment]
Sure @goran-ethernal as long the issue gets fixed, happy to contribute in just raising the issue as well.

**Comment by Stefan-Ethernal** [comment]
#1540 got merged, so marking this one as completed. Fix is going to be a part of next release.
