### ISSUE TITLE
Rootchain Fund Command Fails (Supernets v0.9 commit ef089fb)

### ISSUE THREAD

**Issue by tandooricodes** [0xPolygon/polygon-edge#1542]
# Rootchain Fund Command Fails (Supernets v0.9 commit ef089fb)
## Description
It seems that in the recent commiits (since 3rd week of May) the rootchain fund command listed on the documentation fails.

## Your environment
- Ubuntu 22 (PopOS).
- Edge / Supernets Version 0.9  (refer commit below)
- Commit #ef089fb on the `develop` branch.
- Locally
- No containerization, following the [fast-track docs for deploying a local private Supernet] (https://wiki.polygon.technology/docs/supernets/operate/supernets-local-deploy-supernet#what-youll-do)

## Steps to reproduce
- Build Polygon Edge binary
```
 go build -o polygon-edge .
```
- Initialize secrets
```
./polygon-edge polybft-secrets --data-dir test-chain- --num 4 --insecure
```
- Create genesis file
```
./polygon-edge genesis --block-gas-limit 10000000 --epoch-size 10 --reward-wallet 0xba283e439Bd444B595Dd4790f662aD073cD103eE:1000000000000000000
```
- Initialise rootchain
```
./polygon-edge rootchain server
```
- Finally, we run the command to fund the rootchain
```
./polygon-edge rootchain fund --data-dir ./test-chain-1
```

## Expected behavior
- The rootchain should be funded with a success message
- Instead the following error is returned:
```
Error: unknown flag: --data-dir
```
This is followed by a list of flags the command accepts, none of which include --data-dir

## Logs
```
one@pop-os:~/Desktop/supernets-stake/polygon-edge$ ./polygon-edge rootchain fund --data-dir ./test-chain-1

Error: unknown flag: --data-dir
Usage:
   rootchain fund [flags]

Flags:
      --addresses strings          validator addresses
      --amounts strings            token amounts which is funded to validator on a root chain
  -h, --help                       help for fund
      --json-rpc string            the rootchain JSON RPC endpoint (default "http://127.0.0.1:8545")
      --mint                       indicates if root token deployer should mint root tokens to given validators
      --native-root-token string   address of native root token
      --private-key string         hex-encoded private key of the account which executes rootchain commands

Global Flags:
      --json   get all outputs in json format (default false)

unknown flag: --data-dir

```
## Proposed solution
In order to fix this we'll need to determine in what format the `rootchain fund` command expects the addresses and their funding amounts. Since this command is intended for testing purposes I am not completely sure of it's intended utility in production.

**Comment by Stefan-Ethernal** [comment]
It is not executed that way anymore. This [README](https://github.com/0xPolygon/polygon-edge/tree/develop/consensus/polybft#:~:text=Fund%20validators%20on%20rootchain) has an example of how to employ fund command:
```go
$ polygon-edge rootchain fund \
    --addresses 0x1234567890123456789012345678901234567890 \
    --amounts 200000000000000000000 \
    --private-key <hex encoded private key of the account which sends rootchain transactions>
```

> Since this command is intended for testing purposes I am not completely sure of it's intended utility in production.

Currently, it is not possible to use it if not using locally running Geth instance, ran in dev mod, due to the #1528. When it gets fixed, I believe it should be able to use on production networks as well, as long as the account with provided `--private-key` has enough funds.

**Comment by tandooricodes** [comment]
Thanks @Stefan-Ethernal , that was helpful!
