### ISSUE TITLE
Staking on root chain with other token

### ISSUE THREAD

**Issue by polygomic** [0xPolygon/polygon-edge#1548]
Can we generate ERC20 token on root chain and stake on it or should stake main coin of rootchain ,I mean if my chain was mumbai I only should stake matic or can generate new ERC20 token on mumbai and use it for stake
## Description
Describe your issue in as much detail as possible here.

## Your environment
- OS and version.
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by abdec2** [comment]
i have a same question. did you find the answer?

**Comment by tandooricodes** [comment]
Hi @polygomic, 
We need to deploy our own ERC20 token on the rootchain. Refer Step 4 here:
https://github.com/nonceblox/polygon-edge-tutorials/blob/master/supernets_v0.9_setup.md#4-deploy-stakemanager-contract-to-rootchain-mumbai-in-this-case

**Comment by goran-ethernal** [comment]
Yes you can have your own ERC20 token, and use it for staking. Note that your token has to be already deployed on rootchain before doing `stake-manager-deploy` command. But, if you are using Mumbai, we suggest to use WMATIC as your stake token.
