### ISSUE TITLE
[ Creating cluster & Generate the manifest file ]

### ISSUE THREAD

**Issue by shahbaz004** [0xPolygon/polygon-edge#1568]
# [ Creating cluster & Generate the manifest file ]
## Description
1. I run the command `scripts/cluster ibft` to create a cluster but it goes into infinite. let me know how much time it will take because I ran that script for 3 days but the process does not complete. Do I need to wait for the process to be completed? 
2. on the other side when i'm trying to Generate the manifest file using this command `./polygon-edge manifest` it throughs error: `unknown command "manifest" for ""`. Do I need to wait for the cluster to complete and then try this command?

## Your environment
- Ubuntu and 22.04
- The version of the Polygon Edge.    
  `https://github.com/0xPolygon/polygon-edge.git`
- Branch Develop
- Locally

**Comment by zuiris** [comment]
What is the version of Polygon Edge you are using? Most probably you issue can be fixed by using the latest version

**Comment by zuiris** [comment]
Feel free to reopen if the issue persists
