### ISSUE TITLE
How Can is possible to remove validator

### ISSUE THREAD

**Issue by polygomic** [0xPolygon/polygon-edge#1579]
How Can is possible to remove validator
We can register new validator with command polygon-edge polybft but how can we remove validator from rootchain and supernet?
 

## Your environment
- OS and version.
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by upendra-metasky** [comment]
You can use this command to vote out the node by each node. The node will be dropped as a validator once you place votes so that the number is greater 2/3 rd of total numberof nodes

polygon-edge ibft propose --addr <address of the node to be removed> --bls <bls key of node to b removed> --vote drop --grpc-address <grpc address of the node that is voting>

**Comment by polygomic** [comment]
this solution is for ibft what about polybft?

**Comment by goran-ethernal** [comment]
@polygomic For `polybft` it is enough to unstake all tokens that the validator you want to remove staked.
