### ISSUE TITLE
Tracer bugs related to `SSTORE` and `CALL`/`STATICCALL`

### ISSUE THREAD

**Issue by atanmarko** [0xPolygon/polygon-edge#1590]
Tracer bugs related to `SSTORE` and `CALL`/`STATICCALL`

## Description
* For `SSTORE` tracer has permuted `key` and `value` reading from the stack
* `CALL` instruction is not correctly traced. New environment (stack/memory/storage) need to be created for message call, and at the moment they are mixed. `CALL` captures memory/storage, then external call overwrites these, and eventually on `ExecuteState` `CALL` reads random values for stack/memory/storage.

## Your environment
- Ubuntu 20.04/22.04
- 0.8

## Steps to reproduce
- Trace any block with smart contracts performing `CALL` to other smart contract
- Examine the trace for `CALL`

## Proposed solution
Solution implemented for the need of our project fixing `SSTORE` and using array for memory/storage/stack to create new environment for every `CALL` trace [HERE](https://github.com/topos-network/polygon-edge/commit/5a51279d93b1fabb9190ab4b1d056339f050fc38)

**Comment by vcastellm** [comment]
Thanks for reporting this @atanmarko, we're working on a fix using the suggested patch.
