### ISSUE TITLE
Transactions allowlist suddenly not working

### ISSUE THREAD

**Issue by giovanni-pucci** [0xPolygon/polygon-edge#1617]
# Transactions allowlist suddenly not working
## Description
The first time I've created the chain, both locally and on AWS using the ansible script, I've been able to get the transactions allowlist working. However, once I had to recreate the chain (completely deleted the environment and created a new one) to tweak some settings, it would just not work, meaning everyone were able to create transactions.

The flags that I've added to the genesis script were the following:

```
--transactions-allow-list-admin {{ loadtest_account }},$(cat validator-*.json | jq -r ".[].address" | tr "\n" ",")
--transactions-allow-list-enabled {{ loadtest_account }},{{ bridge_account }},$(cat validator-*.json | jq -r ".[].address" | tr "\n" ",")
```

Where the only allowed addresses would be the deployer/owner account, the LZ bridge account and all the 4 validators previously created.

Questions:

- Is the allowlist stored completely on the supernets client or is it hosted somewhere else?
- Am I missing any additional flag?
- In case this happens again for any other reason, is there a way to manually enable it post deployment?

### The bootstrap script:

Keep in mind that this script runs within ansible but had to be changed in order to fit the client needs (Mumbai testnet).

```bash
#!/bin/bash -x

main() {

if [[ -d "/var/lib/bootstrap" ]]; then
	echo "It appears this network has already been boot strapped"
	exit
fi

mkdir /var/lib/bootstrap
pushd /var/lib/bootstrap

{% for item in hostvars %}
{% if (hostvars[item].tags.Role == "fullnode" or hostvars[item].tags.Role == "validator") %}
polygon-edge polybft-secrets --data-dir {{ hostvars[item].tags["Name"] }} \
	--json \
	--insecure > {{ hostvars[item].tags["Name"] }}.json
{% endif %}
{% endfor %}

polygon-edge genesis \
	--consensus polybft \
	{% for item in hostvars %}{% if (hostvars[item].tags.Role == "fullnode" or hostvars[item].tags.Role == "validator") %} --bootnode /dns4/{{ hostvars[item].tags["Name"] }}/tcp/{{ edge_p2p_port }}/p2p/$(cat {{ hostvars[item].tags["Name"] }}.json | jq -r '.[0].node_id') {% endif %}{% endfor %} \
	{% for item in hostvars %}{% if (hostvars[item].tags.Role == "fullnode" or hostvars[item].tags.Role == "validator") %} --premine $(cat {{ hostvars[item].tags["Name"] }}.json | jq -r '.[0].address'):1000000000000000000000000 {% endif %}{% endfor %} \
	{% for item in hostvars %}
	{% if (hostvars[item].tags.Hostname == "validator-001") %}
	--reward-wallet $(cat {{ hostvars[item].tags["Name"] }}.json | jq -r '.[0].address'):1000000000000000000000000000 \
	{% endif %}
	{% endfor %}
  --premine {{ loadtest_account }}:1000000000000000000000000000 \
	--premine {{ bridge_account }}:1000000000000000000000000000 \
	--block-gas-limit {{ block_gas_limit }} --block-time {{ block_time }}s \
  {% for item in hostvars %}{% if (hostvars[item].tags.Role == "validator") %} --validators /dns4/{{ hostvars[item].tags["Name"] }}/tcp/{{ edge_p2p_port }}/p2p/$(cat {{ hostvars[item].tags["Name"] }}.json | jq -r '.[0].node_id'):$(cat {{ hostvars[item].tags["Name"] }}.json | jq -r '.[0].address' | sed 's/^0x//'):$(cat {{ hostvars[item].tags["Name"] }}.json | jq -r '.[0].bls_pubkey') {% endif %}{% endfor %} \
  --epoch-size 10 \
	--transactions-allow-list-admin {{ loadtest_account }},$(cat validator-*.json | jq -r ".[].address" | tr "\n" ",") \
	--transactions-allow-list-enabled {{ loadtest_account }},{{ bridge_account }},$(cat validator-*.json | jq -r ".[].address" | tr "\n" ",") \
	--contract-deployer-allow-list-admin {{ loadtest_account }},$(cat validator-*.json | jq -r ".[].address" | tr "\n" ",") \
  --contract-deployer-allow-list-enabled {{ loadtest_account }},{{ bridge_account }},$(cat validator-*.json | jq -r ".[].address" | tr "\n" ",") \
	--native-token-config "My Token:MTK:8:true" \
	--chain-id 2007

{% for item in hostvars %}
{% if (hostvars[item].tags.Role == "validator") %}

cast send --rpc-url {{ rootchain_json_rpc }} --from {{ loadtest_account }} --private-key {{ deployer_key }} --value 0.02ether $(cat {{ hostvars[item].tags["Name"] }}.json | jq -r '.[0].address')

{% endif %}
{% endfor %}

polygon-edge polybft stake-manager-deploy \
	--jsonrpc {{ rootchain_json_rpc }} \
	--private-key {{ deployer_key }} \
	--genesis ./genesis.json \
	--stake-token 0x0e698696674eabb217457ecebce36c2a8777f531

polygon-edge rootchain deploy \
	--deployer-key {{ deployer_key }} \
	--json-rpc {{ rootchain_json_rpc }} \
	--genesis ./genesis.json \
	--stake-manager $(cat genesis.json | jq -r '.params.engine.polybft.bridge.stakeManagerAddr') \
	--stake-token $(cat genesis.json | jq -r '.params.engine.polybft.bridge.stakeTokenAddr')

polygon-edge polybft whitelist-validators \
	--private-key {{ deployer_key }} \
	--addresses $(cat validator-*.json | jq -r ".[].address" | tr "\n" ",") \
	--supernet-manager $(cat genesis.json | jq -r '.params.engine.polybft.bridge.customSupernetManagerAddr') \
	--json-rpc {{ rootchain_json_rpc }}

{% for item in hostvars %}
{% if (hostvars[item].tags.Role == "validator") %}

polygon-edge polybft register-validator --data-dir {{ hostvars[item].tags["Name"] }} \
	--supernet-manager $(cat genesis.json | jq -r '.params.engine.polybft.bridge.customSupernetManagerAddr') \
	--json-rpc {{ rootchain_json_rpc }}

{% endif %}
{% endfor %}

{% for item in hostvars %}
{% if (hostvars[item].tags.Role == "validator") %}
polygon-edge polybft stake --data-dir {{ hostvars[item].tags["Name"] }} \
	--chain-id $(cat genesis.json | jq -r '.params.engine.polybft.bridge.supernetID') \
	--amount 10 \
	--stake-manager $(cat genesis.json | jq -r '.params.engine.polybft.bridge.stakeManagerAddr') \
	--stake-token $(cat genesis.json | jq -r '.params.engine.polybft.bridge.stakeTokenAddr') \
	--jsonrpc {{ rootchain_json_rpc }}
{% endif %}
{% endfor %}

polygon-edge polybft supernet --private-key {{ deployer_key }} \
	--supernet-manager $(cat genesis.json | jq -r '.params.engine.polybft.bridge.customSupernetManagerAddr') \
	--stake-manager $(cat genesis.json | jq -r '.params.engine.polybft.bridge.stakeManagerAddr') \
	--finalize-genesis-set --enable-staking \
	--jsonrpc {{ rootchain_json_rpc }}

tar czf {{ base_dn }}.tar.gz *.json *.private genesis.json
popd

}

main
```

### The edge service file

```
[Unit]
Description=Polygon Edge Client
Documentation=https://github.com/0xPolygon/polygon-edge/

# Bring this up after the network is online
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=polygon-edge server --data-dir {{ edge_home_dir }} \
    --chain {{ edge_home_dir }}/genesis.json \
    --grpc-address 0.0.0.0:{{ edge_grpc_port }} \
    --json-rpc-batch-request-limit 999 \
    --libp2p 0.0.0.0:{{ edge_p2p_port }} \
    --jsonrpc 0.0.0.0:{{ edge_jsonrpc_port }} \
    --prometheus 127.0.0.1:{{ edge_prometheus_port }} \
    --max-slots 276480 \
    --max-enqueued 276480 \
    --log-level ERROR \
    --block-gas-target {{ block_gas_limit }} \
    --num-block-confirmations 2 \
    --price-limit 1000000 \
    {% if (hostvars[inventory_hostname].tags.Hostname == "validator-001") %}
    --relayer \
    {% endif %}
    {% if is_validator %}
    --seal
    {% endif %}

MemoryHigh={{ (ansible_memtotal_mb * 0.7) | round | int }}M
MemoryMax={{ (ansible_memtotal_mb * 0.8) | round | int }}M
MemorySwapMax=0

Restart=on-failure
RestartSec=5s

Type=simple

User={{ edge_user }}
Group={{ edge_user }}-group

TimeoutStartSec=infinity
TimeoutStopSec=600

RuntimeDirectory=edge
RuntimeDirectoryMode=0700

ConfigurationDirectory=edge
ConfigurationDirectoryMode=0700

StateDirectory=edge
StateDirectoryMode=0750

# Hardening measures
# https://www.linuxjournal.com/content/systemd-service-strengthening
# sudo systemd-analyze security
# systemd-analyze syscall-filter
####################

# Provide a private /tmp and /var/tmp.
PrivateTmp=true

# Mount /usr, /boot/ and /etc read-only for the process.
ProtectSystem=full

# Deny access to /home, /root and /run/user
ProtectHome=true

# Disallow the process and all of its children to gain
# new privileges through execve().
NoNewPrivileges=true

# Use a new /dev namespace only populated with API pseudo devices
# such as /dev/null, /dev/zero and /dev/random.
PrivateDevices=true

# Deny the creation of writable and executable memory mappings.
MemoryDenyWriteExecute=true

# Deny any ability to create namespaces. Should not be needed
RestrictNamespaces=true

# Restrict any kind of special capabilities
CapabilityBoundingSet=

# Allow minimal system calls for IO (filesystem network) and basic systemctl operations
SystemCallFilter=@signal @network-io @ipc @file-system @chown @system-service

# Access to  /sys/fs/cgroup/ should not be needed
ProtectControlGroups=true

# We don't need access to special file systems or extra kernel modules to work
ProtectKernelModules=true

# Access to proc/sys/, /sys/, /proc/sysrq-trigger, /proc/latency_stats, /proc/acpi, /proc/timer_stats, /proc/fs and /proc/irq is not needed
ProtectKernelTunables=true

# From the docsk "As the SUID/SGID bits are mechanisms to elevate privileges, and allow users to acquire the identity of other users, it is recommended to restrict creation of SUID/SGID files to the few programs that actually require them"
RestrictSUIDSGID=true

[Install]
WantedBy=multi-user.target


```
## Your environment
- Polygon Edge Client v1.0.0-rc1
- Cloud hosted, AWS Linux deployed by the terraform script
- The rootchain is the mumbai testnet, not geth.
- Branch name: tags/v1.0.0-rc1
- Validators are not running in a containerized environment.

## Steps to reproduce
You could simply add those flags to a local deployment script and redo the process after the first deployment.

## Expected behavior
- Expected: The addresses that were not initially allowlisted should not be able to create transactions.
- Delivered: The addresses that were not initially allowlisted were able to create transactions.

## Logs
There is no logs for this issue since it doesn't throw any errors, it only fails the validation.

## Proposed solution
Perhaps this issue is related to the chain id? it's just a guess but it could make sense somehow. I did not change the chain id very often.

**Comment by vcastellm** [comment]
> Questions:
> 
> * Is the allowlist stored completely on the supernets client or is it hosted somewhere else?

Allowlists are stored on-chain, they run using a precompile.

> * Am I missing any additional flag?

It looks correct

> * In case this happens again for any other reason, is there a way to manually enable it post deployment?

Allowlists should be enabled at Genesis, if that condition is met, the list can be administered post genesis at will.

What's the result when querying an allowlist address role? using:

`cast call --rpc-url https://rpc_url 0x0200000000000000000000000000000000000002 "function readAddressList(address) returns (uint256)" {{ loadtest_account }}`

Also can you paste the relevant content from your `genesis.json` file?

Thanks for reporting

**Comment by giovanni-pucci** [comment]
@vcastellm Thank you for your response.

We had another issue regarding the allowlist which @praetoriansentry is looking into internally.

In the meantime, I've disabled both the contract-deployer-allowlist and the transactions-allowlist so I'll not be able to run your cast command for now.

Our client will like to make his chain public at some point in the future, from my understanding of your response:

> Allowlists should be enabled at Genesis, if that condition is met, the list can be administered post genesis at will.

It's only possible to decide whether the chain has the allowlist enabled or not during its creation, is that correct?

**Comment by vcastellm** [comment]
Ok, we're reviewing internally.

> It's only possible to decide whether the chain has the allowlist enabled or not during its creation, is that correct?

That's correct

I'm closing the issue in the meantime, feel free to reopen if necessary.

**Comment by RonTuretzky** [comment]
@vcastellm how do I interact with the precompile ? 

cast call --rpc-url http://localhost:10004 0x0200000000000000000000000000000000000002 "function setEnabled(address)" <address_to_add> -f <admin_acc> --private-key <private key> 

does not seem to work , as the next read doesn't reflect an update to the role but returns the same as before the command (command returns 0x)

**Comment by vcastellm** [comment]
@RonTuretzky your interaction looks ok, here you can find some more info https://wiki.polygon.technology/docs/supernets/operate/deploy/access-control/supernets-allowlist-add-remove, but just confirm that you need to enable the ACL at genesis time, ACLs can not be enabled at execution time, so your call won't work in that case.

**Comment by RonTuretzky** [comment]
@vcastellm 
the interaction consistently failed, & that article is insufficient as it does not provide the ABIs nor the contract addresses. 

I was able to resolve this issue by accessing the addresses stored at contracts/system_addresses and by compiling the abi for the contract on my own based on lines 15-18 in the file addresslist.go in state/runtime and interfacing with a standard ethers script, not sure why the cast isn't working 

If this information was mentioned or if the addresses\abis were provided in the article it would have saved me a lot of time, if there's a away to open a pull request for the wiki page I'd love to contribute

**Comment by vcastellm** [comment]
Yes, we need to update the document, pasting here for reference:

```
pragma solidity >=0.8.0;

interface AllowListInterface {
    // Set [addr] to have the admin role over the allow list
    function setAdmin(address addr) external;

    // Set [addr] to be enabled on the allow list
    function setEnabled(address addr) external;

    // Set [addr] to have no role over the allow list
    function setNone(address addr) external;

    // Read the status of [addr]
    function readAllowList(address addr) external view returns (uint256);
}
```

**Comment by RonTuretzky** [comment]
> Yes, we need to update the document, pasting here for reference:
> 
> ```
> pragma solidity >=0.8.0;
> 
> interface AllowListInterface {
>     // Set [addr] to have the admin role over the allow list
>     function setAdmin(address addr) external;
> 
>     // Set [addr] to be enabled on the allow list
>     function setEnabled(address addr) external;
> 
>     // Set [addr] to have no role over the allow list
>     function setNone(address addr) external;
> 
>     // Read the status of [addr]
>     function readAllowList(address addr) external view returns (uint256);
> }
> ```

Thank you, I did not manage to update my previous comment before you replied :) thank you anyways
