### ISSUE TITLE
Bootnode validator not able to sync up to latest block

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#162]
### Description

It seems our 5-validator testnet got stuck and encountered a state where some of our node's latest block numbers fell out of sync, preventing the network from generating new blocks (as 4 validators are required).

`node-4` in our case crashed at block 0xb60d1 and couldn't sync up to 0xb60d7, the latest block on `node-1`.

While investigating, I tried to completely wipe everything within the data-dir of `node-4` hoping that it'll be able to sync up to the latest block on `node-1` (0xb60d7) from a clean slate:

```
rm -rf blockchain keystore trie consensus/metadata consensus/snapshots
```

However upon doing so and re-running `server` on `node-4`, the logs show the node to keep falling back into `RoundChangeState`:
```
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.362Z [INFO]  polygon.blockchain: genesis: hash=0x24d80debadd21a42ae8bcc3b28d39a0e2e2cbf9d7fee3507c1e38a33995fc3f5
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.363Z [INFO]  polygon: GRPC server running: addr=0.0.0.0:10000
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.363Z [INFO]  polygon.jsonrpc: http server started: addr=0.0.0.0:10002
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [DEBUG] polygon.consensus.ibft: state change: new=SyncState
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [DEBUG] polygon.consensus.ibft: current sequence: sequence=1
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [DEBUG] polygon.consensus.ibft: state change: new=AcceptState
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [DEBUG] polygon.consensus.ibft: cycle: state=AcceptState sequence=1 round=0
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [INFO]  polygon.consensus.ibft.acceptState: Accept state: sequence=1
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [INFO]  polygon.consensus.ibft: current snapshot: validators=4 votes=0
Sep 22 18:18:57 ip-172-31-32-129 main[1131978]: 2021-09-22T18:18:57.377Z [INFO]  polygon.consensus.ibft: proposer calculated: proposer=0x4FAC0232243D2C863EF7787e0cb9c9118048d60e block=1
Sep 22 18:19:02 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:02.350Z [DEBUG] polygon.network: dial: local=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW addr="{16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh: [/ip4/3.215.13.226/tcp/10001]}"
Sep 22 18:19:02 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:02.384Z [DEBUG] polygon.network: dial: local=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW addr="{16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW: [/ip4/204.236.222.207/tcp/10001]}"
Sep 22 18:19:02 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:02.384Z [DEBUG] polygon.network: dial: local=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW addr="{16Uiu2HAmJzMKm6c3HUAVzH1oQ6aV3QRzMrEvz5TVtcbvuY2oH54x: [/ip4/34.207.228.138/tcp/10001]}"
Sep 22 18:19:02 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:02.390Z [DEBUG] polygon.network: dial: local=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW addr="{16Uiu2HAmGGueWQo4oudvL6uWGXGMorEHvT7GyUtYN4t2yNi6rujU: [/ip4/3.84.231.38/tcp/10001]}"
Sep 22 18:19:02 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:02.395Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
Sep 22 18:19:07 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:07.353Z [DEBUG] polygon.network: dial: local=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW addr="{16Uiu2HAkwhNtm8iXMoWR7hmVCK3on6Rhz2DM8V6VhQm9bkdUwq1d: [/ip4/54.167.213.167/tcp/10001]}"
Sep 22 18:19:07 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:07.378Z [DEBUG] polygon.consensus.ibft: state change: new=RoundChangeState
Sep 22 18:19:07 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:07.378Z [DEBUG] polygon.consensus.ibft: cycle: state=RoundChangeState sequence=1 round=0
Sep 22 18:19:07 ip-172-31-32-129 main[1131978]: 2021-09-22T18:19:07.378Z [DEBUG] polygon.consensus.ibft: local round change: round=1
```

I then attempted to reset our non-bootnode (`node-5`) back to block 0 to test out whether or not the bug exists in the actual syncing and upon restarting, I could immediately see `node-5` attempt to sync up to `node-1`:
```
Sep 22 18:13:04 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:04.993Z [INFO]  polygon.blockchain: genesis: hash=0x24d80debadd21a42ae8bcc3b28d39a0e2e2cbf9d7fee3507c1e38a33995fc3f5
Sep 22 18:13:04 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:04.994Z [INFO]  polygon: GRPC server running: addr=0.0.0.0:10000
Sep 22 18:13:04 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:04.995Z [INFO]  polygon.jsonrpc: http server started: addr=0.0.0.0:10002
Sep 22 18:13:10 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:10.005Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAm9SX9R9oqi1afyw5Qg1JgNvZfbPwbSEQH5NCBuBNWk8Lh
Sep 22 18:13:10 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:10.014Z [INFO]  polygon.network: Peer connected: id=16Uiu2HAmBv5UkctkZK1ui2tMip6XqpykvMnrzDuLGNjN38YDztmW
Sep 22 18:13:11 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:11.012Z [INFO]  polygon.blockchain: write blocks: num=10 from=1 to=10 parent=0x24d80debadd21a42ae8bcc3b28d39a0e2e2cbf9d7fee3507c1e38a33995fc3f5
Sep 22 18:13:11 ip-172-31-86-180 main[77785]: 2021-09-22T18:13:11.031Z [INFO]  polygon.blockchain: new block: number=1 hash=0x0b0278e54850e679e866e14dd7e238208c16e4abed2b8f0d5ea5c82a29ce9ff9 txns=0 generation_time_in_sec=1630687894
```

I'm not sure why `node-4` crashed in the first place but based on what I observed above, it seems that there is in issue when trying to sync up nodes that are within the genesis.json. 

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon SDK `4afea94 `
* branch that causes this issue `develop`

### Steps to reproduce

1.  Have 5 nodes running as validators (4 bootnodes + 1 non-bootnode)
2. Kill one of the 4 bootnodes (e.g. `node-4`)
3. Vote off the non-bootnode so that it is no longer a validator
4. Start up `node-4` and observe that it cannot sync up to the latest block
5. Attempt to clear the history of `node-4` and attempt to sync, observing the same issue

### Expected behaviour

Nodes (within or outside the bootnode validator set) should be able to sync up to the latest block when they fall behind (due to a crash).

### Actual behaviour

One of the 4 bootnode validators could not sync up to the latest block (it remained in `RoundChangeState`).

### Logs

See Description

**Comment by Kourin1996** [comment]
Hello, @dankostiuk. Thank you for raising the issue. I want to ask following things. I'd appreciate if you could answer them.
(1) According to the first log, node-4 seemed to be able to connect only one node. But it was trying to connect to more 2 nodes (except for own node). node-4 could connect to remaining bootnodes?
(2) According to Line 9 of the first log, number of initial validators seems to be 4. Did you add a non-bootnode into validator set by voting?

I'm trying to reproduce this issue in my local environment. But I couldn't do so far.

FYI, following steps are what I tried
(1) run `ibft init` for 5 nodes
(2) run `genesis` with options of 5 validators and 4 bootnodes like:
```bash
go run ./main.go genesis --consensus ibft \
--ibft-validator [VALIDATOR_1_ADDR] \
--ibft-validator [VALIDATOR_2_ADDR] \
--ibft-validator [VALIDATOR_3_ADDR] \
--ibft-validator [VALIDATOR_4_ADDR] \
--ibft-validator [VALIDATOR_5_ADDR] \
--bootnode [VALIDATOR_1_LIBP2P_ADDR] \
--bootnode [VALIDATOR_2_LIBP2P_ADDR \
--bootnode [VALIDATOR_3_LIBP2P_ADDR \
--bootnode [VALIDATOR_4_LIBP2P_ADDR
```
(3) run `server` for 5 nodes (e.g. `go run ./main.go server --data-dir ./test-chain-1 --grpc :10000 --libp2p :10001 --jsonrpc :$10002 --seal --chain ./genesis.json --log-level DEBUG`)
(4) check all nodes work
(5) terminate node No.4 (last of bootnode)
(6) run `ibft propose` to remove validator No.5 (non-bootnode) (e.g. `go run main.go ibft propose --vote drop --addr 0x7aD81Fa14db7d8f6e5e0eC017e93B18F70bB4ADC --grpc-address :10000`). I send this request to node No.1 - No.3
(7) run `server` for node No.4
(8) node No.4 works

**Comment by dankostiuk** [comment]
Hey @Kourin1996, after running a vscode debugging session over ssh I believe I found the issue:

First off, it looks like when node-4 goes into the immediate SyncState at the start of ibft.start(), the syncer always has an empty list of peers (as seen below), so it immediately moves to AcceptState and eventually gets stuck in RoundChangeState.

![Screen Shot 2021-09-23 at 2 32 23 PM](https://user-images.githubusercontent.com/3344880/134563898-56ea85e1-a1b2-4e2e-a90f-95fc1d363a28.png)

While in RoundChangeState, it looks like we periodically check for a peer to sync to. In this example I only have node-1 and node-4 running so node-1 is recognized as the bestPeer. When on line 704 within ibft.go, it seems like `bestPeer.Number()` returns 0, preventing it from getting back into SyncState:

![Screen Shot 2021-09-23 at 1 54 12 PM](https://user-images.githubusercontent.com/3344880/134562136-70c8e8a9-d082-4f70-a9d7-dc86275d0807.png)

On the same line (704) one can see that the `syncPeer.status.Number` shows the correct latest blockNumber of node-1 (0xb60d7) which differs from the value at `syncPeer.number`:

![Screen Shot 2021-09-23 at 1 53 04 PM](https://user-images.githubusercontent.com/3344880/134562131-aeeb0e98-5fe4-4016-b45b-a97314d8672c.png)

 It seems like the `syncPeer.number` field should be removed and the `Number()` function in syncer.go should instead be modified to return `s.status.Number` as shown below:
![Screen Shot 2021-09-23 at 2 11 33 PM](https://user-images.githubusercontent.com/3344880/134562143-2e8d31e9-6caa-4654-9fc4-caa1f868109d.png)

^ Doing this change above fixed the issue as node-4 is now able to sync to the latest block.

**Comment by Kourin1996** [comment]
Hi, @dankostiuk. Thank you for taking your time to debug. I will also check this part.

**Comment by dankostiuk** [comment]
Appreciate that @Kourin1996 , thank you!

**Comment by Kourin1996** [comment]
Hello, @dankostiuk. I opened new PR https://github.com/0xPolygon/polygon-sdk/pull/164 for the issue. I investigated the code and we still want syncPeer to return number in `Number()` methods because this field is updated when syncer receives latest block from peer. Instead of this, I fixed and initialize number by `status.number`
You can check this PR. Thanks!
