### ISSUE TITLE
Supernet native token balance does not reflect on Metamask (commit a736a9c)

### ISSUE THREAD

**Issue by tandooricodes** [0xPolygon/polygon-edge#1630]
# Supernet native token balance does not reflect on Metamask

I followed the guide here to deploy a Supernet with Mumbai as rootchain: https://github.com/integrations-Polygon/Supernets-Edge-Tutorials/blob/master/Supernets_v1.0.0_setup.md

However, when add the newly created Supernet RPC at `http:127.0.0.1:9545` to metamask, it does not fetch the premined balance of the address. Upon checking the address balance using `ethersjs` we can verify that the premining has been successful. We can also transfer the premine to other addressses via `ethersjs`. It just doesn't reflect on Metamask.

If anyone is able to view the balance on Metamask do let me know.

**Comment by Stefan-Ethernal** [comment]
For starters, please double-check that you have provided the correct JSON RPC URL (I see from your description that you are lacking `//` in the JSON RPC URL, although Metamask wouldn't allow you to save such changes) and chain id.

I'm attaching an image that demonstrates how it looks like on my end:
![image](https://github.com/0xPolygon/polygon-edge/assets/93934272/bf46ce19-93ba-4ff0-ba2e-0a72cee56573).

I have set up a locally running Supernets cluster on my machine and premined this account with 1000 tokens in the genesis. And voila, this is how it looks like in the Metamask:
![image](https://github.com/0xPolygon/polygon-edge/assets/93934272/06185e7c-adf3-48c8-aff0-84f6ad5d9ce3).
Although I have first spun up Supernets and then imported the account. Not sure does it affect displaying the correct balance.

What you could also try is removing and re-importing the account in the Metamask or changing the active network and see whether it helps.
