### ISSUE TITLE
Error while withdrawing from the Supernet

### ISSUE THREAD

**Issue by tandooricodes** [0xPolygon/polygon-edge#1640]
# Error while withdrawing from the Supernet

## Description
I have followed the guide [here](https://github.com/integrations-Polygon/Supernets-Edge-Tutorials/blob/master/Supernets_v1.0.0_setup.md) to setup a local Supernet in the relayer mode. After setting up I used the following command to deposit:

The sender and the receiver are the same address (me sending to myself). The `--root-token` is an ERC20 and the `root-predicate` address has been fetched from the `genesis.json` file. 

```
 ./polygon-edge bridge deposit-erc20 --sender-key <my_private_key_here> --receivers 0xAE3ac03497aB6aFfF786bCFF95DD6e9095Dc5d55 --amounts 1000000000000000000 --root-token 0x7EC3aA587e4c38387C50edff21E4dfdcC84c9C42 --root-predicate 0xceeEC84D7ec37EEd82BFC9B12f86A165C4991408 --json-rpc <mumbai_rpc_here>
```

This is the output I receive:
```
[DEPOSIT ERC 20]
Sender                  = 0xAE3ac03497aB6aFfF786bCFF95DD6e9095Dc5d55
Receivers               = 0xAE3ac03497aB6aFfF786bCFF95DD6e9095Dc5d55
Amounts                 = 1000000000000000000
Inclusion Block Numbers = 37071894
Child Token Address     = 0x371eE3da653c8d11c8cE4de21f5EfE7215C5C1CD
```
Looks like Deposit was a success.

Next, to withdraw the assets I use the following command. I have picked the `--child-predicate` from the `genesis.json` file and `--child-token` from the output of the previous command. The `--json-rpc` is from the local supernet node:
```
./polygon-edge bridge withdraw-erc20 --sender-key <my_private_key_here> --receivers 0xAE3ac03497aB6aFfF786bCFF95DD6e9095Dc5d55 --amounts 1000000000000000000 --child-predicate 0xded80b836541F82FEc7Fd4D7166F3a1D86679b2D --child-token 0x371eE3da653c8d11c8cE4de21f5EfE7215C5C1CD --json-rpc http://localhost:9545
```

This is the output I receive upon attempting withdraw:
```
failed to extract exit event: failed to find exit event log
```

In case I have missed something do let me know, thanks for your time!

## Your environment
- PopOS (Ubuntu 22.04)
- Latest Commit [June 20th] #de084a9
- Local Deployment
- No Containers

**Comment by Stefan-Ethernal** [comment]
We detected that we have a problem regarding child token addresses calculated differently by the root and child predicates. That is why the child token address printed by the deposit command is not the correct one. Therefore we have raised this [PR](https://github.com/0xPolygon/polygon-edge/pull/1621), which should resolve this issue.

I'm closing this for now, and if needed you can reopen it.
