### ISSUE TITLE
How to mint native token

### ISSUE THREAD

**Issue by polygomic** [0xPolygon/polygon-edge#1691]
I created superchain with native mintable token and not premine any token
after that I am going to mint
how should I do that?
I searched and not find any documention or command to mint on superchain

## Your environment
- OS and version.
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by Stefan-Ethernal** [comment]
An account that is set as the owner of `NativeERC20Mintable` during genesis (the address value provided to the `native-token-config` flag) is the one that is allowed to invoke the `mint` function.

So you could do it in the following way, using `foundry` for example:
```bash
cast send --private-key <private key of owner account> 0x0000000000000000000000000000000000001010 "mint(address account, uint256 amount) returns (bool)" <receiver address> <amount>
```
