### ISSUE TITLE
run v1.0.0  scripts/cluster ibft --docker  error

### ISSUE THREAD

**Issue by Billyblingbling** [0xPolygon/polygon-edge#1692]
=> ERROR [init runner 6/6] COPY ./core-contracts/artifacts ./core-contracts/artifacts                                                         0.0s
------
 > [init runner 6/6] COPY ./core-contracts/artifacts ./core-contracts/artifacts:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref e06ff766-58e2-4e13-ac1c-4cbd63e0acfa::ttlk2yskzwaeh6daahl1phrs7: "/core-contracts/artifacts": not found

**Comment by der4eichi** [comment]
I get it running with 2 more steps:
git clone --recurse-submodules  https://github.com/0xPolygon/polygon-edge/
cd polygon-edge/core-contracts/
npm install hardhat
npx hardhat compile --show-stack-traces
docker-compose -f ./docker/local/docker-compose.yml up -d --build

then it was working
thanks to the help of @bytebutcher
