### ISSUE TITLE
Error in calculating proposer: invalid height - expected 40722, got 1

### ISSUE THREAD

**Issue by leonliuyang** [0xPolygon/polygon-edge#1695]
# [ Do not product blocks]
## Description
I encountered an error while running Polygon-Edge v1.0.0 while setting up a new chain. The error message suggests an issue with calculating the proposer, indicating an invalid height. Here are the details:

`2023-07-04T09:14:35.246Z [ERROR] polygon.server.polybft.consensus_runtime: cannot calculate proposer: error="invalid height - expected 40722, got 1"
`

## Your environment
- OS and version.
Linux ubuntu1804601 4.15.0-208-generic 220-Ubuntu SMP Mon Mar 20 14:27:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- The version of the Polygon Edge.    
  [VERSION INFO]
Release version = v1.0.0
Git branch      = <none>
Commit hash     = <none>
Build time      = <none>

## Steps to reproduce
- Provide us with the content of your genesis file.
[genesis.json.txt](https://github.com/0xPolygon/polygon-edge/files/11947716/genesis.json.txt)
- Provide us with commands that you used to start your validators.
polygon-edge server --data-dir ./test-chain-1 --chain ./genesis.json --grpc-address :5001 --libp2p :30301 --jsonrpc :10001 --seal --log-level DEBUG
polygon-edge server --data-dir ./test-chain-2 --chain ./genesis.json --grpc-address :5002 --libp2p :30302 --jsonrpc :10002 --seal --log-level DEBUG
polygon-edge server --data-dir ./test-chain-3 --chain ./genesis.json --grpc-address :5003 --libp2p :30303 --jsonrpc :10003 --seal --log-level DEBUG
polygon-edge server --data-dir ./test-chain-4 --chain ./genesis.json --grpc-address :5004 --libp2p :30304 --jsonrpc :10004 --seal --log-level DEBUG

- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
[PEERS LIST]
Number of peers: 3
[0] = 16Uiu2HAmTJ5bQfbGU9JF51H5YTUCsqtGWQDKfMNHyztkPvKqCDSv
[1] = 16Uiu2HAkxnkiV3su95a3h3w4dMjsorbFEQcVL3iGimkWUNjRUKe9
[2] = 16Uiu2HAm7XCRAg2W5Esi5fUZf5oZb2eHUJaAp8i8FYix9t8hGdX7

- Is the chain producing blocks and serving customers atm?
No, eth_getBlockNumer  always gives 0.

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

 eth_getBlockNumer always returns 0

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`
[log.txt](https://github.com/0xPolygon/polygon-edge/files/11947803/log.txt)

**Comment by stana-miric** [comment]
It appears that the consensusState database was read from an already existing file since the height in the proposer calculator was set to 40722 when the node was started. Does this log also appear for other nodes? Upon examining the logs, it seems that there are some old files that were not cleaned up

**Comment by stana-miric** [comment]
Closing this issue, since the problem occurred due to an invalid configuration(old files).
