### ISSUE TITLE
Missing call to close LevelDB connection for /trie dir on close

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#170]
### Description

When stopping the process gracefully, the `Close()` function in server.go closes the blockchain layer which closes the levelDB session for the /blockchain folder. It looks like the leveldb.DB for the stateStorage (/trie) stays open.

For example when stopping the process at 18:41, one can see in the LOG for /blockchain:
```
18:26:25.559234 table@remove removed @10296
18:26:25.559429 table@remove removed @10297
18:41:23.591281 db@close closing
18:41:23.591489 db@close done T·206.365µs
=============== Sep 29, 2021 (UTC) ===============
18:42:14.243688 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
18:42:14.244604 version@stat F·[0 60 224] S·545MiB[0B 98MiB 447MiB] Sc·[0.00 0.98 0.45]
18:42:14.244632 db@open opening
18:42:14.245225 journal@recovery F·1
18:42:14.245469 journal@recovery recovering @25440
18:42:14.280050 memdb@flush created L0@25508 N·1675 S·172KiB "b\x00k..\b\x9a\x05,v6098864":"r\xffK..\xc5\xedW,v6099554"
18:42:14.280296 version@stat F·[1 60 224] S·545MiB[172KiB 98MiB 447MiB] Sc·[0.25 0.98 0.45]
18:42:14.312486 db@janitor F·288 G·1
18:42:14.312506 db@janitor removing table-25439
18:42:14.312570 db@open done T·67.929489ms
```

/trie/LOG however contains:
```
18:26:23.146333 db@janitor F·15 G·0
18:26:23.146362 db@open done T·76.615875ms
=============== Sep 29, 2021 (UTC) ===============
18:42:14.203082 log@legend F·NumFile S·FileSize N·Entry C·BadEntry B·BadBlock Ke·KeyError D·DroppedEntry L·Level Q·SeqNum T·TimeElapsed
18:42:14.203297 version@stat F·[2 11] S·22MiB[85KiB 22MiB] Sc·[0.50 0.22]
18:42:14.203325 db@open opening
18:42:14.203414 journal@recovery F·1
18:42:14.203984 journal@recovery recovering @167
18:42:14.235378 memdb@flush created L0@169 N·248 S·48KiB "\x03\xbe\xc2..h\x1a>,v112665":"\xfdO\x16..\x1dٚ,v112616"
18:42:14.235692 version@stat F·[3 11] S·22MiB[134KiB 22MiB] Sc·[0.75 0.22]
18:42:14.243432 db@janitor F·16 G·0
18:42:14.243482 db@open done T·40.147145ms
```

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon SDK `96be904 `
* branch that causes this issue `develop`

### Steps to reproduce

1. Stopped process running `server`
2. Attempted to make a backup of data-dir by uploading a .tar.gz to AWS S3
3. Downloaded the .tar.gz and saw error while attempting to extract /trie directory
4. Observed `db@close` in /blockchain/LOG
5. Did not observe `db@close` in /trie/LOG

### Expected behaviour

The trie db session should release its lock and close gracefully.

### Actual behaviour

The trie db session doesn't appear to close.

**Comment by dankostiuk** [comment]
Turns out the issue was as a result of something unrelated which I now figured out. Closing...

**Comment by Kourin1996** [comment]
Hello, @dankostiuk. I appreciate your reporting the issue. I fixed at https://github.com/0xPolygon/polygon-sdk/pulls. Please wait until it's merged. Thanks.
