### ISSUE TITLE
invalid character '<' looking for beginning of value

### ISSUE THREAD

**Issue by AceLuodan** [0xPolygon/polygon-edge#1701]
./polygon-edge polybft stake-manager-deploy --private-key *  --genesis ./genesis.json --jsonrpc https://matic-mumbai.chainstacklabs.com/ --stake-token 0x73aCC587D82Ca7770ef3a7CaB4Ba28EF4D53B0B4

log:
Error: failed sending StakeManager contract deploy transaction: invalid character '<' looking for beginning of value
 failed sending StakeManager contract deploy transaction: invalid character '<' looking for beginning of value

i can't deploy to  polygon mumbai testnet?

**Comment by Stefan-Ethernal** [comment]
It seems that the provided JSON RPC url corresponds to some node that is unavailable. Could you try with the following one: https://polygon-mumbai.g.alchemy.com/v2/JPxV0ktDGv24NhRucZs0I8s3gvDaclZn
