### ISSUE TITLE
Trying migrate from v0.6.3 to v0.8

### ISSUE THREAD

**Issue by Tasmana-banana** [0xPolygon/polygon-edge#1721]
## Description
Trying migrate from v0.6.3 to v0.8

## Your environment
- OS and version.
Ubuntu 20.04

polygon-edge 0.8

## Steps to reproduce
Try execute command from https://wiki.polygon.technology/docs/supernets/operate/supernets-ibft-to-polybft#2-create-trie-snapshot (step 5)

## Logs
`failed to load manifest file from provided path './manifest.json': open ./manifest.json: no such file or directory
`

**Comment by Tasmana-banana** [comment]
What i need set eq manifest.json? If i delete data folder with genesis

**Comment by Tasmana-banana** [comment]
OK, i create this by - `polygon-edge manifest --validators-prefix data`
But now i have error when i start new version
```
node1  | 
node1  | 2023-07-13T11:26:07.076Z [INFO]  polygon.server: Data dir: path=/data
node1  | 2023-07-13T11:26:07.077Z [DEBUG] polygon.server: DataDog profiler disabled, set DD_PROFILING_ENABLED env var to enable it.
node1  | 2023-07-13T11:26:07.081Z [INFO]  polygon.server: Prometheus server started: addr==0.0.0.0:5001
node1  | invalid initial state root
node1 exited with code 0
```

**Comment by rachit77** [comment]
Are you trying to migrate from IBFT to PolyBFT?
and did you stopped your running node before executing the `regenesis` command?

**Comment by rachit77** [comment]
Hi,
Closing this issue for now. Feel free to reopen if needed.
