### ISSUE TITLE
Error: failed sending StakeManager contract deploy transaction: dialing to the given TCP address timed out

### ISSUE THREAD

**Issue by squiddyswap** [0xPolygon/polygon-edge#1732]
Error: failed sending StakeManager contract deploy transaction
When trying to deploy the StakeManager with this command:

sudo ./zroarchain polybft stake-manager-deploy \
    --jsonrpc  https://rpc-mumbai.matic.today/  \
    --private-key private-key \
    --stake-token 0x0000000000000000000000000000000000001010 \
    --genesis /etc/zroarchain/genesis.json 

Getting this error:
Error: failed sending StakeManager contract deploy transaction: dialing to the given TCP address timed out

Describe your issue in as much detail as possible here.

Debian 11 OS

Polygon Edge v1.0.1    

## Steps to reproduce
Run this command:

sudo ./zroarchain polybft stake-manager-deploy \
    --jsonrpc  https://rpc-mumbai.matic.today/  \
    --private-key private-key \
    --stake-token 0x0000000000000000000000000000000000001010 \
    --genesis /etc/zroarchain/genesis.json 

## Expected behavior
should run and deploy stake manager
but it gave a timeout error

**Comment by squiddyswap** [comment]
sudo ./zroarchain polybft stake-manager-deploy
--jsonrpc https://rpc-mumbai.matic.today/
--private-key private-key
--stake-token erc20 token
--genesis /etc/zroarchain/genesis.json

Even if you put in an ERC20 token to stake it come back with the same response.  I researched this error and as it occurs with Polygon it has a gas estimation problem and there is a workaround for this issue.  Looks like some attempt has been used with this very workaround, but that workaround may not be implemented correctly.

**Comment by Stefan-Ethernal** [comment]
Maybe you should try out specifying this JSON RPC url:
`--jsonrpc https://polygon-mumbai.g.alchemy.com/v2/JPxV0ktDGv24NhRucZs0I8s3gvDaclZn`.

Also for stake-token, WMATIC should be used. This is its address on the Mumbai https://mumbai.polygonscan.com/address/0x9c3C9283D3e44854697Cd22D3Faa240Cfb032889.

**Comment by squiddyswap** [comment]
Thank you so much for your response.  I tried your suggestions and it still came back with the same response TCP timeout when trying to deploy the stake manager.

**Comment by squiddyswap** [comment]
looks like this is similar to our problem differences:  we are connecting to Polygon and this issue is Ethereum.

 Error: Max fee less than base fee sometimes when deploying to alternative L1/L2 for rootchain #1738

**Comment by Stefan-Ethernal** [comment]
Ok if you suspect that gas estimation is not correct and that you are facing the same issue as in #1738, then you can either wait for the next release, or try building binary on your own, but make sure that you choose the latest commit from `develop` (namely the one which includes fix #1718).

**Comment by squiddyswap** [comment]
thank you for your response, I will give it my best try.  Not the expert(SME) on the code, but will look at it and see if I can come up with a workaround until the next release.  Thanks again.

**Comment by Stefan-Ethernal** [comment]
@squiddyswap in fact, you can try out with the newest release (https://github.com/0xPolygon/polygon-edge/releases/tag/v1.1.0) and see if it is any better, because mentioned #1718 is part of it.

**Comment by mrandall101** [comment]
Will do.  Thank you.
