### ISSUE TITLE
Mapping tokens in chains

### ISSUE THREAD

**Issue by polygomic** [0xPolygon/polygon-edge#1734]
How If I have a token in rootchain and another token in childchain how could I map this 2 tokens for bridge actions.
there is very good action to add command in polygon-edge to get (rootTokenaddress,name,Symbol,decimal) and generate it and map it to root token.
how could I do that right now?

## Your environment
- OS and version.
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by Stefan-Ethernal** [comment]
It is not supposed to work that way and it is impossible to map two tokens that pre-exist on both root and child chains. If there is an existing token on the rootchain, its counterpart is created and mapped automatically on the child chain (by the `Child*Predicate`) when a deposit is made the first time for the given token. The child chain token is a minimal clone/proxy of the `ChildERC20/721/1155` token implementation.
