### ISSUE TITLE
Metamask problem again

### ISSUE THREAD

**Issue by polygomic** [0xPolygon/polygon-edge#1755]
the version v1.1.0 has problem in gas estimation

I enabled London fork to enable gas estimation
my genesis file is :

{
    "name": "TestChain",
    "genesis": {
        "nonce": "0x0000000000000000",
        "timestamp": "0x0",
        "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f90309f9029df90298f8a4942c8ffc6846c807e99d93b30c6b0b0a44a407042db8802b19a8db7aa4dc1232590390f65a30ef29c020e086ed6dcc6b9fe787d0b3b13e1e628b342fcd86d0bf2f535626be6508fb1eb337acf020ee9b70768150fab75524b4a9dfe50ee4132ee3739eb88a933953ec91ebb9d8b153bc6584b8585f91442ba8e39d1198fddd9fec4e9d1a82500be83b7206bd8a32e9d77d90d27f061f8e8b01a784379d99db4200000001f8a494c7353ec27c51e77e0fb9024cf463087972fe16dab880160fd6e549572362b5e1fe0bfc0d79d21b44f89f4dd1492faeee65dd1bc355ef25fdd40942cd2a4882f1b1c495cb82417e54e01477773c6b8fd8dd94f64f9631294ebffa020d0385c52ca4b74dacff357f830bb08dd83fd0865ef906b62dc2a31171bc48f9a15cfb5cc6a2307bcebf2dbe1b009cf61c46eda1db12bc1e7eb0bf8b01a784379d99db4200000001f8a494db2ce3d5aab26f0cca80a45737b94737f9a097c3b88029da04abfcee502919e5419a95a13c62f6e03c04643390bc11a889cb26da9ac421cf92b71d2b6a95b969be565f0d8f644bce39fb97ecbacbd64d3a32ed42d02423ce30152b6184c4c126c02de69a033cb99ea271f830ba41f0651adf78671237026577f0aa9ab20c25b11cdfab95a8e849904c182523388c7df1814bb83e531a8b01a784379d99db4200000001f8a494bca1ecbfd75c693a6a9c38f25d067361e5d0ff22b8800b62af26dcbd91f92ab226a3da2f931b29a3879a5ad368a339c4d848be0f006412f8bf25ae951b89d60cd878dc972740cf4282087303a39c4a0ca96f63b1d70009d901d3821ac9498ae729354ed2247af7731c9948e3fa747456a7f2f2ebbaaf2160e2bbd012a9b86ec888619d24a8c87007a2711dbc9c4813a6971e70e431ba8b01a784379d99db4200000001c080c0c0f8658080a00000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000000",
        "gasLimit": "0xbebc20",
        "difficulty": "0x0",
        "mixHash": "0xadce6e5230abe012342a44e4e9b6d05997d6f015387ae0e59be924afc7ec70c1",
        "coinbase": "0x0000000000000000000000000000000000000000",
        ...
        "number": "0x0",
        "gasUsed": "0x70000",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "baseFee": "0x3b9aca00",
        "baseFeeEM": "0x2"
    },
    "params": {
        "forks": {
            "EIP150": {
                "block": 1000
            },
            "EIP155": {
                "block": 0
            },
            "EIP158": {
                "block": 0
            },
            "byzantium": {
                "block": 0
            },
            "constantinople": {
                "block": 0
            },
            "homestead": {
                "block": 0
            },
            "istanbul": {
                "block": 0
            },
            "london": {
                "block": 1300
            },
            "petersburg": {
                "block": 0
            },
            "quorumcalcalignment": {
                "block": 1200
            },
            "txHashWithType": {
                "block": 1150
            }
        },
        "chainID": 424,
        "engine": {
            "polybft": {
                "initialValidatorSet": [
                    {
                        "address": "0x2c8FfC6846C807E99D93B30c6B0b0A44A407042D",
                        "blsKey": "2b19a8db7aa4dc1232590390f65a30ef29c020e086ed6dcc6b9fe787d0b3b13e1e628b342fcd86d0bf2f535626be6508fb1eb337acf020ee9b70768150fab75524b4a9dfe50ee4132ee3739eb88a933953ec91ebb9d8b153bc6584b8585f91442ba8e39d1198fddd9fec4e9d1a82500be83b7206bd8a32e9d77d90d27f061f8e",
                        "stake": "0x1a784379d99db42000000",
                        "multiAddr": "/ip4/127.0.0.1/tcp/30301/p2p/16Uiu2HAmJ5W7T6CrqnygCjK2Gtg7QMkeWJu7KAFYTetPk22c3GGR"
                    },
                    {
                        "address": "0xC7353ec27c51e77E0fb9024CF463087972Fe16DA",
                        "blsKey": "160fd6e549572362b5e1fe0bfc0d79d21b44f89f4dd1492faeee65dd1bc355ef25fdd40942cd2a4882f1b1c495cb82417e54e01477773c6b8fd8dd94f64f9631294ebffa020d0385c52ca4b74dacff357f830bb08dd83fd0865ef906b62dc2a31171bc48f9a15cfb5cc6a2307bcebf2dbe1b009cf61c46eda1db12bc1e7eb0bf",
                        "stake": "0x1a784379d99db42000000",
                        "multiAddr": "/ip4/127.0.0.1/tcp/30302/p2p/16Uiu2HAm4NvERKmhyqXzbPpqogWKxtg2GpP7KqAS36Lnu4WWBoVS"
                    },
                    {
                        "address": "0xDb2cE3D5AAb26f0CCA80A45737B94737f9A097C3",
                        "blsKey": "29da04abfcee502919e5419a95a13c62f6e03c04643390bc11a889cb26da9ac421cf92b71d2b6a95b969be565f0d8f644bce39fb97ecbacbd64d3a32ed42d02423ce30152b6184c4c126c02de69a033cb99ea271f830ba41f0651adf78671237026577f0aa9ab20c25b11cdfab95a8e849904c182523388c7df1814bb83e531a",
                        "stake": "0x1a784379d99db42000000",
                        "multiAddr": "/ip4/127.0.0.1/tcp/30303/p2p/16Uiu2HAmHHZm1E1SZGLfrBXUpSTe1gd4413NCxCbamYYfioun4SU"
                    },
                    {
                        "address": "0xbCA1ecBfd75C693A6a9C38f25D067361e5D0fF22",
                        "blsKey": "0b62af26dcbd91f92ab226a3da2f931b29a3879a5ad368a339c4d848be0f006412f8bf25ae951b89d60cd878dc972740cf4282087303a39c4a0ca96f63b1d70009d901d3821ac9498ae729354ed2247af7731c9948e3fa747456a7f2f2ebbaaf2160e2bbd012a9b86ec888619d24a8c87007a2711dbc9c4813a6971e70e431ba",
                        "stake": "0x1a784379d99db42000000",
                        "multiAddr": "/ip4/127.0.0.1/tcp/30304/p2p/16Uiu2HAm1sBmnKftTEhgkd1sx4acPo1eAcBnHtgKXYFP6cCQJVv5"
                    }
                ],
                "bridge": {
                    "stateSenderAddress": "0xB95344b3C5323b91ad1b81a3594a014111AB6915",
                    "checkpointManagerAddress": "0xd29c83E9b08C9b1FebC277596D96FD7B4921FC22",
                    "exitHelperAddress": "0xC4122cE8B0C4C1977d81E470dC574CdB1194d58a",
                    "erc20PredicateAddress": "0x2001B86A39251Dbe9400023dB9e600db82ab9272",
                    "erc20ChildMintablePredicateAddress": "0x7929e999bB3B1756DB8Dfb6407926e73AB023985",
                    "nativeERC20Address": "0x248f59b295E85daBa4ed7E6756B45dAEF08fe14B",
                    "erc721PredicateAddress": "0x5FBC1577d8D84F027DAd95467b0457345aF386B7",
                    "erc721ChildMintablePredicateAddress": "0x78AEc97127Ed4e21e8Eb261B9823172A29097979",
                    "erc1155PredicateAddress": "0x47D89dD9cB3ba14026f0E72a52c9676a19e52B4f",
                    "erc1155ChildMintablePredicateAddress": "0xdDD01Bb750907e8239D9E8a94650014dd07f54b6",
                    "childERC20Address": "0x44F61aF604A4CcbD8f9B8292b41f638F66106B9A",
                    "childERC721Address": "0x62974dE99377252FB0F7A1fC6712e6697E3D4e6c",
                    "childERC1155Address": "0x88Bd624E1B7d19024971133B545b2719E7211aE6",
                    "customSupernetManagerAddr": "0x2C60bDB8d817242217df0D309D2C4BEbFebA8f54",
                    "stakeManagerAddr": "0x639d5C416b67766CfdeB1ac5bA9a166Be8435593",
                    "stakeTokenAddr": "0x092b78Bd3579e3cf0B3Eb26C69222C969805348f",
                    "blsAddr": "0x9F0091700a86715aEfDa3aF4066AA97DCdBdb14c",
                    "bn256G2Addr": "0x6b46fb201Da98E5696ece4e3dCd741651a75734a",
                    "jsonRPCEndpoint": "https://rpc.ankr.com/polygon_mumbai",
                    "eventTrackerStartBlocks": {
                        "0xB95344b3C5323b91ad1b81a3594a014111AB6915": 38326567
                    }
                },
                "epochSize": 100,
                "epochReward": 1,
                "sprintSize": 5,
                "blockTime": "2s",
                "governance": "0x0000000000000000000000000000000000000000",
                "nativeTokenConfig": {
                    "name": "Plinga",
                    "symbol": "PLINGA",
                    "decimals": 18,
                    "isMintable": false,
                    "owner": "0x0000000000000000000000000000000000000000"
                },
                "initialTrieRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "supernetID": 1,
                "minValidatorSetSize": 1,
                "maxValidatorSetSize": 9007199254740990,
                "rewardConfig": {
                    "rewardTokenAddress": "0x0000000000000000000000000000000000001010",
                    "rewardWalletAddress": "0x805743F19dE8836dAF1B63D3414833Daeb180350",
                    "rewardWalletAmount": "0x1"
                },
                "blockTimeDrift": 10
            }
        },
        "blockGasTarget": 0,
        "burnContract": {
            "150": "0x6333A89dB7bBCB3fbb7efA12b09204c2E8757c4a"
        },
        "burnContractDestinationAddress": "0x0000000000000000000000000000000000000000"
    },
    "bootnodes": [
        "/ip4/127.0.0.1/tcp/30301/p2p/16Uiu2HAmJ5W7T6CrqnygCjK2Gtg7QMkeWJu7KAFYTetPk22c3GGR",
        "/ip4/127.0.0.1/tcp/30302/p2p/16Uiu2HAm4NvERKmhyqXzbPpqogWKxtg2GpP7KqAS36Lnu4WWBoVS",
        "/ip4/127.0.0.1/tcp/30303/p2p/16Uiu2HAmHHZm1E1SZGLfrBXUpSTe1gd4413NCxCbamYYfioun4SU",
        "/ip4/127.0.0.1/tcp/30304/p2p/16Uiu2HAm1sBmnKftTEhgkd1sx4acPo1eAcBnHtgKXYFP6cCQJVv5"
    ]
}

but when I try to do a transaction I got Transaction 0 failed! [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32600,"message":"invalid tx type"}}}'

I talked with metamask team and they send me the problem
they said this is polygon-edge problem

here is response from metamask developer team :

https://github.com/0xPolygon/polygon-edge/issues/1743#issuecomment-1649683960

we only can use metamask with version 1.0.1 of polygon-edge
Regards.
 
## Your environment
- OS and version.
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by Stefan-Ethernal** [comment]
Is block number 1300 reached (that's when you specified that the London hard fork should be enabled)?

**Comment by polygomic** [comment]
yes I checked in block 10000
but steel I got the transaction error

**Comment by begmaroman** [comment]
The pproblem is that currently we pass forks state at zero block when initializing tx pool: https://github.com/0xPolygon/polygon-edge/blob/develop/server/server.go#L350. It won't work if some of those forks will be activated at non-zero block. 

Also, one thing that does not make sense if that the burnt contract address is defined from 150th block, but the londong hardfork is activated from 1300.
