### ISSUE TITLE
 The program will exit  error： concurrent map read and map write

### ISSUE THREAD

**Issue by luofei614** [0xPolygon/polygon-edge#176]
### Description

The program will exit  when  200 transitions  request together 。

### Logs

concurrent map read and map write

goroutine 55 [running]:
runtime.throw(0x1051d9ff3, 0x21)
	/opt/homebrew/Cellar/go/1.15.7_1/libexec/src/runtime/panic.go:1117 +0x54 fp=0x14001d47d30 sp=0x14001d47d00 pc=0x104963b54
runtime.mapaccess2(0x1054c4ba0, 0x140022d64b0, 0x1400207ca68, 0x14002aed380, 0x6)
	/opt/homebrew/Cellar/go/1.15.7_1/libexec/src/runtime/map.go:469 +0x230 fp=0x14001d47d70 sp=0x14001d47d30 pc=0x10493f2c0
github.com/0xPolygon/polygon-sdk/txpool.(*TxPool).addImpl(0x140003303f0, 0x1050f5eb5, 0x6, 0x1400207c9c0, 0x0, 0x0)
	/code/txpool/txpool.go:214 +0x1e4 fp=0x14001d47ea0 sp=0x14001d47d70 pc=0x105048284
github.com/0xPolygon/polygon-sdk/txpool.(*TxPool).handleGossipTxn(0x140003303f0, 0x105535760, 0x14002eb8d50)
	/code/txpool/txpool.go:148 +0x180 fp=0x14001d47f10 sp=0x14001d47ea0 pc=0x1050479a0
github.com/0xPolygon/polygon-sdk/txpool.(*TxPool).handleGossipTxn-fm(0x105535760, 0x14002eb8d50)
	/code/txpool/txpool.go:138 +0x40 fp=0x14001d47f40 sp=0x14001d47f10 pc=0x10504b190
github.com/0xPolygon/polygon-sdk/network.(*Topic).readLoop(0x140022d65a0, 0x14001cf6100, 0x14000018be0)
	/code/network/gossip.go:63 +0x1e4 fp=0x14001d47fc0 sp=0x14001d47f40 pc=0x10503aa14
runtime.goexit()
	/opt/homebrew/Cellar/go/1.15.7_1/libexec/src/runtime/asm_arm64.s:1130 +0x4 fp=0x14001d47fc0 sp=0x14001d47fc0 pc=0x104997c34
created by github.com/0xPolygon/polygon-sdk/network.(*Topic).Subscribe
	/code/network/gossip.go:39 +0x88

goroutine 1 [chan receive, 8 minutes]:
github.com/0xPolygon/polygon-sdk/command/helper.HandleSignals(0x14000019510, 0x10562e1b8, 0x14000358180, 0x14000350bd0)
	/code/command/helper/helper.go:183 +0xbc
github.com/0xPolygon/polygon-sdk/command/server.(*ServerCommand).Run(0x14000128e40, 0x1400011cb80, 0xb, 0xb, 0x140001e74b0)
	/code/command/server/server_command.go:201 +0x168
github.com/mitchellh/cli.(*CLI).Run(0x140001697c0, 0x140001697c0, 0x14000000180, 0x300000002)
	/code/vendor/github.com/mitchellh/cli/cli.go:255 +0x2c4
main.Run(0x1400011cb70, 0xc, 0xc, 0x14000000180)
	/code/main.go:25 +0x88
main.main()
	/code/main.go:12 +0x60

goroutine 51 [select, 8 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0x14001cbb340)
	/code/vendor/github.com/syndtr/goleveldb/leveldb/db_compaction.go:91 +0x74
created by github.com/syndtr/goleveldb/leveldb.openDB
	/code/vendor/github.com/syndtr/goleveldb/leveldb/db.go:148 +0x30c

goroutine 7 [select, 8 minutes]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0x140000dd110)
	/code/vendor/github.com/ipfs/go-log/writer/writer.go:71 +0xb4
created by github.com/ipfs/go-log/writer.NewMirrorWriter
	/code/vendor/github.com/ipfs/go-log/writer/writer.go:36 +0xac

**Comment by zivkovicmilos** [comment]
Hey @luofei614,

Thank you for reaching out.

Could you please provide the steps you've taken to get this error?

**Comment by luofei614** [comment]
Thanks for your reply @zivkovicmilos 

I use a script to run 200 accounts for testing , Simulate high concurrency：

> const { ethers } = require("ethers");
> var rpclist=[
>     "http://127.0.0.1:10002",
>     "http://127.0.0.1:20002",
>     "http://127.0.0.1:30002",
>     "http://127.0.0.1:40002"
> ]
> var providerlist=[]
> for (const url of rpclist) {
>     providerlist.push(new ethers.providers.JsonRpcProvider(url));
> }
> mnemonic = "please multiply venue rhythm beach advice jungle flower bulk clever chicken brick" ;
> for(i=0;i<200;i++){
>     var wallet =ethers.Wallet.fromMnemonic(mnemonic,"m/44'/60'/0'/0/"+i)
>     var  activeWallet = wallet.connect(providerlist[i%providerlist.length])
>     activeWallet.sendTransaction({
>             to:"0x8844B6D45fCE2fd6D030B446893f61aA01Ea672E",
>             value:ethers.utils.parseEther("0.0001"),
>             gasLimit:91000, 
>             gasPrice:10,
>             nonce:0
>         })
> }


The genesis.json file presets the balance for these 200 accounts :

`
"alloc": {"0xebb14FD7801F6E654C87f628bAb149312C0A8Bf3":{"balance":"0x3635c9adc5dea00000"},"0xeCEc3a16eB60054eb49d2b953309b78BEb46Ab97":{"balance":"0x3635c9adc5dea00000"},"0x65Cd98fAD79a3C470357f1eE1ab37Ed6c5bB6d31":{"balance":"0x3635c9adc5dea00000"},"0xE6A80A556D9a2B5200e23732cAdDa1e5ac5a6020":{"balance":"0x3635c9adc5dea00000"},"0x70E5E5E38C8eC3c636C2acbf6f1D2db8b81c0436":{"balance":"0x3635c9adc5dea00000"},"0x2EFda9A4d0763E447dE982966E1F9aeAbb345eA3":{"balance":"0x3635c9adc5dea00000"},"0xa37bB9EAf5de5d5964a0ce855939044b0ca5554F":{"balance":"0x3635c9adc5dea00000"},"0x16292cBa022E909a135C0Cc91b66d8A4761f11C1":{"balance":"0x3635c9adc5dea00000"},"0xcE9dA6C9579D7cFC78b99d0751505928E3B4BbE3":{"balance":"0x3635c9adc5dea00000"},"0x3a28E37468fab6fF829FDD8e6e8eD1b3bE8947ab":{"balance":"0x3635c9adc5dea00000"},"0x3127c90A290d9A34F7708b2513A37F43cb8D7410":{"balance":"0x3635c9adc5dea00000"},"0x95D6E0611e1135e8258aCCa477B739c1200CaD3c":{"balance":"0x3635c9adc5dea00000"},"0x03d8906c68B3eA03dC03A4e32B931591d3173C19":{"balance":"0x3635c9adc5dea00000"},"0xe0DdFfF22cc0Eda746F667ad389cd1Eb0C04086a":{"balance":"0x3635c9adc5dea00000"},"0x52223F6AF553aA25874eDb7C0D0B7c0e8dCD543b":{"balance":"0x3635c9adc5dea00000"},"0x8F5283c9Bc715e7509c34cB97e8491A0D74D975F":{"balance":"0x3635c9adc5dea00000"},"0x75cB2D425FB2ff615Fa18e5A7680e79309deFFA9":{"balance":"0x3635c9adc5dea00000"},"0x084EF6a143e0eedd78Aac5a11f7D99CF9220B2D8":{"balance":"0x3635c9adc5dea00000"},"0x9025B0fe8A81bd12F69a6d7C2d8eb1a801b3C1BD":{"balance":"0x3635c9adc5dea00000"},"0xe1a35f5cFA35a9b418A614084440E7AC5bCB5f7f":{"balance":"0x3635c9adc5dea00000"},"0x74DAc730d252377c9b5860Bd1fA70D1F0833a3dA":{"balance":"0x3635c9adc5dea00000"},"0xD7dfB7b2687Afc1B5D33dfd61a87cAE9d188BB20":{"balance":"0x3635c9adc5dea00000"},"0x9D3C8176eB790d7e868866b8eE6B5D9D691F491F":{"balance":"0x3635c9adc5dea00000"},"0xc8482d79dAD8bcc8b204A70705A9cEF122c6Daf9":{"balance":"0x3635c9adc5dea00000"},"0x21AC2445767A56053c7C9d617Bad5521dAD38d32":{"balance":"0x3635c9adc5dea00000"},"0x11B46C8c9E4085189e4748d81B546B276620a631":{"balance":"0x3635c9adc5dea00000"},"0x70b427D36212cc3D94cec3D690dc4AF2F74b245C":{"balance":"0x3635c9adc5dea00000"},"0xC0B8865EC294A78Dba0da67B73Af4fd4cF80c765":{"balance":"0x3635c9adc5dea00000"},"0xd660C26eeD595165792fB05990d35ae5a3B5d63A":{"balance":"0x3635c9adc5dea00000"},"0xD3592d7aDd76b3A5e7E812Fb85b9366F37384A08":{"balance":"0x3635c9adc5dea00000"},"0xCF9Def585FE9c12d23e9443fED6BdaAB5772e145":{"balance":"0x3635c9adc5dea00000"},"0xa7c7BEE25016EAba0f5b10F39A22Cf2ccA3E0B20":{"balance":"0x3635c9adc5dea00000"},"0xd710E92459fc2b19FAE862e0037404dFcaE3aD34":{"balance":"0x3635c9adc5dea00000"},"0x78E402c976be0b821A854E75F747B07716E58a26":{"balance":"0x3635c9adc5dea00000"},"0xBAe7653eF08835d6DA78048aB38708b90d586Be2":{"balance":"0x3635c9adc5dea00000"},"0x7Dfb8bc6fCfA563F9651c22c8Ff1CD3374db6c13":{"balance":"0x3635c9adc5dea00000"},"0x4ff077AeD6F423FC279F56ffBE16BC36481F9F1a":{"balance":"0x3635c9adc5dea00000"},"0xCeFf743BCBb0E3C4B8920DA352aa6eBD7F5B13Ad":{"balance":"0x3635c9adc5dea00000"},"0x8bdf1e5B76152F7CB794F826bd6F7b227b4F4222":{"balance":"0x3635c9adc5dea00000"},"0x097Ba55459C7721D00FEfc1ffDA567E4E8A81238":{"balance":"0x3635c9adc5dea00000"},"0xcd3525c2A1746f24bDF8fCaDc64764B7Ce5C3F46":{"balance":"0x3635c9adc5dea00000"},"0xB52F5d89DdF0a88104d66300B8e82dFFACC6d9cb":{"balance":"0x3635c9adc5dea00000"},"0x810Ba168033fA3e22dC98F3c868B84f90db88cc6":{"balance":"0x3635c9adc5dea00000"},"0xcEf7A938eB7847aE88F557770fcdB700e8A323d0":{"balance":"0x3635c9adc5dea00000"},"0xa18c15453D8e400411d23C7C2e801aacE9cff2ed":{"balance":"0x3635c9adc5dea00000"},"0x7d752644Dce077C8790b606c00772FD52D1FeDfB":{"balance":"0x3635c9adc5dea00000"},"0x89E537BDA5A3D275D45Bc71766b4290B87ce51E1":{"balance":"0x3635c9adc5dea00000"},"0xa99e0815DC7BCc14f513126C2E0c1407145f46DA":{"balance":"0x3635c9adc5dea00000"},"0x0F63899710EbE259c89fc26626fd49bbcf1fB1Ff":{"balance":"0x3635c9adc5dea00000"},"0xade67AD146C92bF1878AEFD70178712C075aDCfe":{"balance":"0x3635c9adc5dea00000"},"0x3fa8d09F52Bfb461A4b8503543ce4e346fb1a41b":{"balance":"0x3635c9adc5dea00000"},"0x8e47C80A9bBC9caF043b8D1077BB577Dd27fF23b":{"balance":"0x3635c9adc5dea00000"},"0x5Ac75CCE7080f27d1815B9737A259eFd7197CA2e":{"balance":"0x3635c9adc5dea00000"},"0x7A1168967c8562f72F165656C0658AEE5241EE4E":{"balance":"0x3635c9adc5dea00000"},"0x5922c923a1261DA0a3dDf3eDfC5f07055364A9cF":{"balance":"0x3635c9adc5dea00000"},"0x1e5739977BDD167a515B9fbAaB603d048421DD52":{"balance":"0x3635c9adc5dea00000"},"0x588691dF4b0a9C847fb3438B9EDEEE5a94b0f3C4":{"balance":"0x3635c9adc5dea00000"},"0xe7f669C41fDd943E7aC8F584d4ac2A9ceCa28487":{"balance":"0x3635c9adc5dea00000"},"0xB4EABbf4d978a293EEE531Fc33F7F98CA9655427":{"balance":"0x3635c9adc5dea00000"},"0x2C7C7310aA5E5cC2e864ba3b5836aE794891F92D":{"balance":"0x3635c9adc5dea00000"},"0x4E18f6bafB6DAb61ee43cb8A850a64d173554C96":{"balance":"0x3635c9adc5dea00000"},"0xB78f9d10EE421373fa98263672A9B2361dDa6fC6":{"balance":"0x3635c9adc5dea00000"},"0x959cD311c74C5B76FCF19F899ceC73bD9F13A14C":{"balance":"0x3635c9adc5dea00000"},"0x7d8497C9cfD27539fC6c0Cced83f3864b9Ed0Ea2":{"balance":"0x3635c9adc5dea00000"},"0x07fEcde6Af7E428A607322b4B048b5Cacbb21110":{"balance":"0x3635c9adc5dea00000"},"0xfA934971055F9D52C844291B234D0Cdcb05DE8b3":{"balance":"0x3635c9adc5dea00000"},"0xf12C9209f8Ffc754dFf9125D175E9DA2b861f4fB":{"balance":"0x3635c9adc5dea00000"},"0xFb7ee5dbE52E4ECf62C53B84fcDB168Aa4a3A3FC":{"balance":"0x3635c9adc5dea00000"},"0x27ED3B646Ebe7e8aBcbEb6079aBbaFFc7F6fa929":{"balance":"0x3635c9adc5dea00000"},"0x0717460A9daf68F141A881fa086AF517F0acD701":{"balance":"0x3635c9adc5dea00000"},"0x73D6499c5b0785701794Bc2417445E83913f7DD2":{"balance":"0x3635c9adc5dea00000"},"0xed16fdC8FFb33ccDFB793B070AEa224a46998651":{"balance":"0x3635c9adc5dea00000"},"0x03f4e43722e69815A9bF8649Ea6E8c76d2BfdFb5":{"balance":"0x3635c9adc5dea00000"},"0xeD0D86D3e511D58FF71172E135773B109fabd568":{"balance":"0x3635c9adc5dea00000"},"0x2DA3D135964a6f51aAA0c32510acf7479e852794":{"balance":"0x3635c9adc5dea00000"},"0x656907E78092ef4EA8C6A22839A3371540359059":{"balance":"0x3635c9adc5dea00000"},"0x90E889e3ce85d772783b4F882b1B2cF834a71934":{"balance":"0x3635c9adc5dea00000"},"0x9ce13737cCfc7ED81FBD2dE36442973Cee0032a6":{"balance":"0x3635c9adc5dea00000"},"0x9983a472B404292Ba19DBF26FaCD8b293ad73197":{"balance":"0x3635c9adc5dea00000"},"0x5486f5645bCda157fB63CF6D70258Eb6706e5191":{"balance":"0x3635c9adc5dea00000"},"0xbbDf6229D1d1A46E0d5B317091F44d05313ec93D":{"balance":"0x3635c9adc5dea00000"},"0xa92b115a090488C5Ad1c1c3f0c871958b51347E8":{"balance":"0x3635c9adc5dea00000"},"0x5dB9E5B62A8C419F4084cd04f83585d945Fa84bd":{"balance":"0x3635c9adc5dea00000"},"0xaa916DADE9b31EcAEDFf2B3a7B2D2779Bf99A594":{"balance":"0x3635c9adc5dea00000"},"0x2851Ff4A47364f4fd1088a9958Fd26D77a61A318":{"balance":"0x3635c9adc5dea00000"},"0xA7bffddfC99D5FdA5463EfeFCC57e2af0f6147b4":{"balance":"0x3635c9adc5dea00000"},"0x1ecC3ad6A852173B82c240cc02B3C9c671b582CB":{"balance":"0x3635c9adc5dea00000"},"0x0C585247FC71D86088960E6348718D920B828bF7":{"balance":"0x3635c9adc5dea00000"},"0x4c930BDDf8d14be713869770c77E2A69665Ce084":{"balance":"0x3635c9adc5dea00000"},"0xFB792E40136112d52E7dF03Ac2209d2Cc1fB3efC":{"balance":"0x3635c9adc5dea00000"},"0x6b8094ed09F15B6Bf8Cf1f1d61CB078b43D26ED6":{"balance":"0x3635c9adc5dea00000"},"0x15F690ED8166B822d6b45b42132cEeb0443DdaF8":{"balance":"0x3635c9adc5dea00000"},"0x20B68121625877FBCfd40ABC7821f961ED74b15D":{"balance":"0x3635c9adc5dea00000"},"0xB8cE8bF84B74047A747F6112aE7d0b305F7Ed8Ed":{"balance":"0x3635c9adc5dea00000"},"0xcb96a2363728e36Ec81BB11F5A29ED04cEC358F1":{"balance":"0x3635c9adc5dea00000"},"0xC00C4d9255D8bCe228B5345A82937cc518d19e69":{"balance":"0x3635c9adc5dea00000"},"0x969c39F18Ba30369DB017e1F50237C39cEcEF2bD":{"balance":"0x3635c9adc5dea00000"},"0xc5F9493b2c7E7e906025A2492fe59682e8E8ccEf":{"balance":"0x3635c9adc5dea00000"},"0x9c3fb8d9107491eAb6e35f8c2Db68A4960fE3ff8":{"balance":"0x3635c9adc5dea00000"},"0xD8b3F4c5DcfE8825ccaE34D4eA15a7C43Df9D4F0":{"balance":"0x3635c9adc5dea00000"},"0x1B1740d4aB1f0FBF337BA4B23a5221D115367C52":{"balance":"0x3635c9adc5dea00000"},"0x291DB77Fdae98Ef965B294131E959eBC9e45f5e0":{"balance":"0x3635c9adc5dea00000"},"0x1ddccB9A823017Fd9CDe1a31f090adec44D61A74":{"balance":"0x3635c9adc5dea00000"},"0x631696919bbcF7E1B139B026E79a66D4B42e7B0b":{"balance":"0x3635c9adc5dea00000"},"0x4525d6E5B567E9cbb89884085d5002683ce9CFD9":{"balance":"0x3635c9adc5dea00000"},"0x0Bf6cD308DDAD7eC010b41814604d5286F003011":{"balance":"0x3635c9adc5dea00000"},"0x52f32e76AbeF191342884EB989c800EE8B22A8cD":{"balance":"0x3635c9adc5dea00000"},"0x898ACb219cEcC232729a2B0B6Aa4073f735e2887":{"balance":"0x3635c9adc5dea00000"},"0xE73dCCCa42EA54d6ac8F463a880852eCe8B2B43c":{"balance":"0x3635c9adc5dea00000"},"0x87bCeaf80FAB4857D3ae39fF7D516d093397ea83":{"balance":"0x3635c9adc5dea00000"},"0x0b92b532e21891492D8ebb46D9e331CB87887ac2":{"balance":"0x3635c9adc5dea00000"},"0x90053078e5d3A0bb8ae711bbA96525596864053E":{"balance":"0x3635c9adc5dea00000"},"0x631aD865BDf81cbc46520365C09D577280E4Af9E":{"balance":"0x3635c9adc5dea00000"},"0xb0D124E79C96c123b492cC753Fe17B0988672CEd":{"balance":"0x3635c9adc5dea00000"},"0x2E91597058c9Abd5886698D6f89c67D34771a7F7":{"balance":"0x3635c9adc5dea00000"},"0x2e45bd65B572C9835F17FcDE6CE71D35cfB86953":{"balance":"0x3635c9adc5dea00000"},"0x8714940c8D5f484FBa1Af96bf2Dc1285FE08cED7":{"balance":"0x3635c9adc5dea00000"},"0x161D78B2e3d893445Fcd0E38019B6197acB619f8":{"balance":"0x3635c9adc5dea00000"},"0x64f5691f1a9b5a5c3cb4D6295ccF746316591beC":{"balance":"0x3635c9adc5dea00000"},"0xA31d9a4fC0144825380019432F08f1bAdF1E7489":{"balance":"0x3635c9adc5dea00000"},"0x10C053c221D27F9C1A570Ac1BdEae6B16d9134C4":{"balance":"0x3635c9adc5dea00000"},"0xbe957CE3526ad2AfD31942192Ffd5671612eDCa3":{"balance":"0x3635c9adc5dea00000"},"0x0CCa2E25aC9DEd96CcCe82f5083B74EC6A7C2E2D":{"balance":"0x3635c9adc5dea00000"},"0xef7C951f66059532270c4172AbAA1f9f2D3ad71A":{"balance":"0x3635c9adc5dea00000"},"0x929aA002A0EF9652a9290Af180dE7B27E4ab9e4E":{"balance":"0x3635c9adc5dea00000"},"0x7c68A9c8BD6Ba53D956d9F644b90cE3Bd656FC47":{"balance":"0x3635c9adc5dea00000"},"0x4082AacBD992B8B670da278AC184018d6E081e17":{"balance":"0x3635c9adc5dea00000"},"0x648447e658AE59238A11509e81027330b322b422":{"balance":"0x3635c9adc5dea00000"},"0x95f70158A4f0918F3CA42f1484Ca04B2D08AFeb0":{"balance":"0x3635c9adc5dea00000"},"0x7ae82116A257B1E6d52cB23e668Bb431bf7D4A47":{"balance":"0x3635c9adc5dea00000"},"0xa288C8C3AD932f05039AeBAd463593d38De17C94":{"balance":"0x3635c9adc5dea00000"},"0xA638F35e0087dDf0006410fd667627Db485DB34c":{"balance":"0x3635c9adc5dea00000"},"0xe01820957F9ce62aC8B30F3c1A9C7B7EC8AC1BA2":{"balance":"0x3635c9adc5dea00000"},"0x52007CcA8C8108569467139B8d011e1861dcb0A5":{"balance":"0x3635c9adc5dea00000"},"0x5E1953E3a1792A8aFA7916dfF0848b7DAe69c603":{"balance":"0x3635c9adc5dea00000"},"0x4D08926a8282B54C670fDFAFaCbd75cd2A462d52":{"balance":"0x3635c9adc5dea00000"},"0x3cbC10e5D9A80f807eDf4faB2aaCb33E6e422daF":{"balance":"0x3635c9adc5dea00000"},"0x11136B12Fd030ECed2A1ceCB8C63FF115003e1B0":{"balance":"0x3635c9adc5dea00000"},"0xf60594A61A5a3b412737d182AD52e702168751b2":{"balance":"0x3635c9adc5dea00000"},"0x06224848Aa7023F95b00ce09Af3607710fce7302":{"balance":"0x3635c9adc5dea00000"},"0xd10651D28ec834B9dAf770ec0f7dD78dcc88d1a9":{"balance":"0x3635c9adc5dea00000"},"0x683b7fcCE749517c3d7b7FF951Bf257eB44EfCfc":{"balance":"0x3635c9adc5dea00000"},"0xE2A2Ec263f5E1352880C8A00165E58c3a6665b64":{"balance":"0x3635c9adc5dea00000"},"0xD38E56A93a66306795E2C99a7c434c54D42D182d":{"balance":"0x3635c9adc5dea00000"},"0xFE13c6cb24bEBe8fb4511a8ff8cb55316D65A7E5":{"balance":"0x3635c9adc5dea00000"},"0xe38b1Baf7fa4f6bc0aaD89dB5640A7DE7417AfA2":{"balance":"0x3635c9adc5dea00000"},"0x9bcAD064Fd6c9946cDAc8c2033De7adf87FBfd55":{"balance":"0x3635c9adc5dea00000"},"0x03a081F7DA543A34F16b57178330388445B34F62":{"balance":"0x3635c9adc5dea00000"},"0xFdAe5F5AcBC93de183c3da3dcd478635244dFa64":{"balance":"0x3635c9adc5dea00000"},"0xa5eBE17B9a95FF363fC5d45b911280b9418A959e":{"balance":"0x3635c9adc5dea00000"},"0x5386c42D10E8BeFdAc97205184B5E7D71Cd981d9":{"balance":"0x3635c9adc5dea00000"},"0xeBe82335bfF7482B9eC40904208664c66FDa00a2":{"balance":"0x3635c9adc5dea00000"},"0xC65Fc8FfBbb942E5EDa57B781c35126Bf05e0254":{"balance":"0x3635c9adc5dea00000"},"0x57DBD8446A3f403a3CA5f791398e5ce5F9A9E4e3":{"balance":"0x3635c9adc5dea00000"},"0x580323C30dE1501e5E6375FCFC16E522C4ae78a2":{"balance":"0x3635c9adc5dea00000"},"0x966E159E2827E05959F0498E0B750643346b0fA6":{"balance":"0x3635c9adc5dea00000"},"0x11340AA62493B945fD428003e26578A77D36fC9D":{"balance":"0x3635c9adc5dea00000"},"0x7499137e66934aa3249F50BFA2986AC052aAA63D":{"balance":"0x3635c9adc5dea00000"},"0xf3D417067B1Af40473981aC0DF06e8abEF78DA1B":{"balance":"0x3635c9adc5dea00000"},"0x8360a37cc04422a1D4ae0439E69e0AB5742aEDCf":{"balance":"0x3635c9adc5dea00000"},"0x3DE06fC8Aa6801813f1b469558211E26602bDaA7":{"balance":"0x3635c9adc5dea00000"},"0x35F6C7a85900a3723aca91EDa5B252cadD76132b":{"balance":"0x3635c9adc5dea00000"},"0x0179BBFFfabDea2db0c695aDbfB2Ae2F645AB0c7":{"balance":"0x3635c9adc5dea00000"},"0x2D831e804745b112168a3d69ce4e9254dfbA4018":{"balance":"0x3635c9adc5dea00000"},"0x1cc72486E5b4A270fe73b9a3A3D626907DBE176c":{"balance":"0x3635c9adc5dea00000"},"0x4d9d8F263Ca6F76b3cC8E0b8243f9de8BC0980c0":{"balance":"0x3635c9adc5dea00000"},"0xDb5f6FCfb235beAAF513fe845C4490Fa4A7D7008":{"balance":"0x3635c9adc5dea00000"},"0x043358Ae42801aE0Aa7247F70EEfFa7735ed02c5":{"balance":"0x3635c9adc5dea00000"},"0x3Abb6bBCbd5a5aa820797ca90a2bfEfC3E23D7Be":{"balance":"0x3635c9adc5dea00000"},"0x4632d9DA159d5F6e5159e1015797Ba36fC926675":{"balance":"0x3635c9adc5dea00000"},"0x336B14AB2E3f626698f8D2736C4CE4751B4A1b98":{"balance":"0x3635c9adc5dea00000"},"0xb708cF7cec28A72a02c8eE4bd501C47AE457B354":{"balance":"0x3635c9adc5dea00000"},"0xb608eD4107759A4c69542845626e8616C17b0fC1":{"balance":"0x3635c9adc5dea00000"},"0xb34cD778885105e5Fc9fAFfD0b37D2f4F1A403dB":{"balance":"0x3635c9adc5dea00000"},"0xa9f16c7fb8593632395492a17F661AB12b26964C":{"balance":"0x3635c9adc5dea00000"},"0x0584992E9dD24Fc7a809a47BF7B30faB882f9212":{"balance":"0x3635c9adc5dea00000"},"0x68e6cFEea54AF22d01fbe1DbE2ea4f72e799F136":{"balance":"0x3635c9adc5dea00000"},"0xA7173DCb82F91A7bF46EdF5E66448e81fA4Caeb6":{"balance":"0x3635c9adc5dea00000"},"0xcbDB6f5C8157f41668DA95D79e83cA288881e302":{"balance":"0x3635c9adc5dea00000"},"0x9b0Cd8298364c997b1402613132c62F86F4b13b5":{"balance":"0x3635c9adc5dea00000"},"0x8f999C9aa2939f7D7cdBe29D996bF60199F6afc1":{"balance":"0x3635c9adc5dea00000"},"0x94e0775507aEa6857B03dBD4458A75ebf9ea702e":{"balance":"0x3635c9adc5dea00000"},"0x39fDDE119784936Be557763B9fe825Ec77e31954":{"balance":"0x3635c9adc5dea00000"},"0xaEe4a8c5774F3944EFE3FBA6D363e2226d1D317e":{"balance":"0x3635c9adc5dea00000"},"0xDaC1a26e9b4f1Ab81F8091ee89d9Da88AaE21d45":{"balance":"0x3635c9adc5dea00000"},"0x469d647Fe13e33b2f6dBCb9EB27aec8A97155BFf":{"balance":"0x3635c9adc5dea00000"},"0x15dde4FE67Ec35C2b954527e7295dBbBF38782F4":{"balance":"0x3635c9adc5dea00000"},"0x2222587922631743e49154a4A162289390f1dcf6":{"balance":"0x3635c9adc5dea00000"},"0x33e1e170Ad566C20d3df1bB5F7c23e1352C43493":{"balance":"0x3635c9adc5dea00000"},"0x65B2D16f668aFB694463bCE335cc46a9F9bd314E":{"balance":"0x3635c9adc5dea00000"},"0x3DC17fDFc7B48B787BEE283983A25FB6c99278f6":{"balance":"0x3635c9adc5dea00000"},"0x334D14fCDEb158c9e5048a5118D8b2AF40479e24":{"balance":"0x3635c9adc5dea00000"},"0x64890e86eCCB4758a5a036d4cda61fab3a217230":{"balance":"0x3635c9adc5dea00000"},"0x6B3e0FEd837691256E79613ecD78AC2c351e392F":{"balance":"0x3635c9adc5dea00000"},"0x7cB578B3D39E2Acb1BFA1A197D0F5A001702A591":{"balance":"0x3635c9adc5dea00000"},"0x79eb0a213A0f5541767e49c7313c214142351EA9":{"balance":"0x3635c9adc5dea00000"},"0x2eDb4d1C32Dc42166Feb024b9daDb6470Fe63449":{"balance":"0x3635c9adc5dea00000"},"0xc6C0A70d2d0025320c92565050574d772C428f8B":{"balance":"0x3635c9adc5dea00000"},"0x4BE51498f2c42CAD2C7D731CB18bde3379cdEe1A":{"balance":"0x3635c9adc5dea00000"},"0x7212decaFCe211628967BEcEd54D550F2396ee57":{"balance":"0x3635c9adc5dea00000"}},
`

I fixed the bug by increasing  sync.RWMutex
file: txpool.txpool.go :  

> var addImplLock sync.RWMutex 
> func (t *TxPool) addImpl(ctx string, tx *types.Transaction) error {
> 	addImplLock.Lock()
> 	defer addImplLock.Unlock()

But, may not be the best solution

**Comment by zivkovicmilos** [comment]
Thank you for providing this info and scripts. I'll have to test this out and get back to you ASAP, there shouldn't be a concurrency issue there

**Comment by zivkovicmilos** [comment]
Hey @luofei614,

Just confirming that we're seeing this behavior on our end as well.
We have identified the issue, and have a PR with a fix that should be merged out soon 👍

**Comment by luofei614** [comment]
@zivkovicmilos  Good👍 ， Thanks 。  
I did this test in order to know TPS, because the official documents did not explain TPS。 Can you tell how much TPS is theoretically possible for PylgonSDK? thanks。
