### ISSUE TITLE
Remove unnecessary blockchain interface methods in Jsonrpc

### ISSUE THREAD

**Issue by ferranbt** [0xPolygon/polygon-edge#18]
The JsonRPC module uses State and BeginTx methods https://github.com/0xPolygon/polygon-sdk/blob/develop/jsonrpc/blockchain.go#L41 to be used during gas estimation. However, this methods can be replaced by the methods GetAccount and ApplyTxn.

**Comment by zivkovicmilos** [comment]
Solved with [commit](https://github.com/0xPolygon/polygon-sdk/commit/9931227dbbd634616b48e7fd117e7036ee282d4f) 👍
