### ISSUE TITLE
Sequence not correct error. Testnet stalled (Edge v0.6.3) 

### ISSUE THREAD

**Issue by ghost** [0xPolygon/polygon-edge#1810]
# [ Subject of the issue ]
## Description
Describe your issue in as much detail as possible here. Hi, chain stopped producing blocks with a "sequence not correct" error. Restarting didn't solve it. Restoring from a backup did. Is there a way to manually reorg the blocks to the correct order. How do we know what the correct order should be? Is 2 seconds too short for block time? 

## Your environment
- OS and version. Ubuntu 20.04
- The version of the Polygon Edge.   0.6.3
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider). Cloud (Ionos) 
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.). No

## Steps to reproduce
- Tell us how to reproduce this issue. Run 4 nodes on one machine with unique ports on each. 
- Where the issue is, if you know. Unknown
- Which commands triggered the issue, if any. None
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm? No, luckily this was just testnet, and not on our mainnet. 

## Expected behavior
- Tell us what should happen. Chain should just work
- Tell us what happened instead. As above. 

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it. If I knew that, I'd be helping others 🙂

**Comment by igorcrevar** [comment]
Next block in the chain always should have sequence `Number` which is exactly +1 bigger than the previous block. 
Do you still have this issue?
Can you provide us logs and `genesis.json` file?

**Comment by ghost** [comment]
Hi, this was ages ago, and I needed a quick response. I restored from
backups, as I had no other options available. I just assumed that 0.6.3 was
no longer supported.

Thanks, Nex
