### ISSUE TITLE
Failed state sync executions are not retried

### ISSUE THREAD

**Issue by sergerad** [0xPolygon/polygon-edge#1811]
## Description

We have observed that failed state sync executions are not retried by Edge. Its hard to tell based on the src whether this is intended or not.

Is this expected behaviour? I understand that some errors around state sync execution cannot be retried successfully without some intervention first, but some errors (like the one below) could be transient in nature.

The price limit cause is just an example and I expect we would see the same behaviour if we caused this behaviour by different means. I believe we saw the same behaviour for a token that we had not mapped (stateSyncResult event contained msg UNMAPPED_TOKEN)

## Your environment
- Edge in Docker based on image from this repo
- v1.1.0
- Both local and on k8s

## Steps to reproduce

This is the process to recreate this behaviour (we did this on cluster and locally to verify):
1. Bootstrap the supernet as per usual w/ polygon-edge CLI
2. Perform deposit to relayer addr
3. Run validators with --price-limit 100000000 
4. Observe initial state sync execution errors due to price limit (check balance did not update also):
```
[ERROR] polygon.server.relayer: State sync execution failed: err="failed to send execute state sync transaction for id 1: {\"code\":-32600,\"message\":\"insufficient funds for gas * price + value\"}"
[ERROR] polygon.server.relayer: State sync execution failed: err="failed to send execute state sync transaction for id 2: {\"code\":-32600,\"message\":\"insufficient funds for gas * price + value\"}
```
5. Restart validators with --price-limit 0
6. Wait for epochs to tick over, observe that state sync 1 and 2 are not retried
7. Perform deposit to relayer addr again
8. Observe that state sync 3 is processed successfully (check balance is updated also)
```
[INFO]  polygon.server.relayer: Execute commitment: Block=460 StartID=3 EndID=3
[INFO]  polygon.server.relayer: State sync executed: ID=3
```

I believe the relayer does not retry execute transactions against StateReceiver.sol either (the above is just rejected by RPC). 

#### Relayer txs to execute against StateReceiver.sol rejected by RPC:
I would expect the failing txs to be retried. In the above example, they are rejected by RPC on the basis of gas.

#### Relayer txs to execute against StateReceiver.sol fail during execution e.g. UNMAPPED_TOKEN etc:
Unsure whether this should be retried automatically or not given the category of errors that occur here.

## Logs

Relevant logs are in the steps to reproduce

## Proposed solution

Relayer should keep track of failed execute txs and retry? Might depend on the type of error as suggested above in expected behaviour section.

**Comment by Stefan-Ethernal** [comment]
Implemented in #1899.
