### ISSUE TITLE
Not enough information for invalid TX Types for unsupported forks

### ISSUE THREAD

**Issue by lolchocotaco** [0xPolygon/polygon-edge#1826]
# Not enough information for invalid TX Types for unsupported forks
## Description
Not enough context is given about the TX if a user submits an EIP1559 txn to a chain not supporting EIP1559. 

## Steps to reproduce

- Start an edge instance without EIP1559 enabled (Do not specify a burn contract)
- Submit a MM txn to the edge chain (defaults to eip1559)

Relevant Genesis Config Values:
```      
{ 
...
    "burnContract": null,
    "burnContractDestinationAddress": "0x0000000000000000000000000000000000000000"
}
```

## Expected behavior
A detailed error on what about the TX is invalid and instead we get "Invalid TX Type"
![telegram-cloud-photo-size-5-6260395836353656972-y](https://github.com/0xPolygon/polygon-edge/assets/2431304/991e953e-5ded-4729-826b-0891018730cb)

## Proposed solution

Provide more verbose reasoning to why TXNs were rejected from the pool within these code blocks. Should also set a standard for any additional forks. 
https://github.com/0xPolygon/polygon-edge/blob/develop/txpool/txpool.go#L617-L621

geth example:
https://github.com/ethereum/go-ethereum/blob/1aa5520d750147cabcb39030ac86bf31088c767f/core/txpool/validation.go#L63-L65

**Comment by goran-ethernal** [comment]
This will be merged soon, so I am closing this. Reference PR: https://github.com/0xPolygon/polygon-edge/pull/1954
