### ISSUE TITLE
register validator transaction failed

### ISSUE THREAD

**Issue by rapidAman** [0xPolygon/polygon-edge#1828]
# Register validator transaction failed 

I was trying to register validator on root chain. with command  
`./polygon-edge polybft register-validator --data-dir ./kaldi-chain-1 --supernet-manager 0x75aA024A2292A3FD3C17d67b54B3d00435437246 --jsonrpc http://127.0.0.1:8545`

## Your environment
- ubuntu 22.04 LTS
- The version of the Polygon Edge 0.9.0.    

## Steps to reproduce
 go though the steps in this [[link](https://wiki.polygon.technology/docs/supernets/operate/deploy/supernets-genesis-validators)](url).

## Expected behavior
![image](https://github.com/0xPolygon/polygon-edge/assets/95608931/dc6c758a-5a86-41b2-9bb3-fe2fabf00b22)

**Comment by Stefan-Ethernal** [comment]
What is the error message you are getting? Can you provide a `genesis.json` file?

**Comment by rapidAman** [comment]
@Stefan-Ethernal i have solved the issue , by providing manual funds to my validators

**Comment by rapidAman** [comment]
fixed
