### ISSUE TITLE
failed to retrieve genesis validators: failed to retrieve bls key: math/big: cannot unmarshal "054838c1aa292d8a7fee4c3ab2baa6c5067708584124931f91361463134b0891" into a *big.Int

### ISSUE THREAD

**Issue by Zesor** [0xPolygon/polygon-edge#1831]
# [ Subject of the issue ]
## Description
Hello, i have an issue with polygon edge, i am trying to run multiple nodes 

## Your environment
- Ubuntu 22
- latest
- on main branch
- cloud hosted
- running in a virtual machine on ubuntu 22

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- ```polygon-edge genesis —-consensus ibft —-ibft-validators-prefix-path test-chain-1 —-bootnode /ip4/127.0.0.1/tcp/10001/p2p/16Uiu2HAkzeFQkt5373VfvfCDkD2UMXCjShpTfsh67jcbwRRf3uUR —-bootnode /ip4/127.0.0.1/tcp/10001/p2p/16Uiu2HAmMh3ZVKZJm9Z5FUurBctCL4z3ywAtnsH9N93fz843asJc --premine 0x0:100000000000000000 --reward-wallet 0xC2213aa46E2eE9A26461F12Fa95Cd42A41E09a86:1000000000000```

## Expected behavior
- This command should generate my genesis file and then start the node with the --server command
- Instead of having the genesis file, i got this issue "failed to retrieve genesis validators: failed to retrieve bls key: math/big: cannot unmarshal "054838c1aa292d8a7fee4c3ab2baa6c5067708584124931f91361463134b0891" into a *big.Int".

**Comment by Zesor** [comment]
![Screenshot 2023-08-18 at 14 11 39](https://github.com/0xPolygon/polygon-edge/assets/72025077/9c79b13c-c948-48f9-8b3a-51b327c44478)

**Comment by begmaroman** [comment]
@Zesor could you please tell us what secrets manager do you use? 

Anyway, the private key should be stored with `0x` prefix in order to successfully unmarshal it.

**Comment by agentmic487** [comment]
@Zesor Hi mate have you got the issue solved?

**Comment by begmaroman** [comment]
@Zesor did you run the node inside docker or did you use a no docker option?

**Comment by begmaroman** [comment]
Fixed per https://github.com/0xPolygon/polygon-edge/pull/1973
