### ISSUE TITLE
When seven verification nodes are started and three nodes are restarted, no new blocks will be generated

### ISSUE THREAD

**Issue by luofei614** [0xPolygon/polygon-edge#185]
### Description
When seven verification nodes are started and three nodes are restarted, no new blocks will be generated
But there is no problem with four nodes, you need to test with seven nodes。

But when the block is not produced, I found that the program has been running ibft's RoundChange：

Print out the msg of ibft as follows:

type:RoundChange from:"0x26d9117146eD66D8D0b36D80C887A2862B6df74C" signature:"0x7a3a2a52daf3f89b922f3b644d338a6fbc4da90c4ff316b6d6d6c86425a0613d050673c1b2dac395724f548870eb58ff64174e0ee229534d5a6bb40f5fab65a700" view:{round:89 sequence:23}
 
type:RoundChange from:"0x26d9117146eD66D8D0b36D80C887A2862B6df74C" signature:"0x82406f78cc86456837236e0e62b466b8007789e26cb7c0f7729eb1c33953a131530fabb7ddfff8a3ed2eec70aa963af9e37f9413e25e36f4c22b34640987d11800" view:{round:90 sequence:23}
 
type:RoundChange from:"0x26d9117146eD66D8D0b36D80C887A2862B6df74C" signature:"0x98efb770d13d3d3db9ad1b9a10bccb6a8cfeab29b498c867b0bddcead8e08bef6acad2e360c2e9feb5a9b117265869a09581483544670ba97519ae51b447a05600" view:{round:91 sequence:23}

type:RoundChange from:"0xaa4d93d35F538060D2229af50B935ED445806f24" signature:"0x75fd94086e086e100e66b7b4968820b994fe39f431bb3ccb3cbe317582fe68d165829caf2be314816e63b63321b16c2ce3eb9a023fab60e1ed9c6789f17b0c1300" view:{round:29 sequence:23}

type:RoundChange from:"0x26d9117146eD66D8D0b36D80C887A2862B6df74C" signature:"0x301d5d44a7e8eb6aaa4a315813aa719227c67b855652ac00f675ca4e9519736e6e996022cf0e5744db83f65be80f9f89b7829e7765de67723def24758e65ba2701" view:{round:92 sequence:23}

### Steps to reproduce

* Start seven verification nodes
* Turn off the three verification nodes
* Found that all nodes do not produce blocks

**Comment by munna0908** [comment]
Hi @luofei614, Thanks for bringing this up 🙏. 
This [PR](https://github.com/0xPolygon/polygon-sdk/pull/187) will fix this issue
