### ISSUE TITLE
Fix peek function of accountQueue in txpool

### ISSUE THREAD

**Issue by sarvalabs-karthik** [0xPolygon/polygon-edge#1861]
# Fix peek function of accountQueue in txpool

## Description
this check isn't required in account queue as it will be done in peek function of min nonce queue

[https://github.com/0xPolygon/polygon-edge/blob/33e09676d95bf2a2d714bfa02a4a17235f56ed68/txpool/queue_account.go#L81](https://github.com/0xPolygon/polygon-edge/blob/33e09676d95bf2a2d714bfa02a4a17235f56ed68/txpool/queue_account.go#L81)

**Comment by begmaroman** [comment]
Could you @sarvalabs-karthik please clarify what issues it causes?

**Comment by sarvalabs-karthik** [comment]
its just a performance issue. it may be negligible. but a redundant check.
