### ISSUE TITLE
trying to build but having issues

### ISSUE THREAD

**Issue by SECRYPT-2022** [0xPolygon/polygon-edge#1868]
# [ Subject of the issue ]
## Description
trying to build polygon and it appears it wont let me say the below issue and fails.

```
git clone https://github.com/0xPolygon/polygon-edge.git
cd polygon-edge/
go build -o polygon-edge .
```

# github.com/quic-go/quic-go/internal/qtls
/root/go/pkg/mod/github.com/quic-go/quic-go@v0.33.0/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration

## Your environment
- OS and version. - Ubuntu 20.04
- The version of the Polygon Edge. 
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen.
- Tell us what happened instead.

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by SECRYPT-2022** [comment]
# go.uber.org/multierr
Error: ../../../go/pkg/mod/go.uber.org/multierr@v1.11.0/error.go:209:20: undefined: atomic.Bool
note: module requires Go 1.19
# github.com/libp2p/go-libp2p/p2p/host/eventbus
Error: ../../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.27.8/p2p/host/eventbus/basic.go:30:23: undefined: atomic.Bool
Error: ../../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.27.8/p2p/host/eventbus/basic.go:322:23: undefined: atomic.Int32
Error: ../../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.27.8/p2p/host/eventbus/basic.go:375:19: undefined: atomic.Int32
Error: ../../../go/pkg/mod/github.com/libp2p/go-libp2p@v0.27.8/p2p/host/eventbus/opts.go:15:19: undefined: atomic.Int64
note: module requires Go 1.19
# github.com/quic-go/quic-go/internal/qtls
Error: ../../../go/pkg/mod/github.com/quic-go/quic-go@v0.33.0/internal/qtls/go_oldversion.go:5:13: cannot use "The version of quic-go you're using can't be built using outdated Go versions. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built using outdated Go...) as int value in variable declaration
note: module requires Go 1.19
make: *** [Makefile:49: test-e2e] Error 2
Error: Process completed with exit code 2.

**Comment by Stefan-Ethernal** [comment]
Can you double check that you are running golang version >= 1.20? You can check which golang version you have by running
`go version` command.

**Comment by SECRYPT-2022** [comment]
@Stefan-Ethernal 

getting this issue now

/network
network/server.go:470:9: cannot use s.host.Peerstore().GetProtocols(peerID) (value of type []"github.com/libp2p/go-libp2p/core/protocol".ID) as []string value in return statement

**Comment by Stefan-Ethernal** [comment]
Probably you don't have the latest go dependencies. Please try to run `go mod tidy` and see if is it any better.

**Comment by begmaroman** [comment]
Just FYI @SECRYPT-2022, you can also run a local network using Docker. Try `make docker-run` command.

**Comment by Stefan-Ethernal** [comment]
Is it any better now @SECRYPT-2022? Also consider @begmaroman's comment, if you want to spin up a locally running cluster.

**Comment by SECRYPT-2022** [comment]
I don't know how to use the make docker  run.

I'm quite new to all this

**Comment by Stefan-Ethernal** [comment]
In order to execute the `make run-docker` command, you would first need to install the docker engine. The procedure is described [here](https://docs.docker.com/engine/install/ubuntu/).

It allows you to spin up a local test net containing 4 Supernets nodes and 1 rootchain node (Geth client) so that you can play around with it and test it locally.

**Comment by SECRYPT-2022** [comment]
i have fixed this issue.
