### ISSUE TITLE
Pending state of transaction

### ISSUE THREAD

**Issue by amansk2050** [0xPolygon/polygon-edge#1870]
## Description

After the successful configuration of rootchain (mumbai test net) and my supernet, I am running my supernet on any jrpc port and added that chain to my metamask. The problem after that is whenever I am doing a transaction like sending some native token to any other wallet or deploying any erc20 token it goes to a pending state and does not complete the transaction. 

I have used all the commands sequentially as mentioned in the doc.

## operating system
I am using Ubuntu.

## steps to Produce this error.

use this command sequentially.

*  ./polygon-edge polybft-secrets --insecure --data-dir <your_chain_name>- --num 2
*  ./polygon-edge genesis --block-gas-limit 10000000 --epoch-size 10 \
    --validators-path ./ --validators-prefix kaldi-chain- \
    --consensus polybft \
    --premine <your_wallet_address>:1000000000000000000000 \
    --reward-wallet <validator_address>:1000000 \
    --name "chian_name" \
    --burn-contract 100:<busrn_contract>
*   ./polygon-edge rootchain deploy \
  --deployer-key <your private key> \
  --genesis ./genesis.json \
  --json-rpc https://rpc-mumbai.maticvigil.com/ \
  --erc20-token <token address>

"I have deployed this erc20 token seperately on mumbai testnet and used here"

*  ./polygon-edge rootchain fund --amount 10000000000000000000000 \
			      --data-dir ./kaldi-chain-1 \
			      --json-rpc https://rpc-mumbai.maticvigil.com/ \
			      --mint \
			      --native-root-token <token address> \
			      --private-key <private key>
*  ./polygon-edge polybft whitelist-validators   --private-key <private key>   --addresses <nodes_address_comma_seperated>  --supernet-manager <custom_manager_address> --jsonrpc https://rpc-mumbai.maticvigil.com/

*  ./polygon-edge polybft register-validator --data-dir ./<your_chain-1> \
--supernet-manager <custom_manager_address> --jsonrpc https://rpc-mumbai.maticvigil.com/

"repeat this step for all nodes"

*  ./polygon-edge polybft stake \
--data-dir ./<your_chain_1> \
--chain-id 1 \
--amount 1000000000000000000 \
--stake-manager <steake_manager_address> \
--native-root-token <native-token_address> \
--jsonrpc https://rpc-mumbai.maticvigil.com/

"repeat this step for each nodes".

* ./polygon-edge polybft supernet --private-key <your_private_key>\
--genesis ./genesis.json \
--supernet-manager <custom_manager_address> \
--stake-manager <custom_manager_address> \
--finalize-genesis-set --enable-staking \
--jsonrpc https://rpc-mumbai.maticvigil.com/

*  ./polygon-edge server --data-dir ./<your_chain>-1 --chain genesis.json --grpc-address :5001 --libp2p :30301 --jsonrpc :10001 --seal --log-level DEBUG

./polygon-edge server --data-dir ./<your_chain>-2 --chain genesis.json --grpc-address :5002 --libp2p :30302 --jsonrpc :10002 --seal --log-level DEBUG

After that add this chain to your metamask. and try to transfer some native coin to another wallet.

**Comment by pranjali301** [comment]
the validators need to be funded before initializing the contracts (in order to be able to pay for gas for deploying the contracts)

**Comment by pranjali301** [comment]
you need to fund a validator account through this command

./polygon-edge rootchain fund --addresses 0x77C1eedFf656477462ce16084fE5Dc7F8a2507B9 --amounts 1000000000000000000

**Comment by amansk2050** [comment]
funds meanning, matic or native token ?
