### ISSUE TITLE
Fix JsonRPC request conversion

### ISSUE THREAD

**Issue by ferranbt** [0xPolygon/polygon-edge#19]
Due to the use of alias methods in the Jsonrpc module, the dispatcher is unable to reflect the Jsonrpc request into Go structs.

**Comment by zivkovicmilos** [comment]
Fixed in the improved libp2p branch:
https://github.com/0xPolygon/polygon-sdk/blob/feature-libp2p-improv/jsonrpc/dispatcher.go#L232
