### ISSUE TITLE
New Panic regression error on `eth_call`

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#190]
### Description

I observed that `b54f44f` on develop introduces a new issue which causes a previously-working `eth_call` request to throw a panic and no longer return a 200 status.

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon SDK `b54f44f`
* branch that causes this issue `develop`

### Steps to reproduce

1. Checkout `a158b74` (the commit hash prior to `b54f44f`) and build + run `./main server`
2. Observe a 200 response when sending a request similar to the following json-rpc request:
```
{
	"id": 0,
	"jsonrpc": "2.0",
	"method": "eth_call",
	"params": [{
		"data": "0x70a082310000000000000000000000000cd01b344f086d814c72a8d8195b3349f186eabf",
		"from": null,
		"to": "0xeafbbf62dffba085b717e215d82223fe2f212268"
	}, "0xF9309"]
}
```
3. Checkout `a158b74` and build + run
4. Observe a panic (see logs below)

### Expected behaviour

Shouldn't throw a panic.

### Actual behaviour

Observe a panic in the logs and no response from the originating request.

### Logs

```
2021-11-01T18:16:46.455Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_call err=<nil>"}
2021/11/01 18:16:46 http: panic serving 38.147.9.116:50586: runtime error: invalid memory address or nil pointer dereference"}
goroutine 490 [running]:"}
net/http.(*conn).serve.func1(0xc0032d37c0)"}
\t/usr/local/go/src/net/http/server.go:1824 +0x153"}
panic(0xdf7720, 0x1a3ede0)"}
\t/usr/local/go/src/runtime/panic.go:971 +0x499"}
github.com/0xPolygon/polygon-sdk/state.(*TransitionApplicationError).Error(0x0, 0xfdcb38, 0x12)"}
\t/home/ubuntu/sx-node/state/executor.go:345 +0x33"}
github.com/0xPolygon/polygon-sdk/jsonrpc.(*Dispatcher).handleReq(0xc000ae1da0, 0xd9dac0, 0x1914aa0, 0xc000457d88, 0x8, 0xc000631550, 0xae, 0xb0, 0xc00065cca8, 0xc05829a300000002, ...)"}
\t/home/ubuntu/sx-node/jsonrpc/dispatcher.go:299 +0x63c"}
github.com/0xPolygon/polygon-sdk/jsonrpc.(*Dispatcher).Handle(0xc000ae1da0, 0xc00319f400, 0xf1, 0x200, 0x2, 0x2, 0x0, 0xc0033c3280, 0x800)"}
\t/home/ubuntu/sx-node/jsonrpc/dispatcher.go:243 +0x25e"}
github.com/0xPolygon/polygon-sdk/jsonrpc.(*JSONRPC).handle(0xc000b2aea0, 0x1250d78, 0xc0008f96c0, 0xc00335eb00)"}
net/http.HandlerFunc.ServeHTTP(0xc000b26850, 0x1250d78, 0xc0008f96c0, 0xc00335eb00)"}
\t/usr/local/go/src/net/http/server.go:2069 +0x44"}
net/http.(*ServeMux).ServeHTTP(0x1a72b00, 0x1250d78, 0xc0008f96c0, 0xc00335eb00)"}
\t/usr/local/go/src/net/http/server.go:2448 +0x1ad"}
net/http.serverHandler.ServeHTTP(0xc0008f8620, 0x1250d78, 0xc0008f96c0, 0xc00335eb00)"}
sr/local/go/src/net/http/server.go:2887 +0xa3"}
net/http.(*conn).serve(0xc0032d37c0, 0x12537c0, 0xc0033c3180)"}
\t/usr/local/go/src/net/http/server.go:1952 +0x8cd"}
created by net/http.(*Server).Serve"}
\t/usr/local/go/src/net/http/server.go:3013 +0x39b"}
```

### Proposed solution

I'm not sure exactly what causes this error but narrowed it down to something introduced by `b54f44f`.

**Comment by zivkovicmilos** [comment]
Hey @dankostiuk,

Thank you for reaching out. We've identified the issue, and a hotfix has already been applied through PR #189.
Please let us know if the issue has been resolved after you pull the latest changes from develop.

**Comment by dankostiuk** [comment]
Looks like it has been resolved after pulling in that PR thanks @zivkovicmilos 👍

**Comment by zivkovicmilos** [comment]
Glad to head that.

Please make sure to pull the latest changes from develop, as we've pushed out some fixes after the linked hotfix 🙂
