### ISSUE TITLE
Bridge UI

### ISSUE THREAD

**Issue by gnarco** [0xPolygon/polygon-edge#1900]
# Bridge UI
## Description
Is there any bridge UI out there ?

I thought about forking some repo, but I don't know which one. 
Is there a simple solution to fork/adapt or do I need to develop my own ? 

Thanks !

**Comment by Stefan-Ethernal** [comment]
Unfortunately, we don't have any UI for the bridge atm, so you would need to develop your own. 

We have provided bridge testing commands (which make deposits, withdrawals, and exits) as part of the Edge codebase (https://github.com/0xPolygon/polygon-edge/tree/develop/command/bridge).
