### ISSUE TITLE
Register-Validator: execution reverted

### ISSUE THREAD

**Issue by guillermovahi** [0xPolygon/polygon-edge#1946]
# Register-Validator: execution reverted
## Description
I am trying to deploy a local network with docker v1.1.0 polygon-edge. All the first steps seems correct, but when it is the time for register validators, the client refuses the operation. Basically the ouput is:
```Error: {"code":-32000,"message":"execution reverted"}```

In the steps to reproduce, everything seems to work correctly until the line (-------------------)
## Your environment
- MacOS Ventura 13.3
- v1.1.0
- Locally
- Docker

## Steps to reproduce
Full guide:
```bash
polygon-edge polybft-secrets --insecure --data-dir test-chain- --num 4

polygon-edge genesis \
--block-gas-limit 10000000 \
--epoch-size 10 \
--validators "${addressvalidator}" \
--consensus polybft \
--reward-wallet ${validator}:1000000 \
--native-token-config "Polygon:MATIC:18:true:${validator}" \
--transactions-allow-list-admin "${validator}" \
--transactions-allow-list-enabled "${validator}" \
--premine 0x0000000000000000000000000000000000000000 \
--premine ${yourTestingAddress}:1000000000000000000000 \
--premine "${validator}":1000000000000000000000 \
--burn-contract 0:0x0000000000000000000000000000000000000000


polygon-edge polybft stake-manager-deploy \
--private-key ${yourPrivateKey} \
--genesis ./genesis.json \
--jsonrpc ${JSONRPC} \
--stake-token ${yourStakeToken}

polygon-edge rootchain deploy \
--deployer-key ${yourPrivateKey}  \
--genesis ./genesis.json \
--json-rpc ${JSONRPC}  \
--stake-manager ${yourDeployedStakeManagerAddress} \
--stake-token ${yourStakeTokenAddress}

polygon-edge rootchain fund \
--addresses ${validator} \
--amounts 100000000000000 \
--stake-token ${yourStakeTokenAddress} \
--json-rpc ${JSONRPC}  \
--private-key ${yourPrivateKey}  \
--mint

polygon-edge polybft whitelist-validators \
--private-key ${yourPrivateKey}  \
--addresses ${validator} \
--supernet-manager ${yourDeployedSupernetManagerAddress}  \
--jsonrpc ${JSONRPC} 

---------STARTS FAILING ⬇️--------------------------------------------------------------------------------------------------------------
polygon-edge polybft register-validator \
--data-dir test-chain-1 \
--supernet-manager ${yourDeployedSupernetManagerAddress} \
--jsonrpc ${JSONRPC} 

polygon-edge polybft stake \
--data-dir test-chain-1 \
--supernet-id 1 \
--amount 1000000000000 \
--stake-manager ${yourDeployedStakeManagerAddress} \
--stake-token ${yourStakeTokenAddress} \
--jsonrpc ${JSONRPC} 

polygon-edge polybft supernet \
--private-key ${yourPrivateKey} \
--genesis ./genesis.json \
--supernet-manager ${yourDeployedSupernetManagerAddress} \
--stake-manager ${yourDeployedStakeManagerAddress} \
--finalize-genesis-set \
--jsonrpc ${JSONRPC} 


```

## Expected behavior
- Tell us what should happen: it should output the validator address registered and the KOSK signature
- Tell us what happened instead: shows an error ```Error: {"code":-32000,"message":"execution reverted"}```

## Logs
The network can't be initialized because of this failed steps

## Proposed solution
No idea

**Comment by goran-ethernal** [comment]
Things I would check:
1. If the supernet manager address you are passing in the `--supernet-manager` flag in `register-validator` correct.
2. If 1. is correct, check if the validator was whitelisted on `CustomSupernetManager` in the `whitelist-validators` command. You can check that by querying `mapping(address => Validator) public validators` on that contract with the address of problematic validator.

**Comment by Stefan-Ethernal** [comment]
Closing due to an inactivity. 

@guillermovahi if you are able to provide us the information that are required in the https://github.com/0xPolygon/polygon-edge/issues/1946#issuecomment-1746301226, feel free to reopen it.
