### ISSUE TITLE
debug_traceTransaction does not return the output as expected 

### ISSUE THREAD

**Issue by harrybite** [0xPolygon/polygon-edge#1959]
I am using polygon-edge 1.3.0 on my Mac M1
running the local network on http://localhost:8456

I am trying to trace the transaction with debug_traceTransaction 

{
  "method": "debug_traceTransaction",
  "params": [
    "0xf4156f53a9678540552018c3fc96e4a5debde508466b1e323fa1f8d5c4f3ff4a",
    {
      "tracer": "callTracer"
    }
  ],
  "id": 1,
  "jsonrpc": "2.0"
}

and the result should be in this format 
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "from": "0xd018538c87232ff95acbce4870629b75640a78e7",
    "gas": "0xe678",
    "gasUsed": "0x5208",
    "to": "0xe23ffc73d27b29d2369fc21b72a3713ca1e3e0df",
    "input": "0x",
    "value": "0x6a0e7694ff0400",
    "type": "CALL"
  }
}

but the return result too long.
<img width="601" alt="Screenshot 2023-10-05 at 11 11 43 AM" src="https://github.com/0xPolygon/polygon-edge/assets/60419615/737ca11a-8bcc-450c-9101-01f122a4933b">

**Comment by goran-ethernal** [comment]
Edge only has `structTracer` implemented. That is why you see returned response in this format.
