### ISSUE TITLE
/usr/local/go/src/math/erf.go:274:6: Erfc defined in both Go and assembly /usr/local/go/src/math/erf.go:274:6: too many errors

### ISSUE THREAD

**Issue by Poonam911** [0xPolygon/polygon-edge#1978]
Hii everyone

I am trying to create private blockchain using polygon-edge . i am trying to build polygon-edge code using command (go build -o polygon-edge main.go)    but it through error i.e 

/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:36:6: Xadduintptr redeclared in this block
	/usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:58:6: other declaration of Xadduintptr
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:39:6: Xchg redeclared in this block
	/usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:61:6: other declaration of Xchg
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:42:6: Xchg64 redeclared in this block
	/usr/local/go/src/runtime/internal/atomic/atomic_amd64.go:64:6: other declaration of Xchg64
/usr/local/go/src/runtime/internal/atomic/atomic_amd64x.go:45:6: Xchguintptr redeclared in this block
/usr/local/go/src/math/acosh.go:43:6: Acosh defined in both Go and assembly
/usr/local/go/src/math/asin.go:20:6: Asin defined in both Go and assembly
/usr/local/go/src/math/asin.go:58:6: Acos defined in both Go and assembly
/usr/local/go/src/math/asinh.go:40:6: Asinh defined in both Go and assembly
/usr/local/go/src/math/atan.go:96:6: Atan defined in both Go and assembly
/usr/local/go/src/math/atan2.go:30:6: Atan2 defined in both Go and assembly
/usr/local/go/src/math/atanh.go:48:6: Atanh defined in both Go and assembly
/usr/local/go/src/math/cbrt.go:26:6: Cbrt defined in both Go and assembly
/usr/local/go/src/math/erf.go:189:6: Erf defined in both Go and assembly
/usr/local/go/src/math/erf.go:274:6: Erfc defined in both Go and assembly
/usr/local/go/src/math/erf.go:274:6: too many errors

how to resolve this error 
Kindly help me to resolve this error

**Comment by Stefan-Ethernal** [comment]
Hello, it looks like you are having problem with either golang version or dependencies.

First, make sure that you have installed `go 1.20` (or newer). You can find out version that you are currently running by this command:
`$ go version`

If version is matching, then run
- `go mod tidy` - to cleanup and download any potentially missing dependencies
- `make build` - to build the binary

**Comment by Poonam911** [comment]
hello @Stefan-Ethernal 

Thanks for the reply. This solution work for me .
