### ISSUE TITLE
Feature Request : Configure the Checkpoint interval (checkpointOffset in the CheckpointManager constructor) 

### ISSUE THREAD

**Issue by RonTuretzky** [0xPolygon/polygon-edge#1992]
# [ Adding the ability to configure the checkpoint interval to rootchain ]
## Description

Having the ability to configure how many checkpoints are submitted per epoch would be beneficial to users in terms of security , gas optimization\configuration, 

## Proposed solution
Add a flag for the genesis command to configure it, to be passed as the checkpointOffset arg for the checkpointmanager constructor 

If there's another way to do this, would appreciate a pointer in the right direction

**Comment by goran-ethernal** [comment]
We have this in the branch with on-chain governance: https://github.com/0xPolygon/polygon-edge/tree/v1.2.0-rc1, but that is not part of any official release, but a sort of a `prototipe` (not recommended for production yet, as we do not know when it will be released) if you want to check it out.

**Comment by RonTuretzky** [comment]
@goran-ethernal fantastic! ETA on release?

**Comment by goran-ethernal** [comment]
We really do not know at the moment 😕

**Comment by RonTuretzky** [comment]
@goran-ethernal 
I understand, thank you.

I see that this [contract](https://github.com/0xPolygon/core-contracts/blob/5a68054893e8a9755645b11528221e3c68c2af29/contracts/child/NetworkParams.sol)

For release 1.1 did have the ability to change the checkpoint interval, is it possible on 1.1 to configure the checkpoint interval using this?

**Comment by goran-ethernal** [comment]
Those contracts were added in earlier releases, but they are not utilized nor have any purpose without the changes to the client itself on that branch I sent you in the earlier comments.
