### ISSUE TITLE
polygon-edge server command failed: `Error: invalid DNS address`

### ISSUE THREAD

**Issue by 0xDones** [0xPolygon/polygon-edge#2003]
# polygon-edge server command failed: `Error: invalid DNS address`
## Description
I'm trying to run the command `polygon-edge server` with the `--dns example.com` flag, but doesn't matter the value I pass it always return `Error: invalid DNS address`. I'm trying to run my validators using docker-compose and make them find it other using the service DNS, in my case `validator1`, `validator2,` etc... 

Values that failed:
- `validator1`
- `example.com`
- `/dns4/validator1/tcp/30301/p2p/<nodeid>`

I think the issue is with the regex used in the function:
https://github.com/0xPolygon/polygon-edge/blob/develop/network/common/common.go#L86

That is called here:
https://github.com/0xPolygon/polygon-edge/blob/develop/command/server/init.go#L277C37-L277C53

Full command:

```bash
polygon-edge server --chain ./genesis.json --data-dir ./data --dns "example.com"
```

## Your environment
- MacOS
- Polygon Edge 1.3.x

**Comment by goran-ethernal** [comment]
Does the dns address you are inputting to the command, match this regex:

```
// DNSRegex is a regex string to match against a valid dns/dns4/dns6 addr
const DNSRegex = `^/?(dns)(4|6)?/[^-|^/][A-Za-z0-9-]([^-|^/]?)+([\\-\\.]{1}[a-z0-9]+)*\\.[A-Za-z]{2,}(/?)$`
```

We have a test of how valid and invalid dns addresses look like, maybe it can help:
https://github.com/0xPolygon/polygon-edge/blob/fa8c7777588fb75740ebcd8c705e76f01b512eb9/network/server_test.go#L868
