### ISSUE TITLE
polygon-edge server `--seal` argument still appears on docs and help message

### ISSUE THREAD

**Issue by 0xDones** [0xPolygon/polygon-edge#2004]
# polygon-edge server `--seal` argument still appears on docs and help message
## Description
Despite being removed, the argument `--seal` still appears when you run `polygon-edge server -h` and is also is displayed in the [docs](https://wiki.polygon.technology/docs/edge/operate/deploy/how-to-start/)  

## Your environment
- polygon-edge 1.3.x

**Comment by Stefan-Ethernal** [comment]
Hi @refl3ction, [v1.3.1](https://github.com/0xPolygon/polygon-edge/releases/tag/v1.3.1) in fact still has `--seal` flag. It is removed through #1886 (which is merged into the `develop` branch), but there is not yet any release that contains that change.
