### ISSUE TITLE
How to configure zero transaction fees for a private chain?

### ISSUE THREAD

**Issue by Billyblingbling** [0xPolygon/polygon-edge#2005]
# [ Subject of the issue ]
## Description
How to configure zero transaction fees for a private chain?

## Your environment
polygon-edge genesis --chain-id 123456 --consensus ibft --ibft-validators-prefix-path test-chain- \
    --bootnode /ip4/127.0.0.1/tcp/30301/p2p/16Uiu2HAkzUjkge7ppnKnY15NcdAHssMerNN2EdgVDt5uUB7QZcHi \
    --bootnode /ip4/127.0.0.1/tcp/30302/p2p/16Uiu2HAm7odMARYXPseV1kBr5CH9D9S1yhajqPTJwBTWE11mDyhs \
    --bootnode /ip4/127.0.0.1/tcp/30302/p2p/16Uiu2HAkwNunNjfV2BFNP4Vy3nkt5vDQjrJDN1a2qmxKfFFYzL4N \
    --bootnode /ip4/127.0.0.1/tcp/30302/p2p/16Uiu2HAmFAoVmegCntFzAhQwSNkdR2W2QDs4JRaXMRiVwGPrMxdf \
    --block-gas-limit 1000000000 \
    --premine 0xbfE4D90B3Ac9Fd6c703580921893F786A245Ed5B:999999999999999999999999999 \
    --premine 0x0000000000000000000000000000000000000000 \
    --epoch-size 10 \
    --reward-wallet 0xDEADBEEF:1000000 \
    --native-token-config "Polygon:MATIC:18:true:0xbfE4D90B3Ac9Fd6c703580921893F786A245Ed5B" \
    --burn-contract 0:0x0000000000000000000000000000000000000000 \
    --proxy-contracts-admin 0xbfE4D90B3Ac9Fd6c703580921893F786A245Ed5B

  nohup polygon-edge server --data-dir ./test-chain-1 --chain genesis.json \
      --grpc-address :10000 --libp2p :30301 --jsonrpc :10002 \
      --num-block-confirmations 2 --seal --log-level DEBUG  --log-to  ./validator-1.log 2>&1 & disown
    nohup polygon-edge server --data-dir ./test-chain-2 --chain genesis.json \
      --grpc-address :20000 --libp2p :30302 --jsonrpc :20002 \
      --num-block-confirmations 2 --seal --log-level DEBUG  --log-to ./validator-2.log 2>&1  & disown
    nohup polygon-edge server --data-dir ./test-chain-3 --chain genesis.json \
      --grpc-address :30000 --libp2p :30303 --jsonrpc :30002 \
      --num-block-confirmations 2 --seal --log-level DEBUG  --log-to ./validator-3.log 2>&1  & disown
    nohup polygon-edge server --data-dir ./test-chain-4 --chain genesis.json \
      --grpc-address :40000 --libp2p :30304 --jsonrpc :40002 \
      --num-block-confirmations 2 --seal --log-level DEBUG  --log-to ./validator-4.log 2>&1  & disown

linux os

**Comment by Billyblingbling** [comment]
I set the gasPrice field in the Genesis file.
{
    "name": "polygon-edge",
    "genesis": {
        "nonce": "0x0000000000000000",
        "timestamp": "0x0",
        "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f90129f90120f8469491ed11ce6d2dad6cb3227f6188f547099c59da73b08df0c0d9b3c28b900fbe25983674bc5b2b6e613c7e8df6b2d3e37980da2a80c3a36b4764182d2c7d4cfa536c71925e43f84694ef13a615006c946014744e9f9e734582dfffeb1fb087f4b9efcd51aa5f964d607cf89666a5b2cdee20cf31dbc4c93952515f3f2f1f6352fdf93bdf8dfbb0344f367265ee9af84694e639c9feae7a47f7af6bf725070db7b958649d70b08d2ed549f4564ffef64dc8b7d801399ad0a7f655c3c4a0a3d9cce2f856bea09642edf879ed72f1ac524065a00644836df84694ad62bb84d96f6bafdf8469ff9d8537d6c818d34fb0b7b5208c6d778ff5cef841137c8b4adb63b5bba4fa9afe37357813f5bcf9356620ab9badec26380e390bd03f21f4472280c28080c080",
        "gasLimit": "0x3b9aca00",
        "difficulty": "0x1",
        "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "coinbase": "0x0000000000000000000000000000000000000000",
        "alloc": {
            "0x0000000000000000000000000000000000000000": {
                "balance": "0xd3c21bcecceda1000000"
            },
            "0xbfE4D90B3Ac9Fd6c703580921893F786A245Ed5B": {
                "balance": "0x33b2e3c9fd0803ce7ffffff"
            }
        },
        "number": "0x0",
        "gasUsed": "0x70000",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "baseFee": "0x3b9aca00",
        "baseFeeEM": "0x2",
	"gasPrice": "0x0"
    },
    "params": {
        "forks": {
            "EIP150": {
                "block": 0
            },
            "EIP155": {
                "block": 0
            },
            "EIP158": {
                "block": 0
            },
            "byzantium": {
                "block": 0
            },
            "constantinople": {
                "block": 0
            },
            "homestead": {
                "block": 0
            },
            "istanbul": {
                "block": 0
            },
            "london": {
                "block": 0
            },
            "londonfix": {
                "block": 0
            },
            "petersburg": {
                "block": 0
            },
            "quorumcalcalignment": {
                "block": 0
            },
            "txHashWithType": {
                "block": 0
            }
        },
        "chainID": 123456,
        "engine": {
            "ibft": {
                "blockTime": 2000000000,
                "epochSize": 10,
                "type": "PoA",
                "validator_type": "bls"
            }
        },
        "blockGasTarget": 0,
        "burnContract": {
            "0": "0x0000000000000000000000000000000000000000"
        },
        "burnContractDestinationAddress": "0x0000000000000000000000000000000000000000",
        "baseFeeChangeDenom": 8
    },
    "bootnodes": [
        "/ip4/127.0.0.1/tcp/30301/p2p/16Uiu2HAmHhcstENcviJG27w4jZXGWavWKKcY79kieyrph179ZdqT",
        "/ip4/127.0.0.1/tcp/30302/p2p/16Uiu2HAmCXtjU8SPeX5MMFVL7cJdEdnkcvvf2wDKB1z12wreJquG",
        "/ip4/127.0.0.1/tcp/30302/p2p/16Uiu2HAm47FYQ6q12mY4MRHbCXLcsys4Xztx7nzbW7cfVpNhqJGD",
        "/ip4/127.0.0.1/tcp/30302/p2p/16Uiu2HAm7uGhF4aAJpkDNg7zn1cGMVYS9bgntQRMr5hEqwRm37yq"
    ]
}

**Comment by goran-ethernal** [comment]
If you have `London` fork enabled, you can not have zero transaction fees. 

To have zero transaction fees, remove `London` fork when `genesis` command creates the `genesis.json`, and make sure you start your nodes with `--price-limit` set to 0. This is of course only possible if you start your chain from 0.

Also, it is important to note that if any transaction happens to set gas price to any number higher than 0, transactions in the next block, will no longer be free, because of the way Edge calculates rolling average gas prices in Legacy transactions.
