### ISSUE TITLE
Slashing removed in 1.3.1?

### ISSUE THREAD

**Issue by RonTuretzky** [0xPolygon/polygon-edge#2010]
# [ Slashing feature removed ]
## Description
We cannot find any mention of the slashing in 1.3.1, was it removed for this release? If not, where can we find the slashing configuration? Thank you!

**Comment by goran-ethernal** [comment]
Yes, governance and slashing are not a part of any official release. They are on a separate branch: https://github.com/0xPolygon/polygon-edge/tree/v1.2.0-rc1

**Comment by RonTuretzky** [comment]
> Yes, governance and slashing are not a part of any official release. They are on a separate branch: https://github.com/0xPolygon/polygon-edge/tree/v1.2.0-rc1

I don't understand, is this branch production ready? 
Will it be merged into a future release?

**Comment by goran-ethernal** [comment]
We do not know when will it be used in an official release. There are no plans to use it in the near future.
