### ISSUE TITLE
Health check endpoint

### ISSUE THREAD

**Issue by 0xDones** [0xPolygon/polygon-edge#2011]
# Health check endpoint
## Description
Is there any specific endpoint to use as a health check?

## Your environment
- Kubernetes
- Edge 1.3x

**Comment by Stefan-Ethernal** [comment]
Hey @refl3ction, what you can do is invoke some of these JSON RPC functions: `web3_clientVersion`, `eth_blockNumber`, or any other, but those are some lightweight in terms of response they are returning.

**Comment by 0xDones** [comment]
Thanks @Stefan-Ethernal , unfortunately POST requests are not supported for K8s probes, I will see what I can do.

**Comment by Stefan-Ethernal** [comment]
Not sure if this helps, but you are able to send an empty `GET` request to the Edge:

```bash
curl http://localhost:10002 | jq .
```
...and it returns the following response (chain name, chain id and version parameters):

```json
{
  "name": "polygon-edge",
  "chain_id": 100,
  "version": ""
}
```

**Comment by 0xDones** [comment]
This definitely helps!
