### ISSUE TITLE
Error: `gas limit reached in the pool`

### ISSUE THREAD

**Issue by 0xDones** [0xPolygon/polygon-edge#2023]
# Error: `gas limit reached in the pool`
## Description
I'm running a zero gas network (without London fork), using Besu as the L1 and after deploying some smart contracts I started to get lots of warnings on my validators, what's causing it?

```txt
polygon.server.dispatcher: failed to dispatch: method=eth_call err="gas limit reached in the pool"
```

Startup command:
```bash
polygon-edge server --data-dir /data/edge --chain /etc/edge/genesis.json --num-block-confirmations 64 \
--libp2p "0.0.0.0:1478" --jsonrpc "0.0.0.0:8545" --grpc-address "0.0.0.0:9632" --prometheus "0.0.0.0:5001" \
--price-limit 0 --block-gas-target "0x0" --relayer
```

### Note
For this specific network, I initially created it with London fork enabled, and after some time I removed the London fork part from the genesis file, deleted all the data from the validators, and started the network again, using the same management contracts that were deployed previously, it might be it? Should I have configured the network from scratch again?

## Your environment
- Edge 1.3x
- Kubernetes

**Comment by 0xDones** [comment]
After regenerating all the validator keys, the genesis file, and configuring the network again against the same L1, when I redeployed all of the validators with a clean data volume, I got a lot of these errors (from relayer):

```txt
polygon.server.dispatcher: failed to dispatch: method=debug_traceTransaction err="tx 0x6a20145ebaa3de798fc5af451055f8fad1496df4ff8fb1081f60f9b46c0947af not found"
```

I can see that pretty much all token addresses on the `bridge` field from the genesis file changed except for the `"nativeERC20Address": "0x0000000000000000000000000000000000000000",`.

From which place the relayer is pulling this? Am I missing something?

**Comment by goran-ethernal** [comment]
Relayer is definitely not calling the debug rpc endpoints: `failed to dispatch: method=debug_traceTransaction`. Do you have some block scout configured, or some other app that would be calling debug rpc endpoints?

As far as for `nativeERC20Address` is concerned, that is zero because you are using a mintable erc20 native token. You can check that, by looking at the `nativeTokenConfig` in `genesis.json`.

**Comment by 0xDones** [comment]
@goran-ethernal Thank you! It was indeed Blockscout making all those calls to the relayer node (which was the RPC node as well), and it was preventing the node from working properly. The resource consumption was very high and there were all the errors I shared in this issue. Now I have deployed a dedicated relayer and a dedicated RPC instance, with 4 validators, I will keep monitoring the network.

**Comment by goran-ethernal** [comment]
I will close this issue then. If something else pops up, please either reopen this, or open a new issue.
