### ISSUE TITLE
err="gas limit reached in the pool"

### ISSUE THREAD

**Issue by 0xDones** [0xPolygon/polygon-edge#2039]
# err="gas limit reached in the pool"

## Description
We are currently using Graph Node to index transactions on the Edge network. The Graph Node Subgraph works as expected when getting data from events and add it to the graph entities. But for a specific event, it starts to make calls to the RPC endpoint in a loop and the Edge RPC instance starts to throw lots of the warnings as attached below and also consumes 100% of the CPU limits.

### Graph Node

1. The graph has a listener to check each blockchain block.
2. This listener has some events linked to handler (Handler is a function that triggers when event is triggered onchain)
3. We have a handler that call `erc20Contract.name()`. When this call fails, the graph keeps calling on the same block until the request succeeds.

### Logs
```log
# Edge
polygon-edge 2023-11-06T14:05:15.484Z [INFO]  polygon.server.polybft: sync block notification received: block height=306344 current height=306344
polygon-edge 2023-11-06T14:05:15.581Z [WARN]  polygon.server.dispatcher: failed to dispatch: method=eth_call err="gas limit reached in the pool"
polygon-edge 2023-11-06T14:05:16.102Z [WARN]  polygon.server.dispatcher: failed to dispatch: method=eth_call err="gas limit reached in the pool"
polygon-edge 2023-11-06T14:05:16.390Z [WARN]  polygon.server.dispatcher: failed to dispatch: method=eth_call err="gas limit reached in the pool"
polygon-edge 2023-11-06T14:05:16.509Z [WARN]  polygon.server.dispatcher: failed to dispatch: method=eth_call err="gas limit reached in the pool"
polygon-edge 2023-11-06T14:05:16.566Z [WARN]  polygon.server.dispatcher: failed to dispatch: method=eth_call err="gas limit reached in the pool"
polygon-edge 2023-11-06T14:05:16.580Z [WARN]  polygon.server.dispatcher: failed to dispatch: method=eth_call err="gas limit reached in the pool"

# Graph Node
Nov 06 14:05:13.863 INFO Possible reorg detected, retrying, error: failed to process trigger: 
block #295732 (0x056b…235b), transaction 9c39e240a06edb5bd90d14b206d19de350195b7674873043754e76921f28135e:
Ethereum node returned an error when calling function "name" of contract "ERC20Token":
RPC error: Error { code: InvalidRequest, message: "gas limit reached in the pool", data: None }
```

### Notes

- This works on Besu.

## Your environment
- Edge 1.3.2
- Kubernetes

## Related

- #2023

**Comment by goran-ethernal** [comment]
This should not happen, if the `Gas` on transaction that is being passed to `eth_call` is set to 0. Can you please check how this `eth_call` is set up in that handler? How is he calling the `eth_call`? Can you give us the parameters he used in rpc call?

**Comment by 0xDones** [comment]
Hi @goran-ethernal , I just checked and the Graph Node has the Gas set to 50kk when doing RPC calls. Unfortunately, it's hard-coded as you can see here: https://github.com/graphprotocol/graph-node/blob/139f3144d8d878b528416fcd4f9a34353dc3dfb1/chain/ethereum/src/runtime/runtime_adapter.rs#L37

What are the possible solutions here?

Edge:
- Does it makes sense to Ignore this value if Edge is running a zero gas network?

Graph Node:
- Fork Graph Node and change it to zero
- Ask for maintainers to make it configurable (it was once, but now it's hard-coded)

Ref: https://github.com/graphprotocol/graph-node/issues/3881

**Comment by goran-ethernal** [comment]
There are no easy, nor "pretty" fixes on Edge for this, without introducing additional complexity and possible bugs to the code, plus, it would probably require a change in the evm, which by itself is a hard fork. 

If they can make that field configurable again it would be the best option. If not, then I would suggest to fork a Graph Node, and change it to zero.

**Comment by 0xDones** [comment]
@goran-ethernal Thanks for the support. I'll see what I can do on my side.
