### ISSUE TITLE
running rootchain deploy command keep asking for stake token 

### ISSUE THREAD

**Issue by squiddyswap** [0xPolygon/polygon-edge#2048]
Running rootchain deploy errors out 
When running rootchain deploy it causes error and keep asking for stake token and it has been declared

## Your environment
- OS Debian 11
- Polygon Edge 1.3.1    

## Steps to reproduce
- Run this command:
- ./polygon-edge rootchain deploy \
    --stake-manager ${stakeManagerAddr} \
    --stake-token ${stakeToken} \
    --proxy-contracts-admin ${proxyContractsAdmin} 
When running this command it will keep asking for the stake token and the stake token is declared.

## Expected behavior
- Should complete with no errors and not saying that the stake token is not defined.

**Comment by RonTuretzky** [comment]
is your stake token a valid IERC20?
