### ISSUE TITLE
`peer rejected; insufficient capacity` errors even so peers list appears correct

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#206]
### Description

We've been seeing many occurrences of:
```
failed to add peer to routing table: err=\"peer rejected; insufficient capacity\"
```
and 
```
failed to dial bootnode: err=\"peer rejected; insufficient capacity\"
```

even so running `./main peers list --grpc-address localhost:10000` shows that the full list of peers are connected.

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon SDK `ce793fa`
* branch that causes this issue `develop `

### Steps to reproduce

1. Spin up 4 validators and 1 non-validator
2. Observe that during peer discovery, we see `failed to add peer to routing table: err=\"peer rejected; insufficient capacity\"` followed by `failed to dial bootnode: err=\"peer rejected; insufficient capacity\"`

### Expected behaviour

We shouldn't see these error messages.

### Actual behaviour

We see these error messages.

**Comment by dankostiuk** [comment]
Haven't seen this since or been able to repro, closing..

**Comment by ghost** [comment]
@dankostiuk peer rejected:insufficient capacity. I'm getting that error right now. Not all the time. 25 Bootnodes. Max-peers set at 100. We're about to load the other 35 validators on the PoS chain. Did you ever get a fix? Is this a non-issue? I have noted that the Node ID is one of the validators that hasn't staked.
