### ISSUE TITLE
Rootchain on other blockchains

### ISSUE THREAD

**Issue by avenbreaks** [0xPolygon/polygon-edge#2067]
# Deploying Rootchain on L1 Besides Mumbai
## Description
I built a polygon-edge for my friend, but on the rootchain I used another blockchain (Sepolia) and set up 30 SepoliaETH. but on rootchain deploy i got error.

Is polygon-edge only set to mumbai network? because I tried to change to **_mumbai tx can be solved_**, but after that in the **rootchain fund** section I get an error again about the fund token. 

## Build on Mumbai rootchain fund
```bash
polygon-edge rootchain fund \
    --mint \
    --private-key "Mumbai Key" \
    --stake-token 0x444444406D62093fF9B80E230C51948EC090AfC8 \
    --addresses 0xDA71fE85ffE54Fa05fbdf7FD465EBb1CF40EC899,0xf83b989331C10d1d87e373A90aCba236D10b08eC,0x1645465b23560500759599b5eAF0f0420c866213,0x8A5f80bc0FcA973f86d0f8762B1129397981395F \
    --amounts 4200000000000000000000,4200000000000000000000,4200000000000000000000,4200000000000000000000 \
    --json-rpc https://polygon-mumbai.infura.io/v3/API-KEY
```

[ROOTCHAIN FUND] Successfully funded following accounts
failed to send fund validator '0xf83b989331C10d1d87e373A90aCba236D10b08eC' 
transaction: failed to estimate gas: 

```bash
{"code":-32000,"message":"err: insufficient funds for gas * price + value: address 0x00000023DfCdE07675ac95bd09f5DBC2814fEb90 have 1340762817775978066 want 4200000000000000000000 (supplied gas 14748597)"}
```

## Build on Sepolia
```bash
polygon-edge polybft stake-manager-deploy \
    --private-key "Sepolia key" \
    --genesis /root/firechain/genesis.json \
    --jsonrpc https://1rpc.io/sepolia \
    --stake-token "0x444444406D62093fF9B80E230C51948EC090AfC8" \
    --proxy-contracts-admin "0xDA71fE85ffE54Fa05fbdf7FD465EBb1CF40EC899"
```

```bash
polygon-edge rootchain deploy \
    --deployer-key "Sepolia key" \
    --proxy-contracts-admin "0xDA71fE85ffE54Fa05fbdf7FD465EBb1CF40EC899" \
    --stake-manager "0x468C9c3A94f4945d00DF18ebe4CF425ab9D385b8" \
    --stake-token "0x444444406D62093fF9B80E230C51948EC090AfC8" \
    --json-rpc https://1rpc.io/sepolia \
    --genesis /root/firechain/genesis.json
```

failed to deploy rootchain contracts: failed sending BLS contract deploy transaction 
```bash
{"code":-3200,"message":"insufficient fund for gas * gas + value"}
```

## Expected behavior
- Rootchain can deploy contract to other blockchain e.g : holesky, sepolia, or other L1

**Comment by avenbreaks** [comment]
@Stefan-Ethernal hi sir, can you help me?

**Comment by avenbreaks** [comment]
> @Stefan-Ethernal hi sir, can you help me?

I Think this is resolved, rootchain needs as many tokens as we will fund, but normally how much do we need to fund each address?

```js
polygon-edge rootchain fund \
    --mint \
    --private-key "Sepolia Key" \
    --stake-token 0x444444406D62093fF9B80E230C51948EC090AfC8 \
    --addresses 0x602c9E73613Af0229bD4F67A83d7800Ebf4903A2 \
    --amounts 2000000000000000000 \
    --json-rpc https://1rpc.io/sepolia
```

[ROOTCHAIN FUND]
Validator (address) = 0x602c9E73613Af0229bD4F67A83d7800Ebf4903A2
Transaction (hash)  = 0x822e33151fa1912fc27d0ce44d5f564e7010db38696b58fa9aebe19818e86787
Is minted           = true

**Comment by Stefan-Ethernal** [comment]
Hey, @avenbreaks it is indeed doable to have rootchain set to any EVM compatible chain. However, it would help if you assured that the account that is used for interacting with the rootchain (via the following CLI commands) have enough rootchain's native token balance to do the following actions (namely to cover for transaction fees on the rootchain and fund validator accounts):
- rootchain deploy
- rootchain fund (in your particular case, you are sending 4200 native tokens to each validator account via rootchain fund command, so the account that you have provided via `--private-key` must have enough native tokens on its balance)
- stake-manager-deploy

**Comment by avenbreaks** [comment]
> Hey, @avenbreaks it is indeed doable to have rootchain set to any EVM compatible chain. However, it would help if you assured that the account that is used for interacting with the rootchain (via the following CLI commands) have enough rootchain's native token balance to do the following actions (namely to cover for transaction fees on the rootchain and fund validator accounts):
> 
> * rootchain deploy
> * rootchain fund (in your particular case, you are sending 4200 native tokens to each validator account via rootchain fund command, so the account that you have provided via `--private-key` must have enough native tokens on its balance)
> * stake-manager-deploy

```
./polygon-edge polybft register-validator \
      --supernet-manager $(cat genesis.json | jq -r '.params.engine.polybft.bridge.customSupernetManagerAddr') \
      --data-dir firechain-testnet-1 \
      --jsonrpc http://127.0.0.1:8545
```
      
 got the error like this : 
 
 failed to estimate gas: {"code":3,"message":"execution reverted: TransparentUpgradeableProxy: admin cannot fallback to proxy target","data":"0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000425472616e73706172656e745570677261646561626c6550726f78793a2061646d696e2063616e6e6f742066616c6c6261636b20746f2070726f787920746172676574000000000000000000000000000000000000000000000000000000000000"}

**Comment by Stefan-Ethernal** [comment]
The `--proxy-contracts-admin` flag value must be different than the account used to run `rootchain deploy` and `owner` account of different `Ownable` genesis contracts (such as `NativeERC20Mintable` etc.).
