### ISSUE TITLE
Using the Cluster Script on Polygon Edge

### ISSUE THREAD

**Issue by CryptoDevving** [0xPolygon/polygon-edge#2073]
Hello, I decided to use the cluster script for polygon edge. I looked at the documents here https://github.com/0xPolygon/polygon-edge/tree/develop/scripts, but I have not found a way to start it again once I have stopped it. When I run the script again, it makes a new edge install. I just want to start and stop my previous installation. Is there anyway I can do that? 

Am I also able to connect multiple nodes onto it or am I only able to use the script to have everything on one server?

**Comment by RonTuretzky** [comment]
you have to run the server commands at the end of it , not the whole thing again

**Comment by Stefan-Ethernal** [comment]
@CryptoDevving as @RonTuretzky, you just need to re-run the `server` command: https://github.com/0xPolygon/polygon-edge/blob/develop/scripts/cluster#L162-L200.
