### ISSUE TITLE
How to add remote validators to a Supernet?

### ISSUE THREAD

**Issue by tandooricodes** [0xPolygon/polygon-edge#2108]
# Adding Remote Validators to a Supernet

## Description
For both docker and manual setups, we'd like some guide / recommended steps for setting up a remote validator and connecting it to an existing Supernet's bootnodes. We've been able to connect new local validators to an existing Supernet, but have been unable to do it with remote validators.

**Comment by saurabh-lodha-16** [comment]
@Stefan-Ethernal sorry to tag you directly but would love to know a basic guide to achieve this.
Thanks.

**Comment by Stefan-Ethernal** [comment]
It should be done by following the steps (however note that I haven't tested it personally in the past, so it might be possible that this use case is not working. The concern I have is whether discovery network protocol is able to discover those new nodes that are added on fly and belong to the different network):
- the administrator of the network should whitelist a validator. This is accomplished by running the `polybft whitelist-validators` command, 
- the validator should register itself. This is accomplished by running the `polybft register-validator` command,
- the validator should perform stake for itself. This is accomplished by running the `polybft stake` command.

An example of how it is done is found [here](https://github.com/0xPolygon/polygon-edge/blob/597a0f3d44fd21acb547f905366be8a9ee626c01/scripts/cluster#L128-L152). Note that administrator of the network is indeed the account which was used when running the `rootchain deploy` and the `polybft supernet` commands.

**Comment by saurabh-lodha-16** [comment]
I understand. Thanks a lot once again for explaining this.
They way I did was copying the genesis file to the remote validator.
Then whitelisted the validator on the node which is my bootnode.
The register and stake validator worked and the new node was able to join the network.


This issue was created at the genesis case where we want to setup the 4 nodes on different instances.
Would love to know your thoughts for this in brief.

**Comment by Stefan-Ethernal** [comment]
> This issue was created at the genesis case where we want to setup the 4 nodes on different instances.
Would love to know your thoughts for this in brief.

Ok so when you are bootstrapping the network, there is the `--validators` flag in the `genesis` command. You should specify validators in the following format: ` <P2P multi address>:<ECDSA address>:<public BLS key>` and you should be good to go.

**Comment by saurabh-lodha-16** [comment]
Yes I managed to do this.
I looked at the terraform configuration as well and managed to make this work.
Thanks a lot once again. 

We can close this
