### ISSUE TITLE
The Peer connect  success ，but can not open stream of /syncer/0.1 

### ISSUE THREAD

**Issue by luofei614** [0xPolygon/polygon-edge#211]
### Description

error message ：
```
[info] polygon.network:Peer connected id=****  
[error] polygon.consensus.syncer: failed to open a stream: err="protocol not supported"
```

### Steps to reproduce

It may be related to the network environment, unable to describe the steps to reproduce

### Proposed solution
My debugging method is to add a retry mechanism to wait for a while to succeed：
protocol/syncer.go：
```
var open_stream=false
 for !open_stream{
 stream, err := s.server.NewStream(syncerV1, evnt.PeerID)
 if err != nil {
      fmt.Println(syncerV1)
      fmt.Println(evnt.PeerID)
      s.logger.Error("failed to open a stream", "err", err)
      time.Sleep(1*time.Second)
      //continue
 }else{
    fmt.Println("success")
    open_stream=true
 }
fmt.Println(stream)
}
```
I did encounter a bug, and I don’t know how to solve this problem better.  Thanks！

**Comment by zivkovicmilos** [comment]
Hey @luofei614,

Thank you for reaching out. Have you modified the code in any way prior to running the client?

Please post the exact commands + steps you've taken to get this protocol not supported error.

**Comment by luofei614** [comment]
The node is running in docker.      A problem was found when running container with custom docker networkDocker's custom network startup will delay about 40 seconds!   Maybe this reason ：https://developpaper.com/docker-issue-network-delay/

**Comment by zivkovicmilos** [comment]
We need more information than _the node is running in docker_. What kind of setup do you have? What kind of docker configuration? What steps are you taking?

Please post as much information as you can here, so we can try to reproduce this issue.

**Comment by luofei614** [comment]
@zivkovicmilos   Thanks for your reply  ，   The environment for bugs is more complicated ，And this bug is accidental 。  I tried to reproduce the bug after simplifying the environment but did not succeed  。   Wait until I find a way to reproduce it before submitting an issue ，  Thanks again

**Comment by zivkovicmilos** [comment]
Got it.

Feel free to open up a new issue if you run into any problems 👍
