### ISSUE TITLE
Remove go-ethereum

### ISSUE THREAD

**Issue by ferranbt** [0xPolygon/polygon-edge#212]
### Description

Polygon-sdk has Go-ethereum as a dependency only to be used in two places ([here](https://github.com/0xPolygon/polygon-sdk/blob/a231cf496aaf230969fda927d49c4d35c19cc112/state/runtime/precompiled/testing.go) and [here](https://github.com/0xPolygon/polygon-sdk/blob/6af6ba96c0abd6c38a0cd9a56ccef9709a227855/types/header.go#L134)). In one case the function is never used and in the other (hexutil) there is already a replacement in the helper package.

**Comment by zivkovicmilos** [comment]
Hey @ferranbt,

We'll look into phasing it out as soon as we grab a chance.

Thank you for bringing it up and for linking the dependencies 👍 

I'll update this issue with the PR once it's up.

**Comment by zivkovicmilos** [comment]
PR Is up and ready for review 👍 

https://github.com/0xPolygon/polygon-sdk/pull/214
