### ISSUE TITLE
How can I calculate how much disk space is required on a server with bor and heimdalld ?

### ISSUE THREAD

**Issue by sergei-kh** [0xPolygon/polygon-edge#2132]
Is it possible to somehow calculate how much disk space I will need on the server on which bor and heimdalld are running, for example, for a year of operation ?

**Comment by Stefan-Ethernal** [comment]
This is a question for the PoS v1 team, so head to either one of these repositories:
- https://github.com/maticnetwork/bor
- https://github.com/maticnetwork/heimdall
