### ISSUE TITLE
Non-validator nodes pending txn queue does not clear

### ISSUE THREAD

**Issue by mrwillis** [0xPolygon/polygon-edge#223]
### Description

On a non-validator node, transactions in the `pendingQueue` do not get cleared after being mined but they do get cleared on validator nodes. 

### Your environment

* OS and version Ubuntu 20
* version of the Polygon SDK 6efebc6a92f885082620ed2a8d59e37d4d27074c
* branch that causes this issue `develop`

### Steps to reproduce

* Tell us how to reproduce this issue 
Start a chain. Start a non-validator node. Submit any txn TO THE  non-validator node RPC from any account. Don't submit to a validator node as that works fine.  

Call 

```
curl --location --request POST 'http://localhost:8545' \
--header 'Content-Type: application/json' \
--data-raw '{
    "method": "txpool_content"
}'
```
Observe that even after the txn is mined, the txn is not cleared from the txpool.

* Where the issue is, if you know <br />

In validator nodes, in `insertBlock` in ibft.go calls `	i.txpool.ResetWithHeader(block.Header)` which in turn calls `ProcessEvent` after it finishes to reset the tx pool. This is never called in non-validator nodes and is the only thing that I can see that removes txns from the `pendingQueue` in `txpool`. 

* Which commands triggered the issue, if any

### Expected behaviour

Txns should be cleared from pending as soon as they are mined.

### Actual behaviour

Txns stay forever in pending until restart.

### Logs

Please paste any logs here that demonstrate the issue, if they exist

This txn has long been mined:

```
{
    "jsonrpc": "2.0",
    "id": null,
    "result": {
        "pending": {
            "0x7D5e3D5D63225832cbf723526aF2e4EA4833dB35": {
                "37": {
                    "nonce": "0x25",
                    "gasPrice": "0x2540be400",
                    "gas": "0x186a0",
                    "to": "0x178341794621Ae73cC9090dA473B763E9A9b010B",
                    "value": "0x560b8ce73d414c7",
                    "input": "0x",
                    "hash": "0xd1fd7a9f56b623a592a992ca27309c3f1dfc1f3adb51e35cb8625cc97ba8c1c5",
                    "from": "0x7D5e3D5D63225832cbf723526aF2e4EA4833dB35",
                    "blockHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
                    "blockNumber": null,
                    "transactionIndex": null
                }
            }
        },
        "queued": {}
    }
}
```

### Proposed solution

After WriteBlocks in `blockchain.go`, there should be some sort of thing to clear pending txns from the txpool.

**Comment by brkomir** [comment]
@mrwillis, sorry for the late response here.

I have confirmed this behaviour and made the changes required in this PR #249 which is now merged into current develop, so feel free to try it out!
