### ISSUE TITLE
Bug: Navbar style issue in Light Mode

### ISSUE THREAD

**Issue by marpit19** [0xPolygon/polygon-edge#227]
### Description

*Navbar style issue in Light Mode

### Your environment

* OS and version
* version of the Polygon SDK
* branch that causes this issue

### Steps to reproduce

* Tell us how to reproduce this issue <br />
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

Tell us what should happen

### Actual behaviour

![image](https://user-images.githubusercontent.com/54642576/142613009-78665548-189b-4249-8fdd-5900788ceb69.png)

![image](https://user-images.githubusercontent.com/54642576/142613035-91ee2023-4765-4b97-a2cf-042f1f853459.png)

Tell us what happens instead

### Logs

Please paste any logs here that demonstrate the issue, if they exist

### Proposed solution
We can fix this solution by changing the polygondeveloper icon to polygon to make the transition smooth and good

**Comment by marpit19** [comment]
I would love to work on this issue if possible

**Comment by lazartravica** [comment]
Hello @marpit19! Sorry, but this is the wrong repository. 

The repo for the docs is at the following link: https://github.com/maticnetwork/matic-docs/
