### ISSUE TITLE
Discovery peers e2e tests

### ISSUE THREAD

**Issue by ferranbt** [0xPolygon/polygon-edge#23]
Implement a new e2e case for the network discovery of new nodes. 
- Create a n number of nodes.
- Join the nodes in serial: A -> B -> C
- Wait for one minute, after that, all the nodes should know each other.

Before we implement the test we need to fix the Peers operator methods ([here](https://github.com/0xPolygon/polygon-sdk/blob/v3/minimal/system_service.go#L79)) to use the [new](https://github.com/0xPolygon/polygon-sdk/blob/v3/network/server.go#L48) list of connected peers instead.

**Comment by Kourin1996** [comment]
Solved with commit https://github.com/0xPolygon/polygon-sdk/pull/30/commits/8dda751c8ba9b186c92e7ee2c3a73b86ecbc4b1e
