### ISSUE TITLE
`addImpl` in txpool.go incorrectly reports that the pool is full, even if empty, due to overflow

### ISSUE THREAD

**Issue by mrwillis** [0xPolygon/polygon-edge#231]
### Description
`addImpl` in txpool.go incorrectly reports that the pool is full, even if empty, causing broadcast failures. This causes downstream txn delays.

```
2021-11-19T16:22:26.745-0500 [ERROR] polygon.txpool: failed to add broadcasted txn: err="txpool is full"
```

It looks like the `txpool.slot` variable seems to have overflowed (see logs below). So this is two potentially related issues:

1. Node is incorrectly reporting txpool is full as a result of below
2. `txpool.slot` is overflowing

### Your environment

* OS and version Ubuntu 20
* version of the Polygon SDK 6efebc6a92f885082620ed2a8d59e37d4d27074c
* branch that causes this issue `develop`

### Steps to reproduce

* Tell us how to reproduce this issue <br />
Start a cluster with 4 nodes. Send a basic transaction (send 10 ETH) to the fourth node. Observe that on the other nodes, in `addImpl`, an error will be reported that the txpool is full.
* Where the issue is, if you know <br />

https://github.com/0xPolygon/polygon-sdk/blob/develop/txpool/txpool.go#L589 is an overflow if `t.slots = 0`

* Which commands triggered the issue, if any

### Expected behaviour

Node should accept valid gossiped non-local transaction

### Actual behaviour

Node rejects valid gossiped non-local transaction

### Logs

![image](https://user-images.githubusercontent.com/2652683/142695094-9603c7c9-d6f4-4b4f-ac63-f9fbff94619f.png)

![image](https://user-images.githubusercontent.com/2652683/142695674-16bf42f2-e585-405d-a319-8637224645f4.png)

![image](https://user-images.githubusercontent.com/2652683/142700866-c1f54e11-1125-4400-9b8a-224f3024d04c.png)

### Proposed solution

It looks like the discard function does not correctly consider the case with remoteTxns length = 0

**Comment by mrwillis** [comment]
Seems related to https://github.com/0xPolygon/polygon-sdk/pull/213. I can close if that will solve this issue.

**Comment by dbrajovic** [comment]
Hey @mrwillis ,

thank you for raising the issue. The bug has been identified and a fix under way.
