### ISSUE TITLE
Add e2e test to check the premined balance

### ISSUE THREAD

**Issue by ferranbt** [0xPolygon/polygon-edge#24]
Small e2e test to validate that the balance endpoint works.

Steps:
- Create a testserver with some dummy premined account.
- Use the GetBalance method to query the account.

**Comment by zivkovicmilos** [comment]
Solved with commit [96e3f65](https://github.com/0xPolygon/polygon-sdk/commit/96e3f65d9d429b02fabf6558838b4e05e493d356) 👍
