### ISSUE TITLE
Discussion: Remove stale validators from snapshot?

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#247]
### Description

We've been testing out adding and removing validators from the snapshot validator set using the `ibft propose --vote auth` and `ibft propose --vote drop` commands. During our testing, we voted in 8 validators and then stopped 3 of them without dropping them -  as a result the chain is still writing blocks however the 3 validator addresses that are no longer reachable are still being calculated as proposers within IBFT acceptState, wasting some unnecessary rounds and effectively reducing the network's throughput.

We think it would be a valuable addition for the SDK to detect when a validator address hasn't proposed a block in a while (compared to the other validator block-proposal times in the snapshot set) and either silently vote them off or create a new snapshot omitting that stale address.

### Proposed solution

We'd be happy to create a PR ourselves to introduce this feature if you think it'll be beneficial.

**Comment by lazartravica** [comment]
Hello @dankostiuk thank you for the issue.

We will not be adding the Slashing mechanism right now, as there are way more implications to wrap our heads around, most notably the issue of kicking out a validator that shouldn't have been kicked out.

This is definitely something that we are going to work on in the future, but not right now.
