### ISSUE TITLE
Limit to MaxPeers the incoming connections

### ISSUE THREAD

**Issue by ferranbt** [0xPolygon/polygon-edge#28]
## [Subject of the issue]

There is a MaxPeers value that limits the current number of peers we are connected or pending to be connected (in handshake). However, this limit is only respected for outbound connections. We should limit the inbound connections too, this is, if a new connection arrives and we have MaxPeers we should not accept the connection.

### Description

Describe your issue in as much detail as possible here

### Your environment

* OS and version
* version of the Polygon SDK
* branch that causes this issue

### Steps to reproduce

* Tell us how to reproduce this issue <br />
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Logs

Please paste any logs here that demonstrate the issue, if they exist

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

**Comment by Kourin1996** [comment]
Solved with commit https://github.com/0xPolygon/polygon-sdk/pull/33/commits/d856c6aaecc6a1fb1048bf59279dacd8ad5c50d9
