### ISSUE TITLE
Node's txpool stuck when spammed with txs

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#291]
### Description

We've been running stress tests against our testnet using a spamming tool we built (https://github.com/mrwillis/eth-txn-spam) and managed to halt some of our nodes when spammed with txs.

Looking in our logs, it appears that the txpool blocks the consensus state-change cycle for every node we target. I suspect that when flooded with txs, the txpool somehow blocks the ibft consensus from continuing past CommitState/ValidateState (likely the accountQueue or pendingQueue lock isn't being released) halting the consensus. 

Another thing we noticed is that while rpc requests to methods such as `eth_getBlockByNumber` return a response as expected -- sending a request to any txpool-related endpoint such as `txpool_content` will hang indefinitely, leading us to believe that a txpool reference is blocking.

We have been able to reproduce this issue using the `eth-txn-spam` tool but will try to use PSDK's loadboat to halt the chain in a similar manner - I'll update this issue with any additional info we find.

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon SDK `e7b9714 `
* branch that causes this issue `develop`

### Steps to reproduce

1. Create testnet with 4 validators and 1 non-sealing node
2. Using https://github.com/mrwillis/eth-txn-spam, run most basic type of test within that repo (mode=0 / regular transfer) with RANGE 200 and PARALLELISM 10 targeting the RPC url of a validator
    1. Can consistently repro when running on AWS `c4.4xlarge` Ubuntu 20 instance
3. Targeted node then gets stuck, and can no longer write blocks even after stopping the test.
4. RPC requests to txpool methods such as `txpool_content` no longer receive a response.

### Expected behaviour

Sending many requests to a node should not halt its IBFT consensus as this could lead to a chain halt.

### Actual behaviour

The targeted node's txpool gets stuck, blocking the IBFT layer - as a result the node cannot write new blocks.

**Comment by mrwillis** [comment]
Also reproduced this with mode = 4 which is deploying contracts. That will get the blocks full quite quickly and fill up the txpool presumably faster (as it can't drain as fast due to big txn sizes).

Make sure you have enough cores as per https://github.com/mrwillis/eth-txn-spam otherwise you might not fill up the pools as fast you would hope.

**Comment by mrwillis** [comment]
We've also noted that this test slows down the chain significantly, leading to 1 minute plus block times in some cases, but that could be a symptom of the bug or a separate issue.

**Comment by dankostiuk** [comment]
It appears we are also able to reproduce this issue when latest black is half full (41.6% gas used/limit) - also using mode = 0.
