### ISSUE TITLE
question--block generation

### ISSUE THREAD

**Issue by xzyblockChain** [0xPolygon/polygon-edge#303]
Can the block generation time be fixed to the specified time？
![Uploading eb95ef895e7c9b9b2b7a6dcaba57c7f.png…]()

**Comment by zivkovicmilos** [comment]
Hey @xzyblockChain,

We already have a discussion on this here:
https://github.com/0xPolygon/polygon-sdk/discussions/282

Closing this issue now, we can move over to the discussion
