### ISSUE TITLE
Hitting the file descriptor limit is unhandled

### ISSUE THREAD

**Issue by mrwillis** [0xPolygon/polygon-edge#308]
### Description

Not sure if this is the appropriate place for this, but something I wanted to bring up. 

If you have the default FD count on Ubuntu for example per user (1024 or 2048), you very quickly will hit the file descriptor limit due to the sheer amount of http requests some clients can submit to nodes (`eth_blockNumber`, `eth_getTransactionReceipt`, `eth_getLogs`) are some classic ones that are used a lot. 

```
basichost failed to resolve local interface addresses {"error": "route ip+net: netlinkrib: too many open files"}
```

### Your environment

* OS and version Ubuntu 20
* version of the Polygon SDK `develop`
* branch that causes this issue `develop`

### Steps to reproduce

* Tell us how to reproduce this issue 
Start a node using systemctl and set a low FD limit such as `LimitNOFILE=1024`. Use https://github.com/mrwillis/eth-txn-spam or a similar tool to spam transactions at the node. 

Get the PID of the SDK node and run

`lsof -p $PID`

You'll see there is a huge amount of FDs allocated to TCP requests.

* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

Not really sure

### Actual behaviour

All RPC requests after the fact hang after the limit is reached

### Logs

```
basichost failed to resolve local interface addresses {"error": "route ip+net: netlinkrib: too many open files"}
```

### Proposed solution

Maybe this is a documentation improvement for the "recommended minimum" FD amount. Generally you might handle this at a layer above.

**Comment by ZeljkoBenovic** [comment]
Hi @mrwillis ,

Thank you for raising this issue.
After some extensive testing, we've determined that the optimal FD value should be 65535 .

We've updated the official PolygonSDK documentation with this information under the [Local](https://sdk-docs.polygon.technology/docs/get-started/set-up-ibft-locally) and [Cloud Setup](https://sdk-docs.polygon.technology/docs/get-started/set-up-ibft-on-the-cloud) sections.

Closing this issue.
