### ISSUE TITLE
Where is the algorithm to calculate block reward?

### ISSUE THREAD

**Issue by dangminhnhut1993** [0xPolygon/polygon-edge#330]
### Description
In `func (e *Executor) ProcessBlock(parentRoot types.Hash, block *types.Block, blockCreator types.Address)`, we have blockCreator, But I don't see where to calculate block reward, and where to add it to blockCreator's balance

**Comment by zivkovicmilos** [comment]
Hey @dangminhnhut1993,

Thank you for reaching out.

We calculate the coinbase fee on a per transaction basis:
https://github.com/0xPolygon/polygon-sdk/blob/f165be765857477b55b12f7341d4a23ed124c628/state/executor.go#L436-L438

The coinbase being the block proposer (creator) of course:
https://github.com/0xPolygon/polygon-sdk/blob/ee9feb6ded975426f590df1e46b461fdaa39c3d6/state/executor.go#L87

**Comment by dangminhnhut1993** [comment]
Thank so much
