### ISSUE TITLE
Cannot deploy contracts Bridge, ERC20 Handler, ERC721 Handler, Generic Handler, on Polygon PoS local 

### ISSUE THREAD

**Issue by dangminhnhut1993** [0xPolygon/polygon-edge#344]
### Description

I'm trying to deploy contracts(Bridge, ERC20 Handler, ERC721 Handler, Generic Handler, ERC20, and ERC721) to the Polygon PoS chain with `cb-sol-cli`

### Your environment

* version of the Polygon SDK: 1ff87c0
* branch that causes this issue: develop

### Steps to reproduce

* Setup for cb-sol-cli command <br />
* Deploy contracts to Polygon PoS chain by `cb-sol-cli `deploy command<br />
```
cb-sol-cli deploy --all --chainId 99 \
  --url http://localhost:10002 \
  --privateKey [ADMIN_ACCOUNT_PRIVATE_KEY] \
  --relayers [RELAYER_ACCOUNT_ADDRESS] \
  --relayerThreshold 1
```
( http://localhost:10002: rpc local address)

### Expected behaviour

The contracts have been deployed, and I got the following result:
```
Deploying contracts...

✓ Bridge contract deployed
✓ ERC20Handler contract deployed
✓ ERC721Handler contract deployed
✓ GenericHandler contract deployed
✓ ERC20 contract deployed
WARNING: Multiple definitions for safeTransferFrom
✓ ERC721 contract deployed
```

### Actual behaviour

It waiting here forever 
```

Deploying contracts...

```

**Comment by Kourin1996** [comment]
@dangminhnhut1993 Hello, Thank you for raising the issue.

Could you please check a few things?

1. Blocks are being produced regardless of executing `cb-sol-cli deploy`? You can check this by log or fetching latest block in JSON-RPC
2. Block Gas Limit is enough to fit for the contracts? Block Gas Limit is updated every block production and determined by last block gas limit, last block gas usage, and node's block gas limit target.

Please add `--block-gas-limit [BLOCK_GAS_LIMIT]` in `polygon-sdk genesis` command to specify block gas limit in genesis block. To specify node's block gas limit target, please add `--block-gas-target [BLOCK_GAS_TARGET]` in `polygon-sdk server` command. I think `0x7A1200` is enough for deploying ChainBridge contracts.

**Comment by dangminhnhut1993** [comment]
Thank so much sir, I deployed successful all contracts by add` --block-gas-limit [BLOCK_GAS_LIMIT] `in `polygon-sdk genesis` and set `--block-gas-target [BLOCK_GAS_TARGET]` in `polygon-sdk server` command (BLOCK_GAS_TARGET = 0x7A1200)

**Comment by Kourin1996** [comment]
Glad it worked out. Closing this issue
