### ISSUE TITLE
There are no images for 0xpolygon/polygon-edge

### ISSUE THREAD

**Issue by mishamana** [0xPolygon/polygon-edge#377]
### Description

Documentation for polygon-edge says that 

> Official Docker images are hosted under the hub.docker.com registry.
> docker pull 0xpolygon/polygon-edge:latest

However dockerhub contains zero images for 0xpolygon/polygon-edge 

### Your environment

* macOS Monterey 
* 0.1.0
* master 

### Steps to reproduce

`$ docker pull 0xpolygon/polygon-edge:latest`

### Expected behaviour

Latest image being pulled 

### Actual behaviour

`Error response from daemon: manifest for 0xpolygon/polygon-edge:latest not found: manifest unknown: manifest unknown`

### Logs

`Error response from daemon: manifest for 0xpolygon/polygon-edge:latest not found: manifest unknown: manifest unknown`

### Proposed solution

Pushing actual images or fixing documentation would fix the issue

**Comment by lazartravica** [comment]
Hello @mishamana, sorry for the trouble. 

We have recently rebranded from Polygon SDK to Polygon Edge.

You can run the `docker pull 0xpolygon/polygon-sdk:latest` to pull the latest release. Once the new release is made with the Polygon Edge name you will be able to fetch the `polygon-edge` docker repo as well.

I am updating the docs to avoid this confusion until the next release. Thank you for reaching out.
