### ISSUE TITLE
ERC20 transfer not working using bridges

### ISSUE THREAD

**Issue by NorwegianGoat** [0xPolygon/polygon-edge#436]
## [Subject of the issue]
I followed the tutorial about bridge deployment using Chainbridge SDK. The bridge works when transferring ERC721 assets but nothing happens when I try to transfer ERC20 assets.

### Description and Steps to reproduce

My setup is formed by two separate edge-sdk blockchains, each of them with 4 nodes. The two chains use IBFT consensus.

The deployment phase of the bridge seems to be ok:
-  I deploy a simple ERC20PresetMinterPauser contract on the source chain;
- `cb-sol-cli` is then used to deploy the bridge contract and an ERC20 handler on the source chain;
- resource is registered on the source chain bridge;
- on dest chain the bridge, an ERC20 handler and an ERC20 contract are deployed;
- resource is registered on the bridge then I set up the burn and mint for the ERC20 tokens on the destination chain.

When I try to use the bridge:
- I mint some tokens on the source chain and give the ERC20 handler the privileges to manage my ERC20;
- I start the deposit.
After the last action, no event is emitted by the transaction. If I check the transaction receipt, the status is 0 so the transaction fails. The response is `{'code': -32600, 'message': 'unable to execute call: execution was reverted'}`. Not so helpful...

When I try to do the same with an ERC721 (NFT) asset all the procedure works without any problem (i.e. the deposit action emit some events and these are picked up by the relayer). 

### Your environment

* Polygon Edge `0.1.0`
* ChainBridge `1.1.5`
* Chainbridge Deploy Tools `f2aa093` on `main` branch
(As the [tutorial](https://edge-docs.polygon.technology/docs/additional-features/chainbridge/requirements) on how to run a bridge with ChainBridge recommends)

### Expected behaviour

Deposit transactions should produce events picked up by the ChainBridge relayer.

### Actual behaviour

No events are emitted, the deposit fails.

### Logs

Here is a transaction receipt for reference, as you can see the transaction status is 0 and no logs are emitted.
> AttributeDict({'root': '0x0000000000000000000000000000000000000000000000000000000000000000', 'cumulativeGasUsed': 151397, 'logsBloom': HexBytes('0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'), **'logs': []**, **'status': 0**, 'transactionHash': HexBytes('0x8bf51583213e80a9ee05aeaa513cfbef3f6475de8afd9b6cc5cce35ef1c6ceca'), 'transactionIndex': 0, 'blockHash': HexBytes('0x15d7603aa7e74ec52ed38b4aeed8321e351c63c6ef0b40cc27a43eef5af8ffd7'), 'blockNumber': 11354, 'gasUsed': 151397, 'contractAddress': '0x0000000000000000000000000000000000000000', 'from': '0x222b8e2152E189f5282249877e039EF2c1c0C826', 'to': '0x6478b49Ae12070Cab4327Ff85C16B6E8AE2483f2'})

### Proposed solution
No proposed solution

**Comment by Kourin1996** [comment]
@NorwegianGoat Thank you for raising the issue. Could I ask you a few things to find the reason?

* You told that you've depoloyed `ERC20PresetMinterPauser`. Is this contract OpenZeppelin's one?

* Which mode do you use for ERC20 transfer in the source chain, burn or lock?
About the mode, please check this https://edge-docs.polygon.technology/docs/additional-features/chainbridge/setup-erc20-transfer#optional-make-contracts-mintableburnable

* Did you approve token transfer or burning by ERC20 handler before bridging?

And I would appreciate it if you could share the exact steps you did for ERC20 transfer. (e.g. command, params, transaction)

Thank you for your help

**Comment by NorwegianGoat** [comment]
Hi, thank you for your reply. I'm going to answer your questions in points.

>     * You told that you've depoloyed `ERC20PresetMinterPauser`. Is this contract OpenZeppelin's one?
Yes, currently my contract is a simple
`contract CrossCoin is ERC20PresetMinterPauser {
    constructor() ERC20PresetMinterPauser("CrossCoin", "CC") {}
}`

>     * Which mode do you use for ERC20 transfer in the source chain, burn or lock?
Initially, I didn't specify a mode for the source chain because I thought that the default was lock mode.  On the contrary, for the destination chain I configured the burn mode, but after your question I tried to set up burn mode also for the source chain, but this didn't have any effect.

>     * Did you approve token transfer or burning by ERC20 handler before bridging?
Yes, that transaction finishes with status 1 (like all the previous transactions).

> And I would appreciate it if you could share the exact steps you did for ERC20 transfer. (e.g. command, params, transaction)

This results in a pretty long wall of text, so I attach a log file here. The commands I run are inside square brackets because I run the deployment of the bridge and the transfer between chains from a python script.
[exec_log.txt](https://github.com/0xPolygon/polygon-edge/files/8198011/exec_log.txt)

**Comment by Kourin1996** [comment]
@NorwegianGoat Hi, Thank you for your details. Could I ask you a quick question? I don't see you mint new tokens in source chain. Does an sender account has enough balance to transfer?

**Comment by NorwegianGoat** [comment]
Hi, yes. The mint is performed on the source chain by calling directly the smart contract function; this happens in lines 113 and 114. I can confirm that the redeem phase is working because I can see my balance going up in metamask.

**Comment by Kourin1996** [comment]
by the way, cb-sol-cli multiplies given amount by 10^18 as default. Seeing your log, you were trying to send 10^36 tokens. How many tokens do you have in account now?

**Comment by NorwegianGoat** [comment]
> by the way, cb-sol-cli multiplies given amount by 10^18 as default. Seeing your log, you were trying to send 10^36 tokens. How many tokens do you have in account now?

This is one of the most epic facepalm moments of my life. I was convinced that they used Wei as a base unit for transfers and therefore it was my responsibility to make the conversion.
I can confirm everything is working now. Thank you :man_facepalming:

**Comment by Kourin1996** [comment]
Glad to hear that you could transfer tokens. Closing this issue. Please feel free to re-open this or open a new issue when you have new issue.
