### ISSUE TITLE
After migrating to version 0.3.0 deployment fails

### ISSUE THREAD

**Issue by inglkruiz** [0xPolygon/polygon-edge#441]
### Description

Hi, after updating a k8s deployment to use the latest version `v0.3.0` the container reports an error I cannot say what it is. I'm running a PoA network.

The command we run within a container is quite basic:

```
polygon-edge server --config /data/config.json
```

Here's is the config

### `config.json`

```json
{
  "data_dir": "/data/chain",
  "chain_config": "/data/chain/genesis.json",
  "block_time_s": 15,
  "jsonrpc_addr": "0.0.0.0:8545",
  "grpc_addr": "0.0.0.0:9632",
  "seal": true,
  "network": {
    "libp2p_addr": "0.0.0.0:1478",
    "dns_addr": "dns/staging-luis-polygon-edge-01-val-01-9721p.settlemint.com"
  },
  "txpool": {
    "price_limit": 0
  },
  "telemetry": {
    "prometheus_addr": "0.0.0.0:9545"
  }
}
```

### `genesis.json`
```json
{
  "name": "staging-luis-polygon-edge-01-ace8",
  "genesis": {
    "nonce": "0x0000000000000000",
    "timestamp": "0x0",
    "gasLimit": "9007199254740991",
    "difficulty": "0x1",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "alloc": {
      "0x227FBE30d0e9196c889785f539F3C93523420163": {
        "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
      }
    },
    "number": "0x0",
    "gasUsed": "0x70000",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000d8d594b34c88847ea50bf8304f89ba5aab5b844785fd8680c0"
  },
  "params": {
    "forks": {
      "homestead": 0,
      "byzantium": 0,
      "constantinople": 0,
      "petersburg": 0,
      "istanbul": 0,
      "EIP150": 0,
      "EIP158": 0,
      "EIP155": 0
    },
    "chainID": 41510,
    "engine": {
      "ibft": {
        "type": "PoA"
      }
    },
    "blockGasTarget": 10378291982571407000
  },
  "bootnodes": [
    "/dns/staging-luis-polygon-edge-01-val-01-9721p.settlemint.com/tcp/1478/p2p/16Uiu2HAmT7eRZ3LcfgZsoKGPPJ7fP3xjfqEXc818WnJqGjSnkCss"
  ]
}
```

### Your environment

* OS and version: Kubernetes GCP/EKS
* version of the Polygon Edge: `v0.3.0`
* branch that causes this issue: NA

### Steps to reproduce

I believe you could run the server using the config I'm providing but feel free to ask anything.

### Expected behaviour

It should run normally as in `v0.2.1`

### Actual behaviour

![Screenshot 2022-03-09 at 17 11 00](https://user-images.githubusercontent.com/12603425/157494196-320f51fc-4d70-4aad-bccf-10e62febb690.png)

### Logs

NA

### Proposed solution

NA

**Comment by inglkruiz** [comment]
Just sharing it works running the version `v0.2.1`

![image](https://user-images.githubusercontent.com/12603425/157496514-85c31df3-126b-4466-b278-691157493fe3.png)

**Comment by 0xAleksaOpacic** [comment]
@inglkruiz 
Thank you for opening this issue. 
I have been able to reproduce the issue and I will notify you as soon as we fix it.
