### ISSUE TITLE
ethjs-query formatting query for sendRawTransaction

### ISSUE THREAD

**Issue by afeezaziz** [0xPolygon/polygon-edge#46]
When using Metamask and connected to the JSON-RPC url(as per demo video), when sending ETH, the metamask did not transfer any ETH as the error of sendRawTransaction failed to format 'undefined'.

Exact error is as below:
<img width="367" alt="Screenshot 2021-05-30 at 7 44 46 PM" src="https://user-images.githubusercontent.com/677026/120102897-b369e100-c17f-11eb-9557-3b120ed04678.png">

**Comment by zivkovicmilos** [comment]
Hey @afeezaziz,

Thank you for reaching out. We'll take a look at this as soon as possible.
If I understood correctly, you tried to send ETH to another account using Metamask, like in the demo video?

**Comment by afeezaziz** [comment]
Yes, that is correct. I am unable to do so when if the nodes are publicly accessible nodes. If I run the tutorial on my local computer, then it is fine.

**Comment by lazartravica** [comment]
Just to let you know that I was unable to reproduce the issue you have reported.

Still I have some indications of what might be the problem and what you can do to try to fix it.

1. Set the currency symbol in Metmask to anything other than an empty string (e.g. `SDK`)

Current Metamask version has an unresolved bug where if you don't input a "Currency Symbol" it will display wrong balances, gas estimates and might cause more errors.
Just entering any Currency Symbol in this field will fix the issue with Metamask. Here's the link to the issue on the Metamask repo: https://github.com/MetaMask/metamask-extension/issues/9492

2. Spin up 4 IBFT nodes

For IBFT to function properly you need at least 4 connected nodes in the network. If you have less than that, your network will not be able to produce blocks as expected.

Please let me know if any of these solutions worked for you, and I'm here to help if you have any more questions or issues.
