### ISSUE TITLE
Unable to deploy contracts to Polygon Test Net

### ISSUE THREAD

**Issue by spunkyshooter** [0xPolygon/polygon-edge#467]
### Description
I was following [deploy-contracts](https://edge-docs.polygon.technology/docs/additional-features/chainbridge/deploy-contracts/) doc, I was able to deloy contracts on polygon-edge blockchain. 
But I am unable to deploy to Polygon TestNet (Mumbai). I do have enough Test Matic Tokens in both `admin` and `relayer` accounts.

I am trying to deploy the contracts using below command:
```
 cb-sol-cli deploy --all --chainId 99 --url https://rpc-mumbai.matic.today --privateKey <ADMIN_ACCOUNT_PRIVATE_KEY> --relayers <RELAYER_ACCOUNT_ADDRESS> --relayerThreshold 1 --gasPrice 1000000000
```
But its stuck after showing Deploying contracts... for around 12ish hours. No logs after that.

I raised the [Issue with ChainBridge](https://github.com/ChainSafe/chainbridge-deploy/issues/97) as well , we have no response and we are blocked due to this. Reaching out here if anyone knows what's the issue. Thanks.

### Your environment

* OS and version Ubuntu 20.04.4 LTS
* version of the Polygon Edge: NA
* branch that causes this issue: NA

### Steps to reproduce
- Install chain bridge, have sufficient Test Matic tokens in both admin and relayer accounts, then try the above command. 

### Expected behaviour

Contracts Should be deployed to Polygon TestNet

### Actual behaviour

Getting stuck after showing after showing `Deploying contracts...`

### Logs

Please paste any logs here that demonstrate the issue, if they exist

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

**Comment by Kourin1996** [comment]
@spunkyshooter Did you check gas price from gas station and set proper gas price?

The average gas price right now from Mumbai Gas Station (https://gasstation-mumbai.matic.today/v2) is 1.6851500227999998 GWei = 1685150022 Wei. 1000000000 is too cheap compared to average gas price.

**Comment by Kourin1996** [comment]
And please note https://rpc-mumbai.matic.today has API rate limitation. You might want to use some services like Infura or Alchemy

**Comment by spunkyshooter** [comment]
Thanks @Kourin1996  for the direction, I tried changing the gas price to 7586724964 Wei (7.586724964 GWEI) which is `maxFee` as per the Gas Station api, I am now getting below error:

```
responseText: '{"jsonrpc":"2.0","id":45,"error":{"code":-32000,"message":"transaction underpriced"}}'
```

**Comment by Kourin1996** [comment]
@spunkyshooter This error occurs when you're sending transaction with a lower gas price than the gas price of the transaction with same nonce. Please use higher gas price than the value you used before for same nonce to replace transaction.

**Comment by spunkyshooter** [comment]
Thanks @Kourin1996, Closing this issue, I signed up for Alchemy and used their RPC url, Its seems to be deploying. I can see the large number of requests on dashboard.

**Comment by spunkyshooter** [comment]
Still facing the same issue. 
The previous execution got timedout after 10hours

```
manu@DESKTOP-2UP34D7:~/projects/chainbridge-deploy/cb-sol-cli$ cb-sol-cli deploy --all --chainId 99 --url https://polygon-mumbai.g.alchemy.com/v2/<APIKEY> --privateKey <My private key> --relayers 0xfCB8f249fC313eBEbFd626982B61f4435898327D --relayerThreshold 1 --gasPrice 3005150022 --fee 0.000000005925192625
Deploying contracts...
{
  e: Error: timeout
      at Timeout._onTimeout (/home/manu/projects/chainbridge-deploy/cb-sol-cli/node_modules/ethers/utils/web.js:54:20)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)
}
```

I tried to increase the gasPrice and included gasLimit after following [this](https://forum.moralis.io/t/deploy-to-polygon-matic-mumbai-fails/700/4) but still fails.

Failed after 6 hours. 


```
cb-sol-cli deploy --all --chainId 99 \
> --url https://polygon-mumbai.g.alchemy.com/v2/<APIKEY> \
> --privateKey <My private key> \
> --relayers 0xfCB8f249fC313eBEbFd626982B61f4435898327D \
> --relayerThreshold 1 \
> --gasPrice 7000000000 \
> --gasLimit 6000000

Deploying contracts...
{
  e: Error: invalid response - 524
      at exports.XMLHttpRequest.request.onreadystatechange (/home/manu/projects/chainbridge-deploy/cb-sol-cli/node_modules/ethers/utils/web.js:84:29)
      at exports.XMLHttpRequest.dispatchEvent (/home/manu/projects/chainbridge-deploy/cb-sol-cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (/home/manu/projects/chainbridge-deploy/cb-sol-cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (/home/manu/projects/chainbridge-deploy/cb-sol-cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    statusCode: 524,
    responseText: '<html>\r\n' +
      '<head><title>524 Origin Time-out</title></head>\r\n' +
      '<body bgcolor="white">\r\n' +
      '<center><h1>524 Origin Time-out</h1></center>\r\n' +
      '<hr><center>cloudflare-nginx</center>\r\n' +
      '</body>\r\n' +
      '</html>\r\n'
  }
}
```

I wanna know, did any one had luck deploying ChainBridge contracts to Polygon testnet and if so what were those settings and how much time generally it takes. 

Kindly help if you are aware.

**Comment by Kourin1996** [comment]
@spunkyshooter 

* Please check the deployer account you gives in `--privateKey` has enough balance to deploy contract
* Please check `gasPrice` is enough expensive
* Please check `gasLimit` is enough to process deployment

Actually, I could deploy all contracts with the following command:

```
$ cb-sol-cli deploy --all --chainId 99 \
  --url <alchemy_json_rpc_endpoint> \
  --privateKey <myprivate_key> \
  --relayers <myrelayer_addr> \
  --relayerThreshold 1 \
  --gasPrice 4012292811 \
  --fee 0.000000005925192625 \
  --gasLimit 6000000
```

If you couldn't, please go to Alchemy dashbord, check transaction hash, and check this transaction in explorer

**Comment by Kourin1996** [comment]
@spunkyshooter Also you might want to check previous transactions (meaning transactions with lower nonces) are stuck or not.

**Comment by spunkyshooter** [comment]
@Kourin1996 

Thanks for reply. 

My both admin and relayer account have 10 Matic test Tokens, which I think is enough. 
I tried with very high gasPrice and gasLimit as well, max fee and various combinations. it didn't work. 

I have let it deploy using your settings. hoping it works out. 

1. How do we know the previous transactions with lower nonces are stuck ? I don't see a way to see those. 
2. How long does deploying usually takes ?

**Comment by Kourin1996** [comment]
@spunkyshooter 

1. You can get the number of the transactions, created by an account and mined into the past blocks, by getTransactionCount in JSON-RPC API. This count will be next nonce basically. So you get the count and the nonce in the transaction you're sending right now. If there is a gap of the nonce, which may mean some previous transactions are still in queue.
2. Depends on the number of queued transactions and the situation. Transactions usually will be mined within 10 mins in Munbai, as far as I've tried.

**Comment by spunkyshooter** [comment]
@Kourin1996 

Thanks for explaining. 

I checked eth_getTransactionCount:
```
curl <alchemy_json_rpc_endpoint> \
-X POST \
-H "Content-Type: application/json" \
-d '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":[<admin_account_address>,"latest"],"id":0}'
```

This result is 0:
```
{"jsonrpc":"2.0","id":0,"result":"0x0"}
```

But this is what I see on my Alchemy dashboard. 

![image](https://user-images.githubusercontent.com/29997888/160197222-b08c03ee-6dc4-453a-8b1a-e6086a3f6061.png)
![image](https://user-images.githubusercontent.com/29997888/160197487-24c385b5-9750-42a0-96d5-bb2e54bcf4a1.png)

There are 2 type of requests, `eth_getTransactionReceipt` and `eth_blockNumber` continuously triggered. 

Do you see anything suspicious ? 

Btw, the last deployment from 3 hrs back is again stuck.

**Comment by Kourin1996** [comment]
@spunkyshooter All result in last your message shows any transactions you've sent from this account have never been processed. Also you can check this fact in Polygon scan.

https://mumbai.polygonscan.com/address/0xbc726fee350e4afe042e5a2ba7a130509ee4f3ac
This result shows there are no transactions from your account. (You can see one transaction, but this is deposit and not from your account)

The nonce of the transaction 0x7f030a34e5b0b7c6f32559eb58ca86c89e51b4f7468d3ee292afa46911ff2c9f, which you're sending right now, is 0xc. You can check this transaction by eth_getTransactionByHash. So you have pending transactions between nonces from 0x0 to 0xc. You can't process any new transaction until they are mined.

You will need to cancel all transactions from 0x0 to 0xc. (Or replace them with new) You can create transfer transactions with 0 amount, higher gas price, and each nonce. You can send transaction with custom nonce in Metamask.

**Comment by Kourin1996** [comment]
@spunkyshooter I recommend you to create a brand new account in wallet like Metamask, move assets to it by tx with 0 nonce and enough expensive gas price, and send contract creation transactions with enough expensive gas price from new account if you can create new one

**Comment by spunkyshooter** [comment]
@Kourin1996 Thanks a lot for putting effort and deep diving. Helped us to deploy the contracts finally. We were blocked for days.
Closing it.
