### ISSUE TITLE
 High CPU utilization on AWS ec2 when running node

### ISSUE THREAD

**Issue by JSHan94** [0xPolygon/polygon-edge#469]
### Description

When we run a full node on `t2.small` AWS ec2 instance, CPU utilization goes too high abnormally then the instance/node is crushed .  ![스크린샷 2022-03-23 오전 10 31 39](https://user-images.githubusercontent.com/29887117/159604259-65aa1d14-0aed-45ae-9dd9-07fbb7cec536.png)

### Your environment

* OS and version : ubuntu
* version of the Polygon Edge : `develop`
* branch that causes this issue : `develop`

8 validator nodes
- 4 nodes on `t2.micro` 
- 4 nodes on `t3.small`

### Steps to reproduce

* Run a nodes on ec2 t2.micro instance

### Expected behaviour

work as full node

### Actual behaviour

ec2 instance status check failed and node is crushed

![스크린샷 2022-03-23 오전 10 34 29](https://user-images.githubusercontent.com/29887117/159604456-d94b7662-af56-4cf0-844e-6f41f658206e.png)

### Logs

instance is crushed so we couldn't log

### Proposed solution

t3.small or better spec instances are never crushed, but there are too expensive.. we want to know what is the problem.

**Comment by zivkovicmilos** [comment]
Hey @JSHan94,

Thank you for reaching out.

Can you please provide additional information on the actual problem?

What were you doing on the network? What kind of transactions were you sending, if any?

**Comment by JSHan94** [comment]
I think we didn't do anything special task on these crushed nodes.

They are just in a validator set.

What we only do is just monitoring the nodes with `ethstats` monitoring server. 

![스크린샷 2022-03-24 오전 10 10 39](https://user-images.githubusercontent.com/29887117/159822172-1dc4a651-05f4-42f6-aafe-32fc99cd05b6.png)

Once a day, t2.micro nodes are crushed like node3 in the figure.

`ethstats` server is set on t2.2xlarge instance .

and the following image is the running node logs.

![스크린샷 2022-03-24 오전 10 14 09](https://user-images.githubusercontent.com/29887117/159822697-be205240-3f2b-4581-8f14-f111186cc1ac.png)

we get a tons of `eth_getFilterChanges` and `eth_getBlockTransactionCountByNumber` errors.

Does this have anything to do with a node crashing?

**Comment by zivkovicmilos** [comment]
@JSHan94

Thank you for the update 🙏 

Could you please provide full node logs for the node that gets crushed?

**Comment by zivkovicmilos** [comment]
Hey @JSHan94,

Any updates on the logs?
Have you managed to reproduce the problem still?

**Comment by JSHan94** [comment]
After upgrading our node instance, it is hard to reproduce same issues.

I think it's just a AWS issue. Thank you anyway.

**Comment by zivkovicmilos** [comment]
Hey @JSHan94,

Thank you for updating!

I'll close this issue for now, so feel free to open up a new one if it comes up again.
