### ISSUE TITLE
LoadBot fails with SIGSEGV

### ISSUE THREAD

**Issue by kirillt** [0xPolygon/polygon-edge#472]
### Description

Attempt to perform stress testing using built-in tool "LoadBot" fails. 

### Your environment

* OS and version: **Fedora 35**
* version of the Polygon Edge: **v0.1.0**
* branch that causes this issue: **develop**

### Steps to reproduce
Open MetaMask, create an account. In my case the following account was created (possible to import for debugging):
```
helmet pool broom actual inflict enter bitter tourist hungry walk render mind #mnemonic
db22fc73512d3e40c57056f24b2a4fa6e8a0c8ff9bdd98d4f398fa4514fd0524              #private key
0xD45d663eC1368C04Af04BC18c3d8e19a4D5F1cDD                                    #address
```

Use the address in Genesis config as pre-mined account: [genesis_json.txt](https://github.com/0xPolygon/polygon-edge/files/8356225/genesis_json.txt) (rename the file to `genesis.json`).

Start Polygon Edge on a cloud instance:
```
polygon-edge server --data-dir ./data --chain genesis.json --libp2p 0.0.0.0:1478 --seal --nat
```

Open MetaMask again, add custom network pointing to the just launched node:
![lenovo-fedora-20220326-214124-642592993](https://user-images.githubusercontent.com/581023/160254796-1c6fb92f-d019-4055-8bdf-7acf98ddf536.png)

Now, we can see in MetaMask that our account indeed has pre-mined balance:
![lenovo-fedora-20220326-214142-807062178](https://user-images.githubusercontent.com/581023/160254883-e5f93253-be77-4b82-9886-53536ff8daf5.png)

Run LoadBot following [stress testing guide](https://edge-docs.polygon.technology/docs/additional-features/stress-testing):

```bash
# Example
export LOADBOT_0xD45d663eC1368C04Af04BC18c3d8e19a4D5F1cDD=db22fc73512d3e40c57056f24b2a4fa6e8a0c8ff9bdd98d4f398fa4514fd0524

polygon-edge loadbot \
  --jsonrpc http://127.0.0.1:8545 \
  --grpc-address 127.0.0.1:9632 \
  --sender 0xD45d663eC1368C04Af04BC18c3d8e19a4D5F1cDD \
  --receiver 0xD45d663eC1368C04Af04BC18c3d8e19a4D5F1cDD \ #sending to ourselves
  --count 1000 \
  --value 0x100 \
  --tps 100
```

### Expected behaviour

Transactions get created and submitted, loading the network.

### Actual behaviour

```
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x14e8fe5]

goroutine 1 [running]:
github.com/0xPolygon/polygon-edge/command.(*CLIOutput).getCommandOutput(...)
        /tmp/polygon-edge/command/cli_output.go:31
github.com/0xPolygon/polygon-edge/command.(*CLIOutput).WriteOutput(0xc0004487a0)
        /tmp/polygon-edge/command/cli_output.go:23 +0xc5
panic(0x16b7ac0, 0x2bb2850)
        /usr/lib/golang/src/runtime/panic.go:965 +0x1b9
github.com/0xPolygon/polygon-edge/command/loadbot.(*Loadbot).Run(0xc0004487c0, 0x0, 0x0)
        /tmp/polygon-edge/command/loadbot/execution.go:165 +0x5ad
github.com/0xPolygon/polygon-edge/command/loadbot.runLoadbot(0xc000464be0, 0xc000464b00, 0xf, 0x0, 0x15)
        /tmp/polygon-edge/command/loadbot/loadbot_command.go:164 +0xa5
github.com/0xPolygon/polygon-edge/command/loadbot.runCommand(0xc000456f00, 0xc0001ac540, 0x0, 0xe)
        /tmp/polygon-edge/command/loadbot/loadbot_command.go:151 +0x20b
github.com/spf13/cobra.(*Command).execute(0xc000456f00, 0xc0001ac460, 0xe, 0xe, 0xc000456f00, 0xc0001ac460)
        /tmp/polygon-edge/vendor/github.com/spf13/cobra/command.go:860 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003c2a00, 0xc00045e280, 0xc00045e500, 0xc00045e780)
        /tmp/polygon-edge/vendor/github.com/spf13/cobra/command.go:974 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /tmp/polygon-edge/vendor/github.com/spf13/cobra/command.go:902
github.com/0xPolygon/polygon-edge/command/root.(*RootCommand).Execute(0xc000010c68)
        /tmp/polygon-edge/command/root/root.go:58 +0x32
main.main()
        /tmp/polygon-edge/main.go:17 +0x4c
```

**Comment by zivkovicmilos** [comment]
Hey @kirillt,

Thank you for reaching out 🙏 

We have identified the bug you were experiencing, and have resolved it in a PR that will get merged out soon, it was an issue with the loadbot module having incorrectly set modes.

**Comment by kirillt** [comment]
@zivkovicmilos awesome! Looking forward to try again.

**Comment by kirillt** [comment]
Looks working, thanks.
