### ISSUE TITLE
`ibft snapshot` command not returning expected output

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#476]
### Description

It seems like after https://github.com/0xPolygon/polygon-edge/pull/410, the grpc `ibft snapshot` call no longer returns the validator set from the last snapshot as expected:

```
./main ibft snapshot --grpc-address localhost:10000

[IBFT SNAPSHOT]
```

Describe your issue in as much detail as possible here

### Your environment

* OS and version `Ubuntu 20`
* version of the Polygon Edge `v0.3.0`
* branch that causes this issue `develop`

### Steps to reproduce

1. Pull in change including  https://github.com/0xPolygon/polygon-edge/pull/410
2. Run `ibft snapshot`
3. Observe just the text `[IBFT SNAPSHOT]`

### Expected behaviour

I would expect the list of validators to display for the current snapshot, similar to below:
```
[IBFT SNAPSHOT]
Block = 3700
Hash  = 0xb30b384de2808a417663730dff656628e51fb23a49cbcf8e1b8162edc275f10f

[VOTES]
No votes found

[VALIDATORS]
ADDRESS
0xA3a585c6d59CCE6aAe7035e8df48b3327cC8BE54
0x7EFF16a34e3433182D636488bc97919b10283F37
0x3e64F88C6C7a1310236B242180c0Ba1409d10F4d
0x9cde4F11EA57163023A9a8a5dF499b27813639EB
0x6c230a5f8dd3413aA04e0860dD225F887b36f101

```

### Actual behaviour

The list of validators of the current snapshot no longer appears.

**Comment by 0xAleksaOpacic** [comment]
@dankostiuk You are right, I will create hotFix today.
