### ISSUE TITLE
Running an Edge network with 0 transaction fee

### ISSUE THREAD

**Issue by ashlesh-settlemint** [0xPolygon/polygon-edge#477]
### Description

After running the polygon edge network with below `config.json` and `genesis.json` file, when I query the validator node with the `eth_gasPrice` RPC method it sometimes returns zero and sometimes non-zero values. And when the value is non-zero, I am unable to make the transaction with 0 `gasPrice` as it throws the insufficient funds error.

#### `config.json`
```
{
  "data_dir": "/data/chain",
  "chain_config": "/data/chain/genesis.json",
  "block_time_s": 15,
  "jsonrpc_addr": "0.0.0.0:8545",
  "grpc_addr": "0.0.0.0:9632",
  "seal": true,
  "network": {
    "libp2p_addr": "0.0.0.0:1478",
    "dns_addr": "dns/staging-luis-polygon-edge-01-val-01-9721p.settlemint.com"
  },
  "txpool": {
    "price_limit": 0
  },
  "telemetry": {
    "prometheus_addr": "0.0.0.0:9545"
  }
}
```

#### `genesis.json`
```
{
  "name": "staging-luis-polygon-edge-01-ace8",
  "genesis": {
    "nonce": "0x0000000000000000",
    "timestamp": "0x0",
    "gasLimit": "9007199254740991",
    "difficulty": "0x1",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "alloc": {
      "0x227FBE30d0e9196c889785f539F3C93523420163": {
        "balance": "0x446c3b15f9926687d2c40534fdb564000000000000"
      }
    },
    "number": "0x0",
    "gasUsed": "0x70000",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000d8d594b34c88847ea50bf8304f89ba5aab5b844785fd8680c0"
  },
  "params": {
    "forks": {
      "homestead": 0,
      "byzantium": 0,
      "constantinople": 0,
      "petersburg": 0,
      "istanbul": 0,
      "EIP150": 0,
      "EIP158": 0,
      "EIP155": 0
    },
    "chainID": 41510,
    "engine": {
      "ibft": {
        "type": "PoA"
      }
    },
    "blockGasTarget": 10378291982571407000
  },
  "bootnodes": [
    "/dns/staging-luis-polygon-edge-01-val-01-9721p.settlemint.com/tcp/1478/p2p/16Uiu2HAmT7eRZ3LcfgZsoKGPPJ7fP3xjfqEXc818WnJqGjSnkCss"
  ]
}
```

And here is the response from the `eth_gasPrice` RPC method -
```
{
  "jsonrpc":"2.0"
  "id":42
  "result":"0x0"
}
```

```
{
"jsonrpc":"2.0"
"id":42
"result":"0x19e6"
}

```
### Your environment

* OS and version: Kubernetes GCP/EKS
* version of the Polygon Edge: v0.3.1
* branch that causes this issue: NA

### Steps to reproduce

After running the network, run the `eth_gasPrice` ethereum RPC method to see that the gasPrice is sometimes non-zero and is dynamic.

### Expected behaviour

We are expecting gasPrice to be static and 0, so transactions won't require a network token to make a transaction.

### Actual behaviour

gasPrice is coming dynamic with non-zero values sometimes and because of this, the transactions are failing with insufficient funds error.

### Logs

NA

### Proposed solution

NA

**Comment by zivkovicmilos** [comment]
Hey @ashlesh-settlemint,

Thank you for opening up the issue. I have identified the problem and started working on a fix.
I've linked the PR that should fix this issue once it's merged out. I'll keep you updated as soon as this issue has been resolved 👍
