### ISSUE TITLE
ERC721 deposit failing with chainbridge

### ISSUE THREAD

**Issue by vineetaparodkar** [0xPolygon/polygon-edge#492]
### Description

Chainbridge sample ERC721 token is transferred between Polygon POS chain and local network setup with polygon edge. ERC 721 token is deposited and proposal is executed at relayer but tokens are not released in Polygon edge network.

### Your environment

* OS and version: ubuntu
* version of the Polygon Edge : 0.2.1
* branch that causes this issue: development branch

### Steps to reproduce
- Alchemy URLs are used for RPC, for testing common account is used for admin,relayer and user
- All gas prices are used from matic gasstation for POS chain transactions
- chainbridge's default lock release mode is used in below setup
- Polygon edge block gas limit is set to 0x7A1200
- Relayer config is set to  "blockConfirmations": "1"  
1. Created a polygon edge local network as per documentation [ [documentation](https://edge-docs.polygon.technology/docs/get-started/set-up-ibft-locally/) ]

2. Deployed chainbridge contracts on Polygon POS chain 

`cb-sol-cli deploy --all --chainId 99 \
   --url  <RPCURL> \
   --privateKey <PRIVATE_KEY> \
   --relayers 0xbE6401aaBFd8B019747205787E6FaeA82BA46C60 \
   --relayerThreshold 1 \
   --gasPrice 24854016445 \
`

3. Deploy chainbridge contracts on polygon edge chain

`cb-sol-cli deploy --all --chainId 100  \
   --url http://localhost:8002 \
   --privateKey <PRIVATE_KEY> \
   --relayers 0xbE6401aaBFd8B019747205787E6FaeA82BA46C60 \
   --relayerThreshold 1 \
`

4. Register resource on pos chain and polygon edge chain

`cb-sol-cli bridge register-resource \
   --url http://localhost:8002 \
   --privateKey <PRIVATE_KEY> \
   --resourceId "0x000000000000000000000000000000e389d61c11e5fe32ec1735b3cd38c69501" \
   --bridge "0x545f55f6cC8D95307C712e68eaCcfE848bfb10d6" \
   --handler "0xA5630f58dc7422CF9B4EE763F156e771D8C8Dda4" \
   --targetContract "0xa1F5DFbd3CeAC105b173481CcCcee3D32Da877c5" \
`

`cb-sol-cli bridge register-resource \
   --url <RPCURL> \
   --privateKey <PRIVATE_KEY> \
   --resourceId "0x000000000000000000000000000000e389d61c11e5fe32ec1735b3cd38c69501" \
   --bridge "0x545f55f6cC8D95307C712e68eaCcfE848bfb10d6" \
   --handler "0xA5630f58dc7422CF9B4EE763F156e771D8C8Dda4" \
   --targetContract "0xa1F5DFbd3CeAC105b173481CcCcee3D32Da877c5" \
   --gasPrice 48678101393 \
`

5. Mint erc721 token on Polygon POS chain 

`cb-sol-cli erc721 mint   --url <RPCURL>   --privateKey <PRIVATE_KEY>   --erc721Address "0xa1F5DFbd3CeAC105b173481CcCcee3D32Da877c5"   --id 0x90   --gasPrice 43850705630 `

6. Approve token to be spent by handler contract on POS chain

`cb-sol-cli erc721 approve \
   --url <RPCURL> \
   --privateKey <PRIVATE_KEY> \
   --erc721Address "0xa1F5DFbd3CeAC105b173481CcCcee3D32Da877c5" \
   --recipient "0xA5630f58dc7422CF9B4EE763F156e771D8C8Dda4" \
   --id 0x90 \
   --gasPrice 31606193298 \
`

7. Create a deposit transaction

`cb-sol-cli erc721 deposit \
   --url <RPCURL> \
   --privateKey <PRIVATE_KEY> \
   --bridge "0x545f55f6cC8D95307C712e68eaCcfE848bfb10d6" \
   --resourceId "0x000000000000000000000000000000e389d61c11e5fe32ec1735b3cd38c69501" \
   --id 0x90 \
   --dest 100 \
   --recipient "0x5142C452a671AcbD369Fbf99307e707719C118B3" \
   --gasPrice 18670932665 \
`

8. check erc721 token on polygon edge chain

`cb-sol-cli erc721 owner \
   --url http://localhost:8005 \
   --privateKey <PRIVATE_KEY> \
   --erc721Address "0xa1F5DFbd3CeAC105b173481CcCcee3D32Da877c5" \
   --id 0x90`

### Expected behaviour

Tokens should be released in polygon edge network and  below command should return owner address
`cb-sol-cli erc721 owner \
  --url http://localhost:8005 \
  --privateKey <PRIVATE_KEY> \
  --erc721Address "0x79fd328b623157c4cf9Db77EF7645B7840A75E71" \
  --id 0x90`

### Actual behaviour
Tokens were not released in polygon edge network and `cb-sol-cli erc721 owner` command returned below error

` cb-sol-cli erc721 owner \
   --url http://localhost:8005 \
   --privateKey <PRIVATE_KEY> \
   --erc721Address "0xa1F5DFbd3CeAC105b173481CcCcee3D32Da877c5" \
   --id 0x90
`
> WARNING: Multiple definitions for safeTransferFrom
{
  e: Error: unable to execute call: execution was reverted
      at getResult (/home/ubuntu/polygon-edge/chainbridge-nft/chainbridge-deploy/cb-sol-cli/node_modules/ethers/providers/json-rpc-provider.js:40:21)
      at exports.XMLHttpRequest.request.onreadystatechange (/home/ubuntu/polygon-edge/chainbridge-nft/chainbridge-deploy/cb-sol-cli/node_modules/ethers/utils/web.js:111:30)
      at exports.XMLHttpRequest.dispatchEvent (/home/ubuntu/polygon-edge/chainbridge-nft/chainbridge-deploy/cb-sol-cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
      at setState (/home/ubuntu/polygon-edge/chainbridge-nft/chainbridge-deploy/cb-sol-cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
      at IncomingMessage.<anonymous> (/home/ubuntu/polygon-edge/chainbridge-nft/chainbridge-deploy/cb-sol-cli/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
      at IncomingMessage.emit (node:events:402:35)
      at endReadableNT (node:internal/streams/readable:1343:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    code: -32600,
    data: undefined,
    url: 'http://localhost:8005',
    body: '{"method":"eth_call","params":[{"from":"0xbE6401aaBFd8B019747205787E6FaeA82BA46C60","to":"0xa1F5DFbd3CeAC105b173481CcCcee3D32Da877c5","data":"0x6352211e0000000000000000000000000000000000000000000000000000000000000090"},"latest"],"id":44,"jsonrpc":"2.0"}',
    responseText: '{"jsonrpc":"2.0","id":44,"error":{"code":-32600,"message":"unable to execute call: execution was reverted"}}'
  }
}

### Logs
Relayer Logs:

> INFO[04-05|16:41:44] Connecting to ethereum chain...          chain=polygon-edge url=http://localhost:8005
INFO[04-05|16:41:44] Started mumbai chain                     system=core
INFO[04-05|16:41:44] Started polygon-edge chain               system=core
INFO[04-05|16:41:44] Polling Blocks...                        chain=polygon-edge block=912
INFO[04-05|16:41:44] Polling Blocks...                        chain=mumbai block=25811416
INFO[04-05|16:43:06] Handling nonfungible deposit event       chain=mumbai
INFO[04-05|16:43:06] Attempting to resolve message            chain=polygon-edge type=NonFungibleTransfer src=99 dst=100 nonce=1 rId=000000000000000000000000000000e389d61c11e5fe32ec1735b3cd38c69501
INFO[04-05|16:43:06] Creating erc721 proposal                 chain=polygon-edge src=99 nonce=1
INFO[04-05|16:43:06] Watching for finalization event          chain=polygon-edge src=99 nonce=1
INFO[04-05|16:43:06] Submitted proposal vote                  chain=polygon-edge tx=0x1c1ccca390f3c63be660fc575884889be67baf3ba6bcffaa05a35b3396708778 src=99 depositNonce=1 gasPrice=15475
INFO[04-05|16:43:11] Submitted proposal execution             chain=polygon-edge tx=0xb8f4faa90658f3fa5609f4a88228e6ca4f1dd2d12e0157d84591f7ea38c41df1 src=99 dst=100 nonce=1 gasPrice=15646

cb-sol-cli  deposit Logs;

> [erc721/deposit] Constructed deposit:
[erc721/deposit]   Resource Id: 0x000000000000000000000000000000e389d61c11e5fe32ec1735b3cd38c69501
[erc721/deposit]   Token Id: 0x90
[erc721/deposit]   len(recipient): 20
[erc721/deposit]   Recipient: 0x5142C452a671AcbD369Fbf99307e707719C118B3
[erc721/deposit]   Raw: 0x000000000000000000000000000000000000000000000000000000000000009000000000000000000000000000000000000000000000000000000000000000145142C452a671AcbD369Fbf99307e707719C118B3
[erc721/deposit] Creating deposit to initiate transfer!
Waiting for tx: 0xe937aff4c5c950ec1043ef0ffc3bbff0c457f84d022d3b27f455ff949dc194e1...

**Comment by Kourin1996** [comment]
@vineetaparodkar Thank you for your question. There's one thing I'd like to ask you about:

Did you call `set-burn` to Bridge contract and `add-minter` to ERC721 contract on Edge chain? Before bridging, ERC721 handler on destination chain must have the NFT you want to transfer OR an ability to mint new NFT, of course

I saw the flows you did but you seem not to have given the ability to ERC721 handler. In this case, you need to mint NFT with the same ID and ERC721 handler must have it before you start bridge process.

An alternative way is to switch mode to mint mode and give minting role in ERC721 to ERC721 Handler. In this case, NFT will be minted when execution transaction is processed on destination chain. You can switch and give role by the following steps:

```bash
# Let ERC721 Handler mint new NFT on execution
$ cb-sol-cli bridge set-burn \
  --url [EDGE_JSON_RPC_URL] \
  --privateKey [ADMIN_ACCOUNT_PRIVATE_KEY] \
  --bridge "[BRIDGE_CONTRACT_ADDRESS]" \
  --handler "[ERC721_HANDLER_CONTRACT_ADDRESS]" \
  --tokenContract "[ERC721_CONTRACT_ADDRESS]"

# Grant minter role to ERC721 Handler contract
$ cb-sol-cli erc721 add-minter \
  --url [EDGE_JSON_RPC_URL] \
  --privateKey [ADMIN_ACCOUNT_PRIVATE_KEY] \
  --erc721Address "[ERC721_CONTRACT_ADDRESS]" \
  --minter "[ERC721_HANDLER_CONTRACT_ADDRESS]"
```

Please check for more details: https://edge-docs.polygon.technology/docs/additional-features/chainbridge/setup-erc721-transfer#optional-make-contracts-mintableburnable

**Comment by vineetaparodkar** [comment]
> Did you call set-burn to Bridge contract and add-minter to ERC721 contract on Edge chain? 

I have not called set-burn, add-minter on edge chain above setup was done with default lock/release mode.


@Kourin1996 , Docs here mention about lock release mode https://edge-docs.polygon.technology/docs/additional-features/chainbridge/setup-erc20-transfer 

> (1) Lock/Release mode
> 
> Source chain: The tokens you are sending will be locked in the ERC20 Handler Contract
> Destination chain: The same amount of tokens as you sent in the source chain would be unlocked and transferred from the **ERC20 Handler contract to the recipient account in the destination chain**.
> 

1. This was the default mode used in above setup. What steps needs to be executed inorder to make this transfer from ERC721handler contract to recepient account in destination chain on deposit event? Need to mint NFT 90 on POS chain and also on destination chain (with holder being erc721 handler on polygon edge chain)?

2. How to mint erc721 token on erc721 handler with cb-sol-cli? Do we have to mint it with admin private key and then approve it to be spent by ERC721 handler contract?

Above ERC721 transfer works with burn/mint mode after executing set-burn and add-minter commands.

**Comment by Kourin1996** [comment]
@vineetaparodkar 

1. Yes, you're right. You needed to mint NFT on Edge chain (destination chain) and pass it to ERC721 handler. So you need to execute the below command between step 5 and 6.

```
# Mint same NFT on Edge chain

cb-sol-cli erc721 mint --url <EDGE_RPC_URL> --privateKey <ADMIN_PRIVATE_KEY> --erc721Address "<EDGE_ERC721_ADDRESS>" --id 0x90 --gasPrice 43850705630
```

2. Yes. So the account that has deployed ERC721 contract has a minter role, then you can mint new NFT from admin account. You can do that with the above command.

**Comment by vineetaparodkar** [comment]
Closing this issue as deposit/transfers of NFT is working as expected with above suggestions
