### ISSUE TITLE
ERC20 deposit failing with ChainBridge

### ISSUE THREAD

**Issue by spunkyshooter** [0xPolygon/polygon-edge#493]
### Description
I was going through the [this](https://edge-docs.polygon.technology/docs/additional-features/chainbridge/setup-erc20-transfer/) doc trying to transfer Chainbridge sample ERC20 token between Mumbai Polygon POS chain and local network setup with polygon edge. 

I was able to register the resource, mint ERC20 tokens, approve them, the last `deposit` command also works fine, it logs transaction hash and closes.

But when investigated the transaction hash on polygonscan, it shows the error status: `"Fail with error 'Incorrect fee supplied'"` event though the fee is in right format and reasonable as per gas-station.

Transaction Reference: https://mumbai.polygonscan.com/tx/0x5c58c88457b657add1ef27bfbdaba999e73d36263dd69c1c4424bf236d4cf0ff

Contract Address:
https://mumbai.polygonscan.com/address/0x7fad470b67ef6759890ddf5e1ac1e77f90e4b864 

### Your environment

OS and version: ubuntu
version of the Polygon Edge : NA
branch that causes this issue: NA

### Steps to reproduce

1. Created a polygon edge local network as per [documentation](https://edge-docs.polygon.technology/docs/get-started/set-up-ibft-locally/)
2. Deployed chainbridge contracts on Polygon POS chain and Polygon-SideChain
3. Follow this [doc](https://edge-docs.polygon.technology/docs/additional-features/chainbridge/setup-erc20-transfer/) to transfer ERC20 Tokens
3.1 Register the resource Id on Polygon POS chain:
```
cb-sol-cli bridge register-resource \
  --url <ALCHEMY_URL> \
  --privateKey <PRIVATE_KEY> \
  --resourceId "0x000000000000000000000000000000c76ebe4a02bbc34786d860b355f5a5ce00" \
  --bridge "0x7FAd470b67ef6759890DDf5e1Ac1e77f90e4B864" \
  --handler "0x2285D00a7d0F661278b059a97882BbEc355639ad" \
  --targetContract "0xD4d5C111FceC382Ed5cB858F76cA4bC719FC571e" \
  --gasPrice 60000000000
```
3.2 Register the resourceId on Polygon SideChain
```
cb-sol-cli bridge register-resource \
  --url http://localhost:10002 \
  --privateKey <PRIVATE_KEY> \
  --resourceId "0x000000000000000000000000000000c76ebe4a02bbc34786d860b355f5a5ce00" \
  --bridge "0xA36fAFf125511C04B298769e53Da403982DD3688" \
  --handler "0xc81B47f9Fd5D276E88B0f167c2079ADb722fd9e6" \
  --targetContract "0xA1132596355cAB27eA3b52962846E2F194070aBe" \
  --gasPrice 53644064086
``` 
3.3 Approve transfer from the account by ERC20 Handler
```
cb-sol-cli erc20 approve \
  --url <ALCHEMY_URL> \
  --privateKey <PRIVATE_KEY>\
  --erc20Address "0xD4d5C111FceC382Ed5cB858F76cA4bC719FC571e" \
  --recipient "0x2285D00a7d0F661278b059a97882BbEc355639ad" \
  --amount 500 \
  --gasPrice 43707910921
```
3.4 Start transfer from Polygon PoS to Polygon Edge chain
```
cb-sol-cli erc20 deposit \
  --url <ALCHEMY_URL> \
  --privateKey <PRIVATE_KEY> \
  --amount 10 \
   --dest 100 \
  --bridge "0x7FAd470b67ef6759890DDf5e1Ac1e77f90e4B864" \
  --recipient "0x424469E56Bf6C6c80A626f6E76A5E66EddF02612" \
  --resourceId "0x000000000000000000000000000000c76ebe4a02bbc34786d860b355f5a5ce00" \
--gasPrice 60000000000
```

Response: (Successfully closes without any issues)
```
[erc20/deposit] Constructed deposit:
[erc20/deposit]   Resource Id: 0x000000000000000000000000000000c76ebe4a02bbc34786d860b355f5a5ce00
[erc20/deposit]   Amount: 0x8ac7230489e80000
[erc20/deposit]   len(recipient): 20
[erc20/deposit]   Recipient: 0x424469E56Bf6C6c80A626f6E76A5E66EddF02612
[erc20/deposit]   Raw: 0x0000000000000000000000000000000000000000000000008ac7230489e800000000000000000000000000000000000000000000000000000000000000000014424469E56Bf6C6c80A626f6E76A5E66EddF02612
[erc20/deposit] Creating deposit to initiate transfer!
Waiting for tx: 0x5c58c88457b657add1ef27bfbdaba999e73d36263dd69c1c4424bf236d4cf0ff...
```

### Expected behaviour

Transaction shouldn't not fail

### Actual behaviour

Transaction fails showing "Incorrect fee supplied"

https://mumbai.polygonscan.com/tx/0x5c58c88457b657add1ef27bfbdaba999e73d36263dd69c1c4424bf236d4cf0ff

**Comment by Kourin1996** [comment]
@spunkyshooter Hi, This error appears when you set the fee on deploying but you don't set the same value in deposit transaction. Did you give `--fee` when you called `cb-sol-cli deploy`?

**Comment by spunkyshooter** [comment]
> @spunkyshooter Hi, This error appears when you set the fee on deploying but you don't set the same value in deposit transaction. Did you give `--fee` when you called `cb-sol-cli deploy`?

No, I hadn't  set --fee at all.

**Comment by Kourin1996** [comment]
@spunkyshooter 

Right now I checked the fee in your contract `0x7FAd470b67ef6759890DDf5e1Ac1e77f90e4B864` in Mumbai by the code like this

```js
async function main() {
  const [signer] = await ethers.getSigners();

  const contract = new ethers.Contract(
    "0x7FAd470b67ef6759890DDf5e1Ac1e77f90e4B864",
    abi,
    signer
  );

  console.log(await contract._fee());
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });
```

then it returns this value

```bash
BigNumber { value: "5925192625" }
```

so fee is set in your contract

**Comment by Kourin1996** [comment]
@spunkyshooter I have no idea because I don't know how you've deployed this contract. But if you want to change fee, I recommend you use the below command to change fee

```bash
$ cb-sol-cli admin set-fee --bridge <BRIDGE_ADDRESS> --fee 0 --url <JSON_RPC_URL> --privateKey <PRIVATE_KEY>
```

**Comment by spunkyshooter** [comment]
> @spunkyshooter
> 
> Right now I checked the fee in your contract `0x7FAd470b67ef6759890DDf5e1Ac1e77f90e4B864` in Mumbai by the code like this
> 
> ```js
> async function main() {
>   const [signer] = await ethers.getSigners();
> 
>   const contract = new ethers.Contract(
>     "0x7FAd470b67ef6759890DDf5e1Ac1e77f90e4B864",
>     abi,
>     signer
>   );
> 
>   console.log(await contract._fee());
> }
> 
> main()
>   .then(() => process.exit(0))
>   .catch((error) => {
>     console.error(error);
>     process.exit(1);
>   });
> ```
> 
> then it returns this value
> 
> ```shell
> BigNumber { value: "5925192625" }
> ```
> 
> so fee is set in your contract

@Kourin1996 

This could have been set internally by chainbridge. There is no option to pass --fee in `cb-sol-cli` at all and I hadn't set in any other way. 
https://github.com/ChainSafe/chainbridge-deploy/blob/main/cb-sol-cli/docs/erc20.md#deposit

Is there any way to move forward ?

**Comment by Kourin1996** [comment]
@spunkyshooter I checked the deploy contract (https://mumbai.polygonscan.com/tx/0xe0fd13fccf4f6a733b2ce0663c2f61a4551149d4e75847e0d572df26d62c974b) and initial fee is set to the same value I showed you above. You can see constructor parameters after bytecode in contract creation transaction input.

If you've not set fee when running `cb-sol-cli deploy` surely, please ask ChainBridge team.

**Comment by spunkyshooter** [comment]
> @spunkyshooter I checked the deploy contract (https://mumbai.polygonscan.com/tx/0xe0fd13fccf4f6a733b2ce0663c2f61a4551149d4e75847e0d572df26d62c974b) and initial fee is set to the same value I showed you above. You can see constructor parameters after bytecode in contract creation transaction input.
> 
> If you've not set fee when running `cb-sol-cli deploy` surely, please ask ChainBridge team.

@Kourin1996 
Sure, Thanks for the help. Closing it.

**Comment by Kourin1996** [comment]
By the way, there is no explanation about `--fee` because this page is for `cb-sol-cli erc20` command. They explain about `--fee` on this page https://github.com/ChainSafe/chainbridge-deploy/blob/main/cb-sol-cli/docs/deploy.md

**Comment by sahil-springworks** [comment]
@Kourin1996 , could you please explain me how did you write the script to check out the fee for the contract.

I have two main questions ->
1. What and how did you use the value of `abi` ?
2. The `contract._fee()` function does not seem to exist when I'm trying to replicate your script.

Would you please help me figure out how you set up the script?

**Comment by Kourin1996** [comment]
@sahil-springworks 

You can get the ABI of ChainBridge contracts by building solidity files. Please clone it and build locally.

```
$ git clone https://github.com/ChainSafe/chainbridge-solidity.git
$ cd chainbridge-solidity
$ npm i && npm run build
```

You can get the ABI in the json `artifacts/contracts/Bridge.sol/Bridge.json` after you build contract.

`_fee` is public field in Bridge contract but you can read this value by calling like function. Please load ABI before calling this method in JavaScript.

The script I showed above is for Hardhat. Please set up hardhat project. Or actually you don't need to set signer in order to query view function. You can run script in any JavaScript environment where it's possible to use ethers.js

```js
  const contract = new ethers.Contract(
    "0x7FAd470b67ef6759890DDf5e1Ac1e77f90e4B864",
    abi
  );

  console.log(await contract._fee());
```

**Comment by sahil-springworks** [comment]
Thanks for the valuable info @Kourin1996 :)
