### ISSUE TITLE
Loadbot crash: concurrent map writes

### ISSUE THREAD

**Issue by kirillt** [0xPolygon/polygon-edge#494]
### Description

Sometimes (1 of many times) such error log might be generated.

### Your environment

* Fedora 32
* v0.1.0 (f59d3ca12586a910b3f8744ffbefdbbaa19a9e02)
* develop

### Steps to reproduce

Run Loadbot in plain value transactions mode (parameters: 3000 txs, value 0x100, 600 tps).

### Expected behaviour

Something like:
```
=====[LOADBOT RUN]=====

[COUNT DATA]
Transactions submitted = 3000
Transactions failed    = 0

[APPROXIMATE TPS]
Approximate number of transactions per second = 111

[TURN AROUND DATA]
Average transaction turn around = 11.161490s
Fastest transaction turn around = 2.002610s
Slowest transaction turn around = 22.024990s
Total loadbot execution time    = 27.030140s
...
```

### Actual behaviour

Tell us what happens instead

```
fatal error: concurrent map writes
fatal error: concurrent map writes

goroutine 6185 [running]:
runtime.throw(0x1a6b012, 0x15)
        /usr/lib/golang/src/runtime/panic.go:1117 +0x72 fp=0xc0044e1ea8 sp=0xc0044e1e78 pc=0x439012
runtime.mapassign_fast64(0x16bb2c0, 0xc00059d5c0, 0x155, 0xc004486000)
        /usr/lib/golang/src/runtime/map_fast64.go:176 +0x325 fp=0xc0044e1ee8 sp=0xc0044e1ea8 pc=0x414925
github.com/0xPolygon/polygon-edge/command/loadbot.(*Loadbot).calculateGasMetrics.func1(0x100000000000000, 0xc00024a690)
        /root/polygon-edge/command/loadbot/helper.go:92 +0xfe fp=0xc0044e1f78 sp=0xc0044e1ee8 pc=0x150f7be
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0035a69c0, 0xc0035a6b70)
        /root/polygon-edge/vendor/golang.org/x/sync/errgroup/errgroup.go:57 +0x59 fp=0xc0044e1fd0 sp=0xc0044e1f78 pc=0xf5e2d9
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0044e1fd8 sp=0xc0044e1fd0 pc=0x46f581
created by golang.org/x/sync/errgroup.(*Group).Go
        /root/polygon-edge/vendor/golang.org/x/sync/errgroup/errgroup.go:54 +0x66
```

### Logs

Full log of my experiment (running loadbot sequentially on 37 nodes, one by one).
[hetzner-37-cpx51.log](https://github.com/0xPolygon/polygon-edge/files/8459576/hetzner-37-cpx51.log)

### Proposed solution

First 24 runs succeeded, 25th run failed with this error.

**Comment by zivkovicmilos** [comment]
Hey @kirillt,

Thank you for raising the issue 🙏 

I've managed to narrow down the problem and am working on a fix that will be out soon 👍 

I'll update you here once the PR is out.

**Comment by kirillt** [comment]
Extreme case: reproduces consistently with `--block-time` set to `0`.
