### ISSUE TITLE
ERC20 tokens not released in Edge Chain from erc20 deposit command.

### ISSUE THREAD

**Issue by spunkyshooter** [0xPolygon/polygon-edge#496]
### Description

Chainbridge sample ERC20 token is transferred between Polygon POS chain and local network setup with polygon edge. ERC 20 token is deposited and proposal is executed at relayer but tokens are not released in Polygon edge network.

### Your environment

* OS and version Ubuntu 20.04
* version of the Polygon Edge v0.3.2
* branch that causes this issue: development branch

### Steps to reproduce

- chainbridge's default **Lock-Release mode** is used in below setup

1. Create a polygon edge local network
2. Deploy contracts on Edge-SideChain.
```
cb-sol-cli deploy --all --chainId 100 \
--url http://localhost:10002 \
--privateKey <PRIVATE_KEY> \
--relayers 0xfCB8f249fC313eBEbFd626982B61f4435898327D \
--relayerThreshold 1 \
--gasPrice 4000000

```
3. Deploy contracts on Polygon POS chain.
```
cb-sol-cli deploy --all --chainId 99 \
  --url <ALCHEMY_URL> \
  --privateKey <PRIVATE_KEY> \
  --relayers 0xfCB8f249fC313eBEbFd626982B61f4435898327D \
  --relayerThreshold 1 \
  --gasPrice 46000000000 \
  --gasLimit 6000000
```
4. Register ERC20 ResourceId on Polygon POS Chain.
```
 cb-sol-cli bridge register-resource \
  --url <ALCHEMY_URL> \
  --privateKey <PRIVATE_KEY>\
  --resourceId "0x000000000000000000000000000000c76ebe4a02bbc34786d860b355f5a5ce00" \
  --bridge "0xcC33Ab683a1dd1E74a0ff50947A613f0f548da5c" \
  --handler "0x2A57412B4d058492Fe5B1eaE9b76444795C5C681" \
  --targetContract "0xFb659E2714013D7bC877f1916E6617325b9FE965" \
  --gasPrice 46000000000
```
5. Register ERC20 ResourceId on Edge-Chain.
```
cb-sol-cli bridge register-resource \
  --url http://localhost:10002 \
  --privateKey <PRIVATE_KEY> \
  --resourceId "0x000000000000000000000000000000c76ebe4a02bbc34786d860b355f5a5ce00" \
  --bridge "0xA36fAFf125511C04B298769e53Da403982DD3688" \
  --handler "0xc81B47f9Fd5D276E88B0f167c2079ADb722fd9e6" \
  --targetContract "0xA1132596355cAB27eA3b52962846E2F194070aBe"
```
6. Mint Erc20 tokens on Polygon POS chain.
```
cb-sol-cli erc20 mint \
  --url <ALCHEMY_URL> \
  --privateKey <PRIVATE_KEY> \
  --erc20Address "0xFb659E2714013D7bC877f1916E6617325b9FE965" \
  --amount 1000
```
7. Approve transfer from the account by ERC20 Handler
```
cb-sol-cli erc20 approve \
  --url <ALCHEMY_URL> \
  --privateKey <PRIVATE_KEY> \
  --erc20Address "0xFb659E2714013D7bC877f1916E6617325b9FE965" \
  --recipient "0x2A57412B4d058492Fe5B1eaE9b76444795C5C681" \
  --amount 500 \
  --gasPrice 46000000000
```
8. Start Transfer by Depositing
```
cb-sol-cli erc20 deposit \
  --url <ALCHEMY_URL> \
  --privateKey <PRIVATE_KEY> \
  --amount 100 \
  --dest 100 \
  --bridge "0xcC33Ab683a1dd1E74a0ff50947A613f0f548da5c" \
  --recipient "0xF6c7e668481f6ef02601f3afA6a614fEcCAa3deB" \
  --resourceId "0x000000000000000000000000000000c76ebe4a02bbc34786d860b355f5a5ce00" \
--gasPrice 46000000000
```
Txn: [0x07128d8bc5b0059fd377bda5ad32d059dc2e1c75c14084a14f259779a6163fc5](https://mumbai.polygonscan.com/tx/0x07128d8bc5b0059fd377bda5ad32d059dc2e1c75c14084a14f259779a6163fc5)

9. Check the Balance on Edge-Chain.
```
cb-sol-cli erc20 balance \
--url http://localhost:10002 \
--privateKey <PRIVATE_KEY> \
 --erc20Address "0xA1132596355cAB27eA3b52962846E2F194070aBe" \
 --address "0xF6c7e668481f6ef02601f3afA6a614fEcCAa3deB"
```

### Expected behaviour
Tokens should be released and Account balance be updated:
```[erc20/balance] Account 0xF6c7e668481f6ef02601f3afA6a614fEcCAa3deB has a balance of 100.0```

### Actual behaviour
Balance is 0, new tokens aren't released on Edge-Chain. 

```[erc20/balance] Account 0xF6c7e668481f6ef02601f3afA6a614fEcCAa3deB has a balance of 0.0```

### Logs

Deposit Logs:
```
[erc20/deposit] Constructed deposit:
[erc20/deposit]   Resource Id: 0x000000000000000000000000000000c76ebe4a02bbc34786d860b355f5a5ce00
[erc20/deposit]   Amount: 0x056bc75e2d63100000
[erc20/deposit]   len(recipient): 20
[erc20/deposit]   Recipient: 0xF6c7e668481f6ef02601f3afA6a614fEcCAa3deB
[erc20/deposit]   Raw: 0x0000000000000000000000000000000000000000000000056bc75e2d631000000000000000000000000000000000000000000000000000000000000000000014F6c7e668481f6ef02601f3afA6a614fEcCAa3deB
[erc20/deposit] Creating deposit to initiate transfer!
Waiting for tx: 0x07128d8bc5b0059fd377bda5ad32d059dc2e1c75c14084a14f259779a6163fc5...
```

Relayer Logs:
```
INFO[04-11|22:17:49] Handling fungible deposit event          chain=mumbai dest=100 nonce=2                             
INFO[04-11|22:17:57] Attempting to resolve message            chain=polygon-edge type=FungibleTransfer src=99 dst=100 nonce=2 rId=000000000000000000000000000000c76ebe4a02bbc34786d860b355f5a5ce00                                              
INFO[04-11|22:17:57] Creating erc20 proposal                  chain=polygon-edge src=99 nonce=2                         
INFO[04-11|22:17:57] Watching for finalization event          chain=polygon-edge src=99 nonce=2                        
INFO[04-11|22:17:57] Submitted proposal vote                  chain=polygon-edge tx=0xff56a254b334bf3a1e0868f7b6f0b5797ea91d616acbfaecf467366043ed1994 src=99 depositNonce=2 gasPrice=1
INFO[04-11|22:18:22] Submitted proposal execution             chain=polygon-edge tx=0x3f2fe7f1631d60bc139c2c63553915750e3fe64976f6b1634fb57307cdd3ce74 src=99 dst=100 nonce=2 gasPrice=66 
```

**Comment by Kourin1996** [comment]
@spunkyshooter Hello, Thank you for the question. 

May I check this firstly?
ERC20 Handler in Polygon Edge chain has enough tokens to release? As I mentioned at https://github.com/0xPolygon/polygon-edge/issues/492, Handler contract in destination chain must have enough tokens to release for lock-release mode. Could you tell me how much tokens ERC20 handler has?

If you don't have any ERC20 tokens in ERC20 Handler of Polygon Edge chain. Please mint new token and transfer to ERC20 Handler

**Comment by spunkyshooter** [comment]
Thanks @Kourin1996 :)

As rightly pointed out, the issue was with the ERC20Handler not having the ERC20 to release.

The deposit was successful and the tokens were released after I minted the tokens from admin account and send those tokens to ERC0Handler Contract address.

**Comment by spunkyshooter** [comment]
On a side Note, I feel docs should be updated for the rookies to not face this issue.
