### ISSUE TITLE
Multiple targets mode for LoadBot

### ISSUE THREAD

**Issue by kirillt** [0xPolygon/polygon-edge#501]
#feature #question
Would it be useful to implement remote mode for the stress testing module?

This would look like an extra flag `--targets` receiving a list of `IP:PORT` pairs and sending transactions to all specified nodes in round-robin or random way. Such feature should provide less "stressful" but more realistic results since load would be evenly distributed between many nodes.

It might be also a good idea to separate the tool into separate module in this case, since machine used for stress test invocation doesn't have to run blockchain node itself.

**Comment by STZeed** [comment]
I Like it
