### ISSUE TITLE
Unknown command "dev" for ""

### ISSUE THREAD

**Issue by maxifom** [0xPolygon/polygon-edge#506]
### Description

Describe your issue in as much detail as possible here

### Your environment

* OS and version: Ubuntu 21.10
* version of the Polygon Edge: v0.3.3-0.20220414104354-a61e3922bd56
* branch that causes this issue

### Steps to reproduce
go install github.com/0xPolygon/polygon-edge@develop
polygon-edge dev

### Expected behaviour
Starts dev server, bypassing consensus

### Actual behaviour
```
➜  ~ polygon-edge dev
Error: unknown command "dev" for ""
Run ' --help' for usage.
unknown command "dev" for ""

```

### Proposed solution

Remove dev command from https://edge-docs.polygon.technology/docs/get-started/cli-commands ? (is it available anymore?)

**Comment by Kourin1996** [comment]
@maxifom Hello, Thank you for reporting!

`dev` command described on the page has been removed already. You can use same functionality by these steps:

```bash
$ polgon-edge secrets init --data-dir test-chain-1

$ polgon-edge genesis --consensus dev --bootnode /ip4/127.0.0.1/tcp/11001/p2p/<Libp2p NodeID>

$ polgon-edge server --chain ./genesis.json --data-dir ./test-chain-1 --grpc :11000 --libp2p :11001 --jsonrpc 0.0.0.0:11002 --seal
```

And also I've created PR to remove descriptions about this command in the docs repo.

I appreciate your help.

**Comment by zivkovicmilos** [comment]
Closing this issue as we've opened up a PR for the docs, and it's irrelevant for Edge now:

https://github.com/0xPolygon/polygon-edge-docs/pull/82
