### ISSUE TITLE
Could not parse NAT IP address

### ISSUE THREAD

**Issue by flobrown** [0xPolygon/polygon-edge#51]
### Description

Describe your issue in as much detail as possible here

### Your environment

* tried it on macOS 11.4 (M1) and "5.4.0-1047-azure #49-Ubuntu" 20.04 LTS
* go version mac: go version go1.16.4 darwin/amd64 
* go version ubuntu: go version go1.13.8 linux/amd64
* same error on both machines
* sdk version: 0.1.0-dev
* develop branch

### Steps to reproduce

When I try to start the network after following the docs with:
go run main.go server --data-dir ./test-chain-1 --chain genesis.json --grpc :10000 --libp2p :10001 --jsonrpc :10002 --seal
i get the error message:
Could not parse NAT IP address
exit status 1

### Expected behaviour

The nodes should start

### Actual behaviour

Could not parse NAT IP address
exit status 1

### Logs

My genesis.json (with x-outed Node IDs):
{
    "name": "test-chain-",
    "genesis": {
        "nonce": "0x0000000000000000",
        "timestamp": "0x0",
        "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000f858f85494ead46e992b0aae3260b3962f90b7fc5aab4e909e948636bfa3b6c05e9f6297aa6a9112999ef0a91b1694b768bc1f50755432b3e439c240cd86c1c0b8d3de94f1ddce413a857320ac088089831860b330e9e60980c0",
        "gasLimit": "0x1388",
        "difficulty": "0x1",
        "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "coinbase": "0x0000000000000000000000000000000000000000",
        "alloc": {},
        "number": "0x0",
        "gasUsed": "0x0",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
    },
    "params": {
        "forks": {
            "homestead": 0,
            "byzantium": 0,
            "constantinople": 0,
            "petersburg": 0,
            "istanbul": 0,
            "EIP150": 0,
            "EIP158": 0,
            "EIP155": 0
        },
        "chainID": 100,
        "engine": {
            "ibft": {}
        }
    },
    "bootnodes": [
        "/ip4/127.0.0.1/tcp/10001/p2p/16Uiu2mxxxxxxxxxxxxxx",
        "/ip4/127.0.0.1/tcp/20001/p2p/16Uiu2xxxxxxxxxxxx",
        "/ip4/127.0.0.1/tcp/30001/p2p/16Uiu2xxxxxxxxx",
        "/ip4/127.0.0.1/tcp/40001/p2p/16Uiu2xxxxxxxxxxxx"
    ]
}

### Proposed solution

Most likely the error message comes from the server/config.go line 90-92. Seems the IP cannot be parsed.

**Comment by flobrown** [comment]
Ok, so the issue is that the var c.Network.NatAddr does not contain any value (= emtpy string) on my machines. When i exchange the value with an hard-coded IP addr, the server starts up flawlessly. Strange thing is, that this happens on both machines. 
command/server/config.go Line 90-92: 
if conf.Network.NatAddr = net.ParseIP("127.0.0.1"); conf.Network.NatAddr == nil {
			return nil, errors.New("Could not parse NAT IP address")
		}

**Comment by fastepic** [comment]
Hi, The same error - Ubuntu os. After you suggestion - works.

**Comment by lazartravica** [comment]
@fastepic @floberlin This has been fixed with the https://github.com/0xPolygon/polygon-sdk/pull/60

Thank you for your help and patience 🙏
