### ISSUE TITLE
Polygon-Edge Server Always Listening on Ipv6 

### ISSUE THREAD

**Issue by Saif-Uz-Zaman** [0xPolygon/polygon-edge#511]
### Description

Polygon-Edge Server RPC Port Always Listening on Ipv6 but I need to let it listening on Ipv4 as well.

### Your environment

* Ubuntu 20.04 on AWS
*  v0.3.3
* tag-v.0.3.3

### Steps to reproduce

* On that server `telnet tlpn`
```
v-Q Send-Q Local Address           Foreign Address         State       PID/Program name                 
tcp        0      0 127.0.0.1:9632          0.0.0.0:*               LISTEN      20312/polygon-edge  
tcp        0      0 0.0.0.0:1478            0.0.0.0:*               LISTEN      20312/polygon-edge  
tcp6       0      0 :::8545                :::*                    LISTEN      20312/polygon-edge
```

### Expected behaviour

```
v-Q Send-Q Local Address           Foreign Address         State       PID/Program name                 
tcp        0      0 127.0.0.1:9632          0.0.0.0:*               LISTEN      20312/polygon-edge  
tcp        0      0 0.0.0.0:1478            0.0.0.0:*               LISTEN      20312/polygon-edge
tcp4       0      0  0 0.0.0.0:8545        0 0.0.0.0:*                    LISTEN      20312/polygon-edge
tcp6       0      0 :::8545                :::*                    LISTEN      20312/polygon-edge
```

**Comment by ZeljkoBenovic** [comment]
Hi @Saif-Uz-Zaman ,

thank you for reaching out.

This information can be deceiving, it says tcp6 :::8545, but it actually works for both ipv4 and ipv6.
This means that, by default, JSON-RPC API will bind to all available ipv4 and ipv6 interfaces, even though it says tcp6.

You can confirm this by simply running the `curl` command against this ip:port.
`curl <server_ipv4>:8545` and you should get a responce `Polygon Edge JSON-RPC`, which means that JSON-RPC binding on IPv4 address is working properly.

I'm closing this issue.
Feel free to open a new one if you're still facing some troubles with JSON-RPC API.
