### ISSUE TITLE
Transaction Failed

### ISSUE THREAD

**Issue by Saif-Uz-Zaman** [0xPolygon/polygon-edge#521]
### Description

I have created a 5 node ploygon-edge on AWS with t3.xlarge, I have also premined some MATIC with two address, One is with 70 million MATIC and another is with 2 million MATIC. I have also tested an another cluster with 2000 premined matic, which is actually served my purpose. But when I create a cluster with muliple premined account and with 70 million and 2 million account, the problem arises.

### Your environment

* Ubuntu 20.04 (AWS EC2, t3.xlarge, 4cpu, 16 gb Ram)
* 0.3.3
* 0.3.3

### Logs

```
[ERROR] polygon.txpool: failed to add tx: err="already known"
[ERROR] polygon.dispatcher: failed to dispatch: method=eth_sendRawTransaction err="already known"
[ERROR] polygon.txpool: failed to add tx: err="already known"
[ERROR] polygon.dispatcher: failed to dispatch: method=eth_sendRawTransaction err="already known"
[ERROR] polygon.txpool: failed to add tx: err="already known"
[ERROR] polygon.dispatcher: failed to dispatch: method=eth_sendRawTransaction err="already known"
[ERROR] polygon.txpool: failed to add tx: err="already known"
[ERROR] polygon.dispatcher: failed to dispatch: method=eth_sendRawTransaction err="already known"
[ERROR] polygon.txpool: failed to add tx: err="already known"
[ERROR] polygon.dispatcher: failed to dispatch: method=eth_sendRawTransaction err="already known"
```

**Comment by zivkovicmilos** [comment]
Hey @Saif-Uz-Zaman,

What kinds of transactions are you sending?

These errors are unrelated to your premining. How did you premine funds?
Did you premine the native currency of the Polygon Edge network?

**Comment by ThannDev** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by zivkovicmilos** [comment]
@ThannDev,

This Github repo is the only official channel for Polygon Edge related questions and issues.

**Comment by zivkovicmilos** [comment]
Closing issue due to a lack of activity.

@Saif-Uz-Zaman please open a new issue with more details if you are still experiencing it.
