### ISSUE TITLE
polygon-edge txpool add --nonce 0 --from 0x1010101010101010101010101010101010101010 --to 0x0000000000000000000000000000000000000010 --value 0x100

### ISSUE THREAD

**Issue by little-evan-yin** [0xPolygon/polygon-edge#539]
### Description

go with the documents, when deal with "Working with a node " --> "Step4：Send a transfer transaction" throw an error "unknown flag: --nonce"

### Your environment

* OS and version
* centos8
* version of the Polygon Edge
* v0.1.0
* branch that causes this issue
* develop

### Steps to reproduce

* Tell us how to reproduce this issue <br />
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Logs

Please paste any logs here that demonstrate the issue, if they exist

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

**Comment by 0xAleksaOpacic** [comment]
Hi @little-evan-yin 
Thank you for opening an issue
We have removed this method from our CLI. We already have an issue in our docs repo. https://github.com/0xPolygon/polygon-edge-docs/issues/80. Fix is pushed and in review.

I am going to close this one, so we do not have duplicates
