### ISSUE TITLE
Event logs transaction hash is null

### ISSUE THREAD

**Issue by IanDorion** [0xPolygon/polygon-edge#542]
### Description

After a transaction, when looking at the event, the transaction hash is null

### Your environment

* Unbuntu(WSL2) Docker container
* latest
* develop

### Steps to reproduce

Picking up the hash using go-ethereum;

```
for {
		select {
		case myEventSubErr := <-depositsSub.Err():
			log.Fatal("error in deposits event subscription: ", myEventSubErr)
		case myEvent := <-deposits:
			fmt.Printf(myEvent.Raw.TxHash)
		}
	}
	// output 0x0000000000000000000000000000000000000000000000000000000000000000
	
```

### Expected behaviour

I should receive a valid transaction hash

### Actual behaviour

receive a null transaction hash

**Comment by 0xAleksaOpacic** [comment]
Hi @IanDorion , 
We have already created the fix for this issue here is the PR https://github.com/0xPolygon/polygon-edge/pull/528.
We expect  to merge it soon.

**Comment by IanDorion** [comment]
Hello @Aleksao998,
Thank you for you quick response.

**Comment by 0xAleksaOpacic** [comment]
Hi @IanDorion 
The fix is pushed into the develop branch. And we are creating release today.
Because it is breaking change we advise pulling the latest code on all active nodes.

**Comment by IanDorion** [comment]
Thank you very much!
