### ISSUE TITLE
 too many arguments - looks like problem when arguments add to subcommand 

### ISSUE THREAD

**Issue by fastepic** [0xPolygon/polygon-edge#56]
### Description
go run main.go peers list --grpc-address localhost:30000

works correct

go run main.go ibft propose --add 0x2a70a391e65a59e03bf3661502c8a79a1d267ab3 --grpc-address localhost:30000

too many arguments

### Your environment

* OS and version
* version of the Polygon SDK
* branch that causes this issue

### Steps to reproduce

* Tell us how to reproduce this issue <br />
* Where the issue is, if you know <br />
* Which commands triggered the issue, if any

### Expected behaviour

Tell us what should happen

### Actual behaviour

Tell us what happens instead

### Logs

Please paste any logs here that demonstrate the issue, if they exist

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

**Comment by Vuksan** [comment]
Hi @fastepic, thank you for the issue!

I was able to reproduce it. We'll fix it asap.
As a workaround, you should be able to run the command by specifying `--grpc-address` flag first.

**Comment by Vuksan** [comment]
This is now fixed. Try out the `go run main.go ibft propose --help` command to see how it's used.
