### ISSUE TITLE
Peer network dicovery error

### ISSUE THREAD

**Issue by isingh108** [0xPolygon/polygon-edge#572]
[ERROR] polygon.network.discovery: Unable to execute bootnode peer discovery, %w: EXTRA_VALUE_AT_END="unable to create new discovery client connection, peer disconnected before the discovery client was initialized"
  

Please help me on this

**Comment by zivkovicmilos** [comment]
Hey @iqbalsingh108,

Please use the issue template to open up an issue 🙏 

This entire description lacks any kind of context we need to provide assistance with problems you're facing.
