### ISSUE TITLE
Implement Eth_debugTraceTransaction

### ISSUE THREAD

**Issue by samisbakedham** [0xPolygon/polygon-edge#578]

**Comment by zivkovicmilos** [comment]
Hey @samisbakedham,

Thank you for reaching out.

Currently, we still don't have support for `debug` endpoints. We realize that these are extremely helpful for developers, and so we're planning on adding this support in the near future.

Stay tuned for updates regarding this feature set 🙏 

Please check [this discussion](https://github.com/0xPolygon/polygon-edge/discussions/280) as well that has been started by the community.
