### ISSUE TITLE
Cannot register resource ID in polygon mumbai

### ISSUE THREAD

**Issue by harry-nguyen22** [0xPolygon/polygon-edge#595]
### Description

I finished step https://polygon-edge.netlify.app/docs/additional-features/chainbridge/deploy-contracts and step https://polygon-edge.netlify.app/docs/additional-features/chainbridge/setup-relayer without any issues

The result of deploying the contract in polygon Mumbai (via alchemy RPC) is:

```
================================================================
Url:        https://polygon-mumbai.g.alchemy.com/v2/GHr4Koyt1fr4ngb7S6FN7PEKHNDogBLr
Deployer:   0x76829A94932664106627Fc36E3e0577511Fc4fc8
Gas Limit:   6000000
Gas Price:   4012292811
Deploy Cost: 0.058606365427019322

Options
=======
Chain Id:    99
Threshold:   1
Relayers:    0x76829A94932664106627Fc36E3e0577511Fc4fc8
Bridge Fee:  0.000000005925192625
Expiry:      100

Contract Addresses
================================================================
Bridge:             0x6c5BE3bb3b8694037668Eda239838ce9E436da23
----------------------------------------------------------------
Erc20 Handler:      0xA4fd137c16Fb4Ff9b30109C9129a3918953Ca3c4
----------------------------------------------------------------
Erc721 Handler:     0xB03Ff663410d80c7825aeadAbF48Ef9A77B7141a
----------------------------------------------------------------
Generic Handler:    0x71A03928F529cfaDA85CEdA54cA782036bC33564
----------------------------------------------------------------
Erc20:              0x00AC3Cb5EEd2F7438224Cc0E88c6f42eB0A6Ce00
----------------------------------------------------------------
Erc721:             0x1899756Fdf2A8F4f949A2B1939F7304BeE552641
----------------------------------------------------------------
Centrifuge Asset:   Not Deployed
----------------------------------------------------------------
WETC:               Not Deployed
================================================================
```

Then I followed this guide https://polygon-edge.netlify.app/docs/additional-features/chainbridge/setup-erc20-transfer for transferring the erc20 token and I stuck at the first step ( wait like forever ) 

The ADMIN_ACCOUNT_PRIVATE_KEY below is the account's key that I deployed the contract with has address is 0x76829A94932664106627Fc36E3e0577511Fc4fc8

```
cb-sol-cli bridge register-resource \
  --url https://polygon-mumbai.g.alchemy.com/v2/GHr4Koyt1fr4ngb7S6FN7PEKHNDogBLr \
  --privateKey [ADMIN_ACCOUNT_PRIVATE_KEY] \
  --resourceId "0x000000000000000000000000000000c22ebe4a02bbc34786d860b355f5a5ce22" \
  --bridge "0x6c5BE3bb3b8694037668Eda239838ce9E436da23" \
  --handler "0xA4fd137c16Fb4Ff9b30109C9129a3918953Ca3c4" \
  --targetContract "0x00AC3Cb5EEd2F7438224Cc0E88c6f42eB0A6Ce00"
```

The response is 
```
Waiting for tx: 0x46ab70da3095549dcb7a77d8884dc8f3a7689369c9abfde60e349f15c120fe69...
```

And it took forever ... 

The setup-erc20-transfer tutorial has some unclear stuff to me:

1.  Resource ID: is it a random number? What is the best way to create that ID? How to check if that ID already existed before on the blockchain?
2. ERC20_CONTRACT_ADDRESS in register-resource command: This is an ERC20 address returned when I deployed a contract (bridge, relayer, handlers ) above or the ERC20 contract address for the token I want to send? Because I already created my HART token in this contract here 0x7146B43cE5241c5b668084f79aa97dE61Aa152BD

### Your environment

- MacOS 12.4
- 0.4.0
- hash https://github.com/0xPolygon/polygon-edge/commit/8b85d687bc964109cd7935ef62a1e503e47a2fe9

### Steps to reproduce

Already told in the description

### Expected behaviour

Should finish the transaction for registering the resource ID

### Actual behaviour

Transaction is waiting like forever

### Logs

```
[bridge/register-resource] Registering contract 0x7146B43cE5241c5b668084f79aa97dE61Aa152BD with resource ID 0x000000000000000000000000000000c22ebe4a02bbc34786d860b355f5a5ce22 on handler 0xA4fd137c16Fb4Ff9b30109C9129a3918953Ca3c4
Waiting for tx: 0x46ab70da3095549dcb7a77d8884dc8f3a7689369c9abfde60e349f15c120fe69...
```

**Comment by Kourin1996** [comment]
@harry-nguyen22 Hi, Thank you for your questions.

I will answer your questions firstly.
> is it a random number? What is the best way to create that ID? How to check if that ID already existed before on the blockchain?

As [official document](https://chainbridge.chainsafe.io/spec/#resource-id) and [our document](https://polygon-edge.netlify.app/docs/additional-features/chainbridge/setup-erc20-transfer/#step-1-register-resource-id) said, this is 32-bytes arbitrary data. But it may have the chain ID of the home chain in the last byte. This value must be unique in one Bridge contract but you don't have to care about uniqueness in the whole blockchain.

Bridge contract has the public field `_resourceIDToHandlerAddress` which is mapping from resource ID to address. You can read this.

> ERC20_CONTRACT_ADDRESS in register-resource command: This is an ERC20 address returned when I deployed a contract (bridge, relayer, handlers ) above or the ERC20 contract address for the token I want to send? Because I already created my HART token in this contract here 0x7146B43cE5241c5b668084f79aa97dE61Aa152BD

The address of the contract you want to transfer. If you have your ERC20 contract, then its address will be ERC20_CONTRACT_ADDRESS.

Next, I'd like to give you a suggestion against your current issue. I guess your transaction didn't have proper gas price. As [our doc](https://polygon-edge.netlify.app/docs/additional-features/chainbridge/deploy-contracts) mentioned, `cb-sol-cli` uses fixed gas price setting if you don't give `gasPrice` arguments. Please check the latest average gas price [here](https://gasstation-mumbai.matic.today/v2) and give the price when using `cb-sol-cli`

**Comment by harry-nguyen22** [comment]
@Kourin1996 Thank you for your reply. I checked the gas price here: https://gasstation-mumbai.matic.today/v2 like you said and realized that gas on the website is in GWei (at the time I checked, the fast transaction requires around 7 GWei ) so I set the gas price to the registration command below. Note that my admin private key is associated with this account 0x76829A94932664106627Fc36E3e0577511Fc4fc8 which is my current relayer account 
```
cb-sol-cli bridge register-resource \
  --url https://polygon-mumbai.g.alchemy.com/v2/GHr4Koyt1fr4ngb7S6FN7PEKHNDogBLr \
  --privateKey [ADMIN_PRIVATE_KEY] \
  --resourceId "0x7300e2f69e687a6ed811ed9fc365a214e164ecf2fef852b53659e28a8b3f7a77" \
  --bridge "0x6c5BE3bb3b8694037668Eda239838ce9E436da23" \
  --handler "0xA4fd137c16Fb4Ff9b30109C9129a3918953Ca3c4" \
  --targetContract "0x00AC3Cb5EEd2F7438224Cc0E88c6f42eB0A6Ce00" \
  --gasPrice 17000000000
  ```

But the transaction still waiting like forever ( over 10 minutes but nothing return )

```
Waiting for tx: 0x79444d7f81fc9867c2c28bb6fb546d5bad20abe3f30c9074c9e213f4c00b7976...
```

I even tried with gas price 27000000000 or 37000000000 ( when I used 47000000000, it said INSUFFICIENT_FUNDS but my account has around 0.3178 MATIC so I don't know why that error return ) but still the same result.

**Comment by Kourin1996** [comment]
@harry-nguyen22 I think the transactions you sent before are stuck. The simplest way is to use new accoun. If you want to remove stuck transactions, you need to send transaction with specified nonce and much higher gas price in metamask. `cb-sol-cli` has no option to specify nonce.

**Comment by harry-nguyen22** [comment]
@Kourin1996 Thanks! The transactions are stuck and I need to deploy a new contract to a new account and then register resourceID again and everything's good!
