### ISSUE TITLE
Add the method eth_accounts

### ISSUE THREAD

**Issue by samisbakedham** [0xPolygon/polygon-edge#601]
### Description

Was trying to set up ENS on a chain built using polygon-edge, and was met with the error of
 `ProviderError: the method eth_accounts does not exist/is not available`

### Your environment

* Windows Eleven
* v0.4.1
* dev

### Steps to reproduce

* Git clone https://github.com/candleplatforms/ens-contracts
* run `yarn`
* then run `npx hardhat deploy --network candle`

### Expected behaviour

Should successfully compile and deploy contracts onto the polygon-edge chain

### Actual behaviour

Returns an error stating that the method eth_accounts is not available (yet).

### Logs

```
Compiled 113 Solidity files successfully
An unexpected error occurred:

ProviderError: the method eth_accounts does not exist/is not available
    at HttpProvider.request (C:\Users\samue\OneDrive\Documents\GitHub\ens-contracts\node_modules\hardhat\src\internal\core\providers\http.ts:78:19)
    at GanacheGasMultiplierProvider.request (C:\Users\samue\OneDrive\Documents\GitHub\ens-contracts\node_modules\hardhat\src\internal\core\providers\gas-providers.ts:312:34)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
### Proposed solution

Implement this functionality into the polygon-edge chain.

**Comment by Kourin1996** [comment]
@samisbakedham Hello, Thank you for raising the issue.

I'm afraid Polygon Edge doesn't support `eth_accounts` JSON-RPC endpoint currently because Edge doesn't have local account management feature.

I think this error is thrown by hardhat. hardhat calls `eth_accounts` if its config doesn't have private keys. You can put your private keys in `hardhat.config.js` like this:

```js
const config = {
  networks: {
    edge: {
      url: "...",
      accounts: [
        // Put your private keys here
        "0x...",
      ],
    },
  },
};
```

**Comment by samisbakedham** [comment]
> @samisbakedham Hello, Thank you for raising the issue.
> 
> 
> 
> I'm afraid Polygon Edge doesn't support `eth_accounts` JSON-RPC endpoint currently because Edge doesn't have local account management feature.
> 
> 
> 
> I think this error is thrown by hardhat. hardhat calls `eth_accounts` if its config doesn't have private keys. You can put your private keys in `hardhat.config.js` like this:
> 
> 
> 
> ```js
> 
> const config = {
> 
>   networks: {
> 
>     edge: {
> 
>       url: "...",
> 
>       accounts: [
> 
>         // Put your private keys here
> 
>         "0x...",
> 
>       ],
> 
>     },
> 
>   },
> 
> };
> 
> ```
> 
> 
> 
> 

You're right, thanks. Fixed it. Could also be worth looking into adding local account management perhaps?

**Comment by laviniat1996** [comment]
@samisbakedham Glad to hear that it is fixed! :) To reply to your question, we don’t plan on adding Account management to Polygon Edge, as that would be a security liability and the most common modern setups utilize client-side signing. 

If you have any other questions, please let us know.
