### ISSUE TITLE
Approve ERC20 token transfer stuck! 

### ISSUE THREAD

**Issue by harry-nguyen22** [0xPolygon/polygon-edge#606]
### Description

I followed the tutorial here: https://polygon-edge.netlify.app/docs/additional-features/chainbridge/setup-erc20-transfer/

I successfully register resource ID,  mint erc20 token, check balance but when I make an approve command below, it stucks there even I tried to set fast gasPrice (at that time it is around 2 GWei https://gasstation-mumbai.matic.today/v2 )

  cb-sol-cli erc20 approve \
  --url https://polygon-mumbai.g.alchemy.com/v2/GHr4Koyt1fr4ngb7S6FN7PEKHNDogBLr \
  --privateKey [ADMIN_ACCOUNT_KEY] \
  --erc20Address "0x2988C95C4fda85b0Ec4fC4ed86c643e7bac42fB3" \
  --recipient "0xB65926162B2aB8E15279347f7Bc1aF77b5eCD81f" \
  --amount 500 \
  --gasPrice 7000000000

You guys can check all transactions at the address below ( associated with ADMIN_ACCOUNT_KEY above ): https://mumbai.polygonscan.com/address/0xE5D77C6682c4d96EA5aA371bd8c0e9fD308f545a

The transaction for set resource and mint token are successful in the transaction detail page

This is my contract deploy info:

```
cb-sol-cli deploy --all --chainId 99 \
  --url https://polygon-mumbai.g.alchemy.com/v2/GHr4Koyt1fr4ngb7S6FN7PEKHNDogBLr \
  --privateKey [ADMIN_ACCOUNT_PRIVATE_KEY] \
  --relayers 0xE5D77C6682c4d96EA5aA371bd8c0e9fD308f545a \
  --relayerThreshold 1 \
  --gasPrice 4012292811 \
  --fee 0.000000005925192625 \
  --gasLimit 6000000

Url:        https://polygon-mumbai.g.alchemy.com/v2/GHr4Koyt1fr4ngb7S6FN7PEKHNDogBLr
Deployer:   0xE5D77C6682c4d96EA5aA371bd8c0e9fD308f545a
Gas Limit:   6000000
Gas Price:   4012292811
Deploy Cost: 0.058606365427019322

Options
=======
Chain Id:    99
Threshold:   1
Relayers:    0xE5D77C6682c4d96EA5aA371bd8c0e9fD308f545a
Bridge Fee:  0.000000005925192625
Expiry:      100

Contract Addresses
================================================================
Bridge:             0xcCf71922B0e6Dd5951cC640D6Ff43EdafdcB5Dbd
----------------------------------------------------------------
Erc20 Handler:      0xB65926162B2aB8E15279347f7Bc1aF77b5eCD81f
----------------------------------------------------------------
Erc721 Handler:     0x943441e37964Cc07494Ee6F6E16a3dd7cB6704dD
----------------------------------------------------------------
Generic Handler:    0xc8CBc3de1FE5609eF4184E12318963b1615792F6
----------------------------------------------------------------
Erc20:              0x2988C95C4fda85b0Ec4fC4ed86c643e7bac42fB3
----------------------------------------------------------------
Erc721:             0xFFed684ACDfba5D35517d88B0c559576a6342F06
----------------------------------------------------------------
Centrifuge Asset:   Not Deployed
----------------------------------------------------------------
WETC:               Not Deployed
==========================================
```

My first question is I already set a new account for deploying a contract, registering resource id, and mint token .... but the approve transferring transaction is still stuck (I wait for 10 mins with a high gas fee already). If every time transaction is stuck, we need to set up a new account and deploy everything again then I think it is not effective so do we need a way to cancel all stuck transactions?

The second question I want to ask is about the mint concept in the transfer erc20 token tutorial:

I wonder why we need to mint a token every time if we already have it? The current process for transferring is:

```
1. Register resourceId -> 2. Mint token -> 3. Approve transferring -> 4. Deposit token
```

Let's say I have HARC token in Mumbai testnet below:

https://mumbai.polygonscan.com/token/0x7146b43ce5241c5b668084f79aa97de61aa152bd?a=0x2E3E8f108CadF1aE9f1813AA37b501Ec12b6aE59

If I want to transfer that token to polygon edge local then is it correct that I just need to register resourceID with target contract is 0x7146B43cE5241c5b668084f79aa97dE61Aa152BD and then deposit token to polygon edge chain without needed to mint or approve the transferring? 

### Your environment

- MacOS 12.4
- 0.4.0
- hash https://github.com/0xPolygon/polygon-edge/commit/8b85d687bc964109cd7935ef62a1e503e47a2fe9

### Expected behaviour

The approval transaction should not be stuck

### Actual behaviour

The approval transaction is stuck

**Comment by Kourin1996** [comment]
@harry-nguyen22 Hello, Thank you for raising the issue.

1. Another way to remove stuck transaction is to send a transaction with same nonce but higher gas price. Now I have no idea what the reasons are except for gas price issue. From my side, it worked when I tried yesterday.

2. Of course. You don't need to register resource ID and mint token every time. In the example with the ERC20 contract by ChainBridge, user doesn't have initial balance and it needs to call mint. You don't have to call mint if you have enough balance. 

But you need to approve the amount you want to transfer before deposit. For example, you approve 1000 Token but you deposit only 500 Token. In a such case, you can deposit 500 Token without approve. If you want to bridge more than 500 Token, you need to call approve again.

**Comment by harry-nguyen22** [comment]
@Kourin1996 I tried with new accounts and every steps run successfully except the approve step (even I set high gas price). Did you try with Alchemy RPC ? Because Infura requires me to set Billing information before using polygon Mumbai testnet so I don't use it.  Using https://rpc-mumbai.matic.today always return 404 error ( I think due to rate limit)

**Comment by Kourin1996** [comment]
@harry-nguyen22 When I tried it, I used Alchemy RPC API. Does your ERC20 contract implements `approve` method? Actually you don't have to use `cb-sol-cli` to approve. All you need to do is to approve transfer from your account by ERC20Handler.

**Comment by harry-nguyen22** [comment]
@Kourin1996 I cleaned up everything and create new account and setup all stuff again and finally I can approved the ammout and deposit successfully 😁. Here is my address in Mumbai: https://mumbai.polygonscan.com/address/0xd255E1Bd52Bf5c9cF223b32B86a2616431Dff0F0

You can see that the mint, approve and deposit transaction (1 fail and 2 successfully) are successful but somehow the recipient account in my local edge chain still see 0.0 balance. 

Does resourceId from Mumbai chain and localhost chain should be the same value? And we only need to start a relayer only when we need to make a deposit command, right ?

Here is my deposit command:

```
cb-sol-cli erc20 deposit \
  --url https://polygon-mumbai.g.alchemy.com/v2/GHr4Koyt1fr4ngb7S6FN7PEKHNDogBLr \
  --privateKey [USER_ACCOUNT_PRIVATE_KEY] \
  --amount 10 \
  --dest 100 \
  --bridge "0x6EA4d186c7b607DC844c9c2F333fc657923dD6a5" \
  --recipient "0x2E3E8f108CadF1aE9f1813AA37b501Ec12b6aE59" \
  --resourceId "0xf81d0aeb9ea6607d4c4355e3bd75c99e297ed943634e5c14ffc16d4a15dee614" \
  --gasPrice 8000000000
  ```

**Comment by Kourin1996** [comment]
@harry-nguyen22 Great to hear that.

Yes, you need to set the same resource ID for the token you want to bridge in both chain.

And you need to start relayer before you send deposit tx. Please make sure ERC20Handler in the destination chain has enough balance to send the recipient account tokens in case of Lock/Release mode in the destination chain. If you've set burn/mint mode, ERC20Handler needs to be able to mint ERC20 token. Please check document for more details.

**Comment by harry-nguyen22** [comment]
@Kourin1996 Thank for your answer. I don't set any specific mode so I think the default mode still lock/ release. Below is my contract info in destination chain (localhost chain)

```
================================================================
Url:        http://localhost:10002
Deployer:   0xB83f0058833BD87a9EddB9Ca896fE25fA2Adb657
Gas Limit:   8000000
Gas Price:   20000000
Deploy Cost: 0.0002906526

Options
=======
Chain Id:    100
Threshold:   1
Relayers:    0xB83f0058833BD87a9EddB9Ca896fE25fA2Adb657
Bridge Fee:  0
Expiry:      100

Contract Addresses
================================================================
Bridge:             0xca67123ffe12583E4C3DCa9533FBab05F69e6459
----------------------------------------------------------------
Erc20 Handler:      0xDeA74FCB008d43D1Bf1698FB0f20c957C7B13185
----------------------------------------------------------------
Erc721 Handler:     0x6253E277Ce043Cbdb3739eE8Cc16A62579DC4108
----------------------------------------------------------------
Generic Handler:    0x484CCb6f99ee125989da50E75298f161bA591Ecb
----------------------------------------------------------------
Erc20:              0x29371E3050bB4851f7530dFF128d127cA3524544
----------------------------------------------------------------
Erc721:             0x6c416573b8DCF66bd61A41De20352eFb64766607
----------------------------------------------------------------
Centrifuge Asset:   Not Deployed
----------------------------------------------------------------
WETC:               Not Deployed
================================================================
```

You mean the address 0xDeA74FCB008d43D1Bf1698FB0f20c957C7B13185 should have enough balance to be able to transfer the token to the recipient account? I tried to use my local test account ( 890 ETH ) to send 10 eth to that address but the transaction failed. I check activity logs but it just said "encounter error"? I can use metamask to transfer the ETH ( get from primine account ) to other account normally without any issues.

<img width="365" alt="Screen Shot 2022-06-26 at 14 16 52" src="https://user-images.githubusercontent.com/55209704/175803808-5edafe65-9e95-48a7-a363-e13986df6e08.png">

**Comment by harry-nguyen22** [comment]
@Kourin1996 I got your point. So the handler only accepted the token from the erc20 contract it registered before. So we need to mint it first and then transfer it to the handler address. I can make a deposit successful! Thank you very much.
