### ISSUE TITLE
Faucet code?

### ISSUE THREAD

**Issue by ralyodio** [0xPolygon/polygon-edge#607]
is the faucet code from faucet.polygon.technology available on github anywhere?

I'm looking for a faucet I can setup for my polygon erc-20 token. The matic.supply project is dead. Nobody is responding there.

**Comment by 0xAleksaOpacic** [comment]
Hi @ralyodio 
Not sure, we do not have access to the faucet.polygon.technology code. 

Closing this issue, not related with polygon-edge
