### ISSUE TITLE
Web socket url doesn't work behind nginx proxy

### ISSUE THREAD

**Issue by vineetaparodkar** [0xPolygon/polygon-edge#608]
### **Description**
I am trying to configure polygon edge nodes behind nginx proxy. Access to the nodes is restricted using nginx basic authentication mechanism. Web3HttpProvider, Web3WsProvider npm provider packages are used which allows pass authorization headers when rpc/ws calls are made to send transactions. Need some pointers on how to configure web socket urls to work using nginx with basic authorization similar to rpc urls, so that access to nodes are restricted with username/password.

References used: 

- https://ethereum.stackexchange.com/questions/30357/restricted-access-authentication-for-a-remote-geth-node
- https://www.nginx.com/resources/wiki/start/topics/recipes/geth/
- https://stackoverflow.com/questions/57293979/websocket-connection-for-nginx-and-parity

### **Environment**

- OS and version: ubuntu 20.04.4 LTS 
- version of the Polygon Edge: [v0.2.1](https://github.com/0xPolygon/polygon-edge/releases/tag/v0.2.1)
- branch that causes this issue: develop

### **Steps to reproduce**
_**how to reproduce this issue**_
Below are the steps used to configure and test RPC urls

1. Setting up nodes with localhost:port for RPC URLs using  [polygon edge document guide](https://edge-docs.polygon.technology/docs/get-started/set-up-ibft-locally)

2. Setup nginx on ubuntu with below default http server config for node1 running on port 8008 for RPC URLs

- setup credentials for authentication [creating password](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/#creating-a-password-file)

- add below content in nginx.conf at location /etc/nginx/sites-enabled/

```
server {

    listen 80 default_server;

    auth_basic "Protected edge node1";

    auth_basic_user_file /etc/nginx/sites-enabled/.htpasswd;

    server_name subdomain.mydomain.com;

    location / {

      proxy_pass http://localhost:8008;

      proxy_set_header Host $host;

      proxy_redirect http:// https://;

    }
}
```
4. Deploy sample erc20 contract on edge network

5. Using etherjs for accessing node1's rpc url through nginx url( http://localhost:80)

```
const options={
 headers: [{name: 'Authorization', value: 'Basic base64encodedcredentials'}] //credentials created in step2
},
var rpcProvider = new Web3HttpProvider('http://localhost:80',options);
const abi=<contract abi>
const provider= new ethers.providers.Web3Provider(rpcProvider)

const wallet = new ethers.Wallet("<private key>",provider);
const Instance = new ethers.Contract("<contract address>", abi, wallet);

console.log("Retrieving account Balance")
console.log((await Instance.balanceOf("<wallet address>")).toString()) //testing if rpc urls are accessible through nginx authentication

```

Below are the steps used to configure and test Web Socket urls

1. Setting up nodes with localhost:port for RPC URLs using  [polygon edge document guide](https://edge-docs.polygon.technology/docs/get-started/set-up-ibft-locally)

2. Setup nginx on ubuntu with below default http server config for node1 running on port 8008 for RPC URLs (Web socket configured by default on polygon edge on same rpc port ws://localhost:port/ws)

- setup credentials for authentication [creating password](https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/#creating-a-password-file)

- add below content in nginx.conf at location /etc/nginx/sites-enabled/

```
server {

    listen 80 default_server;

    auth_basic "Protected edge node1";

    auth_basic_user_file /etc/nginx/sites-enabled/.htpasswd;

    server_name subdomain.mydomain.com;

    location / {

      proxy_pass http://localhost:8008/ws;

      proxy_set_header Host $host;

      proxy_redirect http:// https://;

    }
}
```
4. Deploy sample erc20 contract on edge network

5. Using etherjs for accessing node1's ws url through nginx url( http://localhost:80)

```
const options={
  headers: {
      authorization: 'Basic username:password' //created in step 2
    },
},

var wsProvider = new Web3WsProvider('ws://localhost:80/ws',options);
const abi=<contract abi>
const provider= new ethers.providers.Web3Provider(wsProvider)

const wallet = new ethers.Wallet("<private key>",provider);
const Instance = new ethers.Contract("<contract address>", abi, wallet);

console.log("Retrieving account Balance")
console.log((await Instance.balanceOf("<wallet address>")).toString())

```
### _**Expected behaviour**_

Both rpc and web socket urls must be accessible through nginx proxy after providing credentials and create provider using above npm packages .

### _**Actual behaviour**_

- With above nginx configuration only rpc url(refer configure and test RPC urls steps section) works with nginx basic authentication(username/password). 
- web socket url (refer steps used to configure and test Web Socket urls steps section)doesnt work, balance cannot be retrieved. 

### _**Logs**_
WS Provider created throws error with bad route. Network not found error.
_ERROR:_
> Authetication Service Error:    Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.5)

**Comment by laviniat1996** [comment]
@vineetaparodkar  Thank you for opening  this issue!

This is our template for reporting issues: https://edge-docs.polygon.technology/docs/community/report-bug and we highly encourage everyone to use it, because it makes our work much easier if we get all the relevant data.

Could you please tell us more info about your environment and provide the logs (if there are any) ?

**Comment by vineetaparodkar** [comment]
Hi @laviniat1996 , Updated issue details above according to template you shared, Please let me know if any other details are required.

**Comment by ZeljkoBenovic** [comment]
Hi @vineetaparodkar ,

sorry for the delay.

Not sure on why you're redirecting to https but you've got no certs configured, and you're hitting plain http. 
The Nginx config that is tested and working with Basic Auth with WS is as following : 
```
http {

    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    upstream polygon-edge {
        server node1:8545;
        server node2:8545;
        server node3:8545;
        server node4:8545;
        server node5:8545;
        server node6:8545;
    }

    upstream polygon-edge-websocket { 
        # enable sticky session based on IP for websocket
        ip_hash;

        server node1:8545;
        server node2:8545;
        server node3:8545;
        server node4:8545;
        server node5:8545;
        server node6:8545;
    }
    
    server {
      listen 8080;

      location / {
          proxy_pass http://polygon-edge;
      }

      location /ws {

          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_pass http://polygon-edge-websocket/ws;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
          proxy_set_header Host $host;

          auth_basic "Admin Restricted";
          auth_basic_user_file ".htpasswd";
      }
    }
}
```
I've pulled this config from a Polygon Edge network that is running in docker containers and the JSON-RPC is exposed via Nginx reverse proxy.

Try implementing similar config on your end, and let us know if it solves the issue.    

For WS auth testing, you can use npm tool `wscat` , just install it globally with `npm install -g wscat` .   
After `wscat` is installed, you can test your WS endpoint with a command similar to this:      
`wscat -c "ws://localhost/ws" --auth "test:test"`  and if the auth works, there should be a message `Connected (press CTRL+C to quit)` in the console.
