### ISSUE TITLE
failed to bulk sync (err="fork not found")

### ISSUE THREAD

**Issue by saravana87** [0xPolygon/polygon-edge#621]
### Description

I set up the polygon edge in our servers. I was able to deploy the bootstrap node and ran the polygon-edge server with the genesis file.
I connected with the wallet and ability to see the 1000 ETH in my account.
when I tried to stack the contract or whatever it was. 
the blockchain doesn't pass the 251 blocks.

this is the output of eth_getBlockByNumber
{"jsonrpc":"2.0","id":1,"result":{"parentHash":"0x2e082ff746c1f5e5c3661221a20e74e76b7171befeddff70fe06921d54e672cb","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","miner":"0x0000000000000000000000000000000000000000","stateRoot":"0xaa5393ef03e148797012b2241c036441623dae9bb6c5f17c9c13f9b1f9a5f5c5","transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","difficulty":"0xfa","totalDifficulty":"0xfa","size":"0x2bf","number":"0xfa","gasLimit":"0x500000","gasUsed":"0x0","timestamp":"0x62c30ac3","extraData":"0x0000000000000000000000000000000000000000000000000000000000000000f89ed594c28436378a0ca15e64d72ffe4a0a012fd321f50cb841739d46c6bf433be9b1ab0ea857e2f2ca05a79ee6e50728d02cf98995a05c1b4c7ea4a522554b70d01cd9724827dcbc6d209e5ed67eaf99ca271d38959612f08b00f843b841da34ef50d4f314a981decc5936799a6072c390b044b70368ff379cbd41d2ce947c01480c973519177059db6ac2102cb93ce854e6d4631590a68ef9cadd376b6701","mixHash":"0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365","nonce":"0x0000000000000000","hash":"0x6839f5515a371b94d1335aeeb14e035af01f4a55e9b94caf8cce20df6d572eae","transactions":[],"uncles":[]}}

Can you please let me know what I did wrong.
![validator](https://user-images.githubusercontent.com/7995075/177203441-fb48739d-0411-44b2-bf88-3f686edd08d0.PNG)
![bootstrap](https://user-images.githubusercontent.com/7995075/177203467-f9e4e518-e0a0-41b8-a8e1-982fabc38288.PNG)

### Your environment
* Ubuntu 21
* Polygon edge develop branch
* branch

**Comment by laviniat1996** [comment]
Hello @saravana87 ,
Thank you for opening this issue!

Could you please share with us the `commit hash` or the release version you are using?

**Comment by saravana87** [comment]
Hi, sorry for the late reply. I am using Develop branch.
commit 0e42bda440eee530ece852bc98ee794fe28fbc13 (HEAD -> develop, origin/develop, origin/HEAD)
I hope this helps.
Thanks

**Comment by laviniat1996** [comment]
@saravana87 This could be related to the old syncer. I suggest to try the latest develop for edge, as we have refactored out syncer module.

**Comment by zivkovicmilos** [comment]
@saravana87 

Closing this issue as this was resolved with PR #591.

Please open up a new issue if the problem persists 🙏

**Comment by saravana87** [comment]
> @saravana87
> 
> Closing this issue as this was resolved with PR #591.
> 
> Please open up a new issue if the problem persists 🙏

I updated the develop branch and the issue seems resolved. Thank you
