### ISSUE TITLE
EXTRA_VALUE_AT_END = unable to create discovery client connection 

### ISSUE THREAD

**Issue by aryaparas** [0xPolygon/polygon-edge#623]
## [Subject of the issue]
When I'm running the command 
polygon-edge server --data-dir ./test-chain-1 --chain genesis.json --grpc-address :10000 --libp2p :10001 --jsonrpc :10002 --seal

### Description
I'm getting [ERROR] polygon.network.discovery: Unable to execute bootnode peer discovery, %w: EXTRA_VALUE_AT_END = "unable to create discovery client connection, peer disconnected before the discovery client was initialized" 
Describe your issue in as much detail as possible here

I'm tryin to run step 4 command from [This website of polygon EDGE](https://edge-docs.polygon.technology/docs/get-started/set-up-ibft-locally)
all the above steps 1-3 are executed successfully and genesis also created  
### Your environment

* OS and version - ubuntu 
* version of the Polygon Edge - latest release 0.4.1

**Comment by laviniat1996** [comment]
Hi @aryaparas ,
Thank you for opening this issue!

Can you please share what were the exact steps followed? Also, the logs from other nodes and genesis.json would help us a lot.

**Comment by zivkovicmilos** [comment]
Hey @aryaparas,

What issue are you having exactly with the Edge node / cluster?

This log is somewhat misleading, it's not indicative of any problem during runtime, but should be downgraded to a `WARN` log instead.

**Comment by zivkovicmilos** [comment]
@aryaparas 

Closing this issue as no further info was provided, please open up a new one in the future if you're still experiencing problems
