### ISSUE TITLE
"named files must be .go files: -o" when I run the "go build main.go -o polygon edge"

### ISSUE THREAD

**Issue by CryptoDevving** [0xPolygon/polygon-edge#625]
## [Subject of the issue]

"named files must be .go files: -o" when I run the "go build main.go -o polygon-edge"

### Description
I am trying to host it on a cloud host. 

For some reason it keeps saying "named files must be .go files: -o" when I run the "go build main.go -o polygon-edge"
I sent up my environment up properly I think. I have the polygon files in home. If I should put them in another directory where should they be? I also would like to know how I am supposed to configure go environment for polygon? There are no steps on how to do that. My go version is 1.18beta1. 

How would I install the docker version? All the docs say to download it. It gives no further details on how to set it into docker or how to use it with docker? I would like to know how to do both to see which way is better. 

### Your environment

* Ubuntu 20.04 vultr cloud host
* latest build from source
* latest

### Steps to reproduce

You download go. Then unzip it and then set export GOROOT=/usr/local/go. Then export GOPATH=$HOME/go. Then export PATH=$GOPATH/bin:$GOROOT/bin:$PATH. Then source ~/.bashrc. 

Credits: nextgentips for the commands to set up a go environment. 

I would have no way of knowing how to set up an environment because the documents do not specify how to do it. 

### Expected behaviour

It should build. 

### Actual behaviour

I get the error: "named files must be .go files: -o"

**Comment by zivkovicmilos** [comment]
Hey @CryptoDevving,

Thank you for reaching out.

This is not an Edge related issue.

Your go build command is wrong, the output flag goes before the go file you're building:
`go build -o polygonEdge main.go`

**Comment by CryptoDevving** [comment]
The documents have the command wrong then.

**Comment by 0xAleksaOpacic** [comment]
@CryptoDevving 
Yes, you are right. Thank you for opening this issue, we will fix our official doc :)
