### ISSUE TITLE
Unable to execute bootnode peer discovery

### ISSUE THREAD

**Issue by CryptoDevving** [0xPolygon/polygon-edge#629]
### Description

When I run "node-1> polygon-edge server --data-dir ./data-dir --chain genesis.json  --libp2p (myip):1478 --nat (myip) --seal node-1" it makes an error saying "unable to parse bootnode data. failed to parse bootnode : failed to parse multiaddr "", empty multiaddr"

I accidentally put my genesis.json in node-1 folder and removed it, then generated it again in the polygon-edge folder. Could that be the reason for the error?

### Your environment

* Ubuntu 20.04
Polygon Edge Latest version and branch

### Steps to reproduce

Follow the instructions, but use "polygon-edge secrets init --data-dir data-dir node-1" for the node initializing.

### Expected behaviour

It should start all the nodes.

### Actual behaviour

I get an error.

I had blanked out my ip for obvious reasons. That is why there are a lot of blank spots.

**Comment by laviniat1996** [comment]
Hi @CryptoDevving ,
Thank you for sharing this issue!

The genesis.json file must be the same across all nodes. As mentioned, you have a different genesis.json file for node 1. Please firstly fix this. Let me know how it goes.

**Comment by CryptoDevving** [comment]
So I put the genesis.json in all nodes?

Edit: I still get the same error even after putting the same genesis.json in all nodes folders. 

Edit2: How would I run that command with node-1, node-2, node-3, and node-4?

**Comment by CryptoDevving** [comment]
I tried to put the Genesis.json in all nodes, but I get this error after I run the command.
![more errors](https://user-images.githubusercontent.com/36123966/178055016-5be3797b-26fa-4dc9-bf25-2c5a82e32db1.jpg)

**Comment by CryptoDevving** [comment]
I fixed the Genesis.json in the polygon-edge folder then ran the command again, then got this
![another error](https://user-images.githubusercontent.com/36123966/178058923-753bdc8b-24eb-4c61-a815-93a809697caa.jpg)
.
