### ISSUE TITLE
Unable to execute bootnode peer discovery

### ISSUE THREAD

**Issue by CryptoDevving** [0xPolygon/polygon-edge#633]
### Description

I had followed all the cloud setup steps in the documents. I generated the genesis.json for all my 4 nodes. These nodes are seperate computers. I used this command on each of the nodes: 
"polygon-edge genesis --consensus ibft --ibft-validator=0xA62D69C8b9240E49A66aE36D267C269036E06822 --ibft-validator=0xbC2332FC4fBA85323D007bbf4957eB049aedEA3F --ibft-validator=0x9ed65F29F49928a07a35af1FD91C0B25Ae745273 --ibft-validator=0xcbC8af33E30E40B3A372F1106Df7c15d6529D991 --bootnode=/ip4/(insert IP here)/tcp/1478/p2p/16Uiu2HAmUfAcnN2qp3x8DHQKrN8Fn8yRvrSgkDBejt4MV8RvcrPw --bootnode /ip4/(insert IP here)/tcp/1478/p2p/16Uiu2HAm58JiCG7SNcNDiKHuAhAFmsEAPKenoNJiX3veApoHLAKf  --bootnode /ip4/(insert IP here)/tcp/1478/p2p/16Uiu2HAmRsRucZG7wxvKFeWMUy89hkmfx4DCskhKRbFqdunwmgQj --bootnode /ip4/(insert IP here)/tcp/1478/p2p/16Uiu2HAmTYs5341pD2Vze3HfpF4ygNQLPbkPh9VWVuJopde2HFFr –premine=0x(insert my address here):1000000000000000000000000 --name extella --chain-id 201993 -epoch-size 50

This generated all the genesis.json on my nodes. I have all the nodes having folders on their respective instances as node-1, node-2, node-3, node-4. 

Then when I go in and put in this command, "polygon-edge server --data-dir ./node-1 --chain genesis.json  --libp2p 0.0.0.0:1478 --nat (insert IP here) --seal", I tried for all the other nodes, replacing node-1 with their respective node folder name. This still ended up in an error.

### Your environment

* Ubuntu 20.04 vultr servers
* latest branch

### Expected behaviour

The nodes should start up.

### Actual behaviour

![error3333](https://user-images.githubusercontent.com/36123966/178132287-b3288139-e7e4-43c5-af4f-19c10e8159ab.jpg)

### Proposed Solution

I tried renaming each folder on each server to data-dir, but this gave me the same error.

I had even tried a command I saw on youtube, but it didn't work. 

Another thought I had was that maybe Vultr cloud servers may not work for it? What cloud servers has Polygon Edge been tested and working on?

**Comment by CryptoDevving** [comment]
In addition, could I get the exact commands someone else used to get their nodes up and running? The documents have errors and are unclear.

How many servers do people run the four nodes on?

Thanks to anyone that shares their steps.

**Comment by laviniat1996** [comment]
Hi @CryptoDevving ,
Thank you for opening this issue!

Did you use the same genesis.json file for all the nodes? Please note that it needs to be the same genesis file for each node.

**Comment by CryptoDevving** [comment]
Yes I did. I copied and pasted the same one into each node instance. Each time I get the same result. I redid my server 3 times in different attempts. I tried a time where all 4 nodes were on the same server and tried a time where each of the four nodes were on a different server. All of it yielded the same thing. 

This is why I asked for someone who has successfully done it to provide their exact steps. This way I could just follow those. From the exact server they used, to how they set up their go environment, how many servers they used, and the commands they used.

**Comment by laviniat1996** [comment]
@CryptoDevving  Thank you for the info.
This seems to be a networking issue. Please  check if libp2p is running on a specific interface, instead of localhost, and if security groups, firewall rules, port forwarding, etc. are configured to allow libp2p traffic ( default tcp 1478 ).
Please let me know how it goes.

**Comment by CryptoDevving** [comment]
I did the command "allow ufw 1478". It still didn't work. I am using ubuntu.  What would the specific interface be? What commands would you use to make sure libp2p will work properly?

I am using a vultr cloud host if that makes any difference.

**Comment by zivkovicmilos** [comment]
Hey @CryptoDevving,

What kind of problems do you have with your cluster?

This error log you're seeing is normal and not indicative of any specific problem.

**Comment by CryptoDevving** [comment]
@zivkovicmilos 

I follow the instructions to a T and I always get that error. I have not way of knowing how to fix it.

I installed go 1.18 and I am unaware if there are any other dependencies or things I gotta do to have it work. 

Do I just wait for an hour and it resolves itself? I keep getting the same output without any change or anything. No blocks are made and no connection is established. I am unsure of how to move forward from that.

**Comment by zivkovicmilos** [comment]
@CryptoDevving

Got it, so your cluster is not running correctly. What is your bootnode config?

Are you sure that the nodes you're running can reach each other (have open connections / ports etc)?

If you've designated `node A` to be the bootnode for example, other nodes need to connect to `node A` in order to discover other nodes and start chugging out blocks.

Are you sure the nodes are able to connect to each other (are reachable)?

cc @ZeljkoBenovic

**Comment by zivkovicmilos** [comment]
I'm fairly certain that it's a problem with the IPs you're specifying - make sure the IPs you specify as part of the bootnode config are public and reachable by nodes in the cluster. You need to expose your libp2p port as well so other nodes in your cluster can connect

**Comment by CryptoDevving** [comment]
@zivkovicmilos how do I do that? How do I ensure they are reachable? I use the "ufw allow 1478" command. What else should I do to connect them? 

Edit: designating the original bootnode is a simple as starting it first?

**Comment by ZeljkoBenovic** [comment]
Hi @CryptoDevving ,

This is purely a networking problem.
Check if your ports are open and if your nodes can connect to each other via TCP 1478 ( or whatever port you define with `--libp2p` flag )

The easiest connectivity check that you can do is try opening a `telnet` connection from one node to all other nodes.     
For example: if have a node with IP 10.150.1.4 and I want it to connect to 10.150.1.5 ( these IPs are private, but the same principal applies to the nodes communicating via public IPs ), I would run the command:     
`telnet 10.150.1.5 1478` ( telnet <ip_address> <port> )       
and if the connection was successful I should see comething like `Connected to <ip_address>`     
```
ubuntu@ip-10-150-1-4:~$ telnet 10.150.1.5 1478
Trying 10.150.1.5...
Connected to 10.150.1.5.
Escape character is '^]'.
/multistream/1.0.0
^CConnection closed by foreign host.
```
You need to run this check on all nodes, from one node to all other nodes as they need to be in a mesh network.
If this test fails, probably the firewall/security group/access list is not setup properly to allow this traffic.     
Please do check your cloud hosting providers documentation on how to properly configure this.     

P.S. Please use the GitHub release to run `polygon-edge` as the releases are most stable and tested.

**Comment by CryptoDevving** [comment]
@zivkovicmilos 

I am using vultr cloud hosting. I will look into it and report back to you with what happens.

**Comment by CryptoDevving** [comment]
@ZeljkoBenovic 

Edit: I got it working. 


I am using vultr cloud hosting. I will look into it and report back to you with what happens.

**Comment by CryptoDevving** [comment]
@ZeljkoBenovic

I got it working so far. That error is a bit misleading. How can I see the RPC now? I am unsure as too where to check.

**Comment by CryptoDevving** [comment]
@ZeljkoBenovic

One last question. How do I change the IP to a link? So for example change the RPC IP from 7.7.7.7:10002 to www.myblockchain.com. 

I am completely confused on how to configure Nginx reverse proxy.  

Edit: how do I set minimum gas price?

**Comment by Kouteki** [comment]
@CryptoDevving this  page should help you with the DNS question

https://docs.polygon.technology/docs/edge/get-started/set-up-ibft-on-the-cloud

**Comment by ZeljkoBenovic** [comment]
Hi @CryptoDevving ,

Firstly, you'd need to setup a reverse proxy, like the Nginx you've mentioned. There is plenty of documentation online ( like [this](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/) ) on how to configure Nginx as a reverse proxy, but for starters you can check out one of your closed issues: https://github.com/0xPolygon/polygon-edge/issues/608 

As for exposing your JSON-RPC via DNS name, you'd first need to setup a reverse proxy which will expose your JSON-RPC API to the internet and add an A record in your DNS zone, pointing the DNS name to your JSON-RPC address. You'd probably need to implement some kind of SSL certificate as most services won't work on plain public http API endpoint.

All of the above is general networking/DevOps Web2 knowledge and there are plenty online resources on this.

If you still can't setup your environment using all available online resources, we can connect you to some of our partners offering premium support and are specialized in Polygon Edge deployments in production ready environments.

I'm closing this Issue as it has nothing to do with the issues in Polygon Edge codebase.
