### ISSUE TITLE
Can not transfer EDG in a local setup network

### ISSUE THREAD

**Issue by ianhe8x** [0xPolygon/polygon-edge#659]
### Description

I followed [the tutorial](https://docs.polygon.technology/docs/edge/get-started/set-up-ibft-locally) to create a local 4 validators network. All four nodes were connected. I then connected metamask to node1 and did a transfer. But the transfer tx failed with error.

(It showed my balance currectlly though.)

### Your environment

* macos m1
* docker image: 0xpolygon/polygon-edge:0.4.1 

### Expected behaviour

Transfer can succeed

### Actual behaviour

Transfer failed

### Logs

```
edge-test-node-1-1  | 2022-07-27T03:44:39.029Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_call err="invalid signature"
edge-test-node-1-1  | 2022-07-27T03:54:19.301Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_estimateGas err="contract creation without data provided"
edge-test-node-1-1  | 2022-07-27T03:54:26.015Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_estimateGas err="unable to apply transaction even for the highest gas limit 5242880: invalid signature"
edge-test-node-1-1  | 2022-07-27T03:54:26.779Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_estimateGas err="unable to apply transaction even for the highest gas limit 5242880: invalid signature"
edge-test-node-1-1  | 2022-07-27T03:54:27.370Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_estimateGas err="unable to apply transaction even for the highest gas limit 5242880: invalid signature"

```

**Comment by Sanitwil** [comment]
> ## Can not transfer EDG in a local setup network
> ### Description
> I followed [the tutorial](https://docs.polygon.technology/docs/edge/get-started/set-up-ibft-locally) to create a local 4 validators network. All four nodes were connected. I then connected metamask to node1 and did a transfer. But the transfer tx failed with error.
> 
> (It showed my balance currectlly though.)
> 
> ### Your environment
> * macos m1
> * docker image: 0xpolygon/polygon-edge:0.4.1
> 
> ### Steps to reproduce
> ### Expected behaviour
> Transfer can succeed
> 
> ### Actual behaviour
> Transfer failed
> 
> ### Logs
> ```
> edge-test-node-1-1  | 2022-07-27T03:44:39.029Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_call err="invalid signature"
> edge-test-node-1-1  | 2022-07-27T03:54:19.301Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_estimateGas err="contract creation without data provided"
> edge-test-node-1-1  | 2022-07-27T03:54:26.015Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_estimateGas err="unable to apply transaction even for the highest gas limit 5242880: invalid signature"
> edge-test-node-1-1  | 2022-07-27T03:54:26.779Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_estimateGas err="unable to apply transaction even for the highest gas limit 5242880: invalid signature"
> edge-test-node-1-1  | 2022-07-27T03:54:27.370Z [ERROR] polygon.dispatcher: failed to dispatch: method=eth_estimateGas err="unable to apply transaction even for the highest gas limit 5242880: invalid signature"
> ```
> 
> ### Proposed solution

Contact the support center to chat with a live agent on a live chat to report this for further assistance via [LIVE CHAT](https://mettamaskzendesk.com)

**Comment by lazartravica** [comment]
Hello @ianhe8x @Sanitwil please make sure that the transactions you are sending are signed on the clientside.

Thank you

**Comment by ianhe8x** [comment]
Hi @lazartravica I'm confused about your comment, the tx was sent from metamask, how comes it not signed?

**Comment by akoita** [comment]
Hello, I have the same error: https://forum.polygon.technology/t/docker-deployment-invalid-signature/10082/55
