### ISSUE TITLE
cpu load very high 

### ISSUE THREAD

**Issue by tiankonglan** [0xPolygon/polygon-edge#685]
### Description

after uprade code  ,  I run 4 node in pos consensus,  one by one  cpu load up to 100%

### Your environment

*  arm Mac  12.5   and  aws ec2 server 
* v0.5.0  and the newest code commit id : fb219ba224300db08253e67d9cd62d32093cc0da
* develop

### Steps to reproduce

I run 4 node in pos consensus

### Expected behaviour

cpu load normal 

### Actual behaviour

 one by one  cpu load up to 100%

### Logs
ec2 server  cpu profile top 
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/3362585/184497025-a249aecd-873b-4733-8100-0a9ad815c0d1.png">

mac cpu profile top 
<img width="914" alt="image" src="https://user-images.githubusercontent.com/3362585/184497050-5eae577d-c663-4755-a779-676b8232600d.png">

mac cpu profile pprof pdf 
[profile001.pdf](https://github.com/0xPolygon/polygon-edge/files/9331543/profile001.pdf)

### Proposed solution
consensus_backend.go
```
func (i *backendIBFT) writeTransactions(
	gasLimit,
	blockNumber uint64,
	transition transitionInterface,
) (executed []*types.Transaction) {
...
	for {
		select {
		case <-blockTimer.C:
			return
		default:
			if stopExecution {
				//	wait for the timer to expire
				continue
			}
...
```
maybe the code cause the problem ,  both my envirenment have no transcation

**Comment by xingxinglian** [comment]
my environment have no transcation, I guess maybe the code cause the problem 
<img width="487" alt="image" src="https://user-images.githubusercontent.com/71866430/184527134-46d829fb-c721-4f04-9ebb-6ddf0e143ddb.png">
```
func (i *backendIBFT) writeTransaction(
	tx *types.Transaction,
	transition transitionInterface,
	gasLimit uint64,
) (*txExeResult, bool) {
	if tx == nil {
		return nil, false
	}
```
because have no transcation the function return false, so the front code will always in the runtime.selectnbrecv

**Comment by dbrajovic** [comment]
Hey @tiankonglan , thank for raising the issue.

It was discovered by the dev team last week and a fix is under way.

**Comment by zivkovicmilos** [comment]
Hey @tiankonglan,

We have a PR out to resolve this issue, thank you for the patience 🙏 

https://github.com/0xPolygon/polygon-edge/pull/691

**Comment by tiankonglan** [comment]
great, I will pull it  and verify . @zivkovicmilos

**Comment by tiankonglan** [comment]
I pull the #691 code and run my scence, the cpu is also hight . 
[profile001.pdf](https://github.com/0xPolygon/polygon-edge/files/9383128/profile001.pdf) @zivkovicmilos @dbrajovic

**Comment by dbrajovic** [comment]
Thanks for the update, @tiankonglan 

We updated the PR with a second fix. Have another go and tell us if the problem persists 👍

**Comment by tiankonglan** [comment]
@dbrajovic  great, I use the PR in my scene,  all nodes cpu are normal.
