### ISSUE TITLE
Unable to execute bootnode peer discovery

### ISSUE THREAD

**Issue by kbatista-nu** [0xPolygon/polygon-edge#695]
### Description

Sometimes my bootnodes reboot and the validators lose connection with the bootnodes

### Your environment

* 0.4.1_linux_amd64

### Steps to reproduce

Run a network with 2 bootnodes and 4 validators.
After stopping all bootnodes and starting the bootnodes again, the validators cannot connect to the bootnodes

### Expected behaviour

Expected would be that the validators would find the bootnodes again

### Actual behaviour

The validators issue an error that they cannot fetch the validators

### Logs

```
2022-08-24T20:11:11.251Z [ERROR] polygon.network.discovery: Unable to execute bootnode peer discovery, %w: EXTRA_VALUE_AT_END="unable to create new discovery client connection, peer disconnected before the discovery client was initialized"
```

### Proposed solution

I would like validators to be able to connect to bootnode without me running the command to add the peer.

When I add a peer to a validator, the network starts working again.

```
polygon-edge peers add --grpc-address 127.0.0.1:10000 --addr
```

**Comment by ZeljkoBenovic** [comment]
Hi @kbatista-nu ,

We already observed some issues with discovery module and the fix might already be there.

Can you please pull this branch `fix/bootnode-peer-discovery` https://github.com/0xPolygon/polygon-edge/tree/fix/bootnode-peer-discovery and let us know if the same issue persists.

Thank you

**Comment by kbatista-nu** [comment]
Hi @ZeljkoBenovic,

I've just tested it, but it didn't work.

Looking at the code, I tried a fix and it worked, my suggestion is when the nodes are searching for the peer, it tries to create the connection.

My code in `network.discovery.discovery.go`

``` golang
// Find peers from the referenced bootnode
	foundNodes, err := d.findPeersCall(bootnode.ID, true)
	if err != nil {
		d.logger.Error("Unable to execute bootnode peer discovery, %w", err)
		d.addToTable(bootnode) // added line
		return
	}
```
	
I need to connect at least the first bootnode, after the other bootnodes could connect to the network using the first

**Comment by ivanbozic21** [comment]
Hi @kbatista-nu 
The issue was identified on our end as well, and please expect a resolution in one of our upcoming releases.

**Comment by zivkovicmilos** [comment]
Hey @kbatista-nu,

Fix is out and awaiting merge into our `develop` branch. I've linked the PR that will resolve this issue.

Stay tuned

**Comment by avenbreaks** [comment]
same issue polygon.network.discovery: Unable to execute bootnode peer discovery, %w: EXTRA_VALUE_AT_END="unable to create new discovery client connection, peer disconnected before the discovery client was initialized" on cloud server
