### ISSUE TITLE
edge not processing new tx and producing new blocks

### ISSUE THREAD

**Issue by ex-shubham-koli** [0xPolygon/polygon-edge#722]
### Description
we are running 4 validator setup on AWS. The network is running with POS consensus on polygon edge v5.0.0.
validator nodes randomly stop processing new transactions, and new blocks are not produced.

The current chain height is 
> Current Block Number (base 10) = 469800

few nodes start throwing nonce errors

![image](https://user-images.githubusercontent.com/53253101/189039263-3a6e90de-06fe-48d8-84ac-7f53a1076ce8.png)

and few nodes are in Initializing state.

![image](https://user-images.githubusercontent.com/53253101/189039310-6ee12914-400f-42e5-b269-d2cc1954c713.png)

This has happened before and I resolved it by restarting all nodes. 
but this time restarting all nodes is not resolving this issue at all new tx are in a pending state and new blocks are not produced. Once the initializing state is completed on the nodes they are throwing the following error

> Polygon.txpool: failed to add broadcast tx: err="txpool is full"

and this is the status of the txpool

![image](https://user-images.githubusercontent.com/53253101/189042591-82eb32ae-3ffb-4067-a8e4-0041040ff74a.png)

PS:- nodes are able to connect to each other there is no connection issue. Node 1 and Node 2 are deployed together on one server and Node3 and Node 4 are deployed together on the second server. ( server size is t3.medium)
![image](https://user-images.githubusercontent.com/53253101/189040268-5e12ad18-33e2-4a68-a751-82f05e5dc36a.png)

### Your environment

* Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-1029-aws x86_64)
* v0.5.0
* Develop

### Steps to reproduce

* Issue happens randomly reproduction steps are not known. <br />

### Expected behavior
blocks should mint properly and new transactions should execute. 

### Actual behavior

polygon edge stops producing blocks and processing new transactions. after restarting all nodes it takes a while to for nodes to get out of initializing state. then they start throwing errors of

> 3|node4  | 2022-09-08T05:24:08.712Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0xa6955e3ece8d7262b46bdcf8b1a42668a0383a4d1e2e3ca895e401a0b59722fd

 but I am still able to read data in the blockchain. but can not write data.

![image](https://user-images.githubusercontent.com/53253101/189042129-2a76f6bc-c7d2-40ad-98af-df662944237a.png)

### Logs

`3|node4  | 2022-09-08T05:24:08.704Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x5cedfed9f02c9f1943f427e4466bb6336f5c0204b13ad6a910d51789a9b3ef3f
3|node4  | 2022-09-08T05:24:08.711Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x1e5c678a43445f82e44bcf9b38e4498238cbaf012e075f85d3f901cc69b7971c
3|node4  | 2022-09-08T05:24:08.712Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0xa6955e3ece8d7262b46bdcf8b1a42668a0383a4d1e2e3ca895e401a0b59722fd
3|node4  | 2022-09-08T05:24:08.719Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0xbd19467b219b9aadb1134043997f97dc85b0fad7f65259927e0e30a897e01637
3|node4  | 2022-09-08T05:24:08.721Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x1469ae8c6bad3cb7ae038f26c7ce95f8f293be714f172b992e6428132cffbb01
3|node4  | 2022-09-08T05:24:10.827Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x37b55f2405cc01e73951cf3a45de6ca9e7e60c8281671adf90acd801b6aeaa7d
3|node4  | 2022-09-08T05:24:10.831Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x0e69c01efdc7a53d0ae99805a5b2042742a566e28d80c2c326a5bf2f7b35f087
3|node4  | 2022-09-08T05:24:10.840Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x10c9f5ff2ddd7ff55efa1e9b514d5e5532881e3488807b7882537ec93d7d5930
3|node4  | 2022-09-08T05:24:10.845Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0xc78ea2a221ae7547d5335cc49d0208921a129dae1c89532853661534ae882b3d
3|node4  | 2022-09-08T05:24:10.851Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x9ea3561b3035af536ff8c39b35f50dfde4c181691190eaa23e003d35186e5baa
3|node4  | 2022-09-08T05:24:10.853Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x2891347712f3b6a5371bbdec3ddd292ca52666fc6a9e66ed8e3ece3404ec0c45
3|node4  | 2022-09-08T05:24:10.857Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0xab378f938db3586a28d37a03328f2cb1862095b8361fd9ac2dfc87488f7fe736
3|node4  | 2022-09-08T05:24:10.863Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x73d42f3b27cfc8b8a5c1e5723a571dfd93c8afb827d2e9d2d18fe5d2e50e3e5f
3|node4  | 2022-09-08T05:24:10.867Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x0f3bed1db792a52056f26ee3e695c2df0d986c3343872f47e37d943fb903e947
3|node4  | 2022-09-08T05:24:12.919Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x744d0e4611f5d8fa5843fce492773cec83f600d486881c4b082b7def052f835e
3|node4  | 2022-09-08T05:24:12.931Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0xce4e2a36a7940a9c8da9c8d8ba23b0e962ac53a2efba94fc040593a07d1aa779
3|node4  | 2022-09-08T05:24:12.940Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x2fb83c822b5172779dbe36b17dff0829e6da8df45ebc559e86b809b607cc92fd
3|node4  | 2022-09-08T05:24:12.941Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x855a3edb5913a4dd699b0f356c2e5de6af6d34923babe8a758a397fd4d1caa5e
3|node4  | 2022-09-08T05:24:12.943Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x7d6d3ffea67d053036476ad8675340ff41c7b55606298f10d5a3b6739a5d7695
3|node4  | 2022-09-08T05:24:12.947Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x2ab05179c50aca865c942f68cccc13a817a90a88cec376fb79fb88951d7a1149
3|node4  | 2022-09-08T05:24:12.948Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0xc3b947bf3bfa9cb98168a06d3230d71e0bd8e046953dac567cab6c68225e4249
3|node4  | 2022-09-08T05:24:12.950Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x340b667cfddfde3b9c9cefa0166903eb739b7e20689ad9f837d730e42b41600b
3|node4  | 2022-09-08T05:24:12.951Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x023490070464f3e2071b812d7cac14174e7556f663cece3862461e1267d2c284
3|node4  | 2022-09-08T05:24:14.765Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x8c2b54c5aa40512277d5ce87a5624c8a5c6ac7ced75334a2970668573e48770a
3|node4  | 2022-09-08T05:24:14.775Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x9fed34a996db96d43cf2d729beb1b380c1234691cbc73e9f5fd724057e0136f5
3|node4  | 2022-09-08T05:24:14.779Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0xdcbb446fdf940da8018e2e40616f993f603de734ae74f3cdfcfce40bb5db61fd
3|node4  | 2022-09-08T05:24:14.782Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x66f923e77ce9de0e37195370c335b9f99af6e57d6100745171edd1895c90e26d
3|node4  | 2022-09-08T05:24:14.788Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x6ffedd7e15e027470bc61bb9519884752689b0c31f985f312bf26fa8f07ec568
3|node4  | 2022-09-08T05:24:14.789Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x2a7c0ecb65c6a94b1c4414b7db75670170d8332455ed72add291bf4d5831a39b
3|node4  | 2022-09-08T05:24:16.871Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0xc48a2ff0a8c8ed975dddf28843ced14bc5b52dcb240e7c6bde4c4e9769e9c579
3|node4  | 2022-09-08T05:24:16.879Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0xf36ad8cb036c7ecf076b734d4426b3cbd3d703ce2e216339a6f3c9859ac060c3
3|node4  | 2022-09-08T05:24:16.883Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0x5641a3f78932c997a5613ee4b32d9bc2a206d25642c24f62eb336120564dcd86
3|node4  | 2022-09-08T05:24:16.886Z [ERROR] polygon.txpool: failed to add broadcast tx: err="txpool is full" hash=0xde34644ad99c6edfd760b87d60158fc55a5c7a172eabd80482c415db017b8758`

**Comment by ivanbozic21** [comment]
Hi @shubham-edx 

Thank you for reporting this, and we shortly review your submitted issue and get back to you.

**Comment by ivanbozic21** [comment]
@shubham-edx 

To further analyze this issue, you will have to provide us with the complete logs for all of your nodes.

Also, can you please tell us in bit more details what action were made before this problem started to occur on your cluster.

**Comment by ex-shubham-koli** [comment]
@ivanbozic21 Thanks for your quick reply. logs may have been deleted in the log rotating process. but I am sharing the logs I still have.
please use this google drive link to download logs.

https://drive.google.com/file/d/1rlSHnz4tKuWg9mGVMEMg3V1bc-v1LZlA/view?usp=sharing

**Comment by ivanbozic21** [comment]
@shubham-edx Thank you for these, and we have already reviewed them but unfortunately, we can't find the root of the problem from them.

When you will be in situation, can you please restart all of your 4 nodes, and start them by using the following flag:
--log-level=DEBUG

Please forward to us the new logs for all nodes once logs are being generated.

**Comment by ex-shubham-koli** [comment]
@ivanbozic21 Thank you for reviewing the logs. your help is appreciated.
here I have started nodes with the` --log-level=DEBUG` as you suggested.

please use this google drive link to download logs.
https://drive.google.com/file/d/16ueHvGJ6HlehtB8l63GM5PiMeiAYCQo6/view?usp=sharing

**Comment by ivanbozic21** [comment]
@shubham-edx We're on it, and we will keep you posted!

**Comment by dbrajovic** [comment]
@shubham-edx 

Can you check if your nodes are properly connected? Judging from the latest logs it seems 2 out of 4 are connected with each other, but the other 2 are not connected at all. Try the [peer commands ](https://docs.polygon.technology/docs/edge/working-with-node/query-operator-info/#peers-list:~:text=Query%20operator%20information-,Query%20operator%20information,-Prerequisites%E2%80%8B) on any of the nodes to determine the network's connectedness. 

The `nonce too low` errors are unrelated - the transactions themselves are not new if the pool is rejecting them. Check how these transactions are created and sent.

**Comment by ex-shubham-koli** [comment]
@dbrajovic Yes the nodes are connecting properly.

**here is the output of the query on server 1. which is running Node 1 and Node 2**

![image](https://user-images.githubusercontent.com/53253101/189275850-3358b3af-1147-4ee9-985b-a7b214b47c0d.png)

**here is the output of the query on server 2. which is running Node 3 and Node 4**

![image](https://user-images.githubusercontent.com/53253101/189275999-329229fc-8747-4dec-aa2e-82421a40280a.png)

**Comment by ivanbozic21** [comment]
@shubham-edx Can you please provide us with the same output for the remaining 2 nodes which are hosted on your other AWS Ec2 vm.

**Comment by ex-shubham-koli** [comment]
@ivanbozic21 
sorry for the confusion but I have already provided it in the earlier comment. I will highlight it better. please refer to the second image in the previous comment.

**Comment by ex-shubham-koli** [comment]
so I deleted the previous blockchain data on all nodes. and started the nodes on the same servers. no changes in any VM specs and they started processing tx and producing new blocks.

![image](https://user-images.githubusercontent.com/53253101/189309848-ba3cbcbf-b8d0-4b0c-81ab-187d633c915f.png)

**Comment by ivanbozic21** [comment]
@shubham-edx Thanks for this feedback, but can you tell us if you tried to perform any test transactions before you started to see the issues with your validator nodes?

**Comment by ex-shubham-koli** [comment]
@ivanbozic21 
No, Nothing extraordinary. all the tx that happened on the network were related to the sending native tokens from one account to another. I have backed up previous blockchain data. I will see if I can reproduce the same issue in my local environment. if I am successful then I shall share these files with you. maybe it will help you resolve it better?

**Comment by ivanbozic21** [comment]
@shubham-edx Yes, and we're curious to know if you will be able to replicate it locally!

**Comment by ivanbozic21** [comment]
@shubham-edx did you manage to replicate this problem, and if not can we go ahead and close this case?

**Comment by ex-shubham-koli** [comment]
@ivanbozic21 Yes I was able to reproduce the same issue on my local machine. should I share the link to download those files with you over email?

**Comment by ivanbozic21** [comment]
@shubham-edx yes please share it with the following email address ivan.bozic@polygon.technology

**Comment by ex-shubham-koli** [comment]
I have shared those files with you over email.

**Comment by ivanbozic21** [comment]
@shubham-edx Thank you for providing us with the data, and we will keep you posted.

**Comment by ex-shubham-koli** [comment]
@ivanbozic21 Hi,
we encountered this problem again. all of our nodes have stopped producing blocks. this time we have 4 validators running on AWS and 4 running on on-premise servers. all 8 of them stopped producing blocks at once.
I have logs of all the 4 nodes which are running on aws uploaded here on the drive.
please see if you can figure out why it is happening. 

https://drive.google.com/drive/folders/1kXoQt7u6rPZBhakvUOCUBBVZG6JfHcg3

**Comment by ex-shubham-koli** [comment]
I will be closing this issue as I belive this issue was caused by TxPool DDoS. updating to version 0.6 has resolved it.
