### ISSUE TITLE
Transaction failed

### ISSUE THREAD

**Issue by isingh108** [0xPolygon/polygon-edge#748]
failed to dispatch: method=eth_getBalance err="failed to get header from block hash or block number"

![image](https://user-images.githubusercontent.com/4157381/191498676-63150bd7-153d-4ea6-824c-4c7f3ac10bab.png)

**Comment by laviniat1996** [comment]
Hi @iqbalsingh108 ,

Can you please add more information to this issue by following [this template](https://wiki.polygon.technology/docs/edge/community/report-bug). It would help us troubleshoot your issue much faster. Thank you!

**Comment by isingh108** [comment]
Hi @laviniat1996 
Actually this issue arises when in case i deleted the genesis block,after that if i create new genesis then this issue is coming.
OS & Version--Ubuntu 22.04.1 LTS
branch ----develop
version-0.50

Issue is when i'm trying to run my node **polygon-edge server --data-dir ./node1 --chain genesis.json --grpc-address :10000 --libp2p :10001 --jsonrpc :10002** with this command its give me the error but my network is running fine.Only problem is transactions failed error is occuring.
Hope this is enough info. for you to look into the issue.I only have this much info.

Thanks

**Comment by isingh108** [comment]
@laviniat1996 I think there is some bug in this release because this run only one time after creating the genesis block,if i delete that genesis and start again with new genesis it gives me **polygon.dispatcher: failed to dispatch: method=eth_getBalance err="failed to get header from block hash or block number"** this error and my transactions failed.

**Comment by laviniat1996** [comment]
@iqbalsingh108 So, the issue happens if you delete the genesis.config file and then create a new one? Were you able to send transactions before deleting it?

**Comment by laviniat1996** [comment]
@iqbalsingh108 Also, would be very helpful if you could provide the logs from the node.

**Comment by isingh108** [comment]
@laviniat1996 Sorry but now i tried with new infra and its working,sorry but i can't provide you logs or transaction details.
I only have this much info. right now with me.
thanks

**Comment by laviniat1996** [comment]
Hi @iqbalsingh108 ,

Did you use `polygon-edge secrets init --data-dir test-chain-1` to generate the keys for your node? If so, if you didn't change anything in your setup, you should use `polygon-edge server --data-dir ./test-chain-1 --chain genesis.json --grpc :10000 --libp2p :10001 --jsonrpc :10002 --seal` to start the node. You have `--data-dir ./node1`, it should be ` --data-dir ./test-chain-1` if you didn't change the name of the directory that contains the keys.

**Comment by laviniat1996** [comment]
@iqbalsingh108 Also, you should never delete the genesis file and create a new one without removing all the data directories too. This will most likely lead to issues in your network. And this is probably the case here too, as you said that with a new setup everything works fine.

I will close this issue now, but if you run into problems again, you can open a new issue.
