### ISSUE TITLE
Help Running Nodes on Cloud 

### ISSUE THREAD

**Issue by Ranofty** [0xPolygon/polygon-edge#757]
Hello please can anyone help on how I can setup polygon-edge on Cloud? I follow all the steps ([here](https://wiki.polygon.technology/docs/edge/get-started/set-up-ibft-on-the-cloud/)) and successful run the Nodes on cloud 

Environments
aws ubuntu 22.04 SSD
aws Amazon Linux

I successful run the Nodes but can’t add my chain to MetaMask also can’t view txhash using
 _curl http://3.86.218.99:3765 -X POST -H "Content-Type: application/json" --data '{"jsопгрс":"2.0","method":"eth_getBlockByNumber",""params":["latest", truel],"id":1}'| jq
_ 

The nodes are always running but can’t get access to them 

can anyone help about this please 😥🙏

**Comment by ivanbozic21** [comment]
Hi @Ranofty 
Please know that we will close this issue request, and we will try to provide you with some guidance in the discussion section.

**Comment by Ranofty** [comment]
Ok Check the Discussion please
