### ISSUE TITLE
Error: invalid values

### ISSUE THREAD

**Issue by avenbreaks** [0xPolygon/polygon-edge#767]
### Description

$ loadbot polygon-edge --chain-id 6969
Error: invalid value
Uses:
loadbot [flags]

i try to change chain-id, jsonrpc but error when i type. position is running bootnode

![image](https://user-images.githubusercontent.com/93043826/192732111-d1cbae94-26d6-4fd6-a4ce-cbc1da640cf4.png)

**Comment by ivanbozic21** [comment]
Hi @avenbreaks,

Please check our official documentation about using loadbot command and example of how you can correctly start the loadbot on your end:

https://wiki.polygon.technology/docs/edge/additional-features/stress-testing/#start-the-loadbot

We will move this topic to discussion section, and let us know if you will need any additional help.
