### ISSUE TITLE
Validators crashing and not producing new blocks ERROR : "out of gas"

### ISSUE THREAD

**Issue by ex-shubham-koli** [0xPolygon/polygon-edge#798]
### Discussed in https://github.com/0xPolygon/polygon-edge/discussions/792

<div type='discussions-op-text'>

<sup>Originally posted by **shubham-edx** October 12, 2022</sup>
Earlier today all my validators crashed and all of them are showing the following logs. I have 8 validator setup on AWS. with 4 Validators created at first and then 4 added later via smart contract. (all BLS supported)

My env
Polygon edge v0.6
Ubuntu 20

> 0|node7    | 2022-10-12T10:04:41.030Z [INFO]  polygon.blockchain: genesis: hash=0x4a5151d9bab06e1da34f05efc5e91c361ce33a58515ea19b21ca7d67c4893c38
0|node7    | out of gas

any idea why am I getting this error? any help is appreciated.

![image](https://user-images.githubusercontent.com/53253101/195315318-f91991fc-4a4a-49a7-a572-b85f29dd7379.png)

![image](https://user-images.githubusercontent.com/53253101/195315217-a2477a8e-5fcc-47b3-8da5-9a3822bd2e35.png)

</div>

**Comment by laviniat1996** [comment]
@shubham-edx Thank you very much for opening this issue. We will update you as soon as we have new info about this.

**Comment by ivanbozic21** [comment]
HI @shubham-edx 
Team is working on a solution and we expect to have it deployed by the end of the week.

Please know that we will continue to keep you posted.

**Comment by ex-shubham-koli** [comment]
@laviniat1996 ,
Thank you for your amazing support. really appreciate it!

**Comment by laviniat1996** [comment]
Hi @shubham-edx ,

I am glad to hear that you are happy with the support provided 😊 

Thank you again for reporting this. The issue was fixed with [this PR](https://github.com/0xPolygon/polygon-edge/pull/821), therefore I will close the issue. If you still encounter this problem, or any other problem, please let us know. 🙏
