### ISSUE TITLE
Can't verify smart contracts with multiple imports on Polygon scan.

### ISSUE THREAD

**Issue by Kaleb47** [0xPolygon/polygon-edge#80]
### Description
While we were able to successfully deploy all of our solidity smart contracts on to Polygonscan, we ran into some issues verifying each smart contract

We were only able to verify smart contracts that did not have imports. As for the ones that did, the interface made it difficult to import multiple files at once (whenever a new file was added, the preceding one got deleted) making it more difficult to verify the smart contracts. Even after importing some the files, our smart contracts were not verified for this following reason.

![New Note](https://user-images.githubusercontent.com/63081938/124651911-8341ec00-de69-11eb-956a-a0859d16b540.jpeg)

We follow the same procedure on Etherscan and it works perfectly.

### Steps to reproduce

Simply trying to verify a multi-file solidity smart contract, choose the compile version, and then import the corresponding files for that smart contract, that includes the other smart contracts that the first one is importing and then attempt to verify.

### Expected behaviour
Smart-contract should be verified.

### Actual behaviour

Smart contract is not verified

**Comment by lazartravica** [comment]
Dear @Kaleb47, this is not an issue related to the `polygon-sdk`, but rather to the Polygon Explorer's contract verification.

I advise you to seek assistance on the [Polygon Discord](https://discord.gg/polygon).

Best regards
