### ISSUE TITLE
Help to run Nodes on cloud even when offline

### ISSUE THREAD

**Issue by Ranofty** [0xPolygon/polygon-edge#802]
### Your environment

* OS and version: Ubuntu 20.04
* version of the Polygon: Edge 0.6.0

Hello please how can I make my nodes running on cloud even when I am offline? 

I use `nohup command` my rpc is online but nodes are not Validating, any solution for this please? My nodes are only validating when am in the terminal

**Comment by avenbreaks** [comment]
you can use pm2 or tmux sessions

**Comment by Ranofty** [comment]
Thanks sir 🙏❤️
