### ISSUE TITLE
0.6.0 validator nodes get stuck due to many "not found in snapshot" errors

### ISSUE THREAD

**Issue by akshar** [0xPolygon/polygon-edge#811]
### Description
- We pulled in the latest 0.6.0 change on a 4 validator node setup. We are seeing the following errors 
```
[ERROR] polygon.ibft: cannot build block: num=301 err="not found snapshot"
[ERROR] polygon.ibft: failed to get validators when calculation quorum: height=301 err="not found snapshot"
[ERROR] polygon.ibft: failed to update submodules: height=301 err="not found snapshot"
```

As a result blocks cannot build past 300 height. Currently we're using following ibft engine config in our genesis.json file:

```
      "engine": {
            "ibft": {
                "epochSize": 100,
                "quorumSizeBlockNum": 5,
            	"type": "PoA"
	    }
        },

```

### Your environment

* Ubuntu 20.04
* [0.6.0](https://github.com/0xPolygon/polygon-edge/commit/e25825cb96ff35db308af06deee69acd5caea9b7)

### Steps to reproduce

- set the epoch size to `100` in genesis.json ibft engine configuration.
- Run 4  validator nodes with [0.6.0](https://github.com/0xPolygon/polygon-edge/commit/e25825cb96ff35db308af06deee69acd5caea9b7) with empty data dir
- Let nodes build block..

### Expected behaviour

- It should function normally and build blocks without any errors 

### Actual behaviour

- It stops building node at block number `300`.

### Logs

```
Oct 17 15:29:03 ip-172-31-92-59 main[406859]: 2022-10-17T15:29:03.584Z [DEBUG] polygon.ibft: validator message received: type=COMMIT height=300 round=0 addr=0x30b3eCF398eEB21D038Ba6a9221BD40255B4fE04
Oct 17 15:29:03 ip-172-31-92-59 main[406859]: 2022-10-17T15:29:03.584Z [INFO]  polygon.ibft.consensus: sequence done: height=300
Oct 17 15:29:03 ip-172-31-92-59 main[406859]: 2022-10-17T15:29:03.584Z [ERROR] polygon.ibft: failed to update submodules: height=301 err="not found snapshot"
Oct 17 15:29:03 ip-172-31-92-59 main[406859]: 2022-10-17T15:29:03.584Z [INFO]  polygon.ibft.consensus: sequence started: height=301
Oct 17 15:29:03 ip-172-31-92-59 main[406859]: 2022-10-17T15:29:03.584Z [INFO]  polygon.ibft.consensus: round started: round=0
Oct 17 15:29:03 ip-172-31-92-59 main[406859]: 2022-10-17T15:29:03.585Z [INFO]  polygon.ibft.consensus: we are the proposer
Oct 17 15:29:03 ip-172-31-92-59 main[406859]: 2022-10-17T15:29:03.585Z [ERROR] polygon.ibft: cannot build block: num=301 err="not found snapshot"
Oct 17 15:29:03 ip-172-31-92-59 main[406859]: 2022-10-17T15:29:03.585Z [ERROR] polygon.ibft.consensus: unable to build proposal
Oct 17 15:29:03 ip-172-31-92-59 main[406859]: 2022-10-17T15:29:03.585Z [ERROR] polygon.ibft: failed to get validators when calculation quorum: height=301 err="not found snapshot"
```
### Proposed solution

- Maybe get validator set from ibftExtra instead of snapshot ? 🤔

**Comment by laviniat1996** [comment]
Hi @akshar,

Thank you for opening this issue. We are aware of this problem, and it was recently fixed with this [PR](https://github.com/0xPolygon/polygon-edge/pull/791).

**Comment by laviniat1996** [comment]
Hi @akshar , 

Did you try the fix? Is everything working okay now?

**Comment by akshar** [comment]
@laviniat1996  Fix works. Thanks! closing this

**Comment by laviniat1996** [comment]
@akshar Thank you for the update! Have a lovely weekend.
