### ISSUE TITLE
Help install SSL in my RPC

### ISSUE THREAD

**Issue by Ranofty** [0xPolygon/polygon-edge#817]
### Your environment

* OS and version: AWS ubuntu 20.04
* version of the Polygon Edge: 0.6.0
* branch that causes this issue

Hello please i need help on how to install ssl to my json rpc any guide can help

**Comment by avenbreaks** [comment]
you can try change ip4 to dns/ and create elastic IP

**Comment by ivanbozic21** [comment]
Hi, we will move your query to the discussion board.
