### ISSUE TITLE
10 node polygon-edge setup

### ISSUE THREAD

**Issue by ghost** [0xPolygon/polygon-edge#857]
# [ Subject of the issue ]
## Description
Good evening, I have recently set up a 10 node testnet on Polygon edge. On my screen , I can see "Validators 10 / 7 commited" I used the exact same genesis for all 10 nodes, and the secrets init was copied and inserted perfectly. Why am I only seeing 7 please?

## Your environment
-Unbuntu server 20.04LTS
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*) I'm a noob, so I am struggling to get this to work.
- The branch that causes this issue. Just in normal running.
- Locally or Cloud hosted (which provider). AWS for 6 nodes, Hetzner for 2 nodes. 2 privately hosted nodes (static IP)
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.). tmux in SSH

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.

- Provide us with commands that you used to start your validators. polygon-edge server --data-dir ./node5 --chain genesis.json --libp2p 0.0.0.0:1478 --jsonrpc 0.0.0.0:10002 --price-limit 100000 --nat 90.194.87.159 --seal

- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`. I can't get this to work. Probably because I don't fully understand ti yet.
- Is the chain producing blocks and serving customers atm? It's making blocks, but tx=0, even after a successful wallet transfer. Transfers are very hit and miss. Managed to increase the gas on a stuck one on the same nonce to clear it. My first node is the RPC node. 54.82.93.215 on port 10002

## Expected behavior
- Tell us what should happen. show 10/10
- Tell us what happened instead. shows 10/7

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
10 commits on 10 validators is what I'm hoping to achieve. I don't know why it isn't, or where to even start. I'm learning linux from a lot of google searches right now... Any help is gratefully received

**Comment by laviniat1996** [comment]
Hi @Nexsuperne101,

If you see 7 out of 10 validators as comitted, that's okay. You only need the supermajority of validators to be comitted in order to produce blocks. All of the validators take turns in proposing the next block (round-robin), and for the block to be validated/inserted in the blockchain, a supermajority (more than 2/3) of the validators must approve the said block.

As this is normal behaviour, and not an actual issue, I will close this now. But fee free to open another issue whenever there's need.

**Comment by Nexsuperne101** [comment]
Thank you for your prompt reply. Our only other issue is stuck
transactions, or they send, but tx=0. Can you recommended a gas limit
please? I can resend with a bit more gas on the same nonce to clear it, but
I am still trying to get this right.

Thanks again for your help

Kind regards
Nexsuperne101

**Comment by Nexsuperne101** [comment]
Good morning, It would appear that my premine was wrong by one zero. I
needed 1 billion coins, but only minted 100 million. Is there a way to mint
the other 900 million without creating genesis again?

Thanks for all your help,

Kind regards,
Nex
