### ISSUE TITLE
Displayed address after 'ibft init' does not match address associated with the validator.key

### ISSUE THREAD

**Issue by dankostiuk** [0xPolygon/polygon-edge#88]
### Description

After running `ibft init`, one can see the generated Public key and Node ID as seen below:

```
polygon-sdk ibft init --data-dir validator-1

[IBFT INIT]
Public key (address) = 0xa43a17ccfde80300364118bc709ba492aa7499c1
Node ID              = 16Uiu2HAm2VBsW751CcQx5eJyrSqTT1sByzQeQLoDKx3NzszboDgm
```

It seems however that this Public key does not match the address derived from `validator-1/consensus/validator.key` when importing into MetaMask. I was under the impression that these should match...

### Your environment

* OSX 11.4
* Polygon SDK version 0.1.0
* Seen on latest on develop (6906ed9)

### Steps to reproduce

1. Run `polygon-sdk ibft init --data-dir validator-1` and note the `Public key (address)` value displayed in the terminal
2. Import account by specifying private key `validator-1/consensus/validator.key` in MetaMask
3. Observe that the Address of the imported account does not resemble what we saw in Step 1.

### Expected behaviour

The private key's associated Address should match what was shown under Public key (address) after running the `ibft init` command.

### Actual behaviour

The Public key (address) after running the `ibft init` is a completely different Address. As a result, one cannot premine that address or send $ to it. Instead, I had to derive the Address first from `consensus/validator.key` and later use that value when running `polygon-sdk genesis --premine 0xa33a17ccfde80300364118bc709ba492aa2499c1`.

**Comment by zivkovicmilos** [comment]
Hey @dankostiuk,

Thank you for reaching out, and I apologize for the late reply.

This issue has now been resolved, and is awaiting approval in [this PR](https://github.com/0xPolygon/polygon-sdk/pull/102).

**Comment by zivkovicmilos** [comment]
[The PR fix has been merged.](https://github.com/0xPolygon/polygon-sdk/pull/102)

Please review the PR description notes, as it contains some breaking fixes.
