### ISSUE TITLE
unable to sychronise on new node

### ISSUE THREAD

**Issue by ghost** [0xPolygon/polygon-edge#881]
# [ Subject of the issue ]
## Description
2022-11-07T17:35:58.752Z [WARN]  polygon.server.syncer: failed to complete bulk sync with peer, try to next one: peer ID=error 16Uiu2HAmPxYCHdnpzxsPYd6rh3DbaGkFHWxNpnQjfJAUPDRNAKdN="unable to verify block, unable to verify block execution result, invalid block state root"
Whilst trying to sync a fresh installed node, I get the error above at block 49999. I have fully reset my machine. Latest version of Go (1.18beta). 

## Your environment
- OS and version. Ubuntu server 20.04LTS
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider). cloud. Hetzner
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.). Tmux

## Steps to reproduce
- Tell us how to reproduce this issue. 
- Where the issue is, if you know.
- Which commands triggered the issue, if any. 
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen. shiukd sync and start making blocks
- Tell us what happened instead. stalled at block 49999. Current block was 75000

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by ghost** [comment]
I've cured this. It was caused by me forgetting that I set a switch to migrate to PoS, but it failed at 50,000. I then set it back to PoA at 51,000, to make blocks to move funds for staking, and then restarted the migration.

**Comment by laviniat1996** [comment]
Hi @Nexsuperne101 , is this still an issue? Also, what version of Edge did you use for this?

**Comment by ghost** [comment]
Hi laviniat1996, I cloned the latest version yesterday afternoon, so whatever one comes of the server is what I have. I'm fully up and running with 10 nodes all on PoS. When we go to mainnet, this won't be an issue, as I now know the order of things to achieve the end result. Last night was the first time I went to bed before 1am, as at last I have learnt enough to get this from 10 people with various cloud and physical solutions to an integrated fully working PoS 10 node setup. It's been an interesting learning curve! Thanks for your help to all of my noob questions.
