### ISSUE TITLE
Setting max number of validators on PoS

### ISSUE THREAD

**Issue by ghost** [0xPolygon/polygon-edge#884]
# [ Subject of the issue ]
## Description
Good afternoon,
I'm trying to set the maximum number of validators to 60. I have sudo nano genesis.json to add this line. It seems to still be showing a huge number of validators, not the 60. Have I gone wrong somewhere?

"engine": {
            "ibft": {
                "epochSize": 100,
                "max-validator-count": 60,

## Your environment
- OS and version. Ubuntu 20.04LTS
- The version of the Polygon Edge.  Cloned 2 days ago.
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?

## Expected behavior
- Tell us what should happen. validators set to 60 at next epoch start.
- Tell us what happened instead. Nothing so far. Validators still set at maximum

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by laviniat1996** [comment]
Hi @Nexsuperne101 ,

This is a genesis flag, therefore you need to use this when creating the genesis file.
Example `polygon-edge genesis --max-validator-count 10`. **Please note that this is the number of stakers that can join the validator set in PoS.**

**Comment by ghost** [comment]
Ok, that clears that one up. I managed to use stake.ts to set a 5 million
coin limit per validator. That seems to work quite well, as the maximum
supply will limit the number of possible minimum validators to no more than
100 .
As always, thanks for your help,
Nex

**Comment by laviniat1996** [comment]
Hi @Nexsuperne101 ,

I'm glad to hear that my reply was helpful. Feel free to reach out anytime there is an issue. 👍
