### ISSUE TITLE
genesis.json import and export

### ISSUE THREAD

**Issue by simone1999** [0xPolygon/polygon-edge#888]
genesis.json import and export
## Description
It seems like currently there is no way to import and export genesis.json files to and from other node architectures.
This prevents from running Polygon Edge for networks that were not initially started with Polygon edge like Ethereum as well as to run diverse node clients for a Polygon Edge network.
I'm running RPC nodes for multiple chains and would like to experiment to run Polygon Edge nodes instead of Geth or Parity nodes for these networks as I feel more familliar with the Polygon Edge codebase.
Also I'm running RPC Nodes for a Polygon Edge based network and would like to also add some Geth nodes for diversification.
For both cases I would need an export and import for the genesis.json file towards a standardized format or directly to the Geth genesis.json format.
This is also for RPC nodes, not for validator Nodes, so even if the concencus is not available in other implementations, maybe at least the validation of the blocks work.

## Expected behavior
I can import geth or parity genesis.json files in polygon edge and export polygon edge genesis.json files to geth or parity file formats

As a work around it would also be appreciated if you can give me manual steps how to change the genesis file by hand.

**Comment by laviniat1996** [comment]
Hi @simone1999 ,

Thank you for opening this issue.

Unfortunately, we do not support such interoperability. You can only run an Edge network using the genesis file generated within Edge. You also cannot export our `genesis.json` as a geth or parity file.

I will have to close this issue now, but feel free to reach out whenever there is a problem.
