### ISSUE TITLE
Slow block time on PoS

### ISSUE THREAD

**Issue by ghost** [0xPolygon/polygon-edge#895]
# [ Subject of the issue ]
## Description
Every 5 or 6 blocks (normally 2 seconds each) , we get 2 blocks that take 15 seconds. It only seems to do this on PoS. PoA was 2 seconds for every block. 10 bootnodes. 50 staked validators. 
Epoch at 100. 107,000 blocks made. BLS is on. 
## Your environment
- OS and version. Ubuntu 20.04 server LTS
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider).
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.).

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm?yes

## Expected behavior
- Tell us what should happen. Block time of 2 seconds. 
- Tell us what happened instead. Average time of 7 seconds. 

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by laviniat1996** [comment]
Hi @Nexsuperne101 ,

Please provide the full logs so we can look into this. Thank you.

**Comment by ghost** [comment]
How do I do that please? I've only been using this a couple of weeks now. Before that, I was an Electrical Engineer for 30 years. This is definitely a " learning curve"!

**Comment by laviniat1996** [comment]
By the full logs I mean the logs of a node. The logs usually look something like:
```
2022-11-10T17:13:47.493+0200 [INFO]  polygon.server.ibft: block committed: number=248 hash=0x3048a27042b4a225a667a799eb0f1f19101e134c9d0b1897cf4dfa243e5a7ad3 validation_type=bls validators=5 committed=4
2022-11-10T17:13:47.493+0200 [INFO]  polygon.server.ibft.consensus: sequence done: height=248
2022-11-10T17:13:47.493+0200 [INFO]  polygon.server.ibft.consensus: sequence started: height=249
2022-11-10T17:13:47.493+0200 [INFO]  polygon.server.ibft.consensus: round started: round=0
2022-11-10T17:13:47.517+0200 [INFO]  polygon.blockchain: block already inserted: block=248 source=syncer
2022-11-10T17:13:49.591+0200 [INFO]  polygon.blockchain: new block: number=249 txs=0 hash=0x7fed5b2ce0a0ea2317db091146ee3383fdeb2e53db5abb2904744e2f7419a669 parent=0x3048a27042b4a225a667a799eb0f1f19101e134c9d0b1897cf4dfa243e5a7ad3 generation_time_in_seconds=2
```

**Comment by ghost** [comment]
Ok, so just a screen dump of the text the node displays then. I will get that to you asap

**Comment by laviniat1996** [comment]
@Nexsuperne101 Yes, that would be helpful to figure this out.

**Comment by laviniat1996** [comment]
@Nexsuperne101 For the other issue you have currenlty open too.

**Comment by ghost** [comment]
I reinstalled the 10 nodes. The problem has gone now.
