### ISSUE TITLE
new boot node on PoS

### ISSUE THREAD

**Issue by ghost** [0xPolygon/polygon-edge#896]
# [ Subject of the issue ]
## Description
Good evening. Earlier today I added a new bootnode to my PoS chain. The existing 9 from the original genesis all show "we are the proposer" and "syncer". The new 10th node does not. I can't vote it in, as it's not on PoA. I have added the Node ID and IP4 address to the boot node section of all genesis.json on all 10 nodes, yet I can't get the new node to be like the others. Obviously the secrets init has different values to the original node this replaced on the genesis script.

## Your environment
- OS and version. ubuntu 20.04
- The version of the Polygon Edge.    
  (*Confirm the version of your Polygon edge client by running the following command: `polygon-edge version --grpc-address GRPC_ADDRESS`*)
- The branch that causes this issue.
- Locally or Cloud hosted (which provider). AWS
- Please confirm if the validators are running under containerized environment (K8s, Docker, etc.). tmux

## Steps to reproduce
- Tell us how to reproduce this issue.
- Where the issue is, if you know.
- Which commands triggered the issue, if any.
- Provide us with the content of your genesis file.
- Provide us with commands that you used to start your validators.
- Provide us with the peer list of each of your validators by running the following command: `polygon-edge peers list --grpc-address GRPC_ADDRESS`.
- Is the chain producing blocks and serving customers atm? yes, but slowly, 2 Seconds, 2 Seconds, 3 Seconds, 15 Seconds, 13 Seconds, 2 Seconds , 2 Seconds, and then it repeats.

## Expected behavior
- Tell us what should happen. Node is a boot node
- Tell us what happened instead. Node doesn't appear to be a boot node

## Logs
Provide us with debug logs from all of your validators by setting logging to `debug` output with: `server --log-level debug`

## Proposed solution
If you have an idea on how to fix this issue, please write it down here, so we can begin discussing it

**Comment by laviniat1996** [comment]
Hi @Nexsuperne101 ,

I think you mean that you want the node to be a validator in PoS. In order to do that, it needs to stake some funds.

This is the staking contracts repo: https://github.com/0xPolygon/staking-contracts

You can find [here](https://wiki.polygon.technology/docs/edge/consensus/pos-stake-unstake#using-the-staking-smart-contract-scripts) a full guide on how to stake funds. 

After you stake, wait for the next epoch and look into the logs of that node. You should see "we are the proposer" in the logs now.

**Comment by ghost** [comment]
Good afternoon,

Thank you for your reply. I unstaked and restaked using the npm run unstake and the npm run stake commands in the staking-contracts directory. I checked the block explorer, and the confirmation message on the screen. Both confirm that the 5 million coin staking fee plus gas has been paid, yet I'm still seeing the same issue. I waited for the next epoch, which is only set at 100.

**Comment by laviniat1996** [comment]
@laviniat1996 Are you using BLS? If so, did you register the bls key too?

**Comment by ghost** [comment]
yes, BLS is correctly registered. I double checked the details

**Comment by ghost** [comment]
The only thing that doesn't match is the node ID. In secrets init it generated a Node ID number, but when I added that to the bootnode section of each node's genesis.json, it flagged an error to say that it expected  16Uiu2HAm62vk8GK5z28PnAj7PecFScR5g8hRnzY84i5G7rfe3omN, but found remote 16Uiu2HAmBBouYgFghQMaDF53n1NSXWWrTtNvHTfHUkkEbzB13Upo. I copied the value it found, put that in the bootnode section on each node, and the error cleared.

**Comment by laviniat1996** [comment]
@Nexsuperne101  Can you please provide the full logs from that node?

**Comment by ghost** [comment]
Yes, how do I do that please?
