### ISSUE TITLE
failed extract ECDSA Privatekey

### ISSUE THREAD

**Issue by amandatsalis** [0xPolygon/polygon-edge#937]
# Network Stress Testing
## Description
cannot to test TPS in my local blockchain 

## Steps to reproduce
`polygon-edge secrets init --data-dir tps`

`export LOADBOT_0x57e97056A0d559A95E8c4BF8E1ACDA595cf5E329=0xa720d2fb42e143ad2fec877873842c194ff819d6ade03f340e40f5d0e920a33cd234a25ff9f1e53ef61a504f04e73c36`

```
polygon-edge loadbot \
  --jsonrpc  http://127.0.0.1:10002 \
  --grpc-address 127.0.0.1:9632 \
  --sender 0x57e97056A0d559A95E8c4BF8E1ACDA595cf5E329 \
  --receiver 0xCc4E321F328e1734ff9319bbc2b48415Fab9f43e \
  --count 2000 \
  --gas-price 10000000000 \
  --mode transfer \
  --value 0x100 \
  --tps 100
```

## Logs
`an error occurred while running the loadbot: failed to extract sender account: failed to extract ECDSA private key from bytes: invalid key length (48B), should be 32B`

```
=====[LOADBOT RUN]=====

[COUNT DATA]
Transactions submitted = 2000
Transactions failed    = 2000

[APPROXIMATE TPS]
Approximate number of transactions per second = 100

[TURN AROUND DATA]
Average transaction turn around = 0.000000s
Fastest transaction turn around = 0.000000s
Slowest transaction turn around = 0.000000s
Total loadbot execution time    = 2.155160s

[BLOCK DATA]
Blocks required = 0

[AVERAGE BLOCK UTILIZATION]
Average utilization across all blocks = NaN%
```

**Comment by laviniat1996** [comment]
Hi @amandatsalis,

 Please note that regular performance testing has been paused from release 0.4.1 due to consensus protocol changes that are being implemented. The loadboat will be soon removed from our codebase.
