### ISSUE TITLE
Miner Address always remains 0x00000... in blocks data

### ISSUE THREAD

**Issue by amandatsalis** [0xPolygon/polygon-edge#969]
# Miner Address Always Remains NullAddress 0x0000000
## Description
I've created a polygon blockchain and used its RPC points to get blockchain data. Trying to get information about block miners in polygons. For this I use the web3 method. All information about the block from get_blockByNumber, is displayed as expected except for the miner's address, the miner's hash should be "recipient address that received the mining reward" (or block validator address).
0x0000000000000000000000000000000000000000

## Your environment
- OS and version : Ubuntu AWS large
- The version of the Polygon Edge : v0.6.1
- The branch that causes this issue : develop

## Steps to reproduce

- Call BlockByNumber from RPC 
- Got this response for block

```
"parentHash": "0xc08a859fbc3495e5be578e0273232e82b2e4b623bd8a0097a3865500c12b82ff",
"sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
"miner": "0x0000000000000000000000000000000000000000",
"stateRoot": "0x89cc934352d444a0fff3b934046b00c819c0e800aae931d35f2110587eb03777",
"transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
"receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
```

## Expected behavior
I expect that I got miners address as we can see in polygonscan mumbai or mainnet that they shows validator of blocks.

It should be like
```
miner: [0xe7e2cb8c81c10ff191a73fe266788c9ce62ec754] 
for block number: 36160285
https://polygonscan.com/block/36160285
```
![image](https://user-images.githubusercontent.com/106639635/204201403-609d4d06-3df0-4dd9-8f2e-f6cda7adff03.png)

## Actual behavior
The miner address is always
`miner: 0x0000000000000000000000000000000000000000` hence I am unable to figure out who mined that block.

![image](https://user-images.githubusercontent.com/106639635/204201758-fd068418-c4a2-44d8-9b41-aa3ecfa4102e.png)

**Comment by laviniat1996** [comment]
Hi @amandatsalis ,

This is actually expected behaviour. Please check again the replies from our previous discussion: https://github.com/0xPolygon/polygon-edge/discussions/921 . We cannot change this, you can get the proposer by extracting that info from the block header's extra data field.

**Comment by amandatsalis** [comment]
what the EIPs type for polygon edge? 

> Hi @amandatsalis ,
> 
> This is actually expected behaviour. Please check again the replies from our previous discussion: #921 . We cannot change this, you can get the proposer by extracting that info from the block header's extra data field.

**Comment by nnlgsakib** [comment]
> # Miner Address Always Remains NullAddress 0x0000000
> ## Description
> I've created a polygon blockchain and used its RPC points to get blockchain data. Trying to get information about block miners in polygons. For this I use the web3 method. All information about the block from get_blockByNumber, is displayed as expected except for the miner's address, the miner's hash should be "recipient address that received the mining reward" (or block validator address). 0x0000000000000000000000000000000000000000
> 
> ## Your environment
> * OS and version : Ubuntu AWS large
> * The version of the Polygon Edge : v0.6.1
> * The branch that causes this issue : develop
> 
> ## Steps to reproduce
> * Call BlockByNumber from RPC
> * Got this response for block
> 
> ```
> "parentHash": "0xc08a859fbc3495e5be578e0273232e82b2e4b623bd8a0097a3865500c12b82ff",
> "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
> "miner": "0x0000000000000000000000000000000000000000",
> "stateRoot": "0x89cc934352d444a0fff3b934046b00c819c0e800aae931d35f2110587eb03777",
> "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
> "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
> ```
> 
> ## Expected behavior
> I expect that I got miners address as we can see in polygonscan mumbai or mainnet that they shows validator of blocks.
> 
> It should be like
> 
> ```
> miner: [0xe7e2cb8c81c10ff191a73fe266788c9ce62ec754] 
> for block number: 36160285
> https://polygonscan.com/block/36160285
> ```
> 
> ![image](https://user-images.githubusercontent.com/106639635/204201403-609d4d06-3df0-4dd9-8f2e-f6cda7adff03.png)
> 
> ## Actual behavior
> The miner address is always `miner: 0x0000000000000000000000000000000000000000` hence I am unable to figure out who mined that block.
> 
> ![image](https://user-images.githubusercontent.com/106639635/204201758-fd068418-c4a2-44d8-9b41-aa3ecfa4102e.png)

I can help you to reveal the miner address
