### ISSUE TITLE
Decode extraData key from block header

### ISSUE THREAD

**Issue by AgusVelez5** [0xPolygon/polygon-edge#979]
# Decode extraData key from block header
## Description
I am trying to decode the extraKey field of the header of a block to find out the proposer of that block but I am finding it impossible.

I try to do this because of what they say in the [documentation](https://wiki.polygon.technology/docs/edge/faq/validators/#why-do-the-json-rpc-commands-eth_getblockbynumber-and-eth_getblockbyhash-not-return-the-miners-address):

> The information about the proposer of the block can be found by recovering the pubkey from the Seal field of the RLP encoded Istanbul extra data field in the block headers.

## Your environment
- OS and version. `macOS 12.6`
- The version of the Polygon Edge.  `v0.6.1`
- Locally or Cloud hosted (which provider). `Locally`

## Steps to reproduce
Here is the script that I made:

  ```
package main
  
  import (
	  "fmt"
	  "os"
	  "github.com/0xPolygon/polygon-edge/types"
  )
  
  
  func main() {
	  header := &types.Header{}
	  header2 := types.Header{}
	  by, err := os.ReadFile("./tmp_data.json")
	  if err != nil {
		  panic(err)
	  }
	  err = header.UnmarshalJSON(by)
	  if err != nil {
		  panic(err)
	  }
	  buf := header.MarshalRLPTo(nil)
	  err = header2.UnmarshalRLP(buf)
	  if err != nil {
		  panic(err)
	  }
  
          fmt.Println(header2)
  }
```

I import the functions directly from the package types
The file `tmp_data.json` contains a json with a header data

## Expected behavior
Decode extraKey field and get the block proposer.

**Comment by laviniat1996** [comment]
Hi @AgusVelez5 ,

Thank you for opening this issue.
To obtain the actual proposer you would indeed need to extract the info from the extraData field. Unfortunately, at the moment we do not have an RLP decoder to help you with this. I will check this out and probably give you an update next week, if we can provide anything for this or not.

**Comment by AgusVelez5** [comment]
Hi @laviniat1996, thanks for the reply

I understand, I will wait for your answer then. One more question, although you do not have your own implementation of the RLP decoder, would you have any idea if there is any implementation of someone else or something I could look at in the meantime?

**Comment by laviniat1996** [comment]
Hi @AgusVelez5 ,

Trying to help out with this. Could please let us know if you need this info for a certain purpose or just to see, out of curiosity, who's the proposer?

**Comment by AgusVelez5** [comment]
Hi @laviniat1996,

I want to get the proposer because I am doing several stress tests on different networks (created with polygon-edge) and one of the data I want to get is which node took the fees of each block.

I was looking at this [discussion](https://github.com/0xPolygon/polygon-edge/discussions/663) but it was not very helpful.

**Comment by AgusVelez5** [comment]
For those who encounter the same problem, I leave an example of how to do it in this [repo](https://github.com/AgusVelez5/decode-polygon-extraData).

**Comment by ivanbozic21** [comment]
@AgusVelez5 Thank you for your contribution, and we point out other users to the repo link that you include!

**Comment by stephenhodgkiss** [comment]
> Hi @AgusVelez5 ,
> 
> Thank you for opening this issue. To obtain the actual proposer you would indeed need to extract the info from the extraData field. Unfortunately, at the moment we do not have an RLP decoder to help you with this. I will check this out and probably give you an update next week, if we can provide anything for this or not.

Hi there, do you have any plans to include the decoder functionality soon?
