### ISSUE TITLE
Can't send transactions via metamask in dev mode as `v` in the signature is invalid

### ISSUE THREAD

**Issue by mrwillis** [0xPolygon/polygon-edge#99]
### Description

When running in dev mode and trying to send a transaction, the sdk errors out with "invalid sender" which is actually a result of the error "invalid txn signature". Interestingly, `txn.From` is always the zero address.

### Your environment

* OS and version Unbutu 20
* version of the Polygon SDK 2f50a194f21d972b542ccd1e1571ccba40c5c810
* branch that causes this issue `develop`

### Steps to reproduce

* Tell us how to reproduce this issue 
Start up dev mode. Example:

```
dev --log-level DEBUG --premine 0x6F75bA6c90E3da79b7ACAfc0fb9cf3968aa4ee39 --gas-limit 1000000
```

* Where the issue is, if you know <br />
It looks like the signature is being sent as invalid as `v` because it's greater than 1 here. Is 21 a valid value for `v`?

![image](https://user-images.githubusercontent.com/2652683/126841787-1c217106-e3a9-42cb-9dd5-3d7b30896705.png)

https://github.com/0xPolygon/polygon-sdk/blob/develop/crypto/txsigner.go#L183

* Which commands triggered the issue, if any

### Expected behaviour

It should send the balance fine

Tell us what should happen

### Actual behaviour

Metamask errors out

### Logs

![image](https://user-images.githubusercontent.com/2652683/126840525-d0b3fff5-e630-4a03-82a8-82e37b877cd4.png)

```
2021-07-23T16:54:33.469-0400 [ERROR] polygon-dev.dispatcher: failed to dispatch: method=eth_sendRawTransaction err="invalid sender"
```

### Proposed solution

If you have an idea of how to fix this issue, please write it down here, so we can begin discussing it

**Comment by mrwillis** [comment]
After some more investigation, it's using `eth_sendRawTransaction` which then gets decoded via the RLP decoder. Then it hits this line here https://github.com/0xPolygon/polygon-sdk/blob/develop/txpool/txpool.go#L172. Unrelated: curious why the RLP decoder doesn't decode the `from` field? 

https://github.com/0xPolygon/polygon-sdk/blob/develop/types/rlp_unmarshal.go#L271

Anyways I believe this has to do with a signature format issue that the sdk doesn't recognize. I think it has to do with signature malleability as noted in the comment on the error line but could be wrong. is `21` a valid value?

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/cryptography/ECDSA.sol#L104

**Comment by lazartravica** [comment]
@mrwillis Unfortunately, I am unable to reproduce the issue, I am able to properly submit a transaction when interfacing through Metamask.

Can you provide some information on how you are sending the raw transaction?

**Comment by mrwillis** [comment]
@lazartravica this is just straight through metamask (version 9.8.2). So like selecting an account from the list, and just doing a simple transfer to that account (can use any gas price, i tried 0gwei and 1gwei). I was able to reproduce it again on a0618c48b8896fb994f8ef42699617cb81fc4af0 immediately. Seems like metamask is using `eth_sendRawTransaction` in this case to execute the transfer.

**Comment by lazartravica** [comment]
I am almost certain that this issue is due to the wrongly set chainId in Metamask.

The chainId in dev mode of polygon-sdk is always `100`.

Can you please double check that Metamask is configured to have `100` for the `chainId` for the network running in dev mode?

For more info on chainId and the `v` value of the signature: https://eips.ethereum.org/EIPS/eip-155

**Comment by mrwillis** [comment]
@lazartravica yep that was it. It was set to something else. Seems to work now!
